### ISSUE TITLE
DynamicProperties to be serializable

### ISSUE THREAD

**Issue by SchulteMarkus** [spring-projects/spring-data-neo4j#135]
Hi,

this issue is about the class DynamicProperties. Further more, this issue is related to Pull-Request #127, which itself is related to Pull-Request #124.

Following issue-description is C+P from #124:
______________________________________
DynamicProperties are in general properties of NodeEntities or -relationships, which are supposed to be serializable(?!). Using DynamicProperties makes a NodeElement having a field which itself is not serializable. [...]

I have recognized this suggestion for improvement because of findbugs integration in my project (which uses spring-data-neo4j):

Class [ab.cd] defines non-transient non-serializable instance field [ef] // ([ef] is of type DynamicProperties):

This Serializable class [ab] defines a non-primitive instance field which is neither transient, Serializable, or java.lang.Object, and does not appear to implement the Externalizable interface or the readObject() and writeObject() methods. Objects of this class will not be deserialized correctly if a non-Serializable object is stored in this field.
______________________________________

I am opening this issue, because the problem still occurs in spring-data-neo4j-2.3.1.RELEASE. A comment¹ at #124 implied, this problem would be fixed by spring-data-neo4j-2.3.0

¹ https://github.com/spring-projects/spring-data-neo4j/pull/127#issuecomment-23556757

**Comment by mangrish** [comment]
Closed. Issue out of date.
