### ISSUE TITLE
spring-data-neo4j with aspects, using entiy.persist() does not fire BeforeSaveEvent

### ISSUE THREAD

**Issue by SchulteMarkus** [spring-projects/spring-data-neo4j#139]
Hi,

in my usecase I am using BeforeSaveEvent for some auditing reasonse. I am using spring-data-neo4j-aspects to have spring-data-neo4j with Advanced Mapping.

In my spring-data-neo4j(-2.3.1.RELEASE) project, when doing

    entity.persist() // aspect-version

the BeforeSaveEvent-handler is not called.

When doing

    neoTemplate.save(entity)

everyting works as expected.

**Comment by mangrish** [comment]
Closed. Issue out of date.
