### ISSUE TITLE
Missing xsd at http://www.springframework.org/schema/data/repository/spring-repository.xsd

### ISSUE THREAD

**Issue by gcolbert** [spring-projects/spring-data-neo4j#143]
The spring-neo4j-2.2.xsd:

http://www.springframework.org/schema/data/neo4j/spring-neo4j-2.2.xsd

has a reference to:

http://www.springframework.org/schema/data/repository/spring-repository.xsd

but that gives a 404 error.

**Comment by mangrish** [comment]
Closed. Issue out of date.
