### ISSUE TITLE
Request ability to specify DEFAULT_QUERY_DEPTH for each Repository [DATAGRAPH-953]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1515]
**[Mark Angrish](https://jira.spring.io/secure/ViewProfile.jspa?name=mangrish)** opened **[DATAGRAPH-953](https://jira.spring.io/browse/DATAGRAPH-953?redirect=false)** and commented

When using `@RepositoryRestResource` on my repos, I noticed that some had some significant performance issues under JMeter load. After some research, I narrowed it down to the `DEFAULT_QUERY_DEPTH` of 1 being used on the `findAll` (these specific repos have entities with a large number of direct connections).

Since the `RepositoryRestResource` uses the default pageable `findAll`, this left me few options for improving my performance (ultimately, I create a custom `GraphRepositoryImpl` and implemented my own findAll with depth 0). However, this solution now applies to all of my repositories. It would be very helpful if there was a repository specific way to set the default depth

---

**Affects:** 4.1.4 (Hopper SR4)

**Comment by michael-simons** [comment]
Hey. This can be achieved in all of the 5.x series with the following approach of defining a custom base repository for Neo4j repositories:

```java
import java.io.Serializable;

import org.neo4j.ogm.session.Session;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository;
import org.springframework.data.repository.NoRepositoryBean;

@NoRepositoryBean
public class DefaultToDepth0OnFindAllPageable<T, ID extends Serializable> extends SimpleNeo4jRepository<T, ID> {

	public DefaultToDepth0OnFindAllPageable(
		Class<T> domainClass, Session session
	) {
		super(domainClass, session);
	}

	@Override
	public Page<T> findAll(Pageable pageable) {
		return super.findAll(pageable, 0);
	}
}
```

Needs to be enabled via

```java
import org.springframework.context.annotation.Configuration;
import org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories;

@Configuration
@EnableNeo4jRepositories(repositoryBaseClass = DefaultToDepth0OnFindAllPageable.class)
public class CustomNeo4jConfig {
}
```

Given the following entity

```java
@NodeEntity(label = "User")
public class User  {

	@Id @GeneratedValue
	private Long id;

	private String name;

	@Relationship("HAS_FRIEND")
	User friend;

}
```

and a call site like

```java
for (User user1 : userRepository.findAll(PageRequest.of(1,23))) {
	System.out.println(user1);
}
```

We see 

```
2021-01-04 13:03:50.235 DEBUG 15294 --- [           main] o.n.o.drivers.bolt.request.BoltRequest   : Request: MATCH (n:`User`) WITH n SKIP 23 LIMIT 23 RETURN n with params {}
```

in the log

This can of course be applied to other finders as well.
