### ISSUE TITLE
Feature request: Support transactions with REST API

### ISSUE THREAD

**Issue by pjweisberg** [spring-projects/spring-data-neo4j#152]
Neo4j 2.0 was released today, with support for transactions via the REST API: http://docs.neo4j.org/chunked/stable/rest-api-transactional.html

I'd like to be able to access a remote Neo4j DB and have my @Transactional annotations respected.  I imagine this will be done via SpringRestGraphDatabase, but if the feature is added somewhere else that's great too. :-)

**Comment by mangrish** [comment]
Closed. Issue out of date.
