### ISSUE TITLE
Neo4j v2

### ISSUE THREAD

**Issue by markhowroyd** [spring-projects/spring-data-neo4j#155]
Is Spring Data Neo4j v3 supposed to be compatible with Neo v2.0 ?

When I change versions in the cineasts-rest example POM and try to re-compile I get:

[ERROR] C:\Technical\gitcloned\spring-data-neo4j-master\spring-data-neo4j-examples\cineasts-rest\src\main\java\org\neo4j\cineasts\service\Neo4jDatabaseCleaner.java:39:0::0 The method getReferenceNode() is undefined for the type AbstractGraphDatabase

Is this just an issue with the example using deprecated APIs, or shouldn't I be using it with Neo v2?

Thx
Mark

**Comment by chandnib** [comment]
[ERROR] 'dependencies.dependency.version' for org.neo4j:neo4j-rest-graphdb:jar must be a valid version but is '${neo4j.version}'
