### ISSUE TITLE
Release 4.1.12 (Hopper SR12) [DATAGRAPH-1000]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1562]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGRAPH-1000](https://jira.spring.io/browse/DATAGRAPH-1000?redirect=false)** and commented

---
No further details from [DATAGRAPH-1000](https://jira.spring.io/browse/DATAGRAPH-1000?redirect=false)

**Comment by michael-simons** [comment]
No longer applies.
