### ISSUE TITLE
Spring Data/Spring/Neo version dependencies (and is it Neo v2 compliant?)

### ISSUE THREAD

**Issue by markhowroyd** [spring-projects/spring-data-neo4j#157]
Can you advise what version of Spring should go with v3.0.0 of spring data for Neo4j?

I am trying to start up the examples after moving the version number and I get this which looks like versions are inconsistent maybe ? :

org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.lang.IllegalAccessError: tried to access method org.springframework.context.annotation.AnnotationConfigUtils.processCommonDefinitionAnnotations(Lorg/springframework/beans/factory/annotation/AnnotatedBeanDefinition;)V from class org.springframework.data.repository.config.RepositoryComponentProvider

My versions are 
	<spring.version>3.1.0.RELEASE</spring.version>
	<slf4j.version>1.6.1</slf4j.version>
	<spring-data-neo4j.version>3.0.0.RC1</spring-data-neo4j.version>
        <aspectj.version>1.6.12</aspectj.version>
        <neo4j.version>2.0.1</neo4j.version>

Also, is Spring data v3 supposed to be able to run against Neo v2? (I couldn't see any branches of code examples that do it). I don't really want to install old v1.8 Neo.
Many thx
Mark

**Comment by mangrish** [comment]
Closed. Issue out of date.
