### ISSUE TITLE
withEntityLookup GET for numerical field fails with String cast error [DATAGRAPH-1019]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1580]
**[Tim te Beek](https://jira.spring.io/secure/ViewProfile.jspa?name=timtebeek)** opened **[DATAGRAPH-1019](https://jira.spring.io/browse/DATAGRAPH-1019?redirect=false)** and commented

As per: https://github.com/timtebeek/taxonomy-graph/commit/a51af84323aa81020b4f9a069766364ec609e135

My Taxon class has a numerical field taxonid (manually assigned, not the graph id field), which I would like to use for customized entity lookup as defined in the manual:
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#_customizing_item_resource_uris

However, I get the following exception (which might need to be relayed to the spring-data-rest-core project):

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.springframework.data.rest.core.config.EntityLookupConfiguration$RepositoriesEntityLookup.lookupEntity(EntityLookupConfiguration.java:213) ~[spring-data-rest-core-2.6.6.RELEASE.jar:na]
	at org.springframework.data.rest.core.support.UnwrappingRepositoryInvokerFactory$UnwrappingRepositoryInvoker.invokeFindOne(UnwrappingRepositoryInvokerFactory.java:130) ~[spring-data-rest-core-2.6.6.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.RepositoryEntityController.getItemResource(RepositoryEntityController.java:524) ~[spring-data-rest-webmvc-2.6.6.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.RepositoryEntityController.getItemResource(RepositoryEntityController.java:335) ~[spring-data-rest-webmvc-2.6.6.RELEASE.jar:na]
```

---

**Affects:** 4.2.6 (Ingalls SR6)

**Reference URL:** https://github.com/timtebeek/taxonomy-graph/commit/a51af84323aa81020b4f9a069766364ec609e135

**Comment by michael-simons** [comment]
Hi @timtebeek

This took a while, but alas… :) 

This is not a Spring Data Neo4j issue but is in fact related to Spring Data Rest.

When the request comes it, the ID parameter is a string and unconditionally passed to the lookup. I see nothing wrong in what you did according to the docs. 
However, the example in the docs is a string property.

Here's the config I got this working with

```
@Component
public class SpringDataRestCustomization implements RepositoryRestConfigurer {
	@Override
	public void configureRepositoryRestConfiguration(final RepositoryRestConfiguration config) {
		config.withEntityLookup()
			.forRepository(TaxonRepo.class)
			.withIdMapping(t -> t.getTaxonid() == null ? null : t.getTaxonid().toString())
			.withLookup((repo, id) -> repo.findByTaxonid(Integer.valueOf(id)));
	}
}
```

And for completness, your project updated to Spring Boot, using SDN 5.3.

[taxonomy-graph-new.zip](https://github.com/spring-projects/spring-data-neo4j/files/5765139/taxonomy-graph-new.zip)

It should work with the brand new SDN 6 as well, given the above lookup. I see if I can transfer the issue to data rest.

**Comment by michael-simons** [comment]
Nope, it seems that I can't. 

Maybe @gregturn would like to pick this up, I'm closing it here to get an idea of where we are now after the Jira migration.

**Comment by michael-simons** [comment]
BTW, the recent dump data cannot be loaded as the IDs you prepend will be repeated when the default with of `nl` is reached. I managed to import them with `nl -w 18 -s '	|	' names.dmp > names_prefixed.dmp;`.

**Comment by timtebeek** [comment]
Wow, thanks for putting so much effort into replicating my issue, and even fixing the code as you went along! I'll be sure to update my sample application, as I'd been meaning to upgrade this sample app just because I liked working with Neo4J so much. Good to know the `SpringDataRestCustomization` can make this work after all; nice addition to the toolbox.

Perfectly valid to leave the issue closed with regards to spring-data-neo4j, and thanks again for the fixes & pointing me in the right direction!
