### ISSUE TITLE
spring-data-neo4j-rest imports old annotations package in manifest file

### ISSUE THREAD

**Issue by cemmersb** [spring-projects/spring-data-neo4j#160]
Dear all,

I have encountered, that there is an issue when installing the neo4j-rest bundle in an OSGi environment. The rest bundle imports the following version of the annotations package:
```
Bundle-Vendor: SpringSource
Bundle-Version: 2.3.4.RELEASE
Tool: Bundlor 1.0.0.RELEASE
Bundle-Name: Spring Data Neo4J REST
...
Import-Package: javax.transaction;version="[1.0.1, 2.0.0)";
...
org.springframework.data.neo4j.annotation;version="[1.0.0, 2.0.0)"
...
```
However the spring-data-neo4j bundle exports only version 2.3.4.RELEASE of the annotation package. Since the import stops at version 2.0.0, the package can not be resolved.
```
Bundle-Vendor: SpringSource
Bundle-Version: 2.3.4.RELEASE
Tool: Bundlor 1.0.0.RELEASE
Bundle-Name: Spring Data Neo4J
...
Export-Package: org.springframework.data.neo4j.annotation;version="2.3.4.RELEASE";
...
```

Has anybody encountered similar issues, or an idea, how to resolve this?

Best,

Christoph

**Comment by mangrish** [comment]
Closed. Issue out of date.
