### ISSUE TITLE
Relationships are getting missed when nodes/relationships persisted are too large [DATAGRAPH-1055]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1601]
**[Linda M Thomas](https://jira.spring.io/secure/ViewProfile.jspa?name=lindamthomas07)** opened **[DATAGRAPH-1055](https://jira.spring.io/browse/DATAGRAPH-1055?redirect=false)** and commented

SDN version - 5
OGM - 3

if there is a node that has 27185 edges to other nodes(verified the count before persisting), only 27184 is getting persisted. one or two edges are getting missed frequently.

The issue is reproducible and a sample project is available at below link:
https://gitlab.com/lindamthomas07/Neo4jRelationshipsMissing.git

Code snippet to generate relationships:

```java
  for(int i=0;i<28000;i++){
			DataNode dataNode = new DataNode();
			dataNode.setName("DataNode");
			dataNode.setUuid(UUID.randomUUID().toString());			

			DataDependentNode dataDependentNode = new DataDependentNode();
			dataDependentNode.setUuid(UUID.randomUUID().toString());

			LoadNode loadNode = new LoadNode();
			loadNode.setUuid(UUID.randomUUID().toString());

			dataNode.addLoadNodes(new HashSet<>(Arrays.asList(loadNode)));

			dataDependentNode.addDataNodes(new HashSet<>(Arrays.asList(dataNode)));
			
			revisionNode.addDependentDataNodes(new HashSet<>(Arrays.asList(dataDependentNode)));
			revisionNode.addDataNodes(new HashSet<>(Arrays.asList(dataNode)));
			revisionNode.addLoadNodes(new HashSet<>(Arrays.asList(loadNode)));
		}
```

In the attachment:
* Data Nodes count: 56k (28k in two revisions)
* HAS_DATANODE relationship count in particular revision: 27999 (it should have been 28k)

---

**Attachments:**
- [DataNodes_relationship_missing.PNG](https://jira.spring.io/secure/attachment/25326/DataNodes_relationship_missing.PNG) (_28.84 kB_)

**Comment by michael-simons** [comment]
Hey @lindamthomas07

Sorry for the "slight" delay on answering this.

I tested your setup with
with Spring Boot 2.1.18.RELEASE, Spring Data Neo4j 5.1.21, OGM 3.1.22 against Neo4j 3.5 and
with Spring Boot 2.2.12.RELEASE, Spring Data Neo4j 5.2.12, OGM 3.2.18 against Neo4j 3.5 and and Neo4j 4.2 and 
with Spring Boot 2.2.12.RELEASE, Spring Data Neo4j 5.3.6, OGM 3.2.18 against Neo4j 3.5 and and Neo4j 4.2 and it works as expected.

Thank you for a great reproducer though and have a good day.
