### ISSUE TITLE
"No identity field found for class of type" warnings when no @Id @GeneratedValue field [DATAGRAPH-1076]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1638]
**[Christian](https://jira.spring.io/secure/ViewProfile.jspa?name=ctytgat)** opened **[DATAGRAPH-1076](https://jira.spring.io/browse/DATAGRAPH-1076?redirect=false)** and commented

We have `@NodeEntity` classes with `@Id` properties.
After upgrading from 4.2 -> 5.0.5, logs are flooded with following warnings:

WARN ta.neo4j.mapping.Neo4jPersistentProperty:  95 - No identity field found for class of type: ... when creating persistent property for : ...

This can be avoided by adding a field like

```java
@Id
@GeneratedValue
private Long nodeId;
```

... but this is supposed to be optional since OGM 3.x.  
An `@Id` field should be sufficient

---

**Affects:** 5.0.5 (Kay SR5)

**Comment by michael-simons** [comment]
This has been fixed in SDN 5.0.12 + OGM 3.1.5 in af632c95153b924a2048cccd06359e33e61edaf7.
