### ISSUE TITLE
Docs on GraphTraversal out of date

### ISSUE THREAD

**Issue by sparmboy** [spring-projects/spring-data-neo4j#164]
Section 20.4.6 in the docs talks about using ```TraversalDescriptionImpl``` in the examples but this is now removed from the corresponding ```neo4j-kernel:2.0.1``` of which ```spring-data-neo4j:3.0.1.RELEASE``` is dependent on.

There's a bit of a lack documentation out there on the new replacement classes like TraversalBranchImpl.

**Comment by mangrish** [comment]
Closed. Issue out of date.
