### ISSUE TITLE
Passing Pattern Object to repository methods is not considering flags [DATAGRAPH-1092]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1653]
**[Rizwan Ishtiaq](https://jira.spring.io/secure/ViewProfile.jspa?name=rizwan-ishtiaq)** opened **[DATAGRAPH-1092](https://jira.spring.io/browse/DATAGRAPH-1092?redirect=false)** and commented

When using repository method name conversion to generate query and passing Pattern Object as parameter, it is ignoring the flags which are used to create pattern object

Let suppose we have following pattern object

```java
// passing
Pattern identifier = Pattern.compile("*\\brizwan\\b.*", Pattern.CASE_INSENSITIVE);
```

And have following method in repository

```java
// interface PersonRepository extends Neo4jRepository<Person, Long>
Collection<Person> findByNameRegex(Pattern identifier);
```

It should create following query, NOTE: the flag 

```java
//Should create
MATCH (n:`Person`) WHERE n.`name` =~ { `identifier_0` } RETURN n, ID(n) with params {identifier_0=(?i).*\rizwan\b.*}
```

But it is not considering the flag

```java
//But creating 
MATCH (n:`Person`) WHERE n.`name` =~ { `identifier_0` } RETURN n, ID(n) with params {identifier_0=.*\rizwan\b.*}
```

---
No further details from [DATAGRAPH-1092](https://jira.spring.io/browse/DATAGRAPH-1092?redirect=false)

**Comment by michael-simons** [comment]
Hi @rizwan-ishtiaq 

Please define your query method as

```
// interface PersonRepository extends Neo4jRepository<Person, Long>
Collection<Person> findByNameRegex(String identifier);
```

and pass `*(?i)\\brizwan\\b.*` or any other flag. `java.util.regex.Pattern` is not a valid parameter for SDN 5.x and 6.x repository methods. Gerrit's explanation is correct.
