### ISSUE TITLE
ConversionService collision when using Spring Data Rest [DATAGRAPH-1104]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1665]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1104](https://jira.spring.io/browse/DATAGRAPH-1104?redirect=false)** and commented

When using Spring Data Rest through the spring-boot-starter-data-rest within a Spring Boot application the application will fail to start due to the expectation in `Neo4jOgmEntityInstantiatorConfigurationBean` of just one `ConversionService` in the application.
The dependencies will provide two:
- `mvcConversionService` in `WebMvcAutoConfiguration$EnableWebMvcConfiguration`
- `defaultConversionService` in `RepositoryRestMvcConfiguration`

---
No further details from [DATAGRAPH-1104](https://jira.spring.io/browse/DATAGRAPH-1104?redirect=false)

**Comment by michael-simons** [comment]
This is has been fixed since 5.1.0.RC2 with aa9ba9e0e3c15f65185bca7a6caf579025dcccc0 and did not apply in 5.0.x.
