### ISSUE TITLE
search by numeric and simple index  3.0.1.release

### ISSUE THREAD

**Issue by PaulWeb** [spring-projects/spring-data-neo4j#168]
I have following entity :
@NodeEntity(useShortNames = true)
public class NeoNode  {

    @GraphId
    Long id;

    @Indexed(unique = true, indexName = "link", indexType = IndexType.SIMPLE, numeric = true)
    Long link;

    @Indexed(indexName = "nodealias", indexType = IndexType.FULLTEXT)
    String alias;
}
when i'm trying to execute query "start n=node:link('link:2223') return n" from my spring app i've got empty list but when i execute the same query from server console, i've got one node with props. Also I tried to retrieve node from index directly (template.getIndex("link").query("link:2223").size()) but i've got 0 size but when executed template.getIndex("link").query("link:*").size() i've got 5 size

**Comment by mangrish** [comment]
Closed. Issue out of date.
