### ISSUE TITLE
duplicate value in related node 

### ISSUE THREAD

**Issue by PaulWeb** [spring-projects/spring-data-neo4j#169]
I've following etities:

@NodeEntity(useShortNames = true)
public class NeoNode  {
    @GraphId
    Long id;

    @Indexed(unique = true, indexName = "link",indexType = IndexType.SIMPLE)
    Long link;
}

@NodeEntity(useShortNames = true)
public class CircleGraph  {
    @GraphId
    private Long id;

   @RelatedTo(type = "ITEM", direction = Direction.INCOMING)
    private NeoNode node;
}

I created NeoNode, then I'm trying to save CircleGraph set NeoNode as new NeoNode().link(45781), but i've got exception 
Unique property class java.lang.Long link rel: false idx: true was to be set to duplicate value 45781. 

But when index link in neonode is numeric all work fine without exception.

**Comment by mangrish** [comment]
Closed. Issue out of date.
