### ISSUE TITLE
Fail early if bookmark setup is enabled without a bookmark manager. [DATAGRAPH-1128]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1691]
**[Michael Simons](https://jira.spring.io/secure/ViewProfile.jspa?name=michael.simons)** opened **[DATAGRAPH-1128](https://jira.spring.io/browse/DATAGRAPH-1128?redirect=false)** and commented

Right now calling a `@UseBookmark` method will fail on the latest point possible if the user enabled bookmark support through `@EnableBookmarkSupport` but forgot to add a bookmark manager.

We should fail during startup if there is no bookmark manager available

---

**Affects:** 5.1 RC2 (Lovelace), 5.0.10 (Kay SR10)

**Comment by michael-simons** [comment]
Closed in 5.1.x up to 5.3.x. 6.x+ upwards doesn't need all of this.
