### ISSUE TITLE
Like keyword generates wrong regex. [DATAGRAPH-1136]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1699]
**[Michael Simons](https://jira.spring.io/secure/ViewProfile.jspa?name=michael.simons)** opened **[DATAGRAPH-1136](https://jira.spring.io/browse/DATAGRAPH-1136?redirect=false)** and commented

A derived finder method with the `Like`-Keyword generates the wrong expression.

It generates `(?i)value` which matches exactly lowercase and not "like something". It should add `.*` around the value

---
No further details from [DATAGRAPH-1136](https://jira.spring.io/browse/DATAGRAPH-1136?redirect=false)

**Comment by michael-simons** [comment]
SDN 6 and upwards generate `property =~ .* {param} + .*` param, which is the correct behavior.

We are not gonna change the behavior of SDN 5.2 and 5.3, though, as it potentially would lead to more results than people expect right now.

In SDN 5.2.x and 5.3.x the Neo4j-OGM `CaseInsensitiveLikePropertyValueTransformer` is applied that adds `(?i)` AND replaces all literal `*` in the value passed to the method with `.*`.
