### ISSUE TITLE
Problem accessing /populate 

### ISSUE THREAD

**Issue by emecas** [spring-projects/spring-data-neo4j#173]
I'm getting the following Error 500, once I try to access:

http://localhost:8080/populate

Any idea if it is a temporal issue or should i try to populate pointing to another source?

Thanks

 

HTTP ERROR 500

Problem accessing /populate. Reason:
Failed to get data from http://api.themoviedb.org/2.1/Movie.getInfo/en/json/926d2a79e82920b62f03b1cb57e532e6/19995

Caused by:
java.lang.RuntimeException: Failed to get data from http://api.themoviedb.org/2.1/Movie.getInfo/en/json/926d2a79e82920b62f03b1cb57e532e6/19995

Caused by:
java.io.FileNotFoundException: http://api.themoviedb.org/2.1/Movie.getInfo/en/json/926d2a79e82920b62f03b1cb57e532e6/19995

**Comment by mangrish** [comment]
Closed. Issue out of date.
