### ISSUE TITLE
IgnoreCase does not work in Kotlin [DATAGRAPH-1200]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1762]
**[manuelprinz](https://jira.spring.io/secure/ViewProfile.jspa?name=manuelprinz)** opened **[DATAGRAPH-1200](https://jira.spring.io/browse/DATAGRAPH-1200?redirect=false)** and commented

When creating a repository interface in Kotlin, using `IgnoreCase` will fail with the following error message:

```
Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: Unable to ignore case of java.lang.String types, the property 'label' must reference a String; nested exception is java.lang.IllegalStateException: Unable to ignore case of java.lang.String types, the property 'label' must reference a String
```

This seems to be due to the compiled class being a `kotlin.String` instead of `java.lang.String`.

Using Kotlin strings in `NodeEntities` seems to work fine, so I expected these types of strings being equivalent everywhere.

Example:

```java
interface FooRepository {
    fun findAllByLabelIgnoreCase(label: String): Iterable<Foo>
}
```

Please get back to me if you need more information or examples!

---

**Affects:** 5.1.5 (Lovelace SR5)

**Comment by michael-simons** [comment]
Hi @manuelprinz. I hope this is you. If not, sorry and please ignore the notification.

If you trying to match by the label of a node, this is not gonna work through derived finder methods. You can do this with a custom query around the following idea:

```
match (n) where any (label IN labels(n) WHERE toLower(label) = 'movie') return n
```

Here: All nodes that have a label `movie`. Of course all string operations, like regex etc, can be applied as well.

For the example @meistermeier added above, find the project attached. I tested it with 5.1.x, 5.2.x and 5.3.x (through Spring Boot 2.1.x, 2.2.x and 2.3.x), works as expected.

[gh1762.zip](https://github.com/spring-projects/spring-data-neo4j/files/5803200/gh1762.zip)

Thanks for your contribution.
