### ISSUE TITLE
Ensure final fields of immutable entities are persisted correctly.

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1763]
**[Michael Simons](https://jira.spring.io/secure/ViewProfile.jspa?name=michael.simons)** opened **[DATAGRAPH-1201](https://jira.spring.io/browse/DATAGRAPH-1201?redirect=false)** and commented

See attached reproducer.

```java
@NodeEntity
public class Blub {
	@Id
	@GeneratedValue
	private Long id;

	private final String name;

	public Blub(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
```

fails to be save correctly, `name` is always null.

If you remove the `final`, than everything is ok.

---

**Affects:** 5.1.5 (Lovelace SR5)

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/26185/demo.zip) (_86.22 kB_)

**Comment by michael-simons** [comment]
This has been fixed with https://github.com/neo4j/neo4j-ogm/commit/6475ae81fc6ddb70cf31311a119c6225abd09928, released as OGM 3.1.14 which was part of SDN 5.1.11 for the first time.
