### ISSUE TITLE
@EntityGraph support in Repository [DATAGRAPH-1248]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1809]
**[Arif Rabbani](https://jira.spring.io/secure/ViewProfile.jspa?name=arabbani)** opened **[DATAGRAPH-1248](https://jira.spring.io/browse/DATAGRAPH-1248?redirect=false)** and commented

`@EntityGraph` support is a very handy feature in spring-data-jpa. Is there any way to support this feature in spring-data-neo4j?

---
No further details from [DATAGRAPH-1248](https://jira.spring.io/browse/DATAGRAPH-1248?redirect=false)

**Comment by michael-simons** [comment]
Thanks, @arabbani for your patience.

The 5.2 and 5.3 series are now in maintaince mode and we already have a much stricter mapping model and better support for custom projections in SDN 6 and upwards. So this won't come to SDN for now.

I can understand that this `@EntityGraph` sounds like it was made for a Graph database, but we are following the idea of Command query responsibility segregation (CQRS): If you have the need for different shaped graphy results, use projections or custom query results, please.
