### ISSUE TITLE
Properties with type of Kotlin inline class has mangled name. [DATAGRAPH-1330]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1891]
**[Corneil du Plessis](https://jira.spring.io/secure/ViewProfile.jspa?name=corneil)** opened **[DATAGRAPH-1330](https://jira.spring.io/browse/DATAGRAPH-1330?redirect=false)** and commented

I wanted to use an ``inline class` for the type of an Id to ensure I avoid using a non ID property in a query or when comparing etc.

Kotlin mangles the name of the property when it's type is an inline class an `@Property` doesn't seem to take effect.

https://github.com/corneil/demo-inline-class-property-bug

 

**No property userId-kArDf24 found for type User!**

 

_Do I need a converter for the inline class when the property is found?_

---

**Attachments:**
- [kt1.zip](https://jira.spring.io/secure/attachment/28091/kt1.zip) (_102.44 kB_)
- [User.decompiled.txt](https://jira.spring.io/secure/attachment/28189/User.decompiled.txt) (_3.47 kB_)

**Issue Links:**
- [DATACMNS-1517](https://jira.spring.io/browse/DATACMNS-1517) Add support for Kotlin inline classes

1 votes, 4 watchers

**Comment by michael-simons** [comment]
So it seems that we cannot do much here and therefore we are gonna close this ticket.
