### ISSUE TITLE
Support undirected relationships [DATAGRAPH-1342]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1892]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1342](https://jira.spring.io/browse/DATAGRAPH-1342?redirect=false)** and commented

The current solution to map those is to create outcoming relationships on both sides but this will also have an impact on the query generation and result in matches for outgoing relationships only.
An explicit UNDIRECTED relationship will introduce direction agnostic queries and seems, on an application level, a good addition to retrieve nodes from each side of the relationship no matter which node the query was started on

---

**Affects:** 6.0 M2 (2020.0.0)

**Comment by michael-simons** [comment]
We have agreed for know that we would not like to have that feature back in SDN.
