### ISSUE TITLE
XML configuration in a @Configuration fails

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-data-neo4j#190]
There is a bug (probably) in Spring (https://jira.spring.io/browse/SPR-11858) which exacerbates this. But really it shouldn't be necessary to add `ConfigurationClassPostProcessor` to an application context explicitly (https://github.com/spring-projects/spring-data-neo4j/blob/master/spring-data-neo4j/src/main/java/org/springframework/data/neo4j/config/DataGraphBeanDefinitionParser.java#L98). Maybe Neo4j can do this conditionally (so it doesn't happen in a `@Configuration` app where there is already a `ConfigurationClassPostProcessor`)?

**Comment by Leward** [comment]
I experienced the same issue. However upgrading to a more recent version of Spring did fix it.

**Comment by mangrish** [comment]
Closed. Issue out of date.
