### ISSUE TITLE
Allow findBy on map relationships [DATAGRAPH-1343]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1905]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1343](https://jira.spring.io/browse/DATAGRAPH-1343?redirect=false)** and commented

I want to query relationship nodes when they are defined as map.

Given NodeA - RelationsshipProperties -> NodeB:

```java
@Node("NodeA") 
public class NodeA {
        @Id  
        private final String title;

        @Relationship(type = "RELATED_TO", direction = OUTGOING) 
        private Map<NodeB, RelationshipProperties> related = new HashMap<>();
// ...
}

@Node("NodeB") 
public class NodeB {
        @Id  
        private final String title;

        @Relationship(type = "RELATED_TO", direction = INCOMING) 
        private Map<NodeA, RelationshipProperties> related = new HashMap<>();
// ...
}
```

A Repository Interface-Method Flux\<NodeA> findByRelatedTitle(String title); does currently try to access not present title on RelationsshipProperties instead of NodeBs title.

With comment from Michael:

```
We're discussing atm how we could enhance our @RelationshipProperties-model to make this possible.
```

---

**Affects:** 6.0 M2 (2020.0.0)

**Comment by michael-simons** [comment]
This has been superseded by the work done in https://jira.spring.io/browse/DATAGRAPH-1373?redirect=false.

See the repository under test here

https://github.com/spring-projects/spring-data-neo4j/blob/0858c049f9d335d8f7d29b84463ce6d1a764acd2/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L3860-L3873

And the test for this exact feature here

https://github.com/spring-projects/spring-data-neo4j/blob/0858c049f9d335d8f7d29b84463ce6d1a764acd2/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L3802-L3812
