### ISSUE TITLE
Would be nice to have @OrderBy on collection relationships [DATAGRAPH-1345]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1907]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1345](https://jira.spring.io/browse/DATAGRAPH-1345?redirect=false)** and commented

It would be nice to have `@OrderBy` annotation specifying the ordering of the elements of a `@Relationship` collection.

For example:

 

{{`@OrderBy`("firstName ASC, lastName ASC")
`@Relationship`("HAVE_USER")
private Set\<User> users = new LinkedHashSet<>();}}

This would perform the ordering at the DB level by firstName then lastName with ASC. I know that we can do it programmatically with SortedSet but I guess DB level is a much more great way of doing this.

A `LinkedHashSet` preserves order based on insertion order that is why I used that one

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/neo4j/sdn-rx/issues/227

**Comment by michael-simons** [comment]
Hi @aaramg while this is a quite relatable and good idea, we cannot implement it as such.
We do use a thing called [List comprehensions](https://neo4j.com/docs/cypher-manual/current/syntax/lists/) to fetch the relationships. Those cannot be sorted inline and we would have to unroll them first after creating them, defeating their purpose.

My suggestion is implementing orderable on your domain object and using a sorted collection. We do reuse the collection type.
