### ISSUE TITLE
Dynamic SpEL labels for @Node [DATAGRAPH-1346]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1908]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1346](https://jira.spring.io/browse/DATAGRAPH-1346?redirect=false)** and commented

Hello Neo4j, Thank you for the great work on reactive drivers.

It would be great if we can support Spring SpEL for `@Node` labels.

Use Case: Multi-Tenant application

We could have a Supplier which computes the node label at run time:

```
@Bean("client") Supplier<String> client() { return ClientResolver::resolve; }
```

And use the supplier inside Node annotation.

```
@Node("#{ client.get() }_mynode")
```

Thank you!

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/neo4j/sdn-rx/issues/239

**Comment by michael-simons** [comment]
To have a stable mapping, we need one immutable label for a node. You might use `@DynamicLabels` annotation on a field combined with SpEL expressions inside a custom query. to achieve something similar. 

Paging @singh-gurprit
