### ISSUE TITLE
Dynamic embedded/nested properties [DATAGRAPH-1347]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1909]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1347](https://jira.spring.io/browse/DATAGRAPH-1347?redirect=false)** and commented

it would be great to have dynamic-properties option such as OGM annotation `@Properties`

`[Neo4j-OGM manual](https://neo4j.com/docs/ogm-manual/current/reference/#reference:annotating-entities:node-entity:dynamic-properties)`

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/neo4j/sdn-rx/issues/213

**Comment by Agh42** [comment]
Any new developments on this issue?  I feel that missing the ability to easily save custom properties on a node (like it is possible with OGM or native Cypher queries) is a major miss in an otherwise excellent library.
Is there any proposed way of how to save dynamic properties on individual nodes while using SDN-RX?

**Comment by meistermeier** [comment]
Thanks for the friendly overall feedback :)
I think that the existence of `@CompositeProperty` (https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom.conversions.composite-properties) might brighten your day. An example domain class annotated with the composite properties can be found here: https://github.com/spring-projects/spring-data-neo4j/blob/872a53648bb3e63f02e981482d60340ad2a6c73e/src/test/java/org/springframework/data/neo4j/integration/shared/conversion/ThingWithCompositeProperties.java
If this is not what you are looking for feature-wise, I leave the ticket open for feedback.

**Comment by Agh42** [comment]
This is exactrly what I was looking for - damn I looked up and down through the reference docs and missed it. Thanks a lot!!

**Comment by meistermeier** [comment]
Thanks for your feedback.

**Comment by michael-simons** [comment]
For completeness, we also have [`@DynamicLabels`](https://github.com/spring-projects/spring-data-neo4j/blob/872a53648bb3e63f02e981482d60340ad2a6c73e/src/test/java/org/springframework/data/neo4j/integration/shared/common/EntitiesWithDynamicLabels.java#L55) and [dynamic relationships](https://github.com/spring-projects/spring-data-neo4j/blob/872a53648bb3e63f02e981482d60340ad2a6c73e/src/test/java/org/springframework/data/neo4j/integration/shared/common/PersonWithRelatives.java#L64-L70).
