### ISSUE TITLE
NullPointerException in Neo4jConfiguration

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-data-neo4j#191]
`Neo4jConfiguration` seems to omit to call `afterPropertiesSet()` on its `MappingInfrastructureFactoryBean`, so when it is used directly to create a `Neo4jTemplate` ([here]()) there is always a `NullPointerException`. I can work around it by overriding a method:

```java
	@Override
	public MappingInfrastructureFactoryBean mappingInfrastructure() throws Exception {
		MappingInfrastructureFactoryBean mapping = super.mappingInfrastructure();
		mapping.afterPropertiesSet();
		return mapping;
	}
```

but maybe it would be better for `Neo4jConfiguration` to inject a `MappingInfrastructure` as a method parameter instead of trying to use the `FactoryBean` instance directly:

```java
   @Bean
    public Neo4jTemplate neo4jTemplate(MappingInfrastructure mappingInfrastructure) throws Exception {
        return new Neo4jTemplate(mappingInfrastructure);
    }
```

**Comment by mangrish** [comment]
Closed. Issue out of date.
