### ISSUE TITLE
Provide a way for defining dynamic queries in a type safe way.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1911]
We can support the creation of dynamic and type safe queries with the following addition:

* Use the Cypher-DSL 2021.1.0 [Query-DSL](https://github.com/neo4j-contrib/cypher-dsl/pull/167) support and provide a Neo4j specific implementation of `QuerydslPredicateExecutor`
* Provide a native `CypherdslConditionExecutor` that has basically the same signatures as above, but Cypher-DSL conditions instead of Query-DSL predicates 
* Provide `CypherdslStatementExecutor` and `ReactiveCypherdslStatementExecutor` that works on full statements and also support projections.

Original ticket was  **[DATAGRAPH-1349](https://jira.spring.io/browse/DATAGRAPH-1349?redirect=false)**

**Comment by michael-simons** [comment]
Evaluate a way to provide something analog to `QuerydslJpaPredicateExecutor` and `QuerydslJpaRepository` like we seen in Spring Data JPA.
