### ISSUE TITLE
Possible performance decrease when using dynamic relationships. [DATAGRAPH-1372]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1935]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1372](https://jira.spring.io/browse/DATAGRAPH-1372?redirect=false)** and commented

With the latest version of SDN 6.0.0-M2, I have below observation as of now. When we go with either dynamic relationship or Relationship Properties, records are saving in database quickly, but retrieval taking more time compared to Old SDN 5.3.3 version.

In new version, below are the syntaxes to create either dynamic relationship or Relationship Properties,

Syntax for relationship with properties: Below syntax represents `Sponsor` relationship between two member nodes. `MemberSponsor` entity contains all relationship properties.

```java
@Relationship(value = "sponsor", direction = Relationship.Direction.OUTGOING)
private Map<Member, MemberSponsor> hasSponsor = new HashMap<>();
```

Syntax for dynamic relationship without any properties: Below syntax represents `Sponsor` relationship between two member nodes. In the Map, key-String represents the relationship name, that we can configure dynamically.

```java
@Relationship(direction = Relationship.Direction.OUTGOING)
private Map<String, Member> sponsors = new HashMap<>();
```

When I am trying to get `Member` data using below JPA method, system taking more time when any of the above relationships exists in the `Member` entity class. It is taking 25 mins to get the single `Member` data using below method from latest version SDN 6.0.0. In old version SDN 5.3.3 – getting same member data within a second. This issue especially occurring only when there is a relationship exists between two nodes with same labels. Here, we are referring relationship between two member nodes of same label.

```java
import org.springframework.data.neo4j.repository.Neo4jRepository;

public interface MemberRepository extends Neo4jRepository<Member, Long> {
Member findByMemberId(String memberId);
}
```

Can you please help me on this. Seems like issue with retrieval when there is a Dynamic relationship on entity

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/spring-projects/spring-boot/pull/22299#issuecomment-686233981

**Comment by michael-simons** [comment]
Closing due to missing further feedback.
