### ISSUE TITLE
Update CI jobs for Java 15 [DATAGRAPH-1383]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1945]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGRAPH-1383](https://jira.spring.io/browse/DATAGRAPH-1383?redirect=false)** and commented

---
No further details from [DATAGRAPH-1383](https://jira.spring.io/browse/DATAGRAPH-1383?redirect=false)

**Comment by meistermeier** [comment]
Closing this because there are Java 15 builds.
