### ISSUE TITLE
Resolve neo4j.core <->  neo4j.repository.support package cycle [DATAGRAPH-1398]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1959]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGRAPH-1398](https://jira.spring.io/browse/DATAGRAPH-1398?redirect=false)** and commented

`Neo4jPersistenceExceptionTranslator` in the `neo4j.repository.support` (previously `neo4j.repository.core`) package creates a package cycle between `neo4j.core` and `neo4j.repository` packages.

Conceptually, the exception translator doesn't belong to the repository infrastructure as it primarily serves exception translation in `DefaultNeo4jClient`.

It would make sense to revisit the exception translator for version 6.1+ to deprecate the existing exception translator and introduce its proper replacement in `neo4j.core`

---

**Affects:** 6.0 RC1 (2020.0.0)

**Comment by michael-simons** [comment]
Good catch, thanks @mp911de
