### ISSUE TITLE
Implement @Transactional(timeout) [DATAGRAPH-1410]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1971]
**[pecollet](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50567)** opened **[DATAGRAPH-1410](https://jira.spring.io/browse/DATAGRAPH-1410?redirect=false)** and commented

Transaction timeouts passed through the `@Transactional` annotation are currently ignored.

It would be useful to pass those down to the Neo4j driver (https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/TransactionConfig.html timeout), so SDN clients can benefit from transaction level timeouts.

 

On pre Neo4j 4.1 versions, transaction timeouts are one of the most effective ways to limit excessive resource consumption on the server

---

**Affects:** 5.3.4 (Neumann SR4)

**Comment by michael-simons** [comment]
We cannot due this in OGM without making OGM dependent of SDN 5.
