### ISSUE TITLE
Build is failing and PR says "All checks have passed." [DATAGRAPH-1432]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1994]
**[Michael Simons](https://jira.spring.io/secure/ViewProfile.jspa?name=michael.simons)** opened **[DATAGRAPH-1432](https://jira.spring.io/browse/DATAGRAPH-1432?redirect=false)** and commented

Please see this PR https://github.com/spring-projects/spring-data-neo4j/pull/554

 

It fails due to various causes and Jenkins actually is aware https://jenkins.spring.io/view/SpringData/job/spring-data-neo4j/job/issue%252FDATAGRAPH-1428/4/

 

The Pr check should not indicate that things are good

---
No further details from [DATAGRAPH-1432](https://jira.spring.io/browse/DATAGRAPH-1432?redirect=false)

**Comment by michael-simons** [comment]
Ping.

**Comment by michael-simons** [comment]
I am unsure if this is solved or not but I do want to get the ticket out of my sight… I assume the Jenkins ping to GH works.
