### ISSUE TITLE
Spring Data not populating Relationships with ID [DATAGRAPH-1444]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2006]
**[Marcos Stival](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50721)** opened **[DATAGRAPH-1444](https://jira.spring.io/browse/DATAGRAPH-1444?redirect=false)** and commented

After upgrading to Spring Boot 2.4.0 (so using SDN 6.0.1) I got some problems.

There's no **`@RelationshipEntity`** anymore so I guess in my code I should change it to **`@RelationshipProperties`**.

 

After searching the documentation I can't figure how to make it return the id property of a relationship. +Before the version upgrade, every relationship property was returned correctly, now it doesn't.+

I tried to add a **`@Property`** annotation to the id field, but an Exception was raised by Spring.

The id field is annotated with **`@Id`** and **`@GeneratedValue`**

 
 
 
 

---

**Affects:** 6.0.1 (2020.0.1)

**Comment by michael-simons** [comment]
Related to #2118 Id properties will be filled very soon.

**Comment by mrksph** [comment]
Nice! @michael-simons

**Comment by meistermeier** [comment]
Is this solved for you with the latest version?

**Comment by meistermeier** [comment]
Closing this because there were no new input and the issue seems to be solved in general.
