### ISSUE TITLE
Support reactive SpEL execution and extensions. [DATAGRAPH-1455]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2017]
**[Michael Simons](https://jira.spring.io/secure/ViewProfile.jspa?name=michael.simons)** opened **[DATAGRAPH-1455](https://jira.spring.io/browse/DATAGRAPH-1455?redirect=false)** and commented

---

**Affects:** 6.0.1 (2020.0.1)

**Comment by michael-simons** [comment]
Not doing until someone explicitly asks for it.
