### ISSUE TITLE
Update CI jobs with Docker Login [DATAGRAPH-1461]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2022]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAGRAPH-1461](https://jira.spring.io/browse/DATAGRAPH-1461?redirect=false)** and commented

---
No further details from [DATAGRAPH-1461](https://jira.spring.io/browse/DATAGRAPH-1461?redirect=false)

**Comment by meistermeier** [comment]
Already done.
