### ISSUE TITLE
Projection not working with Kotlin data class [DATAGRAPH-1468]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2029]
**[BreadAndRoses95](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50756)** opened **[DATAGRAPH-1468](https://jira.spring.io/browse/DATAGRAPH-1468?redirect=false)** and commented

Hello,

 

When a data class has non nullable relationship properties, and we try to fetch it using a projection not referencing those specific relationships, SDN throws an error showing that it tries to use the main repository entity (probably using labels) and not the projection to build the object.

Have you ever faced it, and do you know about a workaround please?

 

Have a nice day

---

**Affects:** 6.0.2 (2020.0.2)

**Comment by meistermeier** [comment]
@BreadAndRoses95 (if you think, you are the wrong user, please feel free to ignore this message)
This is unfortunately not possible out-of-the-box.
When using projection, Spring Data has to create an instance of the entity itself first to then project the values.
There are three options:
First option:
```
@Node
data class MyEntity(@Id @GeneratedValue val id: Long,
                    @Relationship("RELATED_TO") val rel: MyRelatedEntity)
```
has to become _nullable_ 
```
@Node
data class MyEntity(@Id @GeneratedValue val id: Long,
                    @Relationship("RELATED_TO") val rel: MyRelatedEntity?)
```
Second option:
Adding the relationships to the projection to get them included in the generated Cypher statement.
Third option:
Write you own Cypher statement that returns also the relationship to get an instance of the entity correctly setup.
Forth option:
In case you have a collection-based relationship. You provide a secondary constructor like this:
```
@Node
data class MyEntity(@Id @GeneratedValue val id: Long,
                    @Relationship("RELATED_TO") val rel: List<MyRelatedEntity>) {

    @PersistenceConstructor
    constructor(id: Long): this(id, value, ArrayList())
}
```
