### ISSUE TITLE
GraphEntity ConversionService issue

### ISSUE THREAD

**Issue by jkliff** [spring-projects/spring-data-neo4j#203]
I have a GraphProperty of non primitive type for which a Converter is defined. I have a query that fetches that value, and I see that it was correctly executed and the value was brought back to the Repository. Upon conversion (QueryResultBuilder$1.underlyingObjectToObject) it fails with an MappingException: Unknwon persistent entity... 

I traced taht EntityResultConverter.doConvert fails to reach conversionService.convert(value, targetType), already upon checking template.isNodeEntity(targetType), when it attempts to Neo4jMappingContext.cacheType, since strict is true. 

I haven't set strict to true and I wouldn't mind having it set to true (which I don't see as a bad thing in this context). I just have the feeling the order of evaluation is not right, or I am not setting something correctly (for instance, strict to false).

As I understand strict to be by default false, and I am not setting it to true, I see some interaction messing this up. 

I indeed have a feeling of bad asymmetry here, since the mapping from MyObject to String (done when persisting) succeeds, but the opposite fails.

Is this a bug or should I do something differently?
If I were to set strict to false, how would I go about doing that in a sane manner? Would there be any other impact?

**Comment by mangrish** [comment]
Closed. Issue out of date.
