### ISSUE TITLE
Bidirectional RelationshipProperties persist ends up in StackOverflow. [DATAGRAPH-1469]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#2030]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1469](https://jira.spring.io/browse/DATAGRAPH-1469?redirect=false)** and commented

If a bidirectional relationship e.g. 

```java
class User {
    @Relationship("KNOWS")
    private final List<UserRelationship> knows;
}

User user1;
User user2;

user1.knows(user2);
user2.knows(user1);
 
```

gets persisted and the relationship is defined as a relationship with properties, SDN will run into a StackOverflow.

This works perfectly for direct relationships

---

**Affects:** 6.1 M1 (2021.0.0), 6.0.2 (2020.0.2)

**Backported to:** [6.0.3 (2020.0.3)](https://github.com/spring-projects/spring-data-neo4j/milestone/215?closed=1)

**Comment by Lishuaihu-222613** [comment]
The problem still exist
