### ISSUE TITLE
Document manual query creation. [DATAGRAPH-1471]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#2032]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1471](https://jira.spring.io/browse/DATAGRAPH-1471?redirect=false)** and commented

Missing in the docs is how to formulate Cypher queries so that their result can be mapped by correctly by SDN

---
No further details from [DATAGRAPH-1471](https://jira.spring.io/browse/DATAGRAPH-1471?redirect=false)

**Comment by meistermeier** [comment]
Closed by c1422f4 and 1f5d958
