### ISSUE TITLE
Declare the dependency between shared session creator and entity instantiator.

### ISSUE THREAD

**Issue by steffen-harbich-cognitum** [spring-projects/spring-data-neo4j#2099]
I have a database migration script component as in the following code:

```
@Component
public class MigrationLogic {

    // + autowired repositories

    @PostConstruct
    @Transactional
    public void run() {
        // running migration logic, storing entities that rely on converter registered to ConversionService
    }
}
```

Produces the NullPointerException:

> Caused by: java.lang.NullPointerException: null
> 	at org.neo4j.ogm.typeconversion.ProxyAttributeConverter.toGraphProperty(ProxyAttributeConverter.java:56) ~[neo4j-ogm-core-3.2.18.jar:3.2.18]
> 	at org.neo4j.ogm.metadata.FieldInfo.readProperty(FieldInfo.java:492) ~[neo4j-ogm-core-3.2.18.jar:3.2.18]

This is because `Neo4jOgmEntityInstantiatorConfigurationBean` has not been initialized at that point. I would expect it to be initialized once the repositories are available as spring bean. I need to run the migration script before tomcat embedded is opening REST API ports, so I cannot use an event like "context refreshed" to do the migration.

Workaround: Add
```
    @Autowired()
    @Qualifier("org.springframework.data.neo4j.repository.config.Neo4jOgmEntityInstantiatorConfigurationBean#0")
    private Object workaround;
```
which is of course an unwanted hack.

**Comment by steffen-harbich-cognitum** [comment]
Yes, I am struggling with the order of initialization of spring beans. @Order was not working.

**Comment by michael-simons** [comment]
Could you please post an example of your converter logic?

**Comment by michael-simons** [comment]
Yeah, I can work with that.

Btw, I hope you don't have that base class in production:

```java
@NodeEntity
public abstract class EntityBase {

    @Id
    @GeneratedValue
    private Long graphId;

    @Id
    @GeneratedValue(strategy = UuidStrategy.class)
    private String uuid;
}
```

This is 100% guaranteed to cause pain somewhere. You are basically defining two ids here.

**Comment by michael-simons** [comment]
What that work for you?

```java
@Component
public class MigrationLogic implements ApplicationListener<ContextRefreshedEvent> {

    private @Autowired ThingRepository userRepository;
    
    @Override
    public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
        // Do your migration
    }
}
```

Otherwise I would like to pull in @mp911de here. I have no idea why the thing is picked up too late.

**Comment by steffen-harbich-cognitum** [comment]
As stated in the initial comment, I cannot use `ContextRefreshedEvent` because it's too late. 

Regarding the two IDs: I need the UUID as usual ID. The graph ID is needed because I do some manual wiring of configured (not known at compile time) relations when quering and the query is returning `org.neo4j.ogm.model.Edge` which is based on graph IDs but not on user-defined IDs. For now, there were no troubles with this but if you have a better solution in mind, please tell me :)

Thanks for looking into the issue.

**Comment by michael-simons** [comment]
This is fixed and will be included in the next patch releases in February. Thank you for your contribution, @steffen-harbich-cognitum
