### ISSUE TITLE
Cannot map path using SDN 6.0.3

### ISSUE THREAD

**Issue by sureshpw** [spring-projects/spring-data-neo4j#2128]
Similar to issue: #2119. But using `apoc.path.expand` to get all the paths. 
Given a sample model: https://neo4j.com/labs/apoc/4.1/graph-querying/expand-paths/
```
MATCH (p:Person {name: "Alicia"})
CALL apoc.path.expand(p, "FOLLOWS>|KNOWS", ">Engineering", 1, 3)
YIELD path
RETURN path
```
Previously this can be mapped using a custom `@Query` returning a `Person` node (Spring Boot 2.3.4). That in turn will contain all the relationships and connected nodes. With Spring Boot 2.4.2 and SDN 6.0.3 it is not working.

**Comment by meistermeier** [comment]
Neo4j-OGM that was used in SDN version < 6 collected all the returned data and mapped it in a batch afterwards.
With targeting real immutability and reactive support in SDN 6, this cannot be done anymore but needs a more record-oriented.
As you have seen at the other issue(s) we currently improving the path mapping but you need also to take action and return a list of path by collecting all resulting parts (`collect(path)`).
You could include the vmware snapshot repositories 
```
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
```
and try the `6.0.4-SNAPSHOT` with the updated query. Would be helpful to get any feedback from your side if this would work or more improvements are needed. Our situation is that we cannot foresee all the ways users create paths. Our improvement unifies paths but there could also be some data inside the path objects that might lead to problems and we are eager to fix those for you.

**Comment by sureshpw** [comment]
Thanks for the suggestion. Snapshot works fine on one-to-many relationships. But not fetching one-to-one relationships
```
Node("A")
class A {
    @Relationship("TO_B")
    B b;

    @Relationship("TO_C")
    Set<C> cset;
}
```
In this case `collect(path)` correctly obtains all the elements of `cset`. But not the `TO_B` relationship.

**Comment by mrksph** [comment]
Wow, just found this. It really broke our expand functionality. Thanks for the collect tip

**Comment by meistermeier** [comment]
@sureshpw could you provide the query you are using to retrieve A, B and C?

@mrksph That is all due to the record-focused mapping as described in https://github.com/spring-projects/spring-data-neo4j/issues/2128#issuecomment-767389195 
This was done intentionally because this is the only way that allows us to not brake a (possible) reactive flow.

**Comment by sureshpw** [comment]
Not only the `collect(path)` one-to-one relationships, the grand children also not returned. Here is a sample project reproducing these problems:

https://github.com/sureshpw/neo4j-path-issue

**Comment by mrksph** [comment]
@meistermeier Hi Gerrit, if I use "collect(path)" when expanding a node that has many (14k+) relationships I cant LIMIT the results because they are one big row. 

How could I do it?

**Comment by meistermeier** [comment]
@sureshpw There were a problem with the snapshot repository. It did not pick up the latest changes. I re-published the current 6.0.4-SNAPSHOT and from what I see with your test project, everything seems to work. I even migrated the `Child` and `GrandChild` relationships from `Set` to a scalar one and the result stayed the same.

```
>>>From APOC Path>>>Neo4jApplication.Person(id=20, name=person-1, location=Neo4jApplication.Location(id=23, address=123 Main Street), children=Neo4jApplication.Child(id=21, name=child-1, grandChildren=Neo4jApplication.GrandChild(id=22, name=gchild-1)))
```

**Comment by sureshpw** [comment]
Great. @meistermeier I ran the tests again and seeing the correct results. Do you know what is the timeline for next release of SDN with these fixes? Thanks

**Comment by meistermeier** [comment]
I do not have any official at hand (the calendar is down) but since the next milestone of the next released is scheduled for Feb.,17th (https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-2021.0-(Pascal)) I assume that also the next service release of 2020.0 will happen that day.
