### ISSUE TITLE
Relationship type is not working 

### ISSUE THREAD

**Issue by prabjot678** [spring-projects/spring-data-neo4j#213]
I am using GraphAlgoFactory to find paths . so there , i am facing one issue ,unable to understand RelationshipType   is there

GraphAlgoFactory.dijkstra(
    PathExpanders.forTypeAndDirection( RelationshipType Type, Direction.BOTH ), "cost" );

how can i get RelationshipType object here .

#####my entity node is ####

package neo4j

import org.neo4j.graphdb.Direction
import org.springframework.data.neo4j.annotation.GraphId
import org.springframework.data.neo4j.annotation.NodeEntity
import org.springframework.data.neo4j.annotation.RelatedTo
import org.springframework.data.neo4j.annotation.RelatedToVia

@NodeEntity
class Person {
@GraphId Long graphId;

   String name;
   String availble;
   int distance
   
  
    @RelatedToVia(type="FOLLOW",direction=Direction.OUTGOING)
  Set<Person> followers
  
  @RelatedTo(type="FOLLOW",direction=Direction.OUTGOING)
  Set<Person> followers
}
###
Relationship is there

import org.springframework.data.neo4j.annotation.EndNode;
import org.springframework.data.neo4j.annotation.GraphId;
import org.springframework.data.neo4j.annotation.RelationshipEntity;
import org.springframework.data.neo4j.annotation.StartNode;

@RelationshipEntity(type="FOLLOW")
class PersonRelationship {

	@GraphId Long graphId;
	@StartNode Person person
	@EndNode Person  person1
}

Person person=new Person()
PersonRepository.save(person)

Person person1=new Person()
PersonRepository.save(person1)

def person1=PersonRepository.findByName("kartik");
		def person=PersonRepository.findByGraphId(75572);

PathFinder<Path> finder = GraphAlgoFactory.shortestPath(
			PathExpanders.forTypeAndDirection(RelationshipType type , Direction.OUTGOING ),2 );
		
		println finder 
		Iterable<Path> paths = finder.findAllPaths( person, person1 );

**Comment by mangrish** [comment]
Closed. Issue out of date.
