### ISSUE TITLE
Duplicate relation when querying after an update

### ISSUE THREAD

**Issue by AlexPresso** [spring-projects/spring-data-neo4j#2130]
Hey there,
I'm getting relation duplicates when using the repository to find an entity I just saved for a `RelationshipEntity` interpreted in both directions (in two different nodes). 

I supposed the two directions could make it an ambiguous relation, but the problem only occurs when I'm saving the entity and querying it again in the same service (probably using the same session). It's also only doubling the first relation, not the others.

Am I doing something wrong ?

The relation content is the exact same as the duplicate one but it's not referencing the first one, it's stored in a new memory address:

![Sans titre](https://user-images.githubusercontent.com/15526962/105864072-d75ebf80-5ff1-11eb-977f-6f8060e25acc.png)
PS: relations aren't doubled in database

Entities:
```Java
public class Entity extends BaseNode {
    @Relationship(value = "ATTRIBUTE")
    protected List<AttributeRelation> attributeRelations;
    //...
}
```
```Java
@RelationshipEntity(value = "ATTRIBUTE")
public class AttributeRelation {
    @StartNode
    private BaseNode source;
    @EndNode
    private BaseNode target;
    private boolean reference;

   //...
}
```
```Java
@NodeEntity
public abstract class BaseAttribute {
    @Relationship(value = "ATTRIBUTE", direction = Relationship.INCOMING)
    private AttributeRelation parentRelation;
   //...
}
```
Controller:
```Java
@PatchMapping("/{id}")
public APIResponse editEntity(/* args */) {
    final BaseEntity entity = entityService.editEntity(entityRequest, id);
    return new APIResponse("Edited entity", entityDetailService.getEntityFullDetail(entityService.find(entity.getId())));
}
```
(I'm aware I could directly pass the entity to the `getEntityFullDetail` method, but it's an example.)

**Comment by michael-simons** [comment]
Hi. Thank you for opening the ticket.

Can you please share your orchestrating code? The one that calls the repositories or the OGM session?

**Comment by michael-simons** [comment]
Can it be that you have some custom queries in between? If so, please have a look here https://github.com/neo4j/neo4j-ogm/issues/868#issuecomment-775773283 and consider adding a hint to the query: `/*+ OGM_READ_ONLY */` (Just after a match or call)

**Comment by AlexPresso** [comment]
Hi,
I had a look at it, there's no custom queries in between in this service, there are some in the repository but they aren't called in this service

Sure, here is the orchestrating code:
It starts by the controller (Spring RestController) when receiving an HTTP request:
```Java
@PatchMapping("/{id}")
public APIResponse editEntity(/* args */) {
    final BaseEntity entity = entityService.editEntity(entityRequest, id);
    return new APIResponse("Edited entity", entityDetailService.getEntityFullDetail(entityService.find(entity.getId())));
}
```
Then it calls the service and returns the edited entity:
```Java
    @Override
    @Transactional
    public BaseEntity editEntity(final EntityCreationParameters entityParameters, final Long id) throws BaseCustomException, ReflectiveOperationException, JsonProcessingException {
        BaseEntity entity = this.find(id); //method using default Neo4jRepository<BaseEntity, Long>::findById with an orElseThrow

        final Map<String, BaseAttribute> entityAttributes = entity.getAttributes()
            .stream()
            .collect(Collectors.toMap(BaseGraphObject::getUuid, attr -> attr));

        for (AttributeCreationParameters attribute : entityParameters.getAttributes()) {
            final BaseAttribute createdOrUpdated = this.workNodeService.setAttributeValue(entity,
                attribute.getUUID(),
                attribute.getValue()
            ); //no OGM repo nor query usage (directly uses getters/setters)
        }

        this.validateCardinalities(entity);  //no OGM repo nor query usage (directly uses getters/setters)
        this.workNodeService.updatePrivateKey(entity); //no OGM repo nor query usage (directly uses getters/setters)

        final BaseEntity edited = this.entityRepository.save(entity);
        this.eventPublisher.publishEvent(new EntityEditedEvent(this, null, edited));

        return edited;
    }
```
At this point, the returned entity doesn't have any duplicates. But now if I do another `EntityService::find` (method using default Neo4jRepository<BaseEntity, Long>::findById with an orElseThrow), it gives me the entity with duplicates.

Here are the libs versions if it gives you more infos:
- spring-boot-starter-web: 2.2.4.RELEASE
- spring-boot-starter-data-neo4j: 2.2.4.RELEASE
- spring-boot-starter-parent: 2.2.4.RELEASE

**Comment by michael-simons** [comment]
Thanks for the details. Looks correct. Also correct usage of returning the save entity. 

The next find, does it happen in the same or a new transaction?

Also, do you have open session in view enabled or not?

**Comment by AlexPresso** [comment]
does it happen in the same or a new transaction?
It was done in the controller directly (outside the service transaction) so I would say in a different one, but I'm not sure

Also, do you have open session in view enabled or not?
I don't have any setting to set it off, is it enabled by default ? do I need to disable it even if I'm only using Spring data Neo4J ?
