### ISSUE TITLE
SDN6.0.3 findBy* methods slowing down heavily for a small number of nodes.

### ISSUE THREAD

**Issue by vhh23** [spring-projects/spring-data-neo4j#2131]
SDN 6.0.3, After creating a bi-directional relationship between the same Node Entities, for eg A-Follows->B and B-Follows->A, When you load the Node A via FindById method it slows down and takes seconds to fetch just one node. This can be due to self-referencing relationships.
StackOverFlow Question link - https://stackoverflow.com/questions/65941539/spring-data-neo4j-sdn-6

**Comment by meistermeier** [comment]
We changed the path-based queries now to cascading matches. It will still look for everything that is reachable with the given domain model but returns a result (#2140)
