### ISSUE TITLE
Remove `o.s.d.annotation.Persistent` from the set of identifying annotations.

### ISSUE THREAD

**Issue by K-Lovelace** [spring-projects/spring-data-neo4j#2133]
I encountered an issue while working with multiple data sources. 
I just upgraded from the old Spring SDN/RX to spring-boot-starter-data-neo4j 2.4.0.
I have multiple data providers from Mongo, and I use Neo4j on the side for other operations non-repositories related.
On my main class, I have the following annotations:
```
@EnableCaching
@SpringBootApplication
// BEWARE: Point to a non-existent package to avoid having all repositories scanned as Neo4j repositories
@EnableReactiveNeo4jRepositories({"com.example.project.none"})
@EnableReactiveMongoRepositories({"com.example.project.data", "com.example.project.provider.mongo", "com.example.project.provider.parcours"})
```
If I remove the `@EnableReactiveNeo4jRepositories` line, every Repository in my project will be marked as Neo4j repository and the build will crash. I do not want to enable neo4j repositories at all, but am forced to make it look in an inexistent package for the project to work.

Is this by design ? Am I missing something obvious ?

**Comment by michael-simons** [comment]
Hi.

Thanks for the report and sorry for the issues.

Can you please share 

* Configuration classes
* The stack trace(s) of the failing build (I guess you probably mean run)

Thanks.

**Comment by K-Lovelace** [comment]
Hi, here is the configuration class: (I hope this is what you wanted) : 
```
@Configuration
@EnableTransactionManagement
public class TxConfig {
    final Driver driver;

    public TxConfig(Driver driver) {
        this.driver = driver;
    }

    @Bean
    public ReactiveTransactionManager reactiveTransactionManager() {
        return new ReactiveNeo4jTransactionManager(driver);
    }
}
```
And here is the stack trace:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'parcoursMongoRepository', defined in com.example.project.provider.parcours.ParcoursMongoRepository defined in @EnableReactiveNeo4jRepositories declared on Neo4jReactiveRepositoriesRegistrar.EnableReactiveNeo4jRepositoriesConfiguration, could not be registered. A bean with that name has already been defined in com.example.project.provider.parcours.ParcoursMongoRepository defined in @EnableReactiveMongoRepositories declared on Poi and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

```

Please let me know if you need anything else.

**Comment by michael-simons** [comment]
Hi. I can reproduce the issue. It is somewhat related to https://github.com/spring-projects/spring-boot/issues/25069

While the bean in the Boot issue is not a valid `Node`, your's is.
That leads to the following scenario that we believe that your repository can be a Neo4j repository. We must do better checks here.

In the mean time, I recommend to set this

```
spring.data.neo4j.repositories.type=none
```

It will disable the Neo4j repository but still give you
* Driver
* Clients (Imperative / Reactive)
* Templates (Imperative / Reactive)
