### ISSUE TITLE
May be second parameter should be a allValues variable? 

### ISSUE THREAD

**Issue by chudok** [spring-projects/spring-data-neo4j#2134]
https://github.com/spring-projects/spring-data-neo4j/blob/f18e15a6b899cdcdf719e1bc68e61c4c4a7d7d3d/src/main/java/org/springframework/data/neo4j/core/mapping/DefaultNeo4jEntityConverter.java#L517

Because now, custom query returns nested collection of children only second level.  On third level of hierarchy, list is always null

**Comment by meistermeier** [comment]
Thanks for spotting this and notifying us.
The current 6.0.3 does already include the fix https://github.com/spring-projects/spring-data-neo4j/blob/6.0.3/src/main/java/org/springframework/data/neo4j/core/mapping/DefaultNeo4jEntityConverter.java#L520
This should work also for the nested collections. Please tell us if this works for you.

**Comment by chudok** [comment]
Fix was for 520 line. Here I guess the problem is in line 517
![image](https://user-images.githubusercontent.com/12711129/106599386-08973c80-656a-11eb-8ba5-f3d376b12e51.png)

**Comment by meistermeier** [comment]
Thanks for spotting and sorry for the confusion.This is also fixed since last month in 6.0.x and main.
