### ISSUE TITLE
Add support for custom RelationshipProperties Label

### ISSUE THREAD

**Issue by K-Lovelace** [spring-projects/spring-data-neo4j#2136]
Hi there,

I have been struggling with RelationshipProperties annotation:

I have the following relation: 
```
    @Relationship(value = ReferencesRelationship.TYPE, direction = Relationship.Direction.INCOMING)
    private List<ReferencesRelationship> partners;
```
and the following bean:
```
@AllArgsConstructor
@NoArgsConstructor
@RelationshipProperties
@Data
public class ReferencesRelationship {
    public static final String TYPE = "REFERENCES";

    @JsonProperty("is_optin")
    @Property("is_optin")
    Boolean isOptin;

    @TargetNode
    public ApplicationNode partner;
}
```

When I use CrudRepository save method and I pass an empty list as `partners`, it builds a query to delete the relationships (good!)

But the relationship looks like this:
```
MATCH (startNode)<-[rel:`REFERENCES`]-(:`ReferencesRelationship`) WHERE id(startNode) = $fromId DELETE rel
```

When I want it to be : 

```
MATCH (startNode)<-[rel:`REFERENCES`]-(:`ApplicationNode`) WHERE id(startNode) = $fromId DELETE rel
```

Is it possible ? Am I doing something wrong ? 

Also, how would I query this relation in the opposite direction (from ApplicationNode model) ? It's all too confusing for me...

Thanks for the response!

**Comment by meistermeier** [comment]
Could you please tell me which version you are using? I have the slight feeling that I had my hands on this issue before and solved it but cannot find the patch for this.
Maybe also you have the chance to try out the next version 6.0.4-SNAPSHOT of SDN.
But for certain I will have a deeper look and try to figure out if the behaviour is still faulty.

**Comment by K-Lovelace** [comment]
Hi @meistermeier, I am using spring-data-neo4j 6.0.3. I'll try the snapshot and get back to you

**Comment by K-Lovelace** [comment]
I can't find your Snapshot, anywhere, any idea how I can test it ?

**Comment by meistermeier** [comment]
Sorry, I forgot the answer. You have to add Spring's snapshot repository.
```
  <repositories>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

**Comment by meistermeier** [comment]
Could you give an update on this issue? Spring Data Neo4j 6.0.5 is released since a few weeks.
I am pretty sure that this will fix your problem but would be good to get your input on this.

**Comment by meistermeier** [comment]
I assume that this is solved. Please feel free to re-open it, if the problem still exists.
