### ISSUE TITLE
how to define RelationshipEntity property in spring boot 2.4

### ISSUE THREAD

**Issue by wurangbo** [spring-projects/spring-data-neo4j#2163]
Hi guys，
    We have an existing application which is working fine with the SpringBoot 2.2.2.RELEASE. Now we tried to upgrade it to the 
    SpringBoot 2.4.2 version and found properties such as @NodeEntity @RelationshipEntity ,@QueryResult, @StartNode,  
    @EndNode not working. How can we fix？

@NodeEntity(label = "ResourceNode")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ResourceNode {
    @Id
    @GeneratedValue
    private Long id;

    private Long globalResourceId;

    private String globalResourceName;
}

@RelationshipEntity(type = "ResourceNodeRelation")
@Data
@QueryResult
public class ResourceNodeRelation {
    @Id
    @GeneratedValue
    private Long id;

    @StartNode
    private ResourceNode startNode;

    @EndNode
    private ResourceNode endNode;
}
  
@Query("match (n:ResourceNode)-[r:ResourceNodeRelation*]-(m:ResourceNode) where n.globalResourceId={resourceId} 
return  (COLLECT(m)+COLLECT(n)) as relatedNodes")

**Comment by hadiyarajesh** [comment]
@NodeEntity -> @Node
@RelationshipEntity -> @Relationship
@QueryResult, @StartNode, @Endnode -> Removed from SDN. You can use embedded native Neo4jClient if required for such operations.

**Comment by meistermeier** [comment]
I just add for `@QueryResult` you can also go with projections if they project fields of your defined entities.

There is also a section in the reference documentation that helps you with the migration https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#migrating.preparation

If you have any further questions, we can help you either over in our [community Discourse](https://community.neo4j.com/c/drivers-stacks/spring-data-neo4j-ogm/30) or [StackOverflow](https://stackoverflow.com/questions/tagged/spring-data-neo4j)
