### ISSUE TITLE
Replacement of @QueryResult

### ISSUE THREAD

**Issue by panxianhaoo** [spring-projects/spring-data-neo4j#2174]
In Spring Data Neo4j 6.0.5 I can't find @Queryresult. How can I map a result returned from neo4j.

**Comment by michael-simons** [comment]
`QueryResult` is not supported anymore.

You have a couple of options, for example using projections, combining open
dto projections with custom queries and some more.

Is that chapter helpful:
https://docs.spring.io/spring-data/neo4j/docs/6.0.5/reference/html/#faq.custom-queries-and-custom-mappings
(11.8)

Cheers,
Michael.

panxianhaoo ***@***.***> schrieb am Do. 11. März 2021 um
14:54:

**Comment by panxianhaoo** [comment]
Thank you very much, it helps me a lot

**Comment by alxxyz** [comment]
Sometimes we need to return some data, not nodes, and this is not supported by projections
