### ISSUE TITLE
SimpleNeo4jRepository does not implement Neo4jRepository

### ISSUE THREAD

**Issue by aaramg** [spring-projects/spring-data-neo4j#2180]
Hi.
I want to extend the Neo4jRepository interface with my own CommandBasedNeo4jRepository interface. 
So after that, I write CommandBasedNeo4jRepositoryImpl which implements CommandBasedNeo4jRepository. But there are contracts in Neo4jRepository that should be implemented. So for that, I extend SimpleNeo4jRepository which I guess should implement Neo4jRepository but instead, it implements PagingAndSortingRepository so I get some methods not implemented in that situation. And have to handle them by myself. I need this, to add my own methods, and instead of Neo4jRepository use my own CommandBasedNeo4jRepository.
I have experience with the same situation with MongoRepository so there SimpleMongoRepository implements MongoRepository. Please correct me if I miss smth. But I guess also the name SimpleNeo4jRepository says that it should implement Neo4jRepository. 

```
public interface CommandBasedNeo4jRepository<T, ID> extends Neo4jRepository<T, ID> {
// some methods
}
```

```
public class CommandBasedNeo4jRepositoryImpl<T, ID> extends SimpleNeo4jRepository<T, ID> implements CommandBasedNeo4jRepository<T, ID> {

    private final Neo4jOperations neo4jTemplate;
    private final Neo4jEntityInformation<T,ID> metadata;

    @Autowired
    public CommandBasedNeo4jRepositoryImpl(
        final Neo4jEntityInformation<T, ID> metadata,
        final Neo4jOperations neo4jOperations
    ) {
        super(neo4jOperations, metadata);
        this.neo4jTemplate = neo4jOperations;
        this.metadata = metadata;
    }
    
    // some methods
}
```
```
@Configuration
@EnableNeo4jRepositories(basePackages = "com.some.repo.package", repositoryBaseClass =
    CommandBasedNeo4jRepositoryImpl.class){
    // configs
  }
```

Thanks in advance.

**Comment by michael-simons** [comment]
I don't understand your question. The docs got you covered:

https://docs.spring.io/spring-data/neo4j/docs/6.0.5/reference/html/#faq.custom-base-repositories (Chapter 11.9)

if that isn't sufficient, here's a test demonstrating what you want to achieve:

https://github.com/spring-projects/spring-data-neo4j/blob/6.0.5/src/test/java/org/springframework/data/neo4j/integration/imperative/CustomBaseRepositoryIT.java#L67-L87

There are also easier and more flexible ways for custom fragments:

https://docs.spring.io/spring-data/neo4j/docs/6.0.5/reference/html/#faq.custom-queries-and-custom-mappings (Chapter 11.8)

I don't know about Spring Data Mongo and appearantly our friends from VMWare made the `@SimpleMongoRepository` extend the base interface. We didn't do this and we don't plan on doing so right now.

Please pick one of the supported ways linked above. What you are doing should work ootb as we add the missing methods via repository fragments transparently for you.

**Comment by aaramg** [comment]
hmm, ok got it. My fault. Was going the wrong way. :)
You can close this "issue". No more questions.
Thank you.

**Comment by michael-simons** [comment]
Thanks a lot for your feedback.
