### ISSUE TITLE
Add support for projections inside the Neo4j templates.

### ISSUE THREAD

**Issue by aaramg** [spring-projects/spring-data-neo4j#2182]
Hi. 
It would be great to have more helpful methods in Neo4jOperations -> Neo4jTemplate:
for ex:
batchOperations;
aggregations;
finding with geodata
findAndModify(Statement query, Statement update, Class<T> entityClass);
findAndRemove(Statement query, Class<T> entityClass)
mergeNode
createRelationship
mergeRelationship

save() method takes a long time(multiple seconds even) to save the whole hierarchy of for ex: User node (even if all the connected nodes already exist in Neo4j db). Would be great to have a single field update method smth like findAndModify which would accept a query Statement of what to find and a Statement of what to change. (This would be great if in the system concurrency happens)
I know that Cypher DSL can help a lot with a lot of these statements but would be nice to have builtin helper methods in Neo4jTemplate.

P.S> This inspiration comes from MongoTemplate and would be great to have some great helper methods in your awesome Neo4j world.
Thanks in advance. :)

**Comment by meistermeier** [comment]
Thanks for your idea. It somehow aligns with the thoughts we already have in mind.
A first starter would be a `saveJustTheEnittyWithoutLookingAtTheRelationships` (or a little bit shorter :smile: )

**Comment by aaramg** [comment]
Great to hear this :) Do you plan this to have sooner? Or it is very raw for now??

**Comment by aaramg** [comment]
Could you please help me to figure out which is the best way to execute modifying queries?
For example:
```
var mergeStatement = Cypher.merge(n)
    .onCreate().set(n.property("prop").to(Cypher.literalOf(0)))
    .merge(a.relationshipBetween(b, "T"))
    .onCreate().set(a.property("name").to(Cypher.literalOf("me")))
    .onMatch().set(b.property("name").to(Cypher.literalOf("you")))
    .returning(a.property("prop")).build();
```
The way I found to do it was:
 `neo4jClient.query(........).bindAll(......).fetchAs(......).all()`
 
 and also maybe the code below can work. Haven't tried yet. ))
```
neo4jTemplate.toExecutableQuery(PreparedQuery.queryFor(SomeClass.class).withCypherQuery(
            Cypher.merge(n)
                .onCreate().set(n.property("prop").to(Cypher.literalOf(0)))
                .merge(a.relationshipBetween(b, "T"))
                .onCreate().set(a.property("name").to(Cypher.literalOf("me")))
                .onMatch().set(b.property("name").to(Cypher.literalOf("you")))
                .returning(a.property("prop")).build().getCypher())
        );
```
I don't want to use save() as it takes really long time when there are a lot of relationships and nodes hierarchy in the entity object. I want to do a single field update or merge relationships manually, to get rid of a lot of checkings when save is called. 

1. Is there another more proper way to run that?? 
2. Is there a common mistake when using save? I mean that it could take multiple seconds for saving one node hierarchy? Maybe I am missing smth.

P.S. Save takes multiple seconds even if all the connecting nodes are already in DB and it only needs to connect them if there is not yet connections between nodes.

**Comment by michael-simons** [comment]
`client.query(mergeStatement).run()` will be integrated with Spring transaction and execute everything you like.

RE: Long time of ops: Might care to share your domain model?
