### ISSUE TITLE
Wrong link for composite properties

### ISSUE THREAD

**Issue by fbiville** [spring-projects/spring-data-neo4j#2183]
In the [current reference docs](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#mapping.annotations.overview.from.sdn), `[composite-properties]` points to https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#composite-properties, which leads to nowhere.

I assume the correct link is https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom.conversions.composite-properties?

**Comment by meistermeier** [comment]
I have also seen this while answering the older issue.. I will solve this in combination with  #2172

**Comment by meistermeier** [comment]
Solved with e87dbce
Already fixed in the main branch.
