### ISSUE TITLE
Bean validation is not working

### ISSUE THREAD

**Issue by prabjot678** [spring-projects/spring-data-neo4j#219]
I am doing bean validation. but it is not working. i have tried also javax validation's notnull and blank.
but it is not working there

Xml config is 

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:neo4j="http://www.springframework.org/schema/data/neo4j"
	xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd
            http://www.springframework.org/schema/context
            http://www.springframework.org/schema/context/spring-context.xsd
            http://www.springframework.org/schema/data/neo4j
            http://www.springframework.org/schema/data/neo4j/spring-neo4j.xsd">

	<context:component-scan base-package="neo4j"></context:component-scan>
 <neo4j:config
           storeDirectory="target/db"
           base-package="neo4j"/>

<bean id="validator"
class="org.springframework.validation.beanvalidation.LocalValidatorFactoryBean"/>

	<neo4j:repositories base-package="neo4j" />

</beans>
            

Dependecies are 

  dependencies {
        // specify dependencies here under either 'build', 'compile', 'runtime', 'test' or 'provided' scopes e.g.
        // runtime 'mysql:mysql-connector-java:5.1.29'
        // runtime 'org.postgresql:postgresql:9.3-1101-jdbc41'
        test "org.grails:grails-datastore-test-support:1.0-grails-2.4"
		compile 'org.springframework.data:spring-data-neo4j:3.2.0.RELEASE'
		compile 'org.hibernate:hibernate-validator:4.2.0.Final'
		compile 'javax.validation:validation-api:1.0.0.GA'
    }

Domain class is 

package neo4j

import javax.validation.constraints.NotNull
import javax.validation.constraints.Size;

import org.springframework.data.neo4j.annotation.GraphId
import org.springframework.data.neo4j.annotation.NodeEntity

@NodeEntity
class User {

   @GraphId Long graphId
   
   
   
   @Size(min = 3, max = 20)
   String name;
}
 

Controller is 

package neo4j

import javax.validation.Valid;

import org.springframework.transaction.annotation.Transactional;

class UserController {
	
	def UserRepository
	def Neo4jTemplate

	@Transactional
    def index() {
		
		User user=new User()
		user.setName("p")
		Neo4jTemplate.save(user)
		println "saved "
	}
}

**Comment by mangrish** [comment]
Closed. Issue out of date.
