### ISSUE TITLE
Dynamic Query with Template not hydrating relationships

### ISSUE THREAD

**Issue by mrksph** [spring-projects/spring-data-neo4j#2202]
Hi,

Im trying to use the Neo4jTemplate with a dynamic query. This dynamic query can have multiple where conditions, depending on the user inputs so a Custom Query won't work as I need to build it dynamically.

After building the query, I need to execute it against the database. First I tried using the Neo4jClient because of its flexibility to map the results into Domain Entities but although flexible, it's not as easy as I initially thought to map a Path into a Domain Entities List.

Here's an example query: 

MATCH p=(b:BaseHierarchy {code:"JQCLB00"})-[:INCLUDES]->(g:Group)-[:PARENT_OF*]->(c:Client) 
WHERE (g.code = "EMIRG" OR g.code = "BAESS") 
AND c.sector = "14" 
RETURN p, b, g, c
LIMIT 50

Which returns the following graph:

![image](https://user-images.githubusercontent.com/10486135/112817218-7a7b9600-9082-11eb-8d43-2a5d75b947b6.png)

I would like to know what is the easiest way to map that graph into my Domain Entities class. Using the Neo4jTemplate I can receive a List<ClientNode> but it won't return the relationships hydrated.

What am I doing wrong?

Thanks

**Comment by meistermeier** [comment]
There are a few things in there that makes it not possible for SDN to map it directly.
Let's get started:
First of all, the result has to be one record for each _BaseHierachy_ and the result from the query above will not fulfill this because you will end up with a cartesian product of _BaseHierarchy_, _Group_ and _Client_.
To mitigate this we advise the users to put the relationships and other nodes into a list https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-queries.for-relationships. 
In your case this is a little bit more special, because the obvious path you want to get as a result is not a single result but splits into multiple ones. Collecting this results naively e.g. `collect(nodes(p))` will end up in a list of list of relationships/nodes.
(Side note here: For a proper mapping, you have to also return the relationships like _INCLUDES_ and _PARENT_OF_ between the nodes)
Now comes the tricky part: Reducing the list of list construct.
There is no easy way to reduce this list but there is a `reduce` function in Cypher (https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-reduce)
```
MATCH path=(b:BaseHierarchy {code:'JQCLB00'})-[i:INCLUDES]->(g:Group)-[p:PARENT_OF*]->(c:Client) 
WHERE (g.code = 'EMIRG' OR g.code = 'BAESS') 
AND c.sector = '14' 
WITH collect(path) as paths, b 
WITH b, 
reduce(a=[], node in reduce(b=[], c in [aa in paths | nodes(aa)] | b + c) | case when node in a then a else a + node end) as nodes, 
reduce(d=[], relationship in reduce(e=[], f in [dd in paths | relationships(dd)] | e + f) | case when relationship in d then d else d + relationship end) as relationships 
RETURN b, relationships, nodes
```
Would express what you want to achieve.
You could this use either in the template or repository as you can see in the `DemoApplicationTests` in my example https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2202

**Comment by mrksph** [comment]
Wow, thank you Gerrit for the detailed answer with example repo included! 

It actually returns what I want, and now I can work on the query having the relationships hydrated. I came up with what you say in your second point, I tried to extract relationships and nodes and then collecting them in the RETURN statement but it didn't work. 

Thanks again!

**Comment by mrksph** [comment]
@meistermeier just to make sure, those reduce functions should work with whatever subgraph that may be output from a query similar to the one I provided, right?

**Comment by meistermeier** [comment]
It should. Also I am wondering that I may have missed something from your initial domain. As you can see in the example, I created now an extra level of depth and it is still working.
One reason could be that you may have not modeled the `PARENT_OF` relationship in every case(?)
It would be good that you have a deeper look at the example and tell me what differs from your domain/example.

Thanks to @michael-simons for providing a CypherDSL approach for the `Neo4jTemplate`. This is a good choice when it comes to the query building by user selection that you described in the initial post.

**Comment by meistermeier** [comment]
In #2203 I did some work to make it easier to map list of list of relationships/nodes. While doing this I re-remembered that the `PARENT_OF` relationship in your case should be `[:PARENT_OF*..0]` instead of `[:PARENT_OF*]`. Because the latter will only fetch related nodes if there is at least a length of 1.

**Comment by mrksph** [comment]
Hi Gerrit, thanks once again. I'm gonna give it a try with the changes you mention.

**Comment by mrksph** [comment]
Hey, I got it working but now I see labels are missing. I can retrieve some but not all of them. I've tried unwinding nodes(path) into node and then extracting labels(node) and finally collecting them into a list in the same record with the rest of the data but SDN still won't return Entities with their labels 

Do you know why?

Here's the query:

MATCH path=(bh:BaseHierarchy {code:'JQCLB00'})-[:INCLUDES]->(g:Group)-[*]->(c:Client) 
WHERE (g.code = 'EMIRG' OR g.code = 'BAESS') 
AND c.sector = '14' 
UNWIND nodes(path) as node
WITH collect(path) as paths, bh, labels(node) as lbs
WITH lbs, bh, 
reduce(a=[], node in reduce(b=[], c in [aa in paths | nodes(aa)] | b + c) | case when node in a then a else a + node end) as nodes, 
reduce(d=[], relationship in reduce(e=[], f in [dd in paths | relationships(dd)] | e + f) | case when relationship in d then d else d + relationship end) as relationships 
RETURN bh, relationships, nodes, collect(lbs)

**Comment by meistermeier** [comment]
Why are you looking for the labels? They are part of the returned `nodes`.
It might be helpful if you could tell me (or create a PR against my example) how the domain looks like. Especially the `(g:Group)-[*]->(c:Client)` part looks as there are more things in there than I assume.

As another side note: We can continue the discussion here in this special case but general problem solving questions should either be asked over at our community side https://community.neo4j.com/c/drivers-stacks/spring-data-neo4j-ogm/ or StackOverflow. This does not also helps us to have a cleaner separation between bugs/feature requests and questions but also others who typically not assume that they find an answer to their (non-bug-related) problems at GitHub.

**Comment by mrksph** [comment]
I was looking for the labels so I didn't have to set them manually after retrieving the results from the query so I'm not getting them from the nodes

The domain is something like this:

(:BaseHierarchy:Clients)-[:INCLUDES]->(:Client:Group)-[:PARENT_OF*0..N]->(:Client:Firm)-[:PARENT_OF*0..1]->(:Client:Entity)

Okay no problem with that, I can ask a question in the community next time.

**Comment by meistermeier** [comment]
As I said, if I would know how the example code relates to your domain, I can be of a better help.
At the moment I just can help you as much as I get information from your side.
Mapping a `BaseHierarchy` node entity and hydrate it in the way you are describing with SDN repositories works and there is no need to extract any additional labels or similar.

**Comment by mrksph** [comment]
The full feature we are developing is too much coupled with the business rules so describing it here wouldn't help if I don't go deep into details. I don't have any problem with that but it could take long time to explain it well.

Yea you can forget about the labels part that's because sometimes I don't get the right labels when the nodes I'm searching have more than one. It may be something with our code or how we modelled the data.

**Comment by meistermeier** [comment]
So is there anything I can help you with?

**Comment by mrksph** [comment]
Well, actually yes

We have a structure we call "CustomHierarchy" which can represent either a Query (Theres a node representing a query under de CustomHierarchy node) a Fixed Hierarchy (There are a Client under the CustomHierarchy, then always 2 Virtual nodes (with label Virtual) ) or a Snapshot Hierarchy which is the result of executing a Query against the database.

Right now I'm having trouble with SDN because the mapping is inconsistent. I don't know why having a common relationship between Real nodes and Virtual nodes is not working for me. I have to declare two different Relationships of the same type so SDN can retrieve whatever it needs depending on the CustomHierarchy I am searching for.

Example:

![image](https://user-images.githubusercontent.com/10486135/113177980-66848f80-924e-11eb-93e1-bd4e852441bb.png)



![image](https://user-images.githubusercontent.com/10486135/113177764-29b89880-924e-11eb-9960-f5ce0d15d93b.png)

**Comment by mrksph** [comment]
Here you can see the logs after executing the repository.save(snapshotHierarchy). You can see there's a line where SDN mapped a relationship type "PARENT_OF" to a node's label which should happen.

```
2021-03-31 19:20:34.678 DEBUG 40116 --- [nio-8080-exec-6] o.s.d.n.c.t.Neo4jTransactionManager      : Creating new transaction with name [org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.save]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2021-03-31 19:20:34.681 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MATCH (n) WHERE id(n) = $__id__ UNWIND labels(n) AS label WITH label WHERE NOT (label IN $__staticLabels__) RETURN collect(label) AS __nodeLabels__
2021-03-31 19:20:34.685 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
OPTIONAL MATCH (hlp:`CustomHierarchy`) WHERE id(hlp) = $__id__ WITH hlp WHERE hlp IS NULL CREATE (n:`CustomHierarchy`) SET n = $__properties__ RETURN id(n) UNION MATCH (n:`CustomHierarchy`) WHERE id(n) = $__id__ SET n += $__properties__ RETURN id(n)
2021-03-31 19:20:34.689 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MATCH (n) WHERE id(n) = $__id__ UNWIND labels(n) AS label WITH label WHERE NOT (label IN $__staticLabels__) RETURN collect(label) AS __nodeLabels__
2021-03-31 19:20:34.692 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
OPTIONAL MATCH (hlp:`CClient`) WHERE id(hlp) = $__id__ WITH hlp WHERE hlp IS NULL CREATE (n:`CClient`) SET n = $__properties__ REMOVE n:`BaseHierarchy`:`Clients` RETURN id(n) UNION MATCH (n:`CClient`) WHERE id(n) = $__id__ SET n += $__properties__ REMOVE n:`BaseHierarchy`:`Clients` RETURN id(n)
2021-03-31 19:20:34.695 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MATCH (startNode:`CustomHierarchy`) WHERE id(startNode) = $fromId MATCH (endNode) WHERE id(endNode) = $toId MERGE (startNode)-[relProps:`INCLUDES`]->(endNode) SET relProps += $__properties__ RETURN id(relProps)
2021-03-31 19:20:34.698 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MATCH (startNode)-[rel:`PARENT_OF`]->(:`ParentOf`) WHERE (id(startNode) = $fromId AND NOT (id(rel) IN $__knownRelationShipIds__)) DELETE rel
2021-03-31 19:20:34.702 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MERGE (n:`CustomParentOf` {id: $__id__}) SET n += $__properties__ RETURN id(n)
2021-03-31 19:20:34.704 DEBUG 40116 --- [nio-8080-exec-6] org.springframework.data.neo4j.cypher    : Executing:
MATCH (startNode) WHERE id(startNode) = $fromId MATCH (endNode) WHERE id(endNode) = $toId MERGE (startNode)-[relProps:`PARENT_OF`]->(endNode) RETURN id(relProps)
2021-03-31 19:20:34.706 DEBUG 40116 --- [nio-8080-exec-6] o.s.d.n.c.t.Neo4jTransactionManager      : Initiating transaction commit
```

**Comment by meistermeier** [comment]
The resulting `ParentOf` label in the query and also probably the label `CustomParentOf` is due to the fact that you are using a "vague" generic in the `RealNode` relationship definition `List<? extends ParentOf<?>> `.
Spring Data (Neo4j) cannot determine what the type `<T>` will be in the end and tries to create a meta-model of the relationship property class `ParentOf` as a node.
To get around the problem you would have to use the more concrete definitions of the `ParentOf` class like the `VClientParentOf` in the entity definition of `RealNode`.
Just as a side note: I think we already mentioned somewhere that the `UUID` in the relationship properties is not the proper type but should be a `Long`.

**Comment by meistermeier** [comment]
Close this issue because there were no feedback since three weeks. If this does not work for you with the information provided above, feel free to reopen the issue.
