### ISSUE TITLE
Nodes don't appear to be removed from spatial indexes when they are deleted.

### ISSUE THREAD

**Issue by Infiniverse** [spring-projects/spring-data-neo4j#221]
I've got a spatial index in a domain object:

   @Indexed(indexType = IndexType.POINT, indexName = "locations") Point wkt;

When objects are saved they are added to the index (as confirmed by using the Neo4j web console and examining the ReferenceNode tree).

However, when an object that had been added is subsequently removed (using neo4jTemplate.delete), the associated node is not removed from the spatial index.

I don't see any unit tests for SDN that test removal of nodes, and so it appears to be a bug. I've tried to understand the code to see if I can work out where the bug is, but I can't quite get my head around how spatial indexes are plugged in.

Can someone point me in the right direction. I'm willing to roll up my sleeves and so some of the work, but I need some help getting into the code base.

Thanks,
Joe

**Comment by mangrish** [comment]
Closed. Issue out of date.
