### ISSUE TITLE
Mapping only populates one related node instead of all

### ISSUE THREAD

**Issue by LongStockingPipi** [spring-projects/spring-data-neo4j#2211]
我在一对多查询的时候，多的那一方始终只能返回一条记录，也就是说集合provideJobs的大小始终是1，当初我以为是ID重复了，但是我用的是@GeneratedValue，不可能出现重复的呀，大神们帮帮我吧，帮帮孩纸吧！！！

`@Relationship(type = "INPUT", direction = Relationship.Direction.OUTGOING)
  private List<Job> provideJobs;`

`@Node("TABLE")
public class Table {

  @Id
  @GeneratedValue
  private Long nodeId;`

`@Node("JOB")
public class Job {

  @Id
  @GeneratedValue
  private Long id;`

**Comment by michael-simons** [comment]
I'm sorry, but I cannot make sense out of this ticket, even with Google translate. Can you give an English description? Or a colleague?

**Comment by vince-bickers** [comment]
When I am performing a one-to-many query, the collection always returns only one record, that is to say, the size of the set "provideJobs" is always 1. At first I thought the ID was duplicated, but I used @GeneratedValue, so that is impossible. Great gods, help me, help the kids! Dishonour! Dishonour on your family! Dishonour on you, dishonour on your cow.

**Comment by LongStockingPipi** [comment]
> When I am performing a one-to-many query, the collection always returns only one record, that is to say, the size of the set "provideJobs" is always 1. At first I thought the ID was duplicated, but I used @GeneratedValue, so that is impossible. Great gods, help me, help the kids!

very good!!!!

**Comment by meistermeier** [comment]
Missing information to help us to help you:
* Is this a custom Cypher statement that you are executing?
** If so, can you show us the query
** If not, can you show us how you access the data
* Version of Spring Data Neo4j you are running.

**Comment by meistermeier** [comment]
Closing this because there were no response in the last three weeks.
Feel free to open it again if there is any addition.
