### ISSUE TITLE
Allow inheritance of concrete classes

### ISSUE THREAD

**Issue by gsviteri** [spring-projects/spring-data-neo4j#2216]
Hi There,

I've been trying to load nodes via its inheritance type as suggested [here](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-creation.load).

Currently this is the repository I am executing and after adding `__nodeLabels__` I managed to get query to map to the right object, now the issues is that it is loading relationships.
```java
@Repository
public interface DatabaseObjectRepository extends Neo4jRepository<DatabaseObject, Long> {

    @Query("MATCH (a:DatabaseObject)-[r]->(m) " +
                    "WHERE a.dbId = $dbId " +
                    "RETURN a{.*, __internalNeo4jId__: id(a), __nodeLabels__: labels(a)}, " +
                    "collect(r{.*, __internalNeo4jId__: id(r)}), " +
                    "collect(m{.*, __internalNeo4jId__: id(m), __nodeLabels__: labels(m)})")
    <T extends DatabaseObject> T findDatabaseObjectByDbId(@Param("dbId") Long dbId);
```

**Comment by meistermeier** [comment]
The query does not look this complicated and it should be easily get substituted with the "common" custom query design https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-queries
So you won't need the hacks with the node labels (I mentioned them in the #2217 for the more complex case) but a 
```
"MATCH (a:DatabaseObject)-[r]->(m) " +
"WHERE a.dbId = $dbId " +
"RETURN a, collect(r), collect(m)"
```
should be sufficient.
In additional to this: If the `dbId` property is the `@Id` annotated field in your domain, you could also use `repository.findById()`

**Comment by gsviteri** [comment]
Thanks @meistermeier.... 

If I try this query in the `@Query` annotation, which I have already tried before, I am then back to the original problem which was related to the inheritance. In this given example if I use a `dbId` of a `Pathway` (69620L), I am expecting to get back and Pathway object but in fact I am getting absolutely any random object every time I run. That's why Florent Biville suggested  `__internalNeo4jId__: id(a), __nodeLabels__: labels(a)`.

The functionality we've always had is, we will match any given dbId into the corresponding object. Every domain classe extends DatabaseObject and if I give an id for Pathway I will then match Pathway, etc, etc. That's why we had `<T extends DatabaseObject>` for the `findById`. And that's what I am struggling at the moment.

After trying with the common custom query design it fails
```java
@Autowired
public AdvancedDatabaseObjectRepository(Neo4jClient neo4jClient) {
    this.neo4jClient = neo4jClient;
}

public <T extends DatabaseObject> T findById(){
    String query = "MATCH (a:DatabaseObject)-[r]->(m) WHERE a.dbId = 69620 RETURN a,collect(r), collect(m)";
    // silly attempt.
    // don't know how to query with Param, so the ID is hardcoded in the query....
    Optional<DatabaseObject> aa = neo4jClient.query(query).fetchAs(DatabaseObject.class).first();
    return (T) aa.get();
}
```

The exception is given:
```console
java.lang.IllegalArgumentException: Records with more than one value cannot be converted without a mapper.

	at org.springframework.data.neo4j.core.SingleValueMappingFunction.apply(SingleValueMappingFunction.java:52)
	at org.springframework.data.neo4j.core.SingleValueMappingFunction.apply(SingleValueMappingFunction.java:33)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.lambda$partialMappingFunction$0(DefaultNeo4jClient.java:345)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.first(DefaultNeo4jClient.java:319)
	at org.reactome.server.graph.repository.AdvancedDatabaseObjectRepository.findById(AdvancedDatabaseObjectRepository.java:40)
	at org.reactome.server.graph.repository.AdvancedDatabaseObjectRepository$$FastClassBySpringCGLIB$$2ecd3bb.invoke(<generated>)
```

If I use `repository.findById` I ended up with the WHOLE graph loaded until I run out of memory.

**Comment by meistermeier** [comment]
1. As answered in #2217, the `Neo4jClient` does not know anything about the meta-model and cannot map non-trivial (driver supported) types. For this to work you would have to use the `Neo4jTemplate` or repositories.
2. Spring Data Neo4j supports inheritance only for abstract classes, meaning that you cannot extend a concrete class.
`abstract class DatabaseObject <- ConcreteClassA / ConcreteClassB` :heavy_check_mark: 
`abstract class DatabaseObject <- ConcreteClass <- EvenMoreConcreteClass` :stop_sign: 
(We just introduced this in the 6.1 branch for interfaces also but this would be another topic)
Combining this with the information from 1. should produce either `ConcreteClassA` or `ConcreteClassB` for the `@Query` annotated repository method (with the simple version I provided).
3. For the findById you could use a projection describing your limited view (and with that removing unwanted relationships while querying) of the `DatabaseObject`. https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#projections

**Comment by gsviteri** [comment]
Thanks Gerrit
`abstract class DatabaseObject <- ConcreteClassA / ConcreteClassB ✔️`
That has been address in version 6.1.0.

My code using Neo4jTemplate looks like this
```java
@Repository
public class DatabaseObjectRepository {
    private final Neo4jTemplate neo4jTemplate;
    @Autowired
    public DatabaseObjectRepository(Neo4jTemplate neo4jTemplate) {
        this.neo4jTemplate = neo4jTemplate;
    }

    @SuppressWarnings("unchecked")
    public DatabaseObject run(@Param("dbId") Long dbId) {
        String query = "MATCH (a:DatabaseObject{dbId:$dbId})-[r]->(m) RETURN a,collect(r), collect(m)";
        Map<String, Object> params = new HashMap<>(1);
        params.put("dbId", dbId);
        return neo4jTemplate.findOne(query, params, DatabaseObject.class).orElse(null);
    }
}

```

**Comment by gsviteri** [comment]
Seems to be all good from my side. First impression, everything that was failing is now working :)
Thanks!

**Comment by meistermeier** [comment]
@Andy2003 for your information: There is now a `6.1.3-GH-2216-SNAPSHOT` available.

**Comment by meistermeier** [comment]
Update of the snapshot is now available. This solves a flaky detection bug.
