### ISSUE TITLE
Automatic Bean Validation not applied for Constraints with Target TYPE

### ISSUE THREAD

**Issue by amkay** [spring-projects/spring-data-neo4j#222]
I got automatic Bean Validation according to JSR-303 up and running for constraints with `@Target(FIELD)` (e.g. all constraints defined by Hibernate Validator).

Now I defined a custom Constraint that has `@Target(TYPE)`. This one is not automatically applied to the NodeEntities which are annotated with it.

However, if I modify the constraint to `@Target(FIELD)` the constraint works as expected. The problem with this solution is that I need the whole entity for its validation.

**Comment by mangrish** [comment]
Closed. Issue out of date.
