### ISSUE TITLE
Support multiple relationships properties to same node

### ISSUE THREAD

**Issue by VladoKuruc** [spring-projects/spring-data-neo4j#2228]
In my case, I need a fully hydrated Node for modifying and save() without data loss.
My datas has more @RelationshipProperties between same nodes.

To simulate this I modified existing unit test:
org.springframework.data.neo4j.integration.imperative.RepositoryIT.RelationshipProperties
```java
		@Test
		void loadSameNodeWithDoubleRelationship(@Autowired HobbyWithRelationshipWithPropertiesRepository repository) {
			long personId;

			try (Session session = createSession()) {
				Record record = session.run("CREATE (n:AltPerson{name:'Freddie'})," +
						" (n)-[l1:LIKES {rating: 5}]->(h1:AltHobby{name:'Music'})," +
						" (n)-[l2:LIKES {rating: 1}]->(h1)" +
						" RETURN n, h1").single();
				personId = record.get("n").asNode().id();
			}

			AltHobby hobby = repository.loadFromCustomQuery(personId);
			assertThat(hobby.getName()).isEqualTo("Music");
			List<AltLikedByPersonRelationship> likedBy = hobby.getLikedBy();
			assertThat(likedBy).hasSize(2);

			AltPerson altPerson = new AltPerson("Freddie");
			altPerson.setId(personId);
			AltLikedByPersonRelationship rel1 = new AltLikedByPersonRelationship();
			rel1.setRating(5);
			rel1.setAltPerson(altPerson);

			AltLikedByPersonRelationship rel2 = new AltLikedByPersonRelationship();
			rel2.setRating(1);
			rel2.setAltPerson(altPerson);

			assertThat(likedBy).containsExactlyInAnyOrder(rel1, rel2);

			Optional<AltHobby> optHobby = repository.findById(hobby.getId());
			assertThat(optHobby.isPresent()).isTrue();
			hobby = optHobby.get();			
			assertThat(hobby.getName()).isEqualTo("Music");
			likedBy = hobby.getLikedBy();
			assertThat(likedBy).hasSize(2);
			assertThat(likedBy).containsExactlyInAnyOrder(rel1, rel2);
		}
```
Everything is OK until I add to AltHobby node new property with getter()
```java
	@Relationship(type = "CHILD", direction = Relationship.Direction.INCOMING)
	private List<AltHobby> memberOf = new ArrayList<>();

	public List<AltHobby> getMemberOf() {
		return memberOf;
	}
```

Then I have error on assertThat(likedBy).hasSize(2)

`
java.lang.AssertionError: 
Expected size:<2> but was:<1> in:
<[org.springframework.data.neo4j.integration.shared.common.AltLikedByPersonRelationship@3f3af232]>
	at org.springframework.data.neo4j.integration.imperative.RepositoryIT$RelationshipProperties.loadSameNodeWithDoubleRelationship(RepositoryIT.java:1570)
`

My model has more complex mappings but this is the simple case where this error is visible. Maybe is there another way how to change and save node without data lose and loading whole tree of relationships.

**Comment by meistermeier** [comment]
Thanks for reporting this. I can reproduce it with the expanded test case, you provided.

**Comment by meistermeier** [comment]
We target this issue with another bugfix. If you want, you could give `6.0.9-SNAPSHOT` a try and tell us if it is working for you.
(Your test ^^ passes now)

**Comment by VladoKuruc** [comment]
Sorry, but that test doesn't pass even with the latest changes. I've tried both the 6.0.x branch and main. Maybe you missed here the changes in the AltHobby class

**Comment by meistermeier** [comment]
> Maybe you missed here the changes in the AltHobby class

I did in the last run...back to the drawing board.

**Comment by meistermeier** [comment]
Ok, finally. I somehow forgot about the change on my machine.
Just for you, fresh from the build pipeline: `6.0.9-GH-2228-SNAPSHOT`.
If this is working for you, I am happy to merge this in for the next patch release.

**Comment by VladoKuruc** [comment]
I can confirm that this error no longer occurs even in my more complex model

**Comment by meistermeier** [comment]
Great to hear and thanks for your feedback.
