### ISSUE TITLE
How to configure SDN to use external transaction manager programatically

### ISSUE THREAD

**Issue by amkay** [spring-projects/spring-data-neo4j#223]
This one is rather a question...

As the title already says, I want Neo4j to participate in global transactions. The JTA transaction manager I want to use is [Atomikos](http://www.atomikos.com). I also want to configure SDN programatically to use this transaction manager.

I already read the SDN "reference" and looked at https://github.com/digitalstain/Neo4j-Spring-Integration and https://github.com/spring-projects/spring-data-neo4j/tree/master/spring-data-neo4j-tx but could not get anything like this to work.

Help appreciated. Thanks ;)

**Comment by mangrish** [comment]
Closed. Issue out of date.
