### ISSUE TITLE
Given same Query, output is different using Neo4j Browser and SDN Neo4jTemplate

### ISSUE THREAD

**Issue by mrksph** [spring-projects/spring-data-neo4j#2237]
Hi, 

I'm using Neo4j Enterprise Edition v4.2.1 and Spring Data Neo4j 6.0.3.

I have the following Query:

```
MATCH path=(b:BaseHierarchy)-[]->(n:Group)-[:PARENT_OF*]->(c:Client) 
WHERE n.code = 'BPCEG' AND c.industry = '1005' 
WITH collect(path) as paths, b 
WITH b, reduce(a=[], node in reduce(b=[],c in [aa in paths | nodes(aa)] | b + c) | case when node in a then a else a + node end) as nodes, reduce(d=[], relationship in reduce(e=[],f in [dd in paths | relationships(dd)] | e + f) | case when relationship in d then d else d + relationship end) as relationships 
RETURN b, relationships, nodes;
```

If I run this query in the Neo4j Browser I get the following graph:
  
![image](https://user-images.githubusercontent.com/10486135/115708086-d7abf400-a36f-11eb-972c-a8aa3cfe0c8d.png)

But if I run the same query using 

`Neo4jTemplate.findOne(query, new HashMap<>(), BaseHierarchyNode.class)`

The result only includes the first-level children of the blue node BPCEG.

![image](https://user-images.githubusercontent.com/10486135/115706209-ae8a6400-a36d-11eb-9e24-73cada7d791f.png)

The data model is not the problem, as I can successfully retrieve the (correct) graph 

Using Neo4jClient.query(query).fetch().one() I get the following result:

![image](https://user-images.githubusercontent.com/10486135/115707918-a16e7480-a36f-11eb-968a-ccf6d920e3f4.png)

The same node/relationships count as the result of executing the query against Neo4j Browser.

**Comment by meistermeier** [comment]
We made some improvements to the mapping of related of related entities in the last versions of 6.0.x
Could you upgrade to 6.0.8 and see if the problem still exist? Also your query should become now more performant because you could use 
```
MATCH path=(b:BaseHierarchy)-[]->(n:Group)-[:PARENT_OF*]->(c:Client) 
WHERE n.code = 'BPCEG' AND c.industry = '1005' 
RETURN b, collect(nodes(p)), collect(relationships(p));
```

**Comment by mrksph** [comment]
Hi Gerrit, I'll give it a try, for now I tried to run the query with the changes you mention in the browser but the query couldn't be rendered as nodes and edges, could it be because it's intended to be used only with SDN?

**Comment by mrksph** [comment]
Hi, I've just run the query with the changes you said but the results come duplicated. I'm using SDN 6.0.8

![image](https://user-images.githubusercontent.com/10486135/117288453-cf71af80-ae6b-11eb-8a34-f14c826fe2f1.png)

**Comment by meistermeier** [comment]
Duplicates are expected with this query. You can still use the other style if you prefer this. It is basically either let the database do the work (reduce style query) or SDN / application side (collect style).

**Comment by mrksph** [comment]
Ok, I fixed my problem with the duplicates using 
`apoc.coll.toSet(apoc.coll.flatten(collect(relationships))) as relationships, apoc.coll.toSet(apoc.coll.flatten(collect(nodes))) as nodes;`

**Comment by meistermeier** [comment]
So we can close this issue now?

**Comment by mrksph** [comment]
Yes thank you Gerrit, as always
