### ISSUE TITLE
Resolve or remove literal replacements in custom count queries.

### ISSUE THREAD

**Issue by jposthauer** [spring-projects/spring-data-neo4j#2239]
I have the following query where I am trying to have a dynamic sort and paging using a Pageable parameter.
```
  @Query(value = "MATCH (person:Person) "
      + "WHERE toUpper(person.name) CONTAINS toUpper($name) "
      + "WITH DISTINCT(person) AS person "
      + ":#{orderBy(#pageable)} RETURN person SKIP $skip LIMIT $limit;",
      countQuery = "MATCH (person:Person) "
          + "WHERE toUpper(person.name) CONTAINS toUpper($name) "
          + "RETURN COUNT(DISTINCT person);")
  Page<Person> findByName(String name, Pageable pageable);
  ```
  
  When I run the query I get an error stating `Unable to convert org.springframework.data.neo4j.repository.query.Neo4jSpelSupport$StringBasedLiteralReplacement to Neo4j Value.`
  
  If I remove the count query and change the return type to `Slice<Person>` everything returns fine, so the issue comes when translating the count query.
  
  After digging into the SDN code I found that the issue occurs when `getCountQuery` is called, it is including the `SpEL__0__` parameter in it's parameter list even though the count query doesn't use that parameter.
  
  The issue and full stacktrace is identical to the issue identified in the thread of this issue: https://github.com/spring-projects/spring-data-neo4j/issues/1219 #1219

**Comment by jposthauer** [comment]
I should also mention that if I go into debug mode and manually remove the SpEL parameter the query returns fine with the expected paging and sort applied.

**Comment by jposthauer** [comment]
Spring Boot: 2.4.5
Spring Data Neo4j: 6.0.8

**Comment by michael-simons** [comment]
Thank you so very much, @jposthauer and sorry @bujoralexandru, @where-design-meets-art. 

That new ticket helped me to understand what's going on, I was a bit lost in the stack traces in the original ticket. The bug is fixed in all 3 6.x branches.

**Comment by bujoralexandru** [comment]
No problem, @michael-simons. We managed to fix our issue with everyone's help. 

Thank you!
