### ISSUE TITLE
Wrong value when mapping to implementations of Set

### ISSUE THREAD

**Issue by gsviteri** [spring-projects/spring-data-neo4j#2241]
Hi,
I have a Set attribute in my class and whenever I retrieve data using this query [1] this attribute will contain an empty Set instead of null. If I then change it to List, it solves that problem. 

```java
[1]
String query = "MATCH (a:DatabaseObject{dbId:$dbId})-[r]-(m) RETURN a, COLLECT(r), COLLECT(m)";
```

```java
@Relationship(type = "inferredTo", direction = Relationship.Direction.INCOMING)
private Set<Event> inferredFrom;
```

I tried to assign `null` but it hasn't succeed.

Thanks
Guilherme

**Comment by meistermeier** [comment]
Could you checkout the current snapshot(s)? 6.0.9-SNAPSHOT
We target this in GH-2236 but the fix is not yet released.

**Comment by gsviteri** [comment]
Great! That's fixed!
Thanks @meistermeier

**Comment by gsviteri** [comment]
Ok, that seems a bit strange..
I am testing now and I am not getting null. Looks like the instance is randomly assigned. If I mvn clean and run again I might null (as I want)...

**Comment by meistermeier** [comment]
Sorry, I also misread the initial problem. Do you have any shareable project where I can have a look on?
In general there should not be a `null` but an empty collection. I understand that you initial problem says that you expect the `null`, but you should not rely on having `null`.

**Comment by gsviteri** [comment]
Yes.
I am expecting null because it is the behaviour we had with SDN4. It's just weird that it is fine when I replace to List. 
I can always check for notNull / size != 0..
Yes, the code is here https://github.com/reactome/graph-core/tree/feature/major-updates
GraphDB (Neo4j 4.2.x) - https://drive.google.com/drive/folders/1mAqbWymp7wnE4nNYsOKqQgafcQOHVcc6?usp=sharing

This is the class you can test.

```java
@SpringBootTest
public class PlaygroundTest {
    @Test
    public void testInferredFromNull(){
        ReactionLikeEvent sas = databaseObjectRepository.findByDbId(202245L);
        assertNull(sas.getInferredFrom());
        assertEquals(sas.getInferredFrom().size(),0);
        System.out.println(sas);
    }
}
```

**Comment by meistermeier** [comment]
Hi. I could reproduce the issue with your data, thanks.
Could you give `6.0.9-GH-2241-SNAPSHOT` a try?
This should now never return `null` anymore for empty collections but empty collections.

**Comment by gsviteri** [comment]
Hi. Great.
Thank you very much. I've been trying and I couldn't get `null` as you said.

**Comment by meistermeier** [comment]
Thanks for your feedback.
