### ISSUE TITLE
Deterministic mapping of records with mixed results

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-neo4j#2246]
Since we do not officially support this, I would call this an enhancement instead of a bug fix ;)

Given that we want to map something like
```
MATCH (a:DatabaseObject{dbId:$dbId})-[r:output]->(m:PhysicalEntity) RETURN m, r.stoichiometry as n
```
the mapping mechanism will create a `Map` that will only contain the identifier and the node description of the template / repository. If this node description is an (abstract) parent class, we will then lose the information about the concrete type coming from the node's label.

**Comment by gsviteri** [comment]
I am testing using  `6.0.9-GH-2246-SNAPSHOT` and so far all test cases are passing. That's a great enhancement for the Library! Thank @meistermeier. Thanks a lot

It will be really useful to get this code snippet somewhere in the documentation
```java
BiFunction<TypeSystem, MapAccessor, DatabaseObject> mappingFunction = neo4jMappingContext.getRequiredMappingFunctionFor(DatabaseObject.class);
        Collection<QueryResultWrapper> wrapper = neo4jClient.query("MATCH (a:DatabaseObject{dbId:$dbId})-[r:input]->(m:PhysicalEntity) RETURN m, 3 as n")
                .bindAll(map).fetchAs(QueryResultWrapper.class)
                .mappedBy((typeSystem, record) -> {
                    DatabaseObject n = mappingFunction.apply(typeSystem, record.get("m"));
                    int number = record.get("n").asInt();
                    return new QueryResultWrapper(n, number);
                }).all();
```
