### ISSUE TITLE
Explicitly acquire locks on nodes when `@Version` is used.

### ISSUE THREAD

**Issue by marianozunino** [spring-projects/spring-data-neo4j#2259]
Hi guys!

Im having the following issue.

I have a rest API that when It receives multiple calls to the same endpoint I end up loosing data.

For the sake of the issue I made up a simple example. It has two models: `A` and `B`, and `A` has a `List<B>`

The goal is to add Bs to A.

The example has 3 branches `with-out-version`, `with-version` and `with-retry`. To simulate the concurrency I created         `Executors.newFixedThreadPool(10)`.

The issue: I start with a fresh A (empty list of B). Then, each thread attempts to find that A and add a new B.

Each thread succeeded to create a new B (it shows up in neo4j), but only 1 thread succeded to add that B into A.

![sout](https://i.imgur.com/oruM21Q.png)
![neo4j](https://i.imgur.com/D8WpKSh.png)

With out version: the explained above
With version: I get the optimistic lock exception.
With version+retry: No more exception, but I end up with the initial behaviour.

[Example](https://github.com/marianozunino/sdn6-issue-concurrency)

Let me know if this is or isn't enough information, or If I'm taking a totally wrong aproach!

Thanks for you awesome work :D

**Comment by michael-simons** [comment]
That's a great report, thank you! We'll investigate.

**Comment by marianozunino** [comment]
Thank you so much @michael-simons  :D I really appreciate it. Mean while I'm using a `@Query` to save the entity and avoid the issue.
Like so:
```java
  @Query("MATCH (a:A{id: $aId}) WITH a MATCH (b:B{id: $bId}) CREATE (a)-[:HAS]->(b)")
  void storeContactRequest(String aId, String bId);
  ....
  repo.save(b);
  repo.storeContactRequest(a.getId(), b.getId());
```

**Comment by michael-simons** [comment]
Hey. This is now fixed in all 3 maintained branches. Snapshots should be available shortly. I have attached a version of your project using a snapshot build.

The `with-retry` branch is how I would run this basically.

Thanks again for your contribution.

[sdn6-issue-concurrency.zip](https://github.com/spring-projects/spring-data-neo4j/files/6521655/sdn6-issue-concurrency.zip)
