### ISSUE TITLE
Fetch all properties when querying via a base interface.

### ISSUE THREAD

**Issue by sylv1-corre** [spring-projects/spring-data-neo4j#2262]
Hello,

Having the following object models (I am using Kotlin):

```kotlin
interface Movie {
    val id: String
    val name: String
}

@Node("AnimationMovie")
class AnimationMovie(@Id override val id: String, override val name: String, val studio: String): Movie

@Node("Cinema")
class Cinema(@Id val id: String, val name: String,
             @Relationship("Plays", direction = Relationship.Direction.OUTGOING) val plays: List<Movie>
)
```

Along with the following repository:

```
interface CinemaRepository: Neo4jRepository<Cinema, String>
```

My database is setup as follows:

```
CREATE (:AnimationMovie {id: 'movie001', name: 'movie-001', studio: 'Pixar'})<-[:Plays]-(:Cinema {id:'cine-01', name: 'GrandRex'})
```

The cinema object returned by cinemaRepository.findAll() doesn't contain any movie in the plays field. If that field is declared as `List<AnimationMovie>` instead of `List<Movie>`, it works as expected and the relation is fulfilled... But I really want to be able to play different kinds of movies !

If I add a Movie label to the AnimationMovie (as in `CREATE (:Movie:AnimationMovie {id: 'movie001', name: 'movie-001', studio: 'Pixar'})<-[:Plays]-(:Cinema {id:'cine-01', name: 'GrandRex'})`), I get the following error:
Failed to instantiate [Movie]: Specified class is an interface

spring-data-neo4j version: 6.0.8

Any help would be highly appreciated !

Sylvain

**Comment by michael-simons** [comment]
Hi @sylv1-corre thanks for the ticket and the complete description.

Interfaces are allowed in an inheritance hierarchy since 62496fc9200c24994527ddd40eceee5bb7b1a83c which was part of 6.0.8, which is what you are using.

Please have a look at the documentation: [A note on class hierarchies](https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#mapping.annotations.node), you have something like Listing 12.

You need to add a common label to your base interface like this

```kotlin
@Node
interface Movie {
    val id: String
    val name: String
}
```

I have added a test for your scenarios (in Java, though), please see #2ed43e97b59add0be466ff8bbf212133064f7cce

Please let us know if this helps.

**Comment by michael-simons** [comment]
It seams that Kotlin behaves differently… Needs some more investigation.

**Comment by michael-simons** [comment]
For whatever reason Kotlin seems to be less eager to add the concrete class `AnimationMovie` to the mapping context, therefore it cannot be found and we try to instantiate the interface.

You could define a repository for it to load it or do something like this in a `@Configuration` class:

```Kotlin
@Bean
fun neo4jMappingContext(@Autowired neo4JConversions: Neo4jConversions): Neo4jMappingContext {
	val f = Neo4jMappingContext(neo4JConversions)
	f.setInitialEntitySet(setOf(KotlinCinema::class.java, KotlinMovie::class.java, KotlinAnimationMovie::class.java))
	return f
}
```

Or extend from `AbstractNeo4jConfig` and specify the initial packages to scan

```kotlin
override fun getMappingBasePackages(): Collection<String?>? {
	return setOf(Inheritance::class.java.getPackage().name)
}
```

both approaches work for me. 

However, I did spot a bug in what attributes we select based on the interface, which needs to be fixed.

**Comment by michael-simons** [comment]
This is fixed in 6.0.10 and upwards: 

https://github.com/spring-projects/spring-data-neo4j/blob/6.0.x/src/test/kotlin/org/springframework/data/neo4j/integration/imperative/KotlinInheritanceIT.kt#L63-L81

We cannot fix the fact that Kotlin might behave differently in loading a class that is not directly used. 
To be able to map into `AnimatedMovie`, the `AnimatedMovie` Kotlin class must be known to the persistence context.

Thanks a lot for the ticket and the description!

**Comment by sylv1-corre** [comment]
Hello @michael-simons 

Thanks a lot for your work on this issue ! Very appreciated :-)

However, I could not make it to work with any of your suggestions (using neo4jMappingContext and getMappingBasePackages) using 6.0.8. Is the bug correction in 6.0.10 required for this to work ?

I get the following error:
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.example.springdataneo4jissue.AnimationMovie.<init>, parameter studio

I have setup a small repo to highlight the issue: https://github.com/sylv1-corre/spring-neo4j-issue-2262

**Comment by michael-simons** [comment]
Thanks for getting back. Yep, that’s the actual error we discovered. We are not fetching all attributes (we use the interface to determine them), thus `studio` is not fetched and Kotlin complains. You can mark that attribute as nullable (`String?`) but than it’s null. 

As a working workaround I would pull it up to the Interface until 6.0.10 is out. 

A snapshot should available in VMwares snapshot repos soon.

**Comment by sylv1-corre** [comment]
Ok, thank you very much :-)

**Comment by michael-simons** [comment]
Thanks for the excellent reproducer. It works with the 6.0.10-SNAPSHOT:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.springframework.boot") version "2.4.5"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.5.10"
    kotlin("plugin.spring") version "1.5.10"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
    maven { url = uri("https://repo.spring.io/milestone") }
    maven { url = uri("https://repo.spring.io/snapshot") }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-neo4j")
    implementation("org.springframework.data:spring-data-neo4j:6.0.10-SNAPSHOT")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.neo4j.test:neo4j-harness:3.5.18")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```

You can reduce the config a bit by using `@EntityScan`

```kotlin
package com.example.springdataneo4jissue

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.neo4j.driver.AuthTokens
import org.neo4j.driver.Driver
import org.neo4j.driver.GraphDatabase
import org.neo4j.harness.TestServerBuilders
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.autoconfigure.domain.EntityScan
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.data.neo4j.config.AbstractNeo4jConfig
import org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories
import org.springframework.test.context.junit.jupiter.SpringExtension
import org.springframework.transaction.annotation.EnableTransactionManagement

@ExtendWith(SpringExtension::class)
class CinemaRepositoryTest {
    @Autowired
    lateinit var cinemaRepository : CinemaRepository

    @Configuration
    @EnableNeo4jRepositories(considerNestedRepositories = true)
    @EnableTransactionManagement
    @EntityScan(basePackageClasses = [Cinema::class])
    internal class Config : AbstractNeo4jConfig() {
        @Bean
        override fun driver(): Driver {
            return GraphDatabase.driver("${embeddedDatabaseServer.boltURI()}", AuthTokens.none())
        }
    }

    companion object {
        val embeddedDatabaseServer = TestServerBuilders.newInProcessBuilder()
            .withFixture("""
                CREATE (:Movie:AnimationMovie {id: 'movie001', name: 'movie-001', studio: 'Pixar'})<-[:Plays]-(:Cinema {id:'cine-01', name: 'GrandRex'})
            """.trimIndent()).newServer()
    }

    @Test
    fun repositoryTest() {
        val cinemas = cinemaRepository.findAll()

        assert(cinemas.size == 1)
    }
}
```

I like how you setup the embedded test harness, this is exactly how we would recommend it!

calender.spring.io doesn't show a date for the next patch release yet, maybe @mp911de can shed a light.

If you cannot wait until then, modeling like this

```kotlin
package com.example.springdataneo4jissue

import org.springframework.data.neo4j.core.schema.Node

@Node
interface Movie {
    val id: String
    val name: String
    val studio: String
}

@Node
class AnimationMovie(@Id override val id: String, override val name: String, override val studio: String): Movie
```

Albeit it is not nice and probably not applicable in a large domain.

Btw, you don't need to repeat the interface / class names, `@Node` is enough.

Cheers and have a good weekend.
