### ISSUE TITLE
Replacement for RelationshipModel

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-data-neo4j#2263]
What to use instead of `RelationshipModel` class? It was available in previous versions.

```
@Query(""MATCH (:User {id: $userId})-[relationship:PARTNER|FRIEND]-(user) RETURN user, relationship")
```

**Comment by michael-simons** [comment]
I am not aware of any class named `RelationshipModel`. 

In all versions SDN 4.2 to 5.3 it was a `RelationshipEntity`. This is now `RelationshipProperties` and documented.

**Comment by michael-simons** [comment]
Use `@RelationshipEntity` in SDN5/Neo4j-OGM, use `@RelationshipProperties` in SDN 6+.

`RelationshipModel` is an internal interface used in Neo4j-OGM, the object mapper used by SDN 5. Please see related issue there.

**Comment by alxxyz** [comment]
As I understand now `RelationshipModel` is `RelationshipValue`

**Comment by michael-simons** [comment]
No. `RelationshipValue` is a type used by the driver.
