### ISSUE TITLE
查询的问题

### ISSUE THREAD

**Issue by LongStockingPipi** [spring-projects/spring-data-neo4j#2265]
我英语不好，索性用中文写把，我使用的版本是spring-data-neo4j 6.0.3，在一对多查询的时候，A-(1)-[]-(n)-B，返回的B的数量始终是1，有人遇到过这种情况吗，我一直怀疑我的实体类定义的有问题，因为我几年前用的是很老的版本，使用的方法和现在不一样，以前的注解都已经淘汰了，我按照文档去写，依然不奏效，或者谁有例子让我看一下吗，感谢~

**Comment by LongStockingPipi** [comment]
等我回家把代码贴出来

**Comment by meistermeier** [comment]
> My English is not good, so I simply write in Chinese. The version I use is spring-data-neo4j 6.0.3. In one-to-many query, A-(1)-[]-(n)-B is returned The number of B is always 1. Has anyone encountered this situation? I have always suspected that there is a problem with the definition of my entity class, because I used a very old version a few years ago, and the method used is different from now. The annotations have been eliminated, I wrote according to the document, but it still doesn’t work, or does anyone have an example for me to look at, thank you

> I will post the code when I get home

**Comment by LongStockingPipi** [comment]
> > My English is not good, so I simply write in Chinese. The version I use is spring-data-neo4j 6.0.3. In one-to-many query, A-(1)-[]-(n)-B is returned The number of B is always 1. Has anyone encountered this situation? I have always suspected that there is a problem with the definition of my entity class, because I used a very old version a few years ago, and the method used is different from now. The annotations have been eliminated, I wrote according to the document, but it still doesn’t work, or does anyone have an example for me to look at, thank you
> 
> > I will post the code when I get home

thank u very much! I just wanted to write a simple example and put it here at home, but now the program seems to be working, it can return the result normally, I am so confused, I will delete this "issue" tomorrow morning.

**Comment by LongStockingPipi** [comment]
[https://github.com/LongStockingPipi/demo](url)
I have no authority to delete the issue hia hia hia
