### ISSUE TITLE
The complexity of direct storing relation using @RelationshipProterties and @TargetNode

### ISSUE THREAD

**Issue by alizadehei** [spring-projects/spring-data-neo4j#2271]
I have a trouble trying to migrate from SDN+OGM  to SDN 6.0.x.
We used @RelationshipEntity with @StartNode and @EndNode, from the OGM to store relationships directly. I have seen in the documentation that the new way to go is @RelationshipProterties and @TargetNode.
But implementing this case with the new way seems to be costly. In fact, by using the new method, To add a relationship between two nodes we have to read those two nodes and all its relations and then add a relationship between them and finally save again.

Note that Neo4j is aimed at graphs and thus relationship may be an important first-class element in many Neo4j applications. This may not be the case for, e.g., Hibernate, for which forcing a relationship to be started from an entity may be a reasonable choice.

OGM Implementation:
```
@RelationshipEntity(type = "Is_Friend_Of")
public class Friend{
    @Id 
    private Long id;
    @StartNode
    private Person src;
    @EndNode
    private Person dst;
}
```
What do you suggest? Wouldn't it be better to have a solution for this case?

**Comment by michael-simons** [comment]
If this about having a model like `@RelationshipEntity` coming back: This is not going to happen. You cannot query or store an unconnected relationship in Neo4j. The match will _always_ include start and end nodes.

**Comment by shayantabrizi** [comment]
@michael-simons If by "unconnected relationship" you mean a relationship without a start/end nodes, I believe @alizadehei's issue is different. 

Assume that one have a node with 500 relationships and another node with 1000 relationships. In OGM, we could save a new relationship by just setting the start and end nodes in the attributes marked with @StartNode and @EndNode in @RelationshipEntity. I guess it was not required to first retrieve all the 500 relationships of the first node and/or all the 1000 relationships of the second node and then add the new relationship to one/both of them and then save it. 
But, now it seems that you have to do all that work just to add a new relationship between two known nodes (specified by their ids). It seems to me that this not fully consistent with the rationale of a graph database. I like to be able to easily add nodes and relationships, as I do on a piece of paper. I draw some nodes and then connect them by edges. I do not take care about all the other edges of a node when I want to draw an edge between two nodes. Forcing that may have a considerable overhead. 

Also, a graph looks to me as some nodes and some edges. Even, when mentioned in mathematics, a common notation is G=(V, E). Here, E is not inside V. It's a different set. But, it seems that in the new SDN, E is embedded into V:  each node in V has some edges inside it (without any option to behave them more independently, as opposed to OGM). They are not seen as different sets. We have only one set V, in which we may have some edges. One may claim that edges are second-class citizens in the new SDN.

**Comment by shayantabrizi** [comment]
@michael-simons If by "unconnected relationship" you mean a relationship without a start/end nodes, I believe @alizadehei's issue is different.

Assume that one have a node with 500 relationships and another node with 1000 relationships. In OGM, we could save a new relationship by just setting the start and end nodes in the attributes marked with @StartNode and @endnode in @RelationshipEntity. I guess it was not required to first retrieve all the 500 relationships of the first node and/or all the 1000 relationships of the second node and then add the new relationship to one/both of them and then save it.
But, now it seems that you have to do all that work just to add a new relationship between two known nodes (specified by their ids). It seems to me that this not fully consistent with the rationale of a graph database. I like to be able to easily add nodes and relationships, as I do on a piece of paper. I draw some nodes and then connect them by edges. I do not take care about all the other edges of a node when I want to draw an edge between two nodes. Forcing that may have a considerable overhead.

Also, a graph looks to me as some nodes and some edges. Even, when mentioned in mathematics, a common notation is G=(V, E). Here, E is not inside V. It's a different set. But, it seems that in the new SDN, E is embedded into V: each node in V has some edges inside it (without any option to behave them more independently, as opposed to OGM). They are not seen as different sets. We have only one set V, in which we may have some edges. One may claim that edges are second-class citizens in the new SDN.

**Comment by michael-simons** [comment]
Fair, I get that point. 

On the other hand, SDN is is a Spring Data commons project centered around aggregates, a wholistic set of objects, with a given root and a defined structure.

You can always attach nodes with a custom query. The manual provides several options how to do this and we think that our building blocks provide a couple of entry points into the abstraction that serve that specific purpose.

However, we are currently working on making projections more usable in terms of storing a subgraph. We do see that issue,  as a matter of fact.

**Comment by meistermeier** [comment]
I close this for now because there were no further input on this topic. For the projections bits I created  #2313
