### ISSUE TITLE
Allow function calls in Sort / Pageable objects in custom queries.

### ISSUE THREAD

**Issue by pelletier197** [spring-projects/spring-data-neo4j#2273]
Hello! 

Is there a recommended way to sort on computed fields? For instance, in my application, I want to sort by ignoring the diacritics (é, è, à, etc..). To do so, I use `apoc.text.clean(department.name)` with a custom query and a `Pageable`. This used to work in spring-data-neo4j 5, but doesn't work anymore. 

```
: Cannot handle order property `apoc.text.clean(department.name)`, it must be a simple property or one-hop path.
```

The  pageable I use is the following.. 

```kotlin
PageRequest.of(0, 10, Sort.by("apoc.text.clean(department.name)"))
```

Thank you!

**Comment by michael-simons** [comment]
We don't see any reasons not to support this for custom queries. Custom queries must be used with discretion anyway to avoid Cypher injection, so we decided to lift those restrictions, allowing function calls in sorts.
