### ISSUE TITLE
Honor `ignoreCase()` from `Sort.Order`.

### ISSUE THREAD

**Issue by pelletier197** [spring-projects/spring-data-neo4j#2274]
In spring data neo4j 5, We used to be able to sort ignoring the case. This doesn't seem supported anymore 

This is the old query that was created by spring-data-neo4j 5
```cypher
MATCH (department:Department)
RETURN department ORDER BY toLower(department.name) ASC SKIP $sdnSkip LIMIT $sdnLimit
```

And now, with version 6 

```cypher 
MATCH (department:Department) 
RETURN department ORDER BY department.name ASC SKIP $skip LIMIT $limit
```

Here is the `Pageable` I use.

```
PageRequest.of(0, 10, Sort.by(Sort.Order.by("department.name").ignoreCase()))
```

**Comment by michael-simons** [comment]
Thanks for your kind report. I can confirm this as a bug.

**Comment by michael-simons** [comment]
This will be fixed in all version from 6.0.10 onwards. Thanks again.

**Comment by pelletier197** [comment]
Thank you! Is there an announced release date yet for 6.0.10?

**Comment by michael-simons** [comment]
No worries. 

Sadly there isn't yet one in the team calendar (https://calendar.spring.io). I'll ask in the next sync call. 
Until then, are the Snapshot repos an option? 

```xml
<repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
```

they will contain a 6.0.10-SNAPSHOT with the fix shortly.

**Comment by pelletier197** [comment]
If SNAPSHOT is available, we can figure something out. Thank you!
