### ISSUE TITLE
Do not load the relationships of an @Node with the findAll operation.

### ISSUE THREAD

**Issue by alizadehei** [spring-projects/spring-data-neo4j#2278]
I have a class with the following structure:

```
@Node
public class Person {
@Id
private String id;
private String name;
@Relationship (type: "Is_Member_Of", direction = Relationship.Direction.OUTGOING)
private List<Member> members;
}
```

Now when I run the following query; All person relationships(members) return:
`List<Person> persons = neo4jTemplate.findAll(Person.class);`

But when I do the findAll operation with a matching query, the relationships do not return.
`List<Person> persons = neo4jTemplate.findAll("MATCH(n:Person) return n",Person.class);`

What is the cause of this issue?

**Comment by michael-simons** [comment]
Your query does not match the domain model, you are neither matching nor returning the `Member` nodes. 

Your query should probably look similar to this

```
MATCH(n:Person) - [r:Is_Member_Of] -> (m:Whatever) 
return n, collect(r), collect(m)
```

Please read https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#custom-queries

**Comment by alizadehei** [comment]
@michael-simons Thank you very much for your help

**Comment by michael-simons** [comment]
No worries :)
