### ISSUE TITLE
Support derived deleteBy methods.

### ISSUE THREAD

**Issue by awalrus4** [spring-projects/spring-data-neo4j#2281]
In Spring Data Neo4j 6.1.1 (and probably earlier), I noticed that the derived "deleteByX" queries actually don't delete; they do a find instead. 
While it's easy enough to just write a custom delete query, I point this out because it's explicitly a feature in the documentation:
https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#repositories.core-concepts

Thanks!

**Comment by michael-simons** [comment]
Great catch! I labelled this as a bug as I think a find should not happen. Rather an exception or actually do what's promised. Thank you, will be fixed in 6.0.10.
