### ISSUE TITLE
Support to execute a call query in Neo4jTemplate

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-data-neo4j#2283]
At the moment it is not possible to execute a query which return not a node
Example
```
CALL db.indexes() YIELD label RETURN label
```

**Comment by michael-simons** [comment]
Please use the `Neo4jClient`. There should be an instance in a Spring Boot project configured with the defaults. 

```
Collection<String> labels = neo4jClient.query("CALL db.indexes() YIELD name RETURN name")
					.fetchAs(String.class)
					.all();
			labels.forEach(System.out::println);
```

It's specifically designed for the purpose of plugging in your own mapping (or use simple default like in the example above). 

Please see: https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#faq.custom-queries-and-custom-mappings
and https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#building-blocks

**Comment by alxxyz** [comment]
Thank you @michael-simons .
Is it possible to pass some parameters as placeholders to the query?

**Comment by michael-simons** [comment]
You're welcome.

Sure thing, have a look: https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#neo4j-client.mapping.parameters

**Comment by alxxyz** [comment]
Perfect, thanks.
