### ISSUE TITLE
Neo4j 4.0 supports multiple databases - How can I use them?

### ISSUE THREAD

**Issue by zqw961025** [spring-projects/spring-data-neo4j#2284]
I have updated the SDN version to 6.0.2 in spring boot. What is it that does not work when I configure the custom database
My configuration file is as follows,Why is my Database configuration item not working?

data:
    neo4j:
      uri: bolt://ip:port
      username: username
      password: password
      databaes:myDatabase

**Comment by michael-simons** [comment]
Hi. Could be a combination of typographic and namespace errors:

```
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=secret
spring.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.database=fabric
```

**Comment by zqw961025** [comment]
I checked the typography and namespace to make sure it was correct but unfortunately the Database configuration item still doesn't work.
I tried the following and it worked.
Driver driver = GraphDatabase.driver("neo4j://ip:port", AuthTokens.basic("username","password"),null);
Session session = driver.session(SessionConfig.forDatabase(myDatabase));

**Comment by michael-simons** [comment]
You understand that this is a Driver session, which won’t participate in Spring Transaction and won’t be used by repositories or templates? 
That’s what the property you configured is for.

**Comment by zqw961025** [comment]
I think I understand this and I just want to prove that my Neo4j database is OK but my configuration item is still not working. I don't know why, When I configure the database property, the compiler tells me that there is no database property under spring.data.neo4j.

**Comment by meistermeier** [comment]
The parameters @michael-simons showed above are correct.
From the naming pattern, you can see that the `spring.data.neo4j.database` property only applies to Spring Data. The (raw) Java driver is not affected by this property.
The database selection will only get picked up for `Neo4jTemplate` and repositories in SDN 6.0.x.
If you use the `Neo4jClient` with its fluent API, you have to add the database explicitly in SDN 6.0.x by using the `in` method like `neo4jClient.query("").in("databaseName")`.
In SDN 6.1.x this is not necessary anymore.
What are you trying to do?

**Comment by zqw961025** [comment]
I just want to configure the properties of Neo4j (including username, password, connection string, and database since I have more than one database) under my Spring Boot program application.yml.I checked the SDN JAR under Maven, it is 6.0.2, but my database configuration item doesn't seem to work. My editor told me "cannot resolve configuration sping.data.neo4j.database".

**Comment by meistermeier** [comment]
This can have multiple reasons:
1. your IDE has not picked up the latest meta information about the application properties that are available.
2. you are using a Spring Boot version lower than 2.4
Those information are (more or less) directly provided by your editor / IDE vendor.
Basically you should not care too much about this if the application works.

**Comment by zqw961025** [comment]
I will check the reasons you mentioned above. Thank you very much for your reply.

**Comment by meistermeier** [comment]
I assume that we can close this (for now) because it is unrelated to Spring Data Neo4j directly.
If there is a problem with the database usage consider to re-open this issue again.
