### ISSUE TITLE
Version 5.2 to 6.0 change

### ISSUE THREAD

**Issue by zqw961025** [spring-projects/spring-data-neo4j#2286]
Hello, I have some questions to ask. We used version 5.2 before. Our query makes heavy use of the data.neo4j.transaction.SessionFactoryUtils class,Now I want to update to 6.0, but I find that this class is deprecated, I would like to ask if there is a replacement, I want to avoid a lot of code modification.

**Comment by michael-simons** [comment]
Hi. 6.0 is a major upgrade and change. This class is not only deprecated, but it does not exist anymore in 6.0 6.0 does not use Neo4j-OGM but it's Object Mapper on it's own.

Please take a look at the Building blocks:
https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#reference

The migration guide
https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#sdn-appendix

If you used the session factory directly, you might want to look at plethora of options we provide to run custom queries:
https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#custom-queries
https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#faq.custom-queries-and-custom-mappings

Thank you!
