### ISSUE TITLE
Session.clear() equivalent

### ISSUE THREAD

**Issue by shayantabrizi** [spring-projects/spring-data-neo4j#2302]
What is the equivalent of Session.clear() of OGM in the new SDN?

**Comment by michael-simons** [comment]
There is none. SDN 6 is context free outside a transaction.

**Comment by shayantabrizi** [comment]
This means that there is no caching of objects?

**Comment by michael-simons** [comment]
Correct.

**Comment by shayantabrizi** [comment]
Thank you

**Comment by michael-simons** [comment]
No worries, glad to help.

I wonder though, do you appreciate the change or not?

**Comment by shayantabrizi** [comment]
Three points:
1- Caching was a headache for us as developers. I welcome the change from this perspective. Especially for our tests.
2- About the performance, I do not have a comparison. Not having cache may reduce the performance in some scenarios.

**Comment by michael-simons** [comment]
Thanks for your feedback, very appreciated.

Re 1: For us too.
Re 2: I hope that use case specific caching, or explicit client side
caching, is a better solution when performance issues arises. SDN6 supports
fully immutable entities, which are a great fit for a cache of any form.

Thanks for your contribution!

shayantabrizi ***@***.***> schrieb am Mi. 23. Juni 2021 um
07:31:
