### ISSUE TITLE
@Labels annotation not working properly when having @NodeEntity on an abstract class

### ISSUE THREAD

**Issue by AlexPresso** [spring-projects/spring-data-neo4j#2306]
Hey there,

I'm trying to make the `@Labels` annotation work in my inheritance model but it's unable to retrieve labels when I fetch nodes from the repository, the labels Set is always empty even if the inerhitance model is adding every label in the graph.

Here is my class inheritance model:

├ `class BaseObject`
├─ `@NodeEntity class Node extends BaseObject` (having `@Labels protected Set<String> neo4jLabels`)
├── `class SubNodeA extends Node`
├─── `@NodeEntity abstract class SubNodeB extends SubNodeA` (forced to add `@NodeEntity` because it's an abstract class)

At this point when using `subNodeBRepository.findById(0L)`, the `subNodeB.getNeo4jLabels()` always returns an empty Set.
What's strange is that even if the labels Set is empty, adding a label in it an saving the entity does add the label to the node (which already had `:BaseObject:Node:SubNodeA:SubNodeB`)

Am I doing something wrong ?

I did a few tests and noticed that using the following inheritance model, does actually fills the labels Set with only `Node` and `SubNodeA` but then makes the repositories unable to find data ("no results will be returned. Make sure the class is registered, and not abstract without @NodeEntity annotation")
Adding back the `@NodeEntity` on these abstract classes gives an empty labels Set.

├ `class BaseObject`
├─ `abstract class Node extends BaseObject` (having `@Labels protected Set<String> neo4jLabels`)
├── `abstract class SubNodeA extends Node`
├─── `@NodeEntity abstract class SubNodeB extends SubNodeA` (forced to add `@NodeEntity` because it's an abstract class)

Libraries:
- spring-boot-starter-data-neo4j : 2.3.9.RELEASE (tried latest version, same result)
- spring-boot-starter-parent : 2.2.4.RELEASE

**Comment by michael-simons** [comment]
Thanks for your report.

I wonder: what's below `SubNodeB`? What is OGM (the version of SDN you are using is just a shim around https://github.com/neo4j/neo4j-ogm), supposed to load?

**Comment by AlexPresso** [comment]
Hi,

Bellow `SubNodeB` there is a direct `SubNodeB` implementation, to add a few properties in the node depending on some conditions in example: 
├ `class BaseObject`
├─ `@NodeEntity class Node extends BaseObject`
├── `class SubNodeA extends Node`
├─── `@NodeEntity abstract class SubNodeB`
├──── `class SubNodeBImplA extends SubNodeB implements WhateverInterface` 

And there's a few cases where there's another abstract class bellow `SubNodeB`, in example: 
├ `class BaseObject`
├─ `@NodeEntity class Node extends BaseObject`
├── `class SubNodeA extends Node`
├─── `@NodeEntity abstract class SubNodeB`
├──── `abstract class AbstractNodeB extends SubNodeB` 
├───── `class AbstractNodeBImplA extends AbstractNodeB implements WhateverInterface` 

I know it makes a lot of classes for an inheritance model but the project itself highly needs it

**Comment by michael-simons** [comment]
Thanks for the feedback. I cannot reproduce it.

Find a demo attached. 
[demo1123.zip](https://github.com/spring-projects/spring-data-neo4j/files/6700646/demo1123.zip)


The tests with the nodes created outside OGM demonstrate what is necessary to be there in the database

```java
@Test
public void run() {

Long id1 = session.queryForObject(Long.class,
	"create (a:Node:SubNodeA:SubNodeB:SubNodeBImplA {name: 'eins'}) RETURN id(a)",
	Collections.emptyMap());
Long id2 = session.queryForObject(Long.class,
	"create (a:Node:SubNodeA:SubNodeB:AbstractNodeBImplA:More:Labels {name: 'zwei'})  RETURN id(a)",
	Collections.emptyMap());
assertThat(id1).isNotNull();
assertThat(id2).isNotNull();

session.clear();

Optional<SubNodeB> optionalB1 = thingsRepository.findById(id1);
assertThat(optionalB1).hasValueSatisfying(b1 -> {
	assertThat(b1).isInstanceOf(SubNodeBImplA.class);
	assertThat(b1.getName()).isEqualTo("eins");
	assertThat(b1.getNeo4jLabels()).isEmpty();
});

Optional<SubNodeB> optionalB2 = thingsRepository.findById(id2);
assertThat(optionalB2).hasValueSatisfying(b2 -> {
	assertThat(b2).isInstanceOf(AbstractNodeBImplA.class);
	assertThat(b2.getName()).isEqualTo("zwei");
	assertThat(b2.getNeo4jLabels()).containsExactly("More", "Labels");
});

SubNodeB b1 = optionalB1.get();
b1.getNeo4jLabels().add("X");
b1.getNeo4jLabels().add("Y");

SubNodeB b2 = optionalB2.get();
b2.getNeo4jLabels().add("New1");
b2.getNeo4jLabels().add("New2");

thingsRepository.saveAll(Arrays.asList(b1, b2));

long cnt = session.queryForObject(Long.class,
	"match (a:X:Y) WHERE id(a) = $id RETURN count(a)",
	Collections.singletonMap("id", id1));
assertThat(cnt).isEqualTo(1L);

cnt = session.queryForObject(Long.class,
	"match (a:New1:New2) WHERE id(a) = $id RETURN count(a)",
	Collections.singletonMap("id", id2));
assertThat(cnt).isEqualTo(1L);
}
```

**Comment by AlexPresso** [comment]
Thanks for the test project and example

That test `assertThat(b1.getNeo4jLabels()).isEmpty()` is exactly what I mean, maybe I'm mistaking about the @Labels annotation but why is the labels Set supposed to be empty for the `b1` entity ? isn't it supposed to be: `<["Node", "SubNodeA", "SubNodeB", "SubNodeImplA"]>` ?

It also gives me an error when I run the tests, for the `b1` entity, the Set isn't empty, it is `<["BaseObject"]>`

**Comment by michael-simons** [comment]
1. `@Labels` are dynamic labels. They are supposed to contain only those labels that are not mapped statically via `@NodeEntity`. 
2. Your `BaseObject` is not-abstract. I assumed wrongly it isn't, but read the ticket again. If it is not abstract, it's class name will be used, too. In general the test should work. Just tested it again with an empty db 
![image](https://user-images.githubusercontent.com/526383/123088382-f2f5b700-d425-11eb-8a2d-ebd8d4984cec.png)

**Comment by AlexPresso** [comment]
Oooh yes you're right, my bad.

Okay I understand now, so that annotation only deals with non static labels, but is there another way to get/update the static labels of a node using the OGM i.e replace `:SubNodeImplA` by `:SubNodeImplB` ?
Or is it only possible using a Cypher query like `MATCH (n) WHERE id(n) = $0 REMOVE n:SubNodeImplA SET n:SubNodeImplB` / apoc ?

**Comment by michael-simons** [comment]
OGM won't touch your static labels. 

And your query pretty much looks the same I did in a demo:

https://github.com/michael-simons/bootiful-music/blob/master/knowledge/src/main/java/ac/simons/music/knowledge/domain/ArtistService.java#L327-L356

Make sure you have a fresh transaction or a cleared session afterwards.

**Comment by AlexPresso** [comment]
Alright, I'll have a look at it then.
Thank you very much for the details and sorry for the issue, I misunderstood the `@Labels` annotation

**Comment by michael-simons** [comment]
No worries, it was good description and it could have been a bug as well given such a complex tree.
Feel free to reach out to us on discord https://neo4j.com/developer/discord/ or community side.
