### ISSUE TITLE
Passing object as an input to a custom query is not serialized properly

### ISSUE THREAD

**Issue by pelletier197** [spring-projects/spring-data-neo4j#2308]
I have the following repository, where I pass an entity annotated with `@Node` into a custom query.  

```kotlin
// The repository
interface PersonNotesRepository : Neo4jRepository<NoteEntity, String> {
    @Query(
        """
        MATCH (person:Person { id: $${"personId"} })
        CREATE (note:Note) SET note = $${"note"}
        CREATE (person)-[:HAS_NOTE]->(note)
        RETURN note
    """
    )
    fun createNoteOnPerson(personId: String, note: NoteEntity): NoteEntity?
}

// The interface 
@Node("Note")
data class NoteEntity(
    @Id
    val id: String,
    val text: String,
    val date: Instant,
    val edited: Boolean,
    val authorId: String
)
```
I had a hard time understanding that the note parameter is actually serialized as the same parameter that is used for making auto-generated repository queries work.

```
:params {0: "info_1_id", note: {__labels__: ["Note"], __id__: "07996116-861a-47c3-9032-2162627ce32d", __properties__: {date: 2021-06-22T16:58:52.136275-04:00[America/Toronto], edited: FALSE, text: "note_1", authorId: "user_id"}}, 1: {__labels__: ["Note"], __id__: "07996116-861a-47c3-9032-2162627ce32d", __properties__: {date: 2021-06-22T16:58:52.136275-04:00[America/Toronto], edited: FALSE, text: "note_1", authorId: "user_id"}}, infoId: "info_1_id"}
```

What I would have expected is that it would simply be serialized as a map so that it's easy to manipulate the object in the queries.

```
{id: "07996116-861a-47c3-9032-2162627ce32d", date: 2021-06-22T16:58:52.136275-04:00[America/Toronto], edited: FALSE, text: "note_1", authorId: "user_id"}
```

==============

I tried another approach to avoid passing an entity directly to a query as a workaround, by providing another arbitrary object to the query 
```kotlin
data class CreateNoteEntity(
    val id: String,
    val text: String,
    val date: Instant,
    val edited: Boolean,
    val authorId: String
)
```

And modified the signature as is: 
```kotlin
    fun createNoteOnPerson(personId: String, note: CreateNoteEntity): NoteEntity?
```

this attempt results in the following exception being thrown: 
```
No converter found capable of converting from type [a.b.c.CreateNoteEntity] to type [org.neo4j.driver.Value]
```

Again, I would have expected the provided entity to be converted into a map in neo4j, so that I can use it directly in the query.

============== 

Sorry for the really long description. I wanted to give as much detail as possible to help you understand the requirement. I think this might actually be two different issues, that were both supported in the previous version of Neo4j (5), and that are not supported anymore.

**Comment by michael-simons** [comment]
Hi. I am unsure if I understand your request.

The entity is in fact serialized as a `Map` parameter, however there's no map _attribute_ inside Neo4j, you can't just assign this… It will be stored as single attributes.

Having said that, you just need to adapt your query slightly (I write down the original Cypher, because I am unsure about the escaping of `$` in a Kotlin string:

```cypher
MATCH (person:Person { id: $personId })
CREATE (note:Note) SET note = $note.__properties__
CREATE (person)-[:HAS_NOTE]->(note)
RETURN note
```

Does that help?

**Comment by pelletier197** [comment]
The entities are indeed serialized as a map, but not the map I expected. Using the `__properties__` and `__id__` works for node entities, but what I expected was that it would be converted to a map that represents the object, as in neo4j 5. (JSON of the object), not a map with `__id__` and `__properties__`.  

Further more, any object passed to a custom query used to be serialized as a map. Now, they throw an exception.  

So what I want to know is if it's possible to serialize *any object* passed in a custom query into a map by default, as it was done in neo4j 5. It was intuitive to use, and it worked both for entities and arbitrary objects out of the box.

**Comment by michael-simons** [comment]
No, it didn't not work out of the box for _all_ objects, especially not all datatypes. It was merely a coincidence that piping things to Jackson worked most of the time.
We do serialize all known entities in such a way that you can access all informations. The format is officially supported and defined by us and documented, too: https://docs.spring.io/spring-data/neo4j/docs/6.1.2/reference/html/#custom-queries.parameters

We are happy to discuss if it's an option to create maps of non-domain objects via Jackson or similar. 
But than again,  we cannot give type safety there.

**Comment by michael-simons** [comment]
I closed this, works as expected. But we are open to discuss the support for non-domain objects further in #2309 . Thanks.

**Comment by pelletier197** [comment]
Okay, I didn't see that the serialization of node entities was  documented this way. In which case I understand better. Thank you!

**Comment by michael-simons** [comment]
No worries. I do understand that it is convenient to have a map of something in at least 50% of the cases, but let me assure you that this https://github.com/neo4j/neo4j-ogm/blob/master/api/src/main/java/org/neo4j/ogm/driver/ParameterConversion.java#L51 has not been the optimal idea in the rest of the cases (and we don't speak about a big dependency yet).

We improved that already https://github.com/neo4j/neo4j-ogm/blob/master/api/src/main/java/org/neo4j/ogm/driver/TypeSystemBasedParameterConversion.java supporting at least native types, but that was as far as we are able to. go with OGM.

We are open to discuss further mapping approaches in the linked ticket.
