### ISSUE TITLE
Do some things before the transactions become committed

### ISSUE THREAD

**Issue by alizadehei** [spring-projects/spring-data-neo4j#2310]
I want to do some things before the transactions become committed.
For this purpose in SDN 5.2.4 we did this by extending the Neo4jTransactionManager :

```
public class CustomTransactionManager extends Neo4jTransactionManager{

@Override
protected void doCommit(DefaultTransactionStatus status){
     doSomeThings();
     super.doCommit(status);
   }
}
```
And we used this class as a Neo4jTransactionManager Bean.
But in SDN 6.x.x Neo4jTransactionManager class is Final. What is the cause and what is the alternative?

**Comment by michael-simons** [comment]
The reason for this we made it final as we think that extending this essential class might lead to hard to spot errors and we want to be able to evolve this as we please. 

Please use a transactional application listener: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/event/TransactionalEventListener.html

this is build for your purpose.

**Comment by alizadehei** [comment]
@michael-simons First of all, thank you for your guidance.
But this solution is not suitable for our application.
In fact, in the TransactionalEventListener, the function with this anotation is called when we have an event within a transaction. However, we do not have an event at all and we just want a specific action to be performed before each transaction commit, regardless of the presence or absence of the event.

**Comment by michael-simons** [comment]
Hi,
You’re welcome.
Do you want to do things in your application? Or in your database specific?
If so, you might consider a database trigger which is the logical place for
such a thing.

However, I’ll look into spring for you again when I’m back at a keyboard.

alizadehei ***@***.***> schrieb am Mo. 28. Juni 2021 um 06:48:

**Comment by alizadehei** [comment]
I want to do things in my application not database.

**Comment by michael-simons** [comment]
Hey @alizadehei 

This would be my preferred / recommended way of doing this:

```java
import org.neo4j.driver.Driver;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.neo4j.core.DatabaseSelectionProvider;
import org.springframework.data.neo4j.core.transaction.Neo4jTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionException;
import org.springframework.transaction.TransactionStatus;

@Configuration
public class Neo4jConfig {

	@Bean
	public PlatformTransactionManager transactionManager(Driver driver, DatabaseSelectionProvider databaseNameProvider,
		ObjectProvider<TransactionManagerCustomizers> optionalCustomizers) {
		Neo4jTransactionManager transactionManager = new Neo4jTransactionManager(driver, databaseNameProvider);
		return new DelegatingTransactionManager(transactionManager);
	}

	static class DelegatingTransactionManager implements PlatformTransactionManager {

		private final Neo4jTransactionManager delegate;

		public DelegatingTransactionManager(Neo4jTransactionManager delegate) {
			this.delegate = delegate;
		}

		@Override
		public TransactionStatus getTransaction(TransactionDefinition definition)
			throws TransactionException {
			return delegate.getTransaction(definition);
		}

		@Override public void commit(TransactionStatus status) throws TransactionException {

			System.out.println("Before commit with " + status);
			delegate.commit(status);
		}

		@Override public void rollback(TransactionStatus status) throws TransactionException {
			System.out.println("Before rollback with " + status);
			delegate.rollback(status);
		}
	}
}

```

With this, this will be applied to all things transactional, repositories, and transaction templates alike.

Another possibility is doing it with AOP and the TransactionSynchronizationManager utilities.

```java
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

@Component
@Aspect
@Order(Ordered.LOWEST_PRECEDENCE)
public class Dingens {

	@Pointcut("execution(public * ((@org.springframework.transaction.annotation.Transactional *)+).*(..)) && within(@org.springframework.transaction.annotation.Transactional *)")
	private void executionOfAnyPublicMethodInAtTransactionalType() {
	}

	@Pointcut("execution(@org.springframework.transaction.annotation.Transactional * *(..))")
	private void executionOfTransactionalMethod() {
	}

	@Pointcut("execution(* org.springframework.data.repository.CrudRepository+.*(..))))")
	private void anyRepoMethod() {}

	@Around("executionOfAnyPublicMethodInAtTransactionalType() || anyRepoMethod() || executionOfAnyPublicMethodInAtTransactionalType()")
	public Object f(ProceedingJoinPoint proceedingJoinPoint) throws Throwable {
		if(TransactionSynchronizationManager.isSynchronizationActive()) {
			TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
				@Override public void beforeCommit(boolean readOnly) {
					System.out.println("Before");
				}

				@Override public void afterCommit() {
					System.out.println("After");
				}
			});
		}
		return proceedingJoinPoint.proceed();
	}
}
```

That is however really brittle and hard to get right.

If you can't do either dedicated events or database triggers, go with the delegating tx manager.

**Comment by alizadehei** [comment]
Thank you very much for taking the time to answer my question.
I used the first method you mentioned and my problem was solved.

**Comment by shayantabrizi** [comment]
@michael-simons What if someone wants to run something in every transaction (e.g., some request version checking) but he needs it to be performed in the same transaction that is being commited? 

Assume that one wants to receive some version from the user and check it with the version in the database and only commit if the versions match. If we handle it with DelegatingTransactionManager you mentioned, if I'm not mistaken, if we put @Transactional on `commit(TransactionStatus status) `  the `System.out.println("Before commit with " + status);` is not run within the transaction that is being commited, so if we want to access the database and get the version, getting the version is not run in the same transaction, which may cause inconsistencies or other problems.

**Comment by shayantabrizi** [comment]
@michael-simons Can we work with the database in the same transaction in your second solution (aspect-based one)? (e.g., in before commit). If not how can one run a command before commit in the same transaction that is being commited for all transactions? (e.g., to check some version)

**Comment by michael-simons** [comment]
The transaction will be open in before commit for obvious reasons (it cannot be committed when its not there). So your thing will be run in the same tx.

What are you actually trying to solve?

**Comment by shayantabrizi** [comment]
E.g., if I'm not mistaken, in the `doCommit` method of the first @alizadehei 's issue doCommit does not run in the transaction that is being commited and if we want to make `doCommit` @Transactional, it may result in a loop. Is the same true about your second solution? If yes, what is the solution?

**Comment by alizadehei** [comment]
I can confirm that what @shayantabrizi said happens in the first solution, i.e, the `doSomeDatabaseAction` method is not run inside the same transaction that is being committed in the following code:

```
		@Override public void commit(TransactionStatus status) throws TransactionException {
			doSomeDatabaseAction();
			delegate.commit(status);
		}
```

**Comment by michael-simons** [comment]
Well I guess you're using the wrong abstraction. Could it be that you expect `org.neo4j.driver.Driver` to participate in Spring transactions? If so, it does not! Please have a look at the [Building blocks](https://docs.spring.io/spring-data/neo4j/docs/6.1.2/reference/html/#building-blocks). The diagram explains which components participate in Spring transactions.

Here's a working example.

Given

```java
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;

@Node
public class Movie {

	@Id @GeneratedValue
	private Long id;

	private String title;

	public Movie(String title) {
		this.title = title;
	}

	public Long getId() {
		return id;
	}

	public String getTitle() {
		return title;
	}
}
```

```java
import org.springframework.data.neo4j.repository.Neo4jRepository;

public interface MovieRepository extends Neo4jRepository<Movie, Long> {
}
```

and the application and beans:

```java
import java.time.LocalDateTime;

import org.neo4j.driver.Driver;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizers;
import org.springframework.context.annotation.Bean;
import org.springframework.data.neo4j.core.DatabaseSelectionProvider;
import org.springframework.data.neo4j.core.Neo4jClient;
import org.springframework.data.neo4j.core.transaction.Neo4jTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionException;
import org.springframework.transaction.TransactionStatus;

@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	@Bean
	public PlatformTransactionManager transactionManager(Driver driver, DatabaseSelectionProvider databaseNameProvider,
		ObjectProvider<TransactionManagerCustomizers> optionalCustomizers, Neo4jClient neo4jClient) {
		Neo4jTransactionManager transactionManager = new Neo4jTransactionManager(driver, databaseNameProvider);
		return new DelegatingTransactionManager(transactionManager, neo4jClient);
	}

	@Bean
	public CommandLineRunner demo(MovieRepository movies) {
		return new CommandLineRunner() {
			@Override public void run(String... args) {
				movies.save(new Movie("A movie created at " + LocalDateTime.now()));
			}
		};
	}

	static class DelegatingTransactionManager implements PlatformTransactionManager {

		private final Neo4jTransactionManager delegate;

		private final Neo4jClient neo4jClient;

		// THe driver itself DOES NOT PARTICIPATE in Spring trangsactions
		// private Driver driver;

		public DelegatingTransactionManager(Neo4jTransactionManager delegate,
			Neo4jClient neo4jClient) {
			this.delegate = delegate;
			this.neo4jClient = neo4jClient;
		}

		@Override
		public TransactionStatus getTransaction(TransactionDefinition definition)
			throws TransactionException {
			return delegate.getTransaction(definition);
		}

		@Override public void commit(TransactionStatus status) throws TransactionException {

			System.out.println("Before commit with " + status);
			System.out.println("fetching things via the client");
			this.neo4jClient.query("MATCH (m:Movie) RETURN m.title").fetchAs(String.class)
				.all().forEach(System.out::println);
			delegate.commit(status);
		}

		@Override public void rollback(TransactionStatus status) throws TransactionException {
			System.out.println("Before rollback with " + status);
			delegate.rollback(status);
		}
	}
}
```

**Comment by shayantabrizi** [comment]
Thank you. If I'm not mistaken. the problem was that what we wanted to call before commit was an @Transactional method and it didn't understand that we are in an active transaction and tried to get a new transaction.
