### ISSUE TITLE
Make testing cleaner

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data-neo4j#2316]
reading https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#dataneo4jtest

and wondering, couldn't this be easier? I mean how often am I going to care about the actual username and password, couldn't I just inject, for example, a `Neo4j` and have it configured by default when I use `@DataNeo4jTest` depending on what's on the classpath. I don't really see why the sample test should need to do anything other than this (well, it doesn't seem as this is setting up any data, but other than that...)

```java
@DataNeo4jTest
class MovieRepositoryTest {

        @Test
        public void findSomethingShouldWork(@Autowired Neo4jClient client) {

                Optional<Long> result = client.query("MATCH (n) RETURN COUNT(n)")
                        .fetchAs(Long.class)
                        .one();
                assertThat(result).hasValue(0L);
        }
}
```

**Comment by michael-simons** [comment]
`@DataNeo4jTest` is part of https://github.com/spring-projects/spring-boot. While I do think it does exactly what is supposed todo, feel free to raise an issue over there.
