### ISSUE TITLE
Bug in connecting objects

### ISSUE THREAD

**Issue by shayantabrizi** [spring-projects/spring-data-neo4j#2318]
It seems that there is something wrong which causes [this code](https://github.com/shayantabrizi/sample-code-1/tree/multi-path) to behave nondeterministically and sometimes wrong.  

```
        final C c = new C("att");
        final B b = new B(List.of(new B.C2(c)));
        final A a = new A(List.of(c), List.of(b));

        a.getCs().forEach(definition -> template.save(definition));
        a.getBs().forEach(definition -> template.save(definition));
        template.save(a);

        final Optional<Map<String, Object>> one = client.query("Match (n{id:'att'})-[r]-(m:A) return count(r)").fetch().one();
        System.out.println(one.get().get("count(r)"));
```
`a` has a member `cs` which includes a `C` object. However, sometimes a link is created between `a` and `c` (thus, printing 1) and sometimes no link is created between them (thus, printing 0). 

Just run the code several times and see what is printed.

**Comment by meistermeier** [comment]
Could you please tell us which version are you using?

**Comment by meistermeier** [comment]
I cannot really reproduce your issue. Always getting the relationship created without any changes to your code.
Speaking of which: you could skip the `forEach` definition parts because all the cascading relationship and nodes will get persisted during the `template.save(a)` call.
Maybe you can give me any hints how to enforce the faulty behaviour.

**Comment by shayantabrizi** [comment]
We have encountered it on three different computers. Windows and Linux. Neo4j 4.3.2 and 4.3.1 (embedded) and 4.2.1 (Neo4j Desktop). 

The `forEach` parts were mentioned for reproducibility. But, I checked and without them the problem persists. I run on .2.1 (Neo4j Desktop) now and report the results:
First run: 1
Second run: 1
Third run: 0
Forth run: 1
Fifth run: 0
Sixth run: 0
Seventh run: 1

The results are non-deterministic. Maybe, a 0 happens in your system after several runs.
I committed the code I got the above results with now, in which the `forEach`s are removed.

**Comment by meistermeier** [comment]
I can see the problem now. Just re-ran it and at least with a 30/70 ratio it is reproducible.
Investigating...

**Comment by meistermeier** [comment]
It would be helpful if you could give `6.1.3-GH-2318-SNAPSHOT` a try.

To get the snapshot you would have to add Spring's repositories to your application:
```
<repositories>
  <repository>
    <id>spring-milestones</id>
    <name>Spring Milestones</name>
    <url>https://repo.spring.io/milestone</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>spring-snapshots</id>
    <name>Spring Snapshots</name>
    <url>https://repo.spring.io/snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
  </repository>
</repositories>
```

**Comment by shayantabrizi** [comment]
Not solved.
First run: 0
Second run: 1
Third run: 0

The updated code is pushed.

**Comment by meistermeier** [comment]
Thanks for your feedback. Will merge this now into 6.1.x for the 6.1.3 patch and main.
