### ISSUE TITLE
@Query can support SPEL to dynamic replacement method param

### ISSUE THREAD

**Issue by liuzongliang0202** [spring-projects/spring-data-neo4j#2322]
@Query(
        value = "match (s:{0}{label_id:{1}}),(t:{2}{label_id:{3}}) merge (s)-[r:Attention]-(t) return r")
    void insertOrUpdateAttentionRelationShip(String fromLabel, Long fromUserId, String toLabel, Long toUserId);

As in the example above，i want to dynamically replace label ,but it can't work, and I tried many times，like use "?#{0}","#{fromLabel}"...
the Source code ： 
`public static ParameterizedQuery getParameterizedQuery(String queryString, Parameters<?, ?> methodParameters,
			QueryMethodEvaluationContextProvider evaluationContextProvider) {

		Neo4jQueryPlaceholderSupplier supplier = new Neo4jQueryPlaceholderSupplier();

		EvaluatingSpelQueryContext context = SpelQueryContext.of( //
				(index, prefix) -> supplier.parameterName(index), //
				(prefix, name) -> supplier.decoratePlaceholder(name)) //
				.withEvaluationContextProvider(evaluationContextProvider);

		SpelEvaluator evaluator = context.parse(queryString, methodParameters);
		return new ParameterizedQuery(methodParameters, evaluator);
	}
....
`

**Comment by michael-simons** [comment]
I'm sorry, but I don't understand your issue / question.

**Comment by liuzongliang0202** [comment]
i find the answer of my issue, neo4j cypher no support parameterized label .
`

Parameters cannot be used for the following constructs, as these form part of the query structure that is compiled into a query plan:

1.property keys; so, MATCH (n) WHERE n.$param = 'something' is invalid

2.relationship types

3.labels

`

**Comment by liuzongliang0202** [comment]
Spring can replace the value in @ query before calling neo4j API ？

**Comment by michael-simons** [comment]
Aah, that's what you wanted to do. I could have told you that. Labels and Types are constants.

What you want to do is actually possible with SPeL and we do have example / test code for it:

https://docs.spring.io/spring-data/neo4j/docs/6.1.2/reference/html/#custom-queries.spel

See Listing 80. literal-Extension
