### ISSUE TITLE
`saveAll` use the lowest common denominator for determining the entity type to be saved.

### ISSUE THREAD

**Issue by LGDOI** [spring-projects/spring-data-neo4j#2326]
Given a list of entities with mixed types which have common parent.

e.g., 
Base class  does NOT have @Entity annotation

```
public abstract class BaseEntity {}
```

Entity classes have @Entity annotation
```
public abstract class Animal extends BaseEntity {}
public abstract class Pet extends Animal {
  public static  class Cat extends Pet {}
  public static  class Dog extends Pet {}
}
```

Repository class

```
public interface AnimalRepository extends Neo4jRepository<Animal, String> {}
```

List of animals
```
List<Animal> animals = List.of(new Cat(), new Dog());
```

Save iteratively 
```
animals.forEach(animalRepository::save);
```
Two nodes created with all labels (Animal, Pet, Cat, Dog) correctly as expected

Save the list with saveAll does not save correctly.
```
animalRepository.saveAll(animals);
```

Two nodes are created but these nodes only have a label of `BaseEntity`.

**Expected behavior**

The saveAll() method with mixed entity type should create exact same labels as save().

version 6.1.1

**Comment by michael-simons** [comment]
I assume you mean `@Node` annotation, right? There is no `@Entity` annotation.

**Comment by michael-simons** [comment]
Anyway, I can confirm this,

**Comment by michael-simons** [comment]
Thanks for reporting this. This is fixed and will be released this week.

**Comment by LGDOI** [comment]
You are right about the annotation. I updated the original post from @Entity to @Node for a record.
Thank you for quick resolution.

**Comment by LGDOI** [comment]
We are currently using **6.1.1**.  Are you able to include this change in 6.1.3 as well?
