### ISSUE TITLE
Clear exception message on recursive mapping of immutable objects.

### ISSUE THREAD

**Issue by Andy2003** [spring-projects/spring-data-neo4j#2340]
I've created a Test case showing a StackOverflowError at https://github.com/Andy2003/spring-data-neo4j/tree/complex-test (https://github.com/Andy2003/spring-data-neo4j/commit/d54e4beb6ab9ee3ec3070075fd45d2eb7bb60338)

The error occurs when in a parent-child mapping the relation is modeled for both directions, like:

```java
@org.springframework.data.neo4j.core.schema.Node
public abstract class BaseNodeEntity {
	@Relationship(type = "CHILD_OF", direction = OUTGOING)
	BaseNodeEntity childOf;
}
```

and 

```java
@org.springframework.data.neo4j.core.schema.Node
public class Node extends BaseNodeEntity {
	@Relationship(type = "CHILD_OF", direction = INCOMING)
	protected Set<BaseNodeEntity> childNodes;
}
```

and data like:

```cypher
CREATE (root:Node:BaseNodeEntity{nodeId: 'root'})
CREATE (company:Node:BaseNodeEntity{nodeId: 'comp'})
CREATE (company)-[:CHILD_OF]->(root)
```

**Comment by meistermeier** [comment]
You are using the Lombok library with `@AllArgsConstructor(onConstructor = @__(@PersistenceConstructor))` for the `BaseNodeEntity`. Combined with the manual all args `@PersistenceConstructor` in the `Node` you create a hen/egg scenario.
The mapping process wants to create the "root" `Node` but for this it needs the "comp" `Node` which depends again on the not-yet-complete-constructed "root" `Node`.
We will investigate if we could detect this incoming data-wise before running into the SO and log a warning or similar.

**Comment by Andy2003** [comment]
Is it possible, that you inject the not jet fully populated object into the "child"-constructor, so you won't run into the cycle?
I used immutable Objects as the docs suggested it as best practice

**Comment by meistermeier** [comment]
No, we tried this more than once, but it is not possible to do this in any way.
For true immutability the root object for example has to be the _same_ as the root object and the one you can reach by the parent/child object. Every approach failed because it is just not possible to assemble this.

**Comment by Andy2003** [comment]
I found this on StackOverflow https://stackoverflow.com/a/4834584/1666829
I guess I have to care about this scenario in client code and use an approach similar to the one described in the post.
