### ISSUE TITLE
Add additional tests for verifying persistence of related entities with assigned ids.

### ISSUE THREAD

**Issue by LGDOI** [spring-projects/spring-data-neo4j#2346]
Given entities `Application` and `Workflow` where they have one-to-many relationship:  `(:Application)-[:CONTAINS_WORKFLOW]->(:Workflow)`

In Java, Application has outgoing relationship to List<Workflow>. Workflow has incoming relationship to Application. 

```
    val application1 = ApplicationStub.getOne(id = "app-1")
    val application2 = ApplicationStub.getOne(id = "app-2")

    val workflow1 = WorkflowStub.getOne(id = "wf-1", application = application1)
    val workflow2 = WorkflowStub.getOne(id = "wf-2", application = application2)

    application1.workflows = listOf(workflow1)
    application2.workflows = listOf(workflow2)
```
The above Kotlin code wires up both relationships.

In order to create graph correctly I can run either one of the following save methods.
```
//    listOf(application1, application2).forEach(applicationRepository::save)
// or
//    listOf(workflow1, workflow2).forEach(workflowRepository::save)
```

But, none of the following `saveAll` creates four nodes but no relationships are created b/w Application and Workflow
```
//    applicationRepository.saveAll(listOf(application1, application2))
//    applicationRepository.saveAll(listOf(application1))
//    workflowRepository.saveAll(listOf(workflow1, workflow2))
//    workflowRepository.saveAll(listOf(workflow1))
```

Also, tried uncommenting the following "BOTH" `saveAll` calls. But, this did not work either.

```
//    applicationRepository.saveAll(listOf(application1, application2))
//    workflowRepository.saveAll(listOf(workflow1, workflow2))
```

There seems a bug in `saveAll` method. Should we expect the `save` and `saveAll` behaves in the same manner.

Note: We use SDN v6.1.3.

**Comment by LGDOI** [comment]
Further troubleshooting narrowed down to specifying `id` on Workflow causes broken relationship.
Changed the workflow creation without id.
```
    val workflow1 = WorkflowStub.getOne(application = application1)
    val workflow2 = WorkflowStub.getOne(application = application2)
```

Then, `saveAll` works.

```
    applicationRepository.saveAll(listOf(application1, application2))
```

**Comment by michael-simons** [comment]
This is actually the same issue that is behind #2347. Two for the price of one, thanks a ton for your reports. 👍
