### ISSUE TITLE
Use default values for primitive attributes when Graph properties are unset.

### ISSUE THREAD

**Issue by fnordian** [spring-projects/spring-data-neo4j#2348]
I am upgrading my existing application to sdn6. There's a `boolean` field in my entities that is not set for some of the nodes.

Reading those nodes fails with `NullPointerException` when unboxing null to boolean. 

I tried to trace that problem and to me it seems that `DefaultNeo4jConversionService` has extra handling for null-values (valueIsLiteralNullOrNullValue) and that causes that no converters are called.

So the case cannot be caught through a custom converter. Is there another way to handle null-values gracefully?

This problem did not exist with OGM

**Comment by michael-simons** [comment]
Are you happen to have these properties defined as constructor parameters? Than this behavior is expected.

It used to be a mapping exception but that prevents Kotlins explicit defaults from working: 

https://github.com/spring-projects/spring-data-neo4j/commit/871d586c15c7b31dd6d1e31c4de185ab736fac13

Non constructor properties should work. 
If not I take care next week. Also for your other issues. Thanks for reporting them. 👍

**Comment by michael-simons** [comment]
That has been actually more tricky than I thought, as we also want to support Kotlin default values (non JVM defaults, but explicit ones). But things should work now. Thanks again for the report.
