### ISSUE TITLE
RelationshipEntity properties are not flushed to remote DB

### ISSUE THREAD

**Issue by edoshor** [spring-projects/spring-data-neo4j#235]
The relationship entity is persisted in neo4j but without its properties. I get null on all of them. 
I'm using 3.3.0.RC1 with a remote DB.

The problem lies within the SourceStateTransmitter.copyPropertiesTo() method:
The given PropertyContainer is track() and flush() properly. However, setEntityStateValue() will not use it to store the converted values. Instead it uses another PropertyContainer instance coming from the template which reload the entity from the DB all over again for each property.

So, I see the actual conversion taking place correctly but the values are stored on another instance.

**Comment by jexp** [comment]
I found the issue in due to not caching RestRelationships there are two different instances pulled at different times, one has the properties the other has not, so I have to add a relationship cache too. Will try to address that tomorrow.

**Comment by photasa** [comment]
I saw the 3.3.0 is released today, but wondering if this issue is fixed. We can't upgrade to 3.3.0 without this fixed. Thank you for your help.

**Comment by jexp** [comment]
Yes, please try and report back

**Comment by photasa** [comment]
Unfortunately, the issue is still there. It is show stopper for us as we need to create relationship entity directly. Any help would be appreciated.

**Comment by kar33mham** [comment]
Are there any new updates regarding this issue?

**Comment by jexp** [comment]
@photasa I added tests around this which now succeed in 3.3.0, so we should try to figure out what your concrete setup or failing unit-test looks like.

**Comment by photasa** [comment]
I have a small maven project demonstrates the issue. I can send it if necessary. But here are some key part of the test. The test runs successfully with 3.2.2.RELEASE, but failed in 3.3.0. The reason is that the "type" (and all other) property in LikeRelationship is not stored. Your help is greatly appreciated.

spring config:
	<neo4j:repositories base-package="test.neo4j.repository" />
	
	<bean id="graphDatabaseService"
		class="org.springframework.data.neo4j.rest.SpringRestGraphDatabase">
		<constructor-arg value="http://localhost:7474/db/data/" />
	</bean>

	
	<neo4j:config graphDatabaseService="graphDatabaseService"
		base-package="test.neo4j" />

Relationships:

package test.neo4j.resource;

@RelationshipEntity
public class LikeRelationship {

	@GraphId
	public Long id;

	@RelationshipType
	private final TestRelationshipType type = TestRelationshipType.LIKE;

	@StartNode
	protected Resource start;

	@EndNode
	protected Resource end;

	public LikeRelationship() {
	}

	public LikeRelationship(Resource startNode, Resource endNode) {
		this.start = startNode;
		this.end = endNode;
	}
}

Relationship Type:
package test.neo4j.resource;

import org.neo4j.graphdb.RelationshipType;

public enum TestRelationshipType implements RelationshipType {
	LIKE
}

TestNG test:

@Transactional
@ContextConfiguration(locations = { "classpath:spring-bootstrap.xml" })
public class RelationshipTest extends AbstractTestNGSpringContextTests {

	@Autowired
	private MovieRepository movies;

	@Autowired
	private UserRepository users;

	@Autowired
	LikeRelationshipRepository likes;

	@BeforeMethod
	public void beforeTest() {
		likes.deleteAll();
		users.deleteAll();
		movies.deleteAll();
	}

	@Test
	public void f() {
		User a = new User();
		a.setName("John");

		a = users.save(a);

		Assert.assertNotNull(a);

		Movie b = new Movie();

		b.setName("Amazing Spiderman");

		b = movies.save(b);

		Assert.assertNotNull(b);

		LikeRelationship like = new LikeRelationship(a, b);

		likes.save(like);

		List<TestRelationshipType> rels = new ArrayList<>();
		
		rels.add(TestRelationshipType.LIKE);

		List<Movie> ms = movies.getMoviesLikedByPerson(a, rels);

		Assert.assertEquals(ms.size(), 1);

		Movie m = ms.get(0);

		Assert.assertEquals(m.id, b.id);

	}
}

Movie Repository:

public interface MovieRepository extends GraphRepository<Movie> {

	@Query("START u=node({0}) MATCH (u) -[r]-> (m:Movie) WHERE r.type in {1} RETURN m")
	List<Movie> getMoviesLikedByPerson(User person,
			List<TestRelationshipType> relationships);
}

**Comment by jexp** [comment]
You only have the type property which is also final, so can't be set or changed, and will not be set as property but rather used as rel-type. 

Do you have any other properties that are actually not saved?

**Comment by photasa** [comment]
Regardless what properties are there, they are not stored. The example is meant to be brief, but none of the properties got stored in our application. With 3.2.2, the type is stored and the query: "START u=node({0}) MATCH (u) -[r]-> (m:Movie) WHERE r.type in {1} RETURN m" successfully retrieve the result. With 3.3.0, the query returns empty.

Also, even though the 'type' is final, it shouldn't prevent the value to be stored into neo4j.

**Comment by photasa** [comment]
Any update about this issue?

**Comment by photasa** [comment]
I updated the test case above and added another property "level" to the relationship:

```java
@RelationshipEntity
public class LikeRelationship {

	@GraphId
	public Long id;

	private final TestRelationshipType type = TestRelationshipType.LIKE;

	private String level;

	@StartNode
	protected Resource start;

	@EndNode
	protected Resource end;

	public LikeRelationship() {
	}

	public LikeRelationship(Resource startNode, Resource endNode) {
		this.start = startNode;
		this.end = endNode;
	}

	public void setLevel(String level) {
		this.level = level;
	}
}
```

In the test case, I set the level property and save it:
```java
@Test
	public void f() {
		User a = new User();
		a.setName("John");

		a = users.save(a);

		Assert.assertNotNull(a);

		Movie b = new Movie();

		b.setName("Amazing Spiderman");

		b = movies.save(b);

		Assert.assertNotNull(b);

		LikeRelationship like = new LikeRelationship(a, b);

		like.setLevel("HEAVY");
		
		likes.save(like);

		List<TestRelationshipType> rels = new ArrayList<>();
		
		rels.add(TestRelationshipType.LIKE);

		List<Movie> ms = movies.getMoviesLikedByPerson(a, rels);

		Assert.assertEquals(ms.size(), 1);

		Movie m = ms.get(0);

		Assert.assertEquals(m.id, b.id);
}
```

Review the result in Neo4J console, no properties saved. Only property in the relationship node is \__type\__.

Your help is greatly appreciated.

**Comment by photasa** [comment]
The following is the debug log that demonstrate where the issue occur. The relationship has properties of "type" and "level". The rest requests do add them to remote server via "PUT properties/type LIKE" and "PUT properties/level HIGH". However the last PUT request "PUT properties {\__type\__=LikeRelationship} " essentially delete "type" and "level" and replace them with "\__type\__" property.

```
2015-05-01 12:56:28,167 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | POST relationships {to=http://localhost:7474/db/data/node/142503, type=LIKE} 
2015-05-01 12:56:28,170 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | POST index/relationship/__rel_types__ {value=LikeRelationship, uri=http://localhost:7474/db/data/relationship/219041, key=className} 
2015-05-01 12:56:28,175 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | PUT properties/__type__ LikeRelationship 
2015-05-01 12:56:28,177 DEBUG | main | o.s.d.neo4j.fieldaccess.DelegatingFieldAccessorFactory  | Factory org.springframework.data.neo4j.fieldaccess.IdFieldAccessorFactory@4a4539e6 used for field: class java.lang.Long id rel: false idx: false 
2015-05-01 12:56:28,179 DEBUG | main | o.s.d.neo4j.fieldaccess.DelegatingFieldAccessorFactory  | Factory org.springframework.data.neo4j.fieldaccess.ConvertingNodePropertyFieldAccessorFactory@4fba8d2a used for field: class test.neo4j.resource.TestRelationshipType type rel: false idx: false 
2015-05-01 12:56:28,179 DEBUG | main | o.s.d.neo4j.fieldaccess.DelegatingFieldAccessorFactory  | Factory org.springframework.data.neo4j.fieldaccess.PropertyFieldAccessorFactory@6089e94a used for field: class java.lang.String level rel: false idx: false 
2015-05-01 12:56:28,179 DEBUG | main | o.s.d.neo4j.fieldaccess.DelegatingFieldAccessorFactory  | Factory org.springframework.data.neo4j.fieldaccess.RelationshipNodeFieldAccessorFactory@7e332ac9 used for field: interface test.neo4j.resource.Resource end rel: false idx: false 
2015-05-01 12:56:28,179 DEBUG | main | o.s.d.neo4j.fieldaccess.DelegatingFieldAccessorFactory  | Factory org.springframework.data.neo4j.fieldaccess.RelationshipNodeFieldAccessorFactory@7e332ac9 used for field: interface test.neo4j.resource.Resource start rel: false idx: false 
2015-05-01 12:56:28,181 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | GET relationship/219041 
2015-05-01 12:56:28,183 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | PUT properties/type LIKE 
2015-05-01 12:56:28,184 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | PUT properties/level HIGH 
2015-05-01 12:56:28,186 DEBUG | main | org.neo4j.rest.graphdb.RestRequest                      | PUT properties {__type__=LikeRelationship} 
```

The code that generate the debug log is:

```java
@Autowired
LikeRelationshipRepository likes;

LikeRelationship like = new LikeRelationship(a, b);
		
like.setLevel("HIGH");
		
like.setType("LIKE");

like = likes.save(like);

```

**Comment by adi-ads** [comment]
Is there a workaround for this?

**Comment by jexp** [comment]
Which version are you using?

**Comment by adi-ads** [comment]
3.3.1.RELEASE

**Comment by nayish** [comment]
I have an open question in StackOverflow I think may be relavent here http://stackoverflow.com/q/30884270/576831

After upgrading to version 3.3.0 we started getting wierd results. We have 2 different web servers which were giving different results for recently updated data. Might have been because they were being fetchef through a relationship, although we also had a problem with the findOne but I feel it still might have something to do with cached versions fetched via relationships. But that just a hunch

**Comment by nayish** [comment]
was this ever solved?

**Comment by anegrin** [comment]
here's my workaround:

```
//transacted
Relatioinship saved = repository.save(relatioinship);//create
repository.save(saved);//update
```

i.e. create than update (looks like the creation do not consider properties...)

**Comment by Xeemed** [comment]
i got exactly the same problem (version 3.4.2) and the workaround described by @anegrin works for me.

**Comment by mangrish** [comment]
Closed. Issue out of date.
