### ISSUE TITLE
Improve handling of non-distinct collections and already visited objects.

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [spring-projects/spring-data-neo4j#2355]
When saving two nodes with version properties that reference each other, an `OptimisticLockingFailureException` is thrown upon calling `save`. This only occurs when saving with **two** pre-existing nodes, if you create two new nodes with a cyclic relationship or create one new node and use one pre-existing node it works.

The exception is thrown in `ReactiveNeo4jTemplate::saveRelatedNode`, inside of 
```java
switchIfEmpty(Mono.defer(() -> {
    if (targetNodeDescription.hasVersionProperty()) {
        return Mono.error(() -> new OptimisticLockingFailureException(OPTIMISTIC_LOCKING_ERROR_MESSAGE));
    }
    return Mono.empty();
})
```

**Comment by michael-simons** [comment]
Hi. Would you please share the domain or the excerpt of it causing the issues? Thank you.

**Comment by Sm0keySa1m0n** [comment]
The problem occurs if you have two `User`s who are both friends with each other, it also occurs if one `User` has a friend and the other `User` has that `User` as their family etc. Essentially if two `User`s both reference each other in a relationship, it causes this exception.

I've tried with immutable and mutable, I've tried using a `Long` object and `long` primitive for the version, I've tried different types for the ID and I've tried using `Set`s instead of `List`s.

```java
@Node
public class User {

  @Id
  private final Long id;

  @Version
  private final Long version;

  @Relationship(direction = Relationship.Direction.OUTGOING, type = "FRIEND")
  private List<User> friends = new ArrayList<>();

  @Relationship(direction = Relationship.Direction.OUTGOING, type = "FAMILY")
  private List<User> family = new ArrayList<>();

  public User(Long id, Long version) {
    this.id = id;
    this.version = version;
  }

  public Long getId() {
    return this.id;
  }

  public Long getVersion() {
    return this.version;
  }

  public List<User> getFriends() {
    return this.friends;
  }

  public List<User> getFamily() {
    return this.family;
  }

  public void addFamily(User user) {
    this.family.add(user);
  }

  public void remveFamily(User user) {
    this.family.remove(user);
  }

  public void addFriend(User user) {
    this.friends.add(user);
  }

  public void removeFriend(User user) {
    this.friends.remove(user);
  }
}
```

**Comment by michael-simons** [comment]
Thanks for sharing. On it.

**Comment by michael-simons** [comment]
One workaround is to use `save` instead of `saveAll`

```
User u1 = userRepository.findOneByName("U1");
		User u2 = userRepository.findOneByName("U2");
		u1.addFriend(u2);
		u2.addFriend(u1);

		userRepository.save(u1);
```

like this, which will correctly update u2 as well…

**Comment by Sm0keySa1m0n** [comment]
That doesn't throw an exception but doesn't persist the relationship: ![](https://i.imgur.com/Oeso9Ur.png)

**Comment by Sm0keySa1m0n** [comment]
To produce  the above I first ran:
```java
this.repo.save(new User(1L, 0L)).block();
this.repo.save(new User(2L, 0L)).block();
```
Then ran:
```java
var user1 = this.repo.findById(1L).block();
var user2 = this.repo.findById(2L).block();
user1.addFriend(user2);
user2.addFriend(user1);
this.repo.save(user1).block();
```

**Comment by michael-simons** [comment]
Hi. This is fixed. 
Please have a look at this package https://github.com/spring-projects/spring-data-neo4j/tree/main/src/test/java/org/springframework/data/neo4j/integration/versioned_self_references for the supported use cases. 

Thanks a lot for reporting this issue, I think the improvements made here are super valueable.
