### ISSUE TITLE
Docs bug?

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data-neo4j#2358]
I think this might be a bug, though possible I just can't find it, sorry if that's true [reference docs](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#auditing.interfaces). I think this section of documentation comes from Spring Data Commons, in which case a resync needs to be done, it isn't in there anymore (duplicating documentation like this is unwise, IMHO).

> There is also a convenience base class, AbstractAuditable, which you can extend to avoid the need to manually implement the interface methods. Doing so increases the coupling of your domain classes to Spring Data, which might be something you want to avoid. Usually, the annotation-based way of defining auditing metadata is preferred as it is less invasive and more flexible.

**Comment by michael-simons** [comment]
Thanks, I have created a PR with Commons… The class of exists only in Spring Data JPA.
