### ISSUE TITLE
Node's outgoing relationship not preserved when saving more than one adjacent node.

### ISSUE THREAD

**Issue by travishamilton1992** [spring-projects/spring-data-neo4j#2359]
I am not sure if this is a bug or feature.

I have four node classes `Workflow`, `Layout`, `WorkflowMap` and `ReportFilter`.  
An instance of `Workflow` and `Layout` are created with `WorkflowStub` and `LayoutStub`, respectively. 
An instance of `ReportFilter` is created with `BuildFilter()`.
An instance of `WorkflowMap` is created with the `addManyToMany()`.

`Workflow` has an outgoing relationship with `WorkflowMap`
`WorkflowMap` has an outgoing relationship with `Workflow`
`Layout` has an outgoing relationship with `Workflow`
`ReportFilter` has an outgoing relationship with `Workflow`.
All relationships are 1-to-1

Without the `Layout` node, I see the following graph:

```
  @Test
  fun setUpBug() {
    workflow1 = WorkflowStub.getOne()

    reportFilter = BuildFilter()
    reportFilter.workflow = workflow1
    reportFilter.workflow.addManyToMany(workflow1)

    //layoutDisplay1 = LayoutStub.getOne(workflow = workflow1)

    //layoutRepository.save(layoutDisplay1)
    reportFilterRepository.save(reportFilter)

  }
```
![WithoutLayout_NoBug](https://user-images.githubusercontent.com/89268024/130271742-53eedc0d-20be-4791-957f-27dfa4a3f62c.png)

If I add the `Layout` node and remove the `ReportFilter` node (by not saving it), I get the following graph:

```
  @Test
  fun setUpBug() {
    workflow1 = WorkflowStub.getOne()

    reportFilter = BuildFilter()
    reportFilter.workflow = workflow1
    reportFilter.workflow.addManyToMany(workflow1)

    layoutDisplay1 = LayoutStub.getOne(workflow = workflow1)

    layoutRepository.save(layoutDisplay1)
    //reportFilterRepository.save(reportFilter)

  }
```
<img width="1792" alt="WithoutReportFilter_NoBug" src="https://user-images.githubusercontent.com/89268024/130276127-5cc65bc3-fbe4-4c8b-8510-9f6a2e795d1b.png">

When `Layout` and `ReportFilter` are saved, the relationship from `Workflow` to `WorkflowMap` is removed. This corresponds to `Workflow`'s outgoing relationship to `WorkflowMap`:

```
  @Test
  fun setUpBug() {
    workflow1 = WorkflowStub.getOne()

    reportFilter = BuildFilter()
    reportFilter.workflow = workflow1
    reportFilter.workflow.addManyToMany(workflow1)

    layoutDisplay1 = LayoutStub.getOne(workflow = workflow1)

    layoutRepository.save(layoutDisplay1)
    reportFilterRepository.save(reportFilter)

  }
```
![WithLayout_LayoutSavedFirst](https://user-images.githubusercontent.com/89268024/130272122-5f850d16-4a4f-4827-a279-d6a551f1a7b9.png)

The order of the save has no effect on the outcome. `ManyToMany` and `Display` are additional labels for the `WorkflowMap` and `Layout` node, respectively.

**Comment by michael-simons** [comment]
Hi.

Would you please share your logic behind `BuildFilter` and `addManyToMany`?

**Comment by travishamilton1992** [comment]
Hi,

`BuildFilter` creates a `ReportFilter` object. The `ReportFilter` class is decorated with an `@Node`. The decorator's only parameter is `primaryLabel = "ReportFilter"`
`addOneToMany` creates a new `WorkflowMap` object with its workflow field assigned to `workflow1`. The `WorkflowMap` class is also decorated with an `@Node` with `primaryLabel` set to `"WorkflowMap"`.

I am fairly new to SDN so let me know if you need more information. Thank you.

**Comment by michael-simons** [comment]
Can you please share the classes in question?

**Comment by travishamilton1992** [comment]
Unfortunately I can't share the source code, but I will try to recreate the bug with a simpler example and share that code.

**Comment by michael-simons** [comment]
Thanks a lot Travis!

**Comment by michael-simons** [comment]
Important is the definition of the relationships as well what's behind your `addManyToMany`.

**Comment by travishamilton1992** [comment]
Hi Michael, sorry for the delay. After further investigation I found that it was a bug in my own code and not with SDN. Thanks for your help!
