### ISSUE TITLE
relationship not being persisted when saving node with @ID @GeneratedValue (spring-data-neo4j 6)

### ISSUE THREAD

**Issue by kritsel030** [spring-projects/spring-data-neo4j#2363]
### Issue summary

**Situation**
I have a kotlin data class 
* annotated with `@Node` 
* an `id `attribute defined as follows: `@ID @GeneratedValue val id: Long? = null`
* a `@Relationship` attribute

Plus a kotlin interface annotated with `@Repository`

**Issue**
When saving a node via `repository.save(myNode)`, the node itself is saved, but the relationship is not saved, and there are no errors whatsoever.

However, when I change `val id: Long?` into` var id: Long?` in my Node entity, and I save the node, the relationship does get saved as expected. How can this be?

### Code examples

**Node**
```
data class City(
    // changing 'val' into 'var' ensures that this node's relationship does get saved along with the node
    @Id @GeneratedValue
    val id: Long? = null,

    @Relationship(type = "LOCATED_IN")
    var locatedIn: LocatedIn? = null
}
```

**Relationship**
```
@RelationshipProperties
data class LocatedIn(
        @Id @GeneratedValue
        val relationshipId: Long? = null,

        @TargetNode
        val country: Country
)
```

**Repository**

```
@Repository
interface CityRepository : PagingAndSortingRepository<City, Long?> {

}
```

### Tech details

- language: kotlin
- spring-boot 2.4.10
- spring-data-neo4j: 6.0.12

**Comment by meistermeier** [comment]
With the code above, the following works fine for me:
```
val city = City()
city.locatedIn = LocatedIn(country = Country(name = "Here"))
val savedCity = repository.save(city)
assertThat(savedCity.locatedIn).isNotNull
```
did I understand something wrong?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
