### ISSUE TITLE
migrating from SDN 5 to SDN 6: some documentation suggestions

### ISSUE THREAD

**Issue by kritsel030** [spring-projects/spring-data-neo4j#2364]
We recently migrated a kotlin application from SDN 5 (with spring-boot 2.3) to SDN 6 (with spring-boot 2.4). There are a couple of topics which would have saved us valuable time, had they been clearly mentioned in the migration documentation on https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#migrating.migrating

Not really sure if this is the right place to post these, but don't really know a more appropriate place to report these.

**Conversions**
Our applications has quite some DTOs which serve as input parameters for customer query methods in repositories. This worked perfectly fine in SDN 5, without any additional configuration.

In SDN 6, this requires registering a conversion for each DTO as documented here https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom.conversions. However, the need for this is not explicitly stated in the migration paragraph. If it would have been, it would have saved us quite some time.

Additionally, the example code provided for a converter references a method named `convertToNeo4jValue`, without giving an implementation. And converting an arbitrary DTO instance into something that correctly implement the `Value` interface is not straightforward. Below is an example of how we do it in kotlin, making use of jacksonObjectMapper; maybe its a good idea to include such an example.

```
val dataclassAsMap = jacksonObjectMapper().convertValue(source as SomeType, object : TypeReference<Map<String, Any>>() {})
val value = Values.value(dataclassAsMap)
```

**@ID @GeneratedValue: val id or var id?**
In SDN 5 the entity definition below works fine when saving a `City `instance with a `LocatedIn `relationship via a `repository.save(<T>) `method.

In SDN 6 this does NOT work: the `City` instance gets saved, but without its `LocatedIn` relationship. `val id: Long?` had to be replaced with `var id: Long?` to get this to work. (this is also registered as issue #2363).

```
data class City(
    // changing 'val' into 'var' ensures that this node's relationship does get saved along with the node
    @Id @GeneratedValue
    val id: Long? = null,

    @Relationship(type = "LOCATED_IN")
    var locatedIn: LocatedIn? = null
}
```

**Relationships: @StartNode no longer necessary**

SDN 5 had the @StartNode annotation for relationships. SDN 6 does not have a replacement for this annotation, it is not needed.

**Comment by meistermeier** [comment]
Thanks for your helpful input on the migration documentation.
Let's discuss #2363 first and see if this needs to get added.

**Comment by meistermeier** [comment]
Since there wasn't any interaction on #2363 I will also close this issue.
