### ISSUE TITLE
Optimistic Locking

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#237]
We need to support @Version for Node and Relationship-backed entities

We'll use Long ids and persist them in the database.

Loading: Object with @Version attribute will have their version attribute set automatically by the mapper from the node or relationship property. There is no need to do anything "magic" here.

Saving: Objects with @Version attribute set will have an additional WHERE clause added to the Cypher query, which checks the version. Additionally, we will need to know whether the update was successful, so we need to return something (e.g. the version of the current object?).

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-551
