### ISSUE TITLE
Multiple interface implementation

### ISSUE THREAD

**Issue by marichka-spin** [spring-projects/spring-data-neo4j#2372]
Hello team,
I'm trying to migrate our system from OGM to new spring data neo4j. We are using both custom queries to increase performance and spring crud repos for simple queries. I have a question regarding Multiple interface implementation and and mappings. Please consider the scenario:

```java
@Node("Car")
public interface ICar {}

@Node("Small")
public class SmallCar implements ICar{}

public class OrdinaryCar implements ICar{}

@Node("BigCar")
public class BigCar implements ICar{}
```

In Neo4j DB those enties are represented as:

```
(sc:Small:Car:Vehicle {uuid: <some_uuid>, name: 'My small car'})
(oc:Car:Vehicle {uuid: <some_uuid>, name: 'My ordinary car'})
(bc:BigCar:Car:Vehicle {uuid: <some_uuid>, name: 'My big car'})
```

Searching node by UUID may return any of these nodes and retrieving all cars should return all of these nodes. I'm using for retrive our custom queries and Neo4jTemplate to map result to java classes:
```
neo4jTemplate.findAll(<MY_CYPHER_QUERY>, <MapWithParams>, ICar.class)
```

I'm not even sure that it is correct way to do this .

**Comment by mp911de** [comment]
Please refrain from using "guys". While it may seem a small thing, some people feel excluded by "guys" and we don't want them to. I updated the ticket description accordingly.

**Comment by marichka-spin** [comment]
Sorry and thank you!

**Comment by meistermeier** [comment]
I cannot read a question out of this but only guess:
You don't get the `OrdinaryCar`(?)
your initial data `(oc:Car:Vehicle {uuid: <some_uuid>, name: 'My ordinary car'})` does not represent any known entity. It should also have the `OrdinaryCar` label to get read. And you would need to add the `@Node` to the `OrdinaryCar` class.

You are not doing anything wrong by using the `Neo4jTemplate` but you can only query for concrete or abstract classes.
This is due to the fact that the identifier field needs to be of the same type and an interface cannot ensure this. Also the common (abstract) base class needs to define the field to query for: in your case `uuid`.

I created an example for you here and hope that it makes things clearer:
https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2372

As an alternative you could also use the repositories like
```
interface CarRepository extends Neo4jRepository<ACar, Long>
```

**Comment by meistermeier** [comment]
Good to hear. I will change to label again to `waiting-for-feedback` because this is what I basically do from now one :D

**Comment by marichka-spin** [comment]
Ok, I made some experiments and what actually I have in my DB now looks like that:
```
(c1: SmallCar:Car:Vehicle {uuid: <some_uuid>, propertyOfSmallCar: <some_value>, generalPropertyOfTheCar: <some_value>})
(c2: Car:Vehicle {uuid: <some_uuid>, generalPropertyOfTheCar: <some_value>})
(c3: BigCar:Car:Vehicle {uuid: <some_uuid>, propertyOfBigCar: <some_value>, generalPropertyOfTheCar: <some_value>})
```

What I tried to do after your example:
```
public class Domain {

    @Node("Vehicle")
    public static abstract class Vehicle {

       @Id
        private String uuid;

        private String generalPropertyOfTheCar;

       private List<String> labels;

     @Relationship(type = "keepsTo")
      private Route route;
    }

    @Node({"SmallCar","Car"})
    public static class SmallCar extends Vehicle {
       private String propertyOfSmallCar;
    }

    @Node("Car")
    public static class OrdinaryCar extends Vehicle {}

    @Node({"BigCar","Car"})
    public static class BigCar extends Vehicle {
      private String propertyOfBigCar;
    }
}
```

When I try to retrieve car nodes I'm building requests this way:
```
MATCH (car_0:Car:Vehicle) WHERE TRUE  AND (NOT exists(car_0.archived) OR car_0.archived = false)
....
SKIP 0 LIMIT 30
RETURN DISTINCT car_0{.*, labels: labels(car_0) ,Car_keepsTo_Route: [(car_0:Car:Vehicle)-[rel_6:keepsTo]->(route_5:Route) | route_5{.*}]}
``` 
I get "Don't know how to translate exception of type class org.springframework.data.mapping.MappingException" 
And the question is how should I improve organization of the classes or how should I improve my cypher to have all classes mapped properly?

**Comment by meistermeier** [comment]
The returned pattern does not match what SDN is expecting to really identify the correct node -> java type.
Also the part in the documentation (https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-creation.load) is more for transparency than manual how to _fake_ SDN's requested structure.
But what you want to get back should also work with an `optional match` and a `return car_0, collect(relationships), collect(relatedNodes)`.
I updated my example to get closer to your problem and it shows some approaches that you could use in your code base.
Some significant (and hopefully helpful) changes are:
```
String query =
        "MATCH (car_0:Car:Vehicle) WHERE TRUE AND (NOT exists(car_0.archived) OR car_0.archived = false) "
      + "OPTIONAL MATCH (car_0)-[r:keepsTo]->(route:Route) "
      + "RETURN car_0, collect(r), collect(route)";

List<Domain.Vehicle> vehicles = neo4jTemplate.findAll(query, Domain.Vehicle.class);
```
or with the repository
```
List<Domain.Vehicle> vehicles = carRepository.findByArchivedIsNullOrArchivedIsFalse();
assertThat(vehicles).hasAtLeastOneElementOfType(Domain.SmallCar.class);
assertThat(vehicles).hasAtLeastOneElementOfType(Domain.OrdinaryCar.class);
assertThat(vehicles).hasAtLeastOneElementOfType(Domain.BigCar.class);
```

**Comment by marichka-spin** [comment]
Actually we avoid using OPTIONAL as it is very decreasing performance. We have a lot of optional relations in our entities, so with ogm we used pattern comprehension in RETURN clause. 
Example:
```
String query =
        "MATCH (car_0:Car:Vehicle) WHERE TRUE AND (NOT exists(car_0.archived) OR car_0.archived = false) "
      + "RETURN car_0, [(car_0)-[r:keepsTo]->(route:Route) | [r, route]]";
```
With spring-data-neo4j v 6.x I discovered that map projection is used. So how correctly build the map projection scheme in order to make subclasses  map correctly?

**Comment by meistermeier** [comment]
This is the output of the generated repository method query:
```
MATCH (n:`Vehicle`) WHERE (n.archived IS NULL OR n.archived = false) RETURN n{.archived, .generalPropertyOfTheCar, .labels, .propertyOfBigCar, .propertyOfSmallCar, .uuid, __nodeLabels__: labels(n), __internalNeo4jId__: id(n), Vehicle_keepsTo_Route: [(n)-[:`keepsTo`]->(n_route:`Route`) | n_route{.id, __nodeLabels__: labels(n_route), __internalNeo4jId__: id(n_route)}]}
```
important are the "hints" like `___internalNeo4jId___` and `___nodeLabels___`

But if this is enough for you, you could use the query method instead of maintaining your own Cypher query.

**Comment by marichka-spin** [comment]
Finally, thank you a lot for the help!!! I really appreciate
