### ISSUE TITLE
Optimistic locking in the documentation

### ISSUE THREAD

**Issue by shayantabrizi** [spring-projects/spring-data-neo4j#2374]
I did not find a section for optimistic locking in the documentation for the new version. There was one for the previous version [here](https://docs.spring.io/spring-data/neo4j/docs/5.3.8.RELEASE/reference/html/#reference:annotating-entities:version). It may be good to explain it in more detail in the latest documentation.

**Comment by meistermeier** [comment]
You are right, this is truly missing.

**Comment by meistermeier** [comment]
Update documentation in 6.0 (7cb4da92d), 6.1 (1d23bebec) and main (50e3d6694).
