### ISSUE TITLE
`LiteralReplacement`-Cache is not threadsafe.

### ISSUE THREAD

**Issue by ajanoni** [spring-projects/spring-data-neo4j#2375]
It is a random error that occurs in different queries in our application:

Here is the stack trace:
2021-09-08 08:53:41 | at org.springframework.data.neo4j.repository.query.Neo4jSpelSupport.orderBy(Neo4jSpelSupport.java:71)
-- | --
  |   | 2021-09-08 08:53:41 | at org.springframework.data.neo4j.repository.query.Neo4jSpelSupport$StringBasedLiteralReplacement.withTargetAndValue(Neo4jSpelSupport.java:131)
  |   | 2021-09-08 08:53:41 | at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
  |   | 2021-09-08 08:53:41 | Caused by: java.util.ConcurrentModificationException: null

**Comment by meistermeier** [comment]
Could you please provide any further information?
- Query you used. I assume that this is a `@Query` annotated repository method.
- Spring Data Neo4j version
- If applicable custom versions of the Java driver and similar.

The best would be to get a small reproducer for the problem you are facing.

**Comment by ajanoni** [comment]
The error does occur in other queries that have the orderBy clause, but you can check one example bellow: 

Query:

`import org.springframework.data.domain.Pageable
import org.springframework.data.domain.Slice
import org.springframework.data.neo4j.repository.Neo4jRepository
import org.springframework.data.neo4j.repository.query.Query

interface AcmeGroupsRepository : Neo4jRepository<AcmeGroupEntity, String> {
    companion object {
        const val BASE_QUERY =
            """
        MATCH (acmeGroup:AcmeGroup)
        WHERE 
          ($${"ids"} IS NULL OR acmeGroup.id IN $${"ids"}) AND  
          ($${"labels"} IS NULL OR acmeGroup.label IN $${"labels"})
        """
    }

    @Query(
        """
        $BASE_QUERY
        RETURN acmeGroup :#{orderBy(#pageable)} SKIP $${"skip"} LIMIT $${"limit"}
    """
    )
    fun findAllByFilters(ids: List<String>?, labels: List<String>?, page: Pageable): Slice<AcmeGroupEntity>
`

Version: org.springframework.data:spring-data-neo4j:6.1.4

**Comment by michael-simons** [comment]
Thanks for reporting this @ajanoni  The fix will appear in all branches. Snapshots will be ready soon. If you have the chance to try them, I would appreciate feedback on the fix. Thank you.
