### ISSUE TITLE
Support direct retrieval of RelationshipEntity

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#238]
Given the classic film critic example:

    User critic...
    Movie film...
    Rating rating = critic.rate(film, ...);

...where `Rating` is an `@RelationshipEntity`, the following code should retrieve the `Rating` that matches the specified relationship ID.

    Rating loadedRating = ogmSession.load(Rating.class, ratingId);

However, the `Session.load(...)` code currently assumes that it's always going to be looking for a node entity and therefore isn't matching the ID correctly.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-552
