### ISSUE TITLE
Neo4jClient throws No Converter Found 

### ISSUE THREAD

**Issue by mrksph** [spring-projects/spring-data-neo4j#2385]
·SDN v6.0.3

I'm trying to query my database through the Neo4jClient.query() method but I'm getting ConverterNotFoundException because apparently some nodes don't have every property I declared in my NodeEntity class.

Is there any way I can avoid getting this exception without having to implement a custom mapper function?

The query:

```
MATCH (n:Currency) 
WHERE  toUpper(n.nameEs) CONTAINS toUpper('PESETA') 
WITH collect(DISTINCT n) as c1 
UNWIND c1 as nodes 
RETURN nodes
```

The exception:

`org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.neo4j.driver.internal.value.NodeValue] to type [com.gs.scib.jquest.model.currency.CurrencyNode]`

Thanks

**Comment by michael-simons** [comment]
Hi. Can you share how you call the client?

**Comment by mrksph** [comment]
Hi Michael,

I'm calling the client this way:

client.query(query).fetchAs(CurrencyNode.class).all();

**Comment by michael-simons** [comment]
Thanks.

Please have a look at: https://docs.spring.io/spring-data/neo4j/docs/6.1.5/reference/html/#building-blocks, 3.1:

> The client is mapping agnostic. It doesn’t know about your domain classes and you are responsible for mapping a result to an object suiting your needs.

This means if that using the client like this you _must_ provide a custom mapping function like we do for example here:

https://github.com/spring-projects/spring-data-neo4j/blob/2b784bd2b917362e2d98bb2dee7bc2ec14a09eb0/src/test/java/org/springframework/data/neo4j/core/Neo4jClientTest.java#L288-L294

If you want us to map the thing, use the template:

```
neo4jTemplate.findAll(query, CurrencyNode.class);
```


or the fluent form:

```
neo4jTemplate.find(CurrencyNode.class).matching(query).all();
```

**Comment by leiyan** [comment]
Great answer for me, thanks.

**Comment by michael-simons** [comment]
You're very welcome, @leiyan

**Comment by leiyan** [comment]
FYI
https://spring.io/projects/spring-data-neo4j
“Spring Data Neo4j, part of the larger Spring Data family, provides easy configuration and access to Neo4j Graph Databases from Spring applications. It offers three different levels of abstraction to access the store. The Neo4j client, the Neo4j Template, and the Neo4j Repositories. Spring Data Neo4j offers advanced features to map annotated entity classes to the Neo4j Graph Database. The template programming model is equivalent to other Spring templates and builds the basis for interaction with the graph and is also used for the Spring Data repository support. Spring Data Neo4j is a core part of the Spring Data project which aims to provide convenient data access for NoSQL databases.”
“Neo4j Client for low-level abstraction.”
“Neo4j Template and Repositories for high-level abstraction.”
