### ISSUE TITLE
Auto-generated query for findAllById is unoptimized and can lead to memory issues & long execution times

### ISSUE THREAD

**Issue by AlexiosP** [spring-projects/spring-data-neo4j#2387]
When calling the `findAllById` method of a repository, the last cypher query which retrieves all the nodes and their related entities is the below
```
MATCH (rootNodeIds) 
WHERE id(rootNodeIds) IN $rootNodeIds 
OPTIONAL MATCH ()-[relationshipIds]-() 
WHERE id(relationshipIds) IN $relationshipIds 
OPTIONAL MATCH (relatedNodeIds) 
WHERE id(relatedNodeIds) IN $relatedNodeIds 
WITH rootNodeIds AS n, collect(DISTINCT relationshipIds) AS __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ 
RETURN n AS __sn__, __sr__, __srn__
```
This obviously can use a lot extra memory and results to a long execution time due to the fact that it first matches the root nodes, afterwards for **each of related nodes** it matches relationships, etc.

![image](https://user-images.githubusercontent.com/20590643/134918820-a784271f-1352-43d7-924f-8952f6cfbcdc.png)

Compared to something like the below
```
MATCH (rootNodeIds) 
WHERE id(rootNodeIds) IN $rootNodeIds 
WITH collect(rootNodeIds) AS n
OPTIONAL MATCH ()-[relationshipIds]-() 
WHERE id(relationshipIds) IN $relationshipIds 
WITH n, collect(DISTINCT relationshipIds) AS __sr__
OPTIONAL MATCH (relatedNodeIds) 
WHERE id(relatedNodeIds) IN $relatedNodeIds 
WITH n, __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ 
UNWIND n AS rootNodeIds
WITH rootNodeIds AS n, __sr__, __srn__
RETURN n AS __sn__, __sr__, __srn__
```
or due to the [behavior of DISTINCT in neo4j](https://github.com/neo4j/neo4j/issues/12774), it could be written as below
```
MATCH (rootNodeIds) 
WHERE id(rootNodeIds) IN $rootNodeIds 
WITH collect(rootNodeIds) AS n
OPTIONAL MATCH ()-[relationshipIds]-() 
WHERE id(relationshipIds) IN $relationshipIds 
WITH n, collect(relationshipIds) AS __sr__
UNWIND __sr__ AS rel
WITH n, collect(DISTINCT rel) AS __sr__
OPTIONAL MATCH (relatedNodeIds) 
WHERE id(relatedNodeIds) IN $relatedNodeIds 
WITH n, __sr__, collect(relatedNodeIds) AS __srn__ 
UNWIND __srn__ AS relatedNodeIds
WITH n,  __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ 
UNWIND n AS rootNodeIds
WITH rootNodeIds AS n, __sr__, __srn__
RETURN n AS __sn__, __sr__, __srn__
```
there's a significant improvement as can be seen below

![plan (1)](https://user-images.githubusercontent.com/20590643/134920419-3b9bddce-fecd-4cfc-98d1-11bc54fa6907.png)

SDN version that has been tested with: 6.1.4, 6.1.5, 6.2.0-M3
neo4j version: 4.2.3 enterprise

**Comment by michael-simons** [comment]
Thanks a ton for the input, we are gonna discuss this in the upcoming week. 👍

**Comment by asevich** [comment]
@michael-simons is there some quick and dirty solution we can apply now? We invested a lot of time to update to SDN 6.x and this problem really degrades our production performance. We can of course try to revert update, but we would like to avoid it. 
I would appreciate any hints

**Comment by michael-simons** [comment]
You can always run it as custom query via `@Query`.
