### ISSUE TITLE
SpringBoot starter 

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#239]
We should create a spring-boot-starter jar for Neo4j to ensure that there is a build compatible with the latest spring versions "blessed" by spring boot, and also because sdn4 config for boot apps is then a simple 1-line dependency in the pom :)

**Comment by gregturn** [comment]
Spring Boot includes a preselected Spring Data release train version which includes Spring Dara Neo4j. 

The purpose of a starter is to pull in multiple coordinated dependencies commonly associates with neo4j. Ideally this should be an issue filed with Spring Boot listing the artifacts that should be included when using neo4j.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-553
