### ISSUE TITLE
Handle `null` DTO projection conversion for primitive types

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-neo4j#2395]
As raised here https://community.neo4j.com/t/sdn6-using-projection-persistence-with-primitive-fields/45177 SDN will fail with a NPE if the target field would be defined as a primitive.

**Comment by seabamirum** [comment]
This issue still occurs in 6.2.2. The NPE is now on line 77:

PreferredConstructor<?, ? extends PersistentProperty<?>> constructor = targetEntity
				.getPersistenceConstructor();

**Comment by meistermeier** [comment]
This might be something different. But I wonder how the `targetEntity` should become _null_ if you are requesting a known type. Can you provide a reproducer?
