### ISSUE TITLE
Support DynamicProperties

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#241]
Currently SDN 3 has support for persisting DynamicProperties (i.e. using a property map). 

http://docs.spring.io/autorepo/docs/spring-data-neo4j/2.3.0.M1/api/org/springframework/data/neo4j/fieldaccess/DynamicProperties.html

At least one client wants this to be supported.

**Comment by vince-bickers** [comment]
It seems that the idea is to extend the schema-flexible nature of Neo4j all the way into the entity model, so that whatever is in the graph is available on the entity objects (regardless of what it is or how it got there), and vice versa: any attributes set (changed / removed) on the entity objects would always get persisted in the graph. The primary purpose of this feature is to avoid having to make code changes to entity objects as the underlying graph changes.

Some thoughts:

1. Support for relationships with properties (@RelationshipEntity) might be tricky: One day a relationship might have no properties, the next day it might have a timestamp attribute. Does this imply dynamically creating these domain entities depending on their "shape" ?

2. Maybe the requirement would be better served by exposing the underlying Node and Relationship objects via a simple API and let the client decide how to construct its entity model. We already have these objects in the OGM layer, so we should be able to wrap them via API calls: 

````
List<Node> getGraph() 
setGraph(Node node)
````
Some examples from a real requirement would be useful to help start our thinking about this.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-555
