### ISSUE TITLE
Relationship not persisting when relationship property present in both nodes

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [spring-projects/spring-data-neo4j#2416]
I have two nodes:

```java
@Node
public class Group {

  @Id
  private final Long id;
  
  @Version
  private Long version;

  @Relationship(type = "MEMBER", direction = Relationship.Direction.INCOMING)
  private Set<User> members = new HashSet<>();

  public Group(long id) {
    this.id = id;
  }

  public Set<User> getMembers() {
    return this.members;
  }

  public void addMember(User member) {
    this.members.add(member);
  }
}
```
```java
@Node
public class User {

  @Id
  private final Long id;

  @Version
  private Long version;

  @Relationship(type = "MEMBER", direction = Relationship.Direction.OUTGOING)
  private Group group;

  public User(long id) {
    this.id = id;
  }

  public Group getGroup() {
    return this.group;
  }

  public Group setGroup(Group group) {
    this.group = group;
  }
}
```
If you add a `User` to a `Group` and save the `Group`, the relationship **IS NOT** persisted.
If you set the `Group` from the `User`, the relationship **IS** persisted.
It doesn't matter which way round the relationship direction is.

I'm using the latest snapshot (6.2.0).

```java
// Create user
var user = userRepo.save(new User(0L));
// Create group
var group = groupRepo.save(new Group(0L));

// Add user to group
group.addMember(user);

// Does not persist the relationship
groupRepo.save(group);

// However, setting the group from the user does persist the relationship.
user.setGroup(group);
userRepo.save(user);
```

**Comment by Sm0keySa1m0n** [comment]
Update: I have done some further testing and have found that the problem only occurs if a version property is present on the `User` node.

**Comment by meistermeier** [comment]
You have to define the relationship on both sides. Otherwise you would put your model into an inconsistent state.
Either the relationship is set (`Group` to `User`) or not existent (`User` to `Group`).
What happens here is that SDN finds the defined relationship first, creates it but than parses the `User` without any relationship definition and issues a delete.

**Comment by Sm0keySa1m0n** [comment]
Wouldn't it be better if there was some sort of attribute on the `@Relationship` annotation which defined if it was responsible for "setting" the relationship? That way you wouldn't need unnecessary duplicate relationships.

**Comment by Sm0keySa1m0n** [comment]
Unless when you said define the relationship on both sides you mean set the value on both nodes?

**Comment by meistermeier** [comment]
> Wouldn't it be better if there was some sort of attribute on the @Relationship annotation which defined if it was responsible for "setting" the relationship? That way you wouldn't need unnecessary duplicate relationships.

No, because if you define both sides in your domain model, why shouldn't both be of the same priority? Otherwise you could also just not define the relationship at all on the other side.

**Comment by Sm0keySa1m0n** [comment]
I have fixed the issue by using `@ReadOnlyProperty` on the user relationship property.
