### ISSUE TITLE
Relationships not populated by findById

### ISSUE THREAD

**Issue by cberes** [spring-projects/spring-data-neo4j#2418]
I've encountered a couple scenarios where relationships are not populated by a repository's findById method. The effect seems to be random--sometimes one relationship is not populated, sometimes another, or sometimes all relationships. Here is an example project: https://github.com/cberes/neo4j-relationship-bug

Say I have a super class with 2 relationships, one of which is generic:

```java
@Node
@Getter
@Setter
public abstract class Animal<T extends BaseEntity<T>> extends BaseEntity<Animal<T>> {
    private String name;

    @Relationship("PLAYS_WITH")
    private T toy;

    @Relationship("CARED_FOR_BY")
    private Person person;
}
```

And the sub class looks like this:

```java
@Node
public class Dog extends Animal<Bone> {
}
```

I've found that the relationships sometimes are not populated by findById.

This also happens when I move the generic relationship to the sub class. Here is the super class:

```java
@Node
@Getter
@Setter
public abstract class AnimalAlt<T extends BaseEntity<T>> extends BaseEntity<AnimalAlt<T>> {
    private String name;

    @Relationship("CARED_FOR_BY")
    private Person person;

    public abstract T getToy();
}
```

And the sub class:

```java
@Node
@Getter
@Setter
public class DogAlt extends AnimalAlt<Bone> {

    @Relationship("PLAYS_WITH")
    private Bone toy;
}
```

Similarly, relationships are sometimes not populated by findById.

Again, here is an example project: https://github.com/cberes/neo4j-relationship-bug

**Comment by meistermeier** [comment]
Thank you for reporting this. For the non-alternative version, the solution is to add `@Node` to the `BaseEntity`.
This is needed because given the `AnimalRepository` that refers to an `Animal` wants to find a 
```
@Relationship("PLAYS_WITH")
private T toy;
```
where `T` is another `BaseEntity`. So there is a part in the query (simplified) `...-[:PLAYS_WITH]->(toy:BaseEntity)...`
But without the `@Node` on the `BaseEntity`, the `toy` was never enriched with this label and SDN cannot find it.
I am currently looking on the alternative approach and trying to find out what it is missing. The complexity of inheritance and generics does make it too easy ;)

**Comment by cberes** [comment]
Thank you for looking into it.

Your comment got me thinking. I tried removing `getToy()` from AnimalAlt (and removing the generics from its definition so it looked like this: `public abstract class AnimalAlt extends BaseEntity<AnimalAlt>`) and still the relationships are not populated.

**Comment by meistermeier** [comment]
The "Alt-Version" is a different story that I am currently working on. The root problem is that SDN creates a query like `AnimalAlt_CARED_FOR_BY_Person` but the mapping part knows that this is e.g. a `CatAlt` and is looking for `CatAlt_CARED_FOR...`. I tried to generalize this also but this is not stable yet.
The non "Alt-Version" should work with the `@Node` annotation.

**Comment by cberes** [comment]
Ah I see, that makes sense. Thank you for the insight into this. Unfortunately I'm not sure that adding @Node to BaseEntity is an option for us, as it would add a new label to every node.
