### ISSUE TITLE
Projections: Too much data is loaded

### ISSUE THREAD

**Issue by Andy2003** [spring-projects/spring-data-neo4j#2421]
Given:

```java
public interface BaseNodeFieldsProjection {
	String getNodeId();
}
```

```java
public interface BaseNodeWithNodeType {
	NodeType getNodeType();
}
```

```java
public interface BaseNodeWithParent {
	BaseNodeFieldsProjection getParent();
}
```

```java
public interface ApiBaseNodeProjection extends
		BaseNodeFieldsProjection,
		BaseNodeWithParent,
		BaseNodeWithNodeType {
}
```

```java
public interface ApiMeasurementMetaProjection extends ApiBaseNodeProjection, BaseNodeFieldsProjection {
}
```

```java
@Node
@Value
@AllArgsConstructor
@EqualsAndHashCode
@Immutable
public class NodeType {
	@Id
	String nodeTypeId;
}
```

```java
@Node
@NonFinal
@Data
@Setter(AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@SuperBuilder(toBuilder = true)
public class BaseNodeEntity implements
		BaseNodeFieldsProjection,
		BaseNodeWithParent,
		BaseNodeWithNodeType,

		ApiBaseNodeProjection {

	@Id
	@GeneratedValue(UUIDStringGenerator.class)
	@EqualsAndHashCode.Include
	private String nodeId;

	@Relationship(type = "CHILD_OF", direction = OUTGOING)
	private NodeEntity parent;

	@Relationship(type = "HAS_TYPE", direction = OUTGOING)
	private NodeType nodeType;
}
```

```java
@org.springframework.data.neo4j.core.schema.Node
@Data
@Setter(AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
@SuperBuilder(toBuilder = true)
public class NodeEntity extends BaseNodeEntity {
}
```

```java
@Node
@Data
@Setter(AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
@SuperBuilder(toBuilder = true)
public class MeasurementMeta extends BaseNodeEntity implements BaseNodeFieldsProjection {
}
```

```cypher
CREATE (parent:NodeEntity:BaseNodeEntity{nodeId: 'parent'}) 
CREATE (m1:MeasurementMeta:BaseNodeEntity{nodeId: 'm1'}) 
CREATE (nt1:NodeType{nodeTypeId: 'nt1'}) 
CREATE (nt2:NodeType{nodeTypeId: 'nt2'}) 
CREATE (parent)-[:HAS_TYPE]->(nt1)
CREATE (m1)-[:HAS_TYPE]->(nt2)
CREATE (m1)-[:CHILD_OF]->(parent)
```

```java
interface MeasurementMetaRepository extends Repository<MeasurementMeta, String> {
	<R> Optional<R> findByNodeId(String nodeId, Class<R> clazz);
}
```

the following test will fail:

```java
@Test
void test1(@Autowired MeasurementMetaRepository repository) {
	Optional<ApiMeasurementMetaProjection> m1 = repository.findByNodeId("m1", ApiMeasurementMetaProjection.class);
	assertThat(m1)
			.isPresent()
			.get()
			.extracting(projection -> (MeasurementMeta) ((TargetAware)projection).getTarget())
			.extracting(BaseNodeEntity::getParent)
			.extracting(BaseNodeEntity::getNodeType)
			.isNull();
}
```

The generated cypher is:

```cypher
MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`) WHERE measurementMeta.nodeId = $nodeId RETURN measurementMeta{.nodeId, __nodeLabels__: labels(measurementMeta), __internalNeo4jId__: id(measurementMeta), MeasurementMeta_CHILD_OF_NodeEntity: [(measurementMeta)-[:`CHILD_OF`]->(measurementMeta_parent:`NodeEntity`:`BaseNodeEntity`) | measurementMeta_parent{.nodeId, __nodeLabels__: labels(measurementMeta_parent), __internalNeo4jId__: id(measurementMeta_parent), NodeEntity_HAS_TYPE_NodeType: [(measurementMeta_parent)-[:`HAS_TYPE`]->(measurementMeta_parent_nodeType:`NodeType`) | measurementMeta_parent_nodeType{.nodeTypeId, __nodeLabels__: labels(measurementMeta_parent_nodeType), __internalNeo4jId__: id(measurementMeta_parent_nodeType)}]}], MeasurementMeta_HAS_TYPE_NodeType: [(measurementMeta)-[:`HAS_TYPE`]->(measurementMeta_nodeType:`NodeType`) | measurementMeta_nodeType{.nodeTypeId, __nodeLabels__: labels(measurementMeta_nodeType), __internalNeo4jId__: id(measurementMeta_nodeType)}]}
```

This is a condensed example, in my real world example I have much more relations and so plenty of unprojected data is loaded into memory

**Comment by Andy2003** [comment]
Test case provided: https://github.com/Andy2003/spring-data-neo4j/tree/test-case/gh2421

**Comment by Andy2003** [comment]
It's getting even worse if you query with a projection, which is implemented by the domain class (what I would prefer in terms of refactoring):

```java
@Test
void test2(@Autowired MeasurementMetaRepository repository) {
	Optional<BaseNodeWithNodeType> m1 = repository.findByNodeId("m1", BaseNodeWithNodeType.class);
	assertThat(m1)
			.isPresent()
			.get()
			.extracting(projection -> (MeasurementMeta) projection)
			.extracting(BaseNodeEntity::getParent)
			.isNull();
}
```

Logs

```
[main] 2021-11-03 13:18:57,262 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`) WHERE measurementMeta.nodeId = $nodeId WITH collect(id(measurementMeta)) AS __sn__ RETURN __sn__
[main] 2021-11-03 13:18:57,263 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {nodeId: "m1"}
[main] 2021-11-03 13:18:57,373 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`) WHERE measurementMeta.nodeId = $nodeId OPTIONAL MATCH (measurementMeta)-[__sr__:`CHILD_OF`]->(__srn__:`NodeEntity`:`BaseNodeEntity`) WITH collect(id(measurementMeta)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__
[main] 2021-11-03 13:18:57,374 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {nodeId: "m1"}
[main] 2021-11-03 13:18:57,499 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (nodeEntity:`NodeEntity`:`BaseNodeEntity`) WHERE id(nodeEntity) IN $__ids__ OPTIONAL MATCH (nodeEntity)-[__sr__:`HAS_TYPE`]->(__srn__:`NodeType`) WITH collect(id(nodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__
[main] 2021-11-03 13:18:57,499 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {__ids__: [22]}
[main] 2021-11-03 13:18:57,558 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (nodeEntity:`NodeEntity`:`BaseNodeEntity`) WHERE id(nodeEntity) IN $__ids__ OPTIONAL MATCH (nodeEntity)-[__sr__:`CHILD_OF`]->(__srn__:`NodeEntity`:`BaseNodeEntity`) WITH collect(id(nodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__
[main] 2021-11-03 13:18:57,558 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {__ids__: [22]}
[main] 2021-11-03 13:18:57,607 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`) WHERE measurementMeta.nodeId = $nodeId OPTIONAL MATCH (measurementMeta)-[__sr__:`HAS_TYPE`]->(__srn__:`NodeType`) WITH collect(id(measurementMeta)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__
[main] 2021-11-03 13:18:57,608 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {nodeId: "m1"}
[main] 2021-11-03 13:18:57,653 DEBUG    org.springframework.data.neo4j.cypher: 313 - Executing:
MATCH (rootNodeIds) WHERE id(rootNodeIds) IN $rootNodeIds WITH collect(rootNodeIds) AS n OPTIONAL MATCH ()-[relationshipIds]-() WHERE id(relationshipIds) IN $relationshipIds WITH n, collect(DISTINCT relationshipIds) AS __sr__ OPTIONAL MATCH (relatedNodeIds) WHERE id(relatedNodeIds) IN $relatedNodeIds WITH n, __sr__ AS __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ UNWIND n AS rootNodeIds WITH rootNodeIds AS measurementMeta, __sr__, __srn__ RETURN measurementMeta AS __sn__, __sr__, __srn__
[main] 2021-11-03 13:18:57,653 TRACE    org.springframework.data.neo4j.cypher: 334 - with parameters:
:params {rootNodeIds: [23], relatedNodeIds: [22, 24, 25], relationshipIds: [0, 1, 2]}
```

As you can see all relations are queried, even if they are not projected at all.

**Comment by meistermeier** [comment]
It took some time to track this down, sorry.
But in the end it is correct behavior. SDN does exactly load what is defined.

Explanation for the initial example:
As you have correctly noticed, the generated query contains: 
```
MATCH (measurementMeta:MeasurementMeta:BaseNodeEntity) [...] RETURN 
measurementMeta {
...
MeasurementMeta_CHILD_OF_NodeEntity:...,
MeasurementMeta_HAS_TYPE_NodeType:...
}
```
The reason is that `ApiBaseNodeProjection` from `ApiMeasurementMetaProjection extends ApiBaseNodeProjection` defines:
- `NodeType getNodeType()` via `BaseNodeWithNodeType` and
- `BaseNodeFieldsProjection getParent()` via `BaseNodeWithParent`

You can see that only the fields `nodeTypeId` and `nodeId` are requested according to the projection definitions.
This means in the end SDN correctly recognizes both relationships from the original entity because they need to get resolved for getting the fields.

Explanation for the second example:
In this case Spring Data cannot determine the interface a projection-only interface but only as a part of the entity hierarchy.
As you can see in the query it tries to find a `BaseNodeEntity` (given by the initial match `(MeasurementMeta:BaseNodeEntity)`)
This is because the `BaseNodeEntity` is the first concrete implementation of the `MeasurementMeta`, since we are still using the `MeasurementMetaRepository` to retrieve the data and with the field
```
@Relationship(type = "CHILD_OF", direction = OUTGOING)
private NodeEntity parent;
```
we are jumping into a cyclic node type dependency that leads to the explorative queries.

**Comment by Andy2003** [comment]
@meistermeier The Query for test 1 looks like

```cypher
MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`)
  WHERE measurementMeta.nodeId = $nodeId
RETURN measurementMeta{
       .nodeId,
       __nodeLabels__:labels(measurementMeta),
       __internalNeo4jId__:id(measurementMeta),
       MeasurementMeta_CHILD_OF_NodeEntity:[(measurementMeta)-[:`CHILD_OF`]->(measurementMeta_parent:`NodeEntity`:`BaseNodeEntity`) | measurementMeta_parent{
              .nodeId,
              __nodeLabels__:labels(measurementMeta_parent), __internalNeo4jId__:id(measurementMeta_parent),
              NodeEntity_HAS_TYPE_NodeType:[(measurementMeta_parent)-[:`HAS_TYPE`]->(measurementMeta_parent_nodeType:`NodeType`) | measurementMeta_parent_nodeType{
                .nodeTypeId,
                __nodeLabels__:labels(measurementMeta_parent_nodeType),
                __internalNeo4jId__:id(measurementMeta_parent_nodeType)
          }]
       }],
       MeasurementMeta_HAS_TYPE_NodeType:[(measurementMeta)-[:`HAS_TYPE`]->(measurementMeta_nodeType:`NodeType`) | measurementMeta_nodeType{
          .nodeTypeId,
         __nodeLabels__:labels(measurementMeta_nodeType),
         __internalNeo4jId__:id(measurementMeta_nodeType)
       }]
}
```

There is no projection defined to query for `measurementMeta` -> `MeasurementMeta_CHILD_OF_NodeEntity` -> `NodeEntity_HAS_TYPE_NodeType`.

If you go the path from the interfaces:

1. `BaseNodeWithParent::getParent()` via `ApiMeasurementMetaProjection`  maps to `measurementMeta.MeasurementMeta_CHILD_OF_NodeEntity`
2. `BaseNodeWithParent::getParent()`  returns a `BaseNodeFieldsProjection`, which should only project `nodeId` but the cypher projects a field for `nodeType`, so this nodeType (2. level) is not requested

**Comment by Andy2003** [comment]
Background: I'm trying to get only the nodeId of the parent via projection, without resolving any other relations.

**Comment by Andy2003** [comment]
Regarding the 2nd test:

> In this case Spring Data cannot determine the interface a projection-only interface but only as a part of the entity hierarchy.

So is this a spring data issue?
I passed only an interface, which should be used to project the fields. Why is the library (or spring data) using fields from the domain class? The instructions given says: "use only the paths from the interface".

**Comment by meistermeier** [comment]
I think respecting my second comment will solve this. The problem is that `BaseNodeFieldsProjection getParent()` in `BaseNodeWithParent` will get interpreted as a `NodeEntity` because the `MeasurementMeta_CHILD_OF_NodeEntity` points towards a `BaseNodeEntity` (you can see this as part of the query).

**Comment by meistermeier** [comment]
> So is this a spring data issue?
No it isn't. Spring Data does not even support this kind of multi-level projection that you want to define.
It is just not supported and won't ever work because it is an ambiguous constellation of information: 
`BaseNodeFieldsProjection` _could_ be a projection by itself but it can also be a generalization of the entity `BaseNodeEntity`.

**Comment by Andy2003** [comment]
Is that really the way it's supposed to be? I have explicitly projected everything via interfaces. It is not exactly what I would expect, that the library, on the 2nd level, suddenly no longer respects the interfaces.

> It is just not supported and won't ever work because it is an ambiguous constellation of information:
`BaseNodeFieldsProjection` could be a projection by itself but it can also be a generalization of the entity `BaseNodeEntity`.

Would a `@Projection` annotation solve this ambiguity?

**Comment by Andy2003** [comment]
I am a big fan of compile-time checks. Therefore I would like to have my projections being implemented by the domain classes. So  we need a way to mark these projections in a way so the library knows what to do.

**Comment by michael-simons** [comment]
> Why is the library (or spring data) using fields from the domain class? The instructions given says: "use only the paths from the interface".

Because someone might have slapped more annotations at those fields, for example gave them different names than the derived ones.

**Comment by Andy2003** [comment]
> Because someone might have slapped more annotations at those fields, for example gave them different names than the derived ones.

This is perfectly fine, you need to match the projection with the domain model, but you should not load more than requested.

**Comment by Andy2003** [comment]
I can confirm that the generated cypher query meets my expectations if I do not let the domain classes implement the projection interfaces. But as said... compile time checks

**Comment by meistermeier** [comment]
This is something we cannot solve for you. This is not how projection in Spring Data in general work. They are loosely coupled and I am not keen to change this because this will lead render it ambiguous.

**Comment by Andy2003** [comment]
OK, I can understand that. However, some refactorability is lost due to the loose coupling. Is this a topic that should be discussed at Spring data, so that such use-cases are also covered in the future.

**Comment by meistermeier** [comment]
> Is this a topic that should be discussed at Spring data, so that such use-cases are also covered in the future?

No. As I have explained above, this is something orthogonal to the original projection concept.

**Comment by Andy2003** [comment]
@meistermeier Can you please reopen this ticket?

> I can confirm that the generated cypher query meets my expectations if I do not let the domain classes implement the projection interfaces

After playing around a bit with the projections, I'm sorry to say that my statement above is not valid. Even if the domain classes do not implement the projections, too much data is queried:

>  The Query for test 1 looks like
> 
> ```
> MATCH (measurementMeta:`MeasurementMeta`:`BaseNodeEntity`)
>   WHERE measurementMeta.nodeId = $nodeId
> RETURN measurementMeta{
>        .nodeId,
>        __nodeLabels__:labels(measurementMeta),
>        __internalNeo4jId__:id(measurementMeta),
>        MeasurementMeta_CHILD_OF_NodeEntity:[(measurementMeta)-[:`CHILD_OF`]->(measurementMeta_parent:`NodeEntity`:`BaseNodeEntity`) | measurementMeta_parent{
>               .nodeId,
>               __nodeLabels__:labels(measurementMeta_parent), __internalNeo4jId__:id(measurementMeta_parent),
>               NodeEntity_HAS_TYPE_NodeType:[(measurementMeta_parent)-[:`HAS_TYPE`]->(measurementMeta_parent_nodeType:`NodeType`) | measurementMeta_parent_nodeType{
>                 .nodeTypeId,
>                 __nodeLabels__:labels(measurementMeta_parent_nodeType),
>                 __internalNeo4jId__:id(measurementMeta_parent_nodeType)
>           }]
>        }],
>        MeasurementMeta_HAS_TYPE_NodeType:[(measurementMeta)-[:`HAS_TYPE`]->(measurementMeta_nodeType:`NodeType`) | measurementMeta_nodeType{
>           .nodeTypeId,
>          __nodeLabels__:labels(measurementMeta_nodeType),
>          __internalNeo4jId__:id(measurementMeta_nodeType)
>        }]
> }
> ```
> 
> There is no projection defined to query for `measurementMeta` -> `MeasurementMeta_CHILD_OF_NodeEntity` -> `NodeEntity_HAS_TYPE_NodeType`.
> 
> If you go the path from the interfaces:
> 
> 1. `BaseNodeWithParent::getParent()` via `ApiMeasurementMetaProjection`  maps to `measurementMeta.MeasurementMeta_CHILD_OF_NodeEntity`
> 2. `BaseNodeWithParent::getParent()`  returns a `BaseNodeFieldsProjection`, which should only project `nodeId` but the cypher projects a field for `nodeType`, so this nodeType (2. level) is not requested

This statement above (https://github.com/spring-projects/spring-data-neo4j/issues/2421#issuecomment-961987532) is also valid if the domain classes do not implement the projection interfaces.

**Comment by Andy2003** [comment]
I adjusted the test case to reflect the behavior I mentioned above.

**Comment by meistermeier** [comment]
Thanks for checking this again. I can see that there is something unexpected happening in the property/relationship filter with the updated test.

**Comment by meistermeier** [comment]
Spotted the problem. At least your test should runs green now. 
There will be a `6.2.0-GH-2421-SNAPSHOT` available within the next hour. Would be good to get your feedback.

**Comment by Andy2003** [comment]
@meistermeier 

Unfortunately, I can't yet make a final judgement on whether the problem is solved for more complex projections. I cannot currently run the application as I am migrating it from OGM. I am only picking out isolated issues that I am discovering during the migration.

BTW: https://github.com/spring-projects/spring-data-neo4j/commit/03aa5f63eb5fe8bc1b5e0c8099301101e0a8517e#r59936013
