### ISSUE TITLE
Review Strategy for Hydrating Object Relationships by Matching Types

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#243]
At the moment, this is how we try to map a relationship onto a pair of nodes:

1. Try to find a setter method annotated with the relationship type
2. Try to find a field annotated with the relationship type
3. Try to find a setter method whose name matches the relationship type
4. Try to find a field whose name matches the relationship type
5. Try to find a setter method that will accept an instance of the type corresponding to the end node
6. Try to find a field that matches the type that corresponds to the end node

For 5, and 6, it's possible to record a relationship that's different from the one read from the database.  Then, because of the way we resolve the relationship type to write, we'd end up writing back a new relationship with this different type.  For example:

`(user)-[RATED]->(film)`

... could map to `User.setFavouriteFilm(Film film)` (by point 5) but when we go to write it back we'd resolve a relationship type as "FAVOURITE_FILM" instead of "RATED" that was read originally.

Also, when hydrating, if there is a "FAVOURITE_FILM" relationship type that gets set first (by point 3) and also a "RATED" film then it's possible that RATED could overwrite the favourite film if the result set is in a certain order - a bit like the "last commit wins" problem.

Therefore, we should consider dropping support for 5 and 6 when hydrating an object model. However we probably want to get some feedback from users before deciding whether to drop 5/6 because if we did this, we couldn't have multiple rels of the same type with different end node types (user owns pet, user owns car).

At the very least this concern needs to be fully documented.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-557
