### ISSUE TITLE
Retrieving Relationship Properties

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [spring-projects/spring-data-neo4j#2453]
What is the intended way of retrieving a relationship's properties? For instance, lets say I have a `User` node who is related to a `Group` node and I store properties such as their permissions, nickname etc. in a `@RelationshipProperties` class. However, I have no way of retrieving or modifying these properties for a specific `User` without (as far as I know) retrieving the entire `Group` node and performing a linear search to find the desired user's properties which is highly inefficient if I had a `Group` with thousands of members.

If I understand correctly, this used to be possible in version 5 with `@RelationshipEntity` but that is no longer the case with `@RelationshipProperties`. Is there any replacement functionality?

(I know I could do a custom query with `Neo4jClient` but it'd be preferable to use the built-in mapping functionality for relationship properties without having to write a custom converter)

**Comment by meistermeier** [comment]
This were only particular possible in SDN 5 with the `@RelationshipEntity`.
What you want to achieve could be solved
a) with a custom query, as you already said.

b) modelling the relationship (properties) from the `User` to the `Group`, if this is possible at all, and than using projections.
So you would create:
```
interface UserProjection {
UserGroupRealtionshipPropertiesProjection getRelationship();
}

interface UserGroupRealtionshipPropertiesProjection {
String getNickname();
GroupProjection getGroupProjection(); // if needed at all
}

interface GroupProjection {
// everything needed but *NOT* the relationship back to the thousands of users
}
```
than you could do, for example, a `UserRepository#findByRelationshipNickname(String nickname);` to get the sliced-data result.

**Comment by Sm0keySa1m0n** [comment]
I ended up putting the relationship properties on the user instead of group (not sure why I didn't do that in the first place).

Though may I ask why it was decided to not make relationships root entities in SDN 6? It still seems like quite a useful feature, I acknowledge you can use a custom query but you can't take advantage of the mapping framework when you do that.

**Comment by meistermeier** [comment]
We brought a stricter domain driven context into Spring Data Neo4j. This is more in line with the general Spring Data concept. This means that relationships are no entities because they cannot exist without connected entities. If you remember SDN 5 / Neo4j-OGM there was always the need to also load the from- and to-node.
Also we interpret them compared to SQL stores like the equivalent to m:n mapping tables with additional properties. They are nothing you would load by themself in a domain-centric application.
