### ISSUE TITLE
@DynamicLabels doesn't specify the node's label

### ISSUE THREAD

**Issue by mdelmoral** [spring-projects/spring-data-neo4j#2455]
Hi,
In a new phase of our project, we started to use `@DynamicLabels` annotation in the most numerous type of node we have in our database.

```
@Node("Player")
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class PlayerNode extends UpdatableNode {

    @Nonnull
    @Id
    private String userId;

    @EqualsAndHashCode.Exclude
    @Nonnull
    @DynamicLabels
    private Set<String> labels;

....
```

In the DEV environment (~60k nodes), it worked great and we didn't have any problem but we deployed to PRO, the problems arose (~6.5M nodes). The performance of our DB has collapsed, even it is oversized and has plenty of hardware resources.

We started to dig in the changes that we did and fortunately, reading the current queries in execution we found out this query:
```
MATCH (n) WHERE (n.userId = $__id__ AND n.version = coalesce($__version__, 0)) UNWIND labels(n) AS label WITH label WHERE NOT (label IN $__staticLabels__) RETURN collect(label) AS __nodeLabels__
```
and this query is executed by `playerNodeRepository.findById`

As you can see, the `MATCH(n)` is searching in all nodes of our DB when it should specify the `:Player` node.

The difference is in our case times of 2-3 ms versus 20-30 seconds.

**Comment by michael-simons** [comment]
Thanks @mdelmoral excellent catch, will fix ASAP.
