### ISSUE TITLE
Order of Non-Root Nodes Not Being Respected

### ISSUE THREAD

**Issue by myfrontpocket** [spring-projects/spring-data-neo4j#2458]
SDN 6.2

For the following simplified example data model:

```
@Node
public class Group extends Entity<Group> {

  @Property
  private int priority;

  @Relationship("HAS_CONDITION")
  private List<Condition> conditions = new ArrayList<>();

  @Relationship("HAS_OPERATION")
  private List<Operation> operations = new ArrayList<>();
}

@Node
public class Condition extends Entity<Condition> {

  @Property
  private int priority;
}

@Node
public class Operation extends Entitiy<Condition> {

 @Property
  private int priority
}
```

If I had Group with id "12345", that has two operations--Operation A with priority 2 and Operation B with priority 1--and two conditions--Condition A with priority 2 and Condition B with priority 1, then I would expect this statement:

```
MATCH (group:Group {id: "12345"})
WITH group
OPTIONAL MATCH (group)-[has_operation:HAS_OPERATION]->(operation:Operation)
OPTIONAL MATCH (group)-[has_condition:HAS_CONDITION]->(condition:Condition)
WITH group, has operation, operation, has_condition, condition
ORDER BY group.priority ASC, condition.priority ASC, operation.ASC
RETURN group, COLLECT(has_operation), COLLECT(operation),
 COLLECT(has_condition), COLLECT(condition);
```

To map to a `Group` object that would pass this test:

```
assertThat(group.getConditions()).containsExactly(conditionB, conditionA)
assertThat(group.getOperations()).containsExactly(operationB, operationA)
```

The assertions here, `containsExactly`, asserts that, for the given list, it contains exactly the elements given in the order given.  We've found that these assertions will fail, indicating that the related nodes are out of order.  Using this statement in a neo4j browser produces the expected results consistently.

**Comment by meistermeier** [comment]
What you are ordering and returning is not an ordered list 
You are ordering not the lists, you would return -TBH I do not how to do this- but you are just ordering the `group` by those properties.
Simpler example:
Given `(a:Person)-[:LIKES]->(:Food{name:'Seitan"})` and `(b:Person)-[:LIKES]->(:Food{name:'Noodles"})`
and you would do something like `ORDER BY food.name ASC`, you would always end with `b,a`. This is because _noodles_ comes before _seitan_ but if there would be e.g. also _apple_ connected to person _a_, you would get `a,b`.
But as I said, it does not have any influence on the returned list. What you are experiencing with the Browser is just some deterministic randomness.

**Comment by myfrontpocket** [comment]
> 

Ordering a set of nodes in a WITH clause and then returning that data set is not an uncommon thing, and is provided by example in the documentation: https://neo4j.com/docs/cypher-manual/current/clauses/order-by/#order-with

The data, presented, in a tabular form, should be and would be ordered as I've written it.  So, it's not a fluke of randomness that it works in the browser; it works that way because it's supposed to.

Also, I have tried writing the query in such a way as to ensure returning an ordered list, by using `apoc.coll.sortNodes`, but even this does not work.

```
MATCH (group:Group {id: "12345"})
WITH group
OPTIONAL MATCH (group)-[has_operation:HAS_OPERATION]->(operation:Operation)
OPTIONAL MATCH (group)-[has_condition:HAS_CONDITION]->(condition:Condition)
RETURN group, COLLECT(has_operation), apoc.coll.sortNodes(COLLECT(operation), '^priority'),
 COLLECT(has_condition), apoc.coll.sortNodes(COLLECT(condition), '^priority') ORDER BY group.priority ASC;
```

SDN should respect the ordering of any nodes as they are fetched and mapped.

**Comment by meistermeier** [comment]
The first example also refers to the node named `n` respectively `group` in your example. Of course you can order this one but you cannot simply order the attached arrays with Cypher on-board syntax.
I will have a look at the example with the strictly (apoc) ordered list you gave.

**Comment by myfrontpocket** [comment]
"but you cannot simply order the attached arrays with Cypher on-board syntax."

I'm not sure what you mean by this. This is clearly what I've done with the use of the order by here:

```
WITH group, has operation, operation, has_condition, condition
ORDER BY group.priority ASC, condition.priority ASC, operation.ASC
```

This works. If you changed anyone of those ASC to DESC and reran it in the browser, and looked at the data in table format, it would be ordered as specified.

**Comment by meistermeier** [comment]
Sorry that I did not catch the (unwritten) detail in the documentation:
```
row #| m      | p
1    | Matrix | B
2    | Matrix | D
3    | Matrix | C
4    | Matrix | A
```
becomes
```
row #| m      | p
1    | Matrix | A
2    | Matrix | B
3    | Matrix | C
4    | Matrix | D
```
and with the `collect` of p
```
row #| m      | p
1    | Matrix | [A,B,C,D]
```
So it should preserve the ordering even without the use of APOC.
Also there is now a `6.3.0-GH-2458-SNAPSHOT` that should solve the problem. If a 6.3.x does not work for you, I could also bring it to a 6.1 or 6.2 snapshot for feedback.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by myfrontpocket** [comment]
Sorry for the delayed response.  I can confirm that the change in your snapshot works.  Thanks so much!

**Comment by meistermeier** [comment]
Thanks a lot for your feedback. :bow:
