### ISSUE TITLE
Relation mapping using the most abstract label

### ISSUE THREAD

**Issue by marichka-spin** [spring-projects/spring-data-neo4j#2459]
Hello again team :)
I continue working over migrating our code to the new Spring Data. And currently I'm testing version 6.2.1-SNAPSHOT. Lets consider the case:

```
@Node("PetOwner")
public abstract class PetOwner {
    @Relationship(type = "hasPet")
    private List<Animal> pets;
}

@Node("Boy")
public class Boy extends PetOwner {}

@Node("Girl")
public class Girl extends PetOwner {}

@Node("Animal")
public abstract class Animal {}

@Node("Dog")
public class Dog extends Animal {}

@Node("Cat")
public class Cat extends Animal {}
```

So lets consider that Neo4j DB has Node(Boy) that has 1 relation to 1 Cat and 1 relation to 1 Dog, I assumed that projection view that looks like below should work and should result List<Animal> pets with size 2 but results with NULL:
` RETURN petOwner1{.*, PetOwner_hasPet_Animal | [....]}
`
But what I observed in DefaultNeo4jEntityConverter class (lines 349-354) relation mapping is executed in two phases using abstract source label and using concrete source label. During first phase PetOwner_hasPet_Animal is mapped well but during next phase mapped values are overwritten with empty ArrayList. MapAccessor values (line 542) doesn't contain key "Boy_hasPet_Animal" and empty collection is instantiated (line 658). 
https://github.com/spring-projects/spring-data-neo4j/blob/6.2.x/src/main/java/org/springframework/data/neo4j/core/mapping/DefaultNeo4jEntityConverter.java

Thank you for the assistance!

**Comment by marichka-spin** [comment]
I've created test project to reproduce the issue https://github.com/idun-corp/neo4j-test
Everything works using only embedded Neo4jDB

**Comment by meistermeier** [comment]
Thanks for spotting this. I thought that I did something to avoid the override. Must have been wrong ;)

**Comment by marichka-spin** [comment]
No problem! Looking forward to the fix! Wish you Merry Christmas and happy holidays

**Comment by meistermeier** [comment]
There will be a little early Christmas present available for you with version `6.2.1-GH-2459-SNAPSHOT`. :gift: 
But Santa's elves are still working on this, it should arrive in ~30 minutes and Santa would be thankful for feedback :santa: 
Thanks :wink:

**Comment by marichka-spin** [comment]
@meistermeier thank you for the fix. I'm still testing. Are you interested in other issues I may notice during my work? Anyway I'm using neo4j and Neo4j Spring Data actively.

**Comment by meistermeier** [comment]
Great, thanks for the feedback.
Of course we are interested in the issues, you have to report.

**Comment by marichka-spin** [comment]
@meistermeier Thank you! Finally I've finished testing the new fix! Looks good! Looking forward for release!
