### ISSUE TITLE
Cannot resolve sort properties correctly in @Query()

### ISSUE THREAD

**Issue by ImCa0** [spring-projects/spring-data-neo4j#2460]
This is my code:
```java
Sort sort = Sort.by("name").ascending();
PageRequest pageRequest = PageRequest.of(0, 5, sort);
Page<Entity> entityPage = entityRepository.queryPage(pageRequest);
```

This is my repository:
```java
public interface entityRepository extends Neo4jRepository<Entity, Long> {

    @Query(value = "MATCH (n:Entity) RETURN n :#{orderBy(#pageable)} SKIP $skip LIMIT $limit",
           countQuery = "MATCH (n:Entity) RETURN count(n)")
    Page<Entity> queryPage(Pageable pageable);
}
```

The CQL generated is:
```
MATCH (n:Entity) RETURN n ORDER BY name ASC SKIP $skip LIMIT $limit
```

And throw an error:
```
Variable `name` not defined
```

The correct CQL should be:
```
MATCH (n:Entity) RETURN n ORDER BY n.name ASC SKIP $skip LIMIT $limit
```

I can fix it by:
```java
Sort sort = Sort.by("n.name").ascending();
```

But it seem not appropriate using `n.` out of CQL

**Comment by meistermeier** [comment]
As you can also see here in the test case https://github.com/spring-projects/spring-data-neo4j/blob/5e59865cfb305aa6f42777164ab89215efdb8010/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L516 the `n.name` needs to get defined.
There is no (meta-)information to derive the name of the variable from.

**Comment by ImCa0** [comment]
> As you can also see here in the test case
> 
> https://github.com/spring-projects/spring-data-neo4j/blob/5e59865cfb305aa6f42777164ab89215efdb8010/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L516
> 
> the `n.name` needs to get defined.
> There is no (meta-)information to derive the name of the variable from.

I see. Thanks.
