### ISSUE TITLE
Mapping of nested classes collected under common label

### ISSUE THREAD

**Issue by marichka-spin** [spring-projects/spring-data-neo4j#2462]
Hello, team!

I have a question regarding inheritance again. For Example there is the following architecture:

```
@Getter
@Setter
@Node("Base")
public abstract class BaseClass {

    @Id
    private String uuid;
}

@Getter
@Setter
@Node("PetOwner")
public abstract class PetOwner extends BaseClass {

    private String name;

    @Relationship(type = "hasPet")
    private List<Animal> pets;
}

@Node("Boy")
public class Boy extends PetOwner {
}

@Node("Girl")
public class Girl extends PetOwner {
}

@Getter
@Setter
@Node("Animal")
public abstract class Animal extends BaseClass {

    private String name;
}

@Node("Cat")
public class Cat extends Animal {
}

@Node("Dog")
public class Dog extends Animal {
}

public interface BaseClassRepository extends Neo4jRepository<BaseClass, String> {
}

```

I have a use case when I need to get the collection of all entities that are subclassed from BaseClass. With OGM I was able to execute the following query and have everything mapped correctly. 
```
MATCH (n:Base) RETURN n, [(n)-[r]->(b) | [r,b]]
```
But now the cypher response has increased significantly and not totally correct. It doesn't expect to cover even this simple inheritance scheme described in first code block.

Please take a look at my unit tests in the repository https://github.com/idun-corp/neo4j-test (Test PetOwnerNeo4jServiceTest.testGetAllWithRelations)

**Comment by meistermeier** [comment]
This is not as _simple_ as you might think in the first place :wink:  but challenge accepted.
Some background information on this:
The query generator uses the `BaseClass` because of the `BaseClassRepository` as the main type. It has 0 relationship definitions. Only the `PetOwner` as an abstract, inheriting class has. But in the mapping code, SDN finds the implementation of those abstract hierarchy in `Boy` and `Girl`.
So this gives a lot of room for searching for relationships. But as I said, I think this is a great opportunity for us to broaden the mapping capabilities of SDN.

**Comment by marichka-spin** [comment]
Yeah, I didn't have even the smallest thought that it is simple. I've debugged some classes of SDN that are responsible for mappings and I totally understand why it works this way.  And it is just a suggestion for you broad the vision on the possible use cases. I have already spent a lot of hours  trying to migrate our code from OGM (that is not supported anymore) to SDN. I think I'll be able to cope with this particular case (and yeah its complicated :) ). And thank you for the response and have a nice day.

**Comment by meistermeier** [comment]
Could you give `6.3.0-GH-2462-SNAPSHOT` a try?
It's not a sophisticated solution yet but it technical works.

**Comment by marichka-spin** [comment]
Brilliant!!! Its working!!! Many thanks!!!!

**Comment by meistermeier** [comment]
Thanks for your feedback.
