### ISSUE TITLE
Consider whether to add support for spatial queries.

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#247]
SDN 3.0 supported spatial queries via `SpatialRepository` methods such as `findWithinBoundingBox`, which was based on querying against a particular attribute or set of attributes that represent coordinates.

https://github.com/neo4j-contrib/spatial

Consider whether to support this in SDN 4.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-561
