### ISSUE TITLE
Path resolution in Repository

### ISSUE THREAD

**Issue by paulux84** [spring-projects/spring-data-neo4j#2470]
Repository does not map to object result with only one node when cypher return path.

In the following example ServiceEntity (Service) contains a list (ServiceOption) that is correctly hydrated. In the meantime, all Service without relationships (the first match) are not returned as ServiceEntity from Repository while neo4j correctly returns it as result of a direct query to DB.
```
@Query("match p=(s:Service) where ID(s) IN $iterable return p " +
            "union match p=(:Service)-[:HAS_OPTION]->(option:ServiceOption) " +
            "where ID(option) IN $iterable return p")
    List<ServiceEntity> findAllByServiceOrServiceOptionId(Iterable<Long> iterable);
```
Thanks for your works,
Paolo

**Comment by meistermeier** [comment]
Thanks for reporting this.
It seems that an empty path returned by the single node was not correctly respected in SDN.
There will be a `6.2.2-GH-2470-SNAPSHOT` available in ~30 minutes containing the fix. Would be great to get your feedback on this.

**Comment by paulux84** [comment]
Great, I'll try the fix as soon as possible and reply to you with the results.
Thanks again

**Comment by meistermeier** [comment]
Could you provide some data and/or reproducer?
For the pattern above I created two `Services` of which one is connected to a `ServiceOption`.
You can see the example here https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2470 
If you would comment the `6.2.2-GH-2470-SNAPSHOT` dependency, the app will fail.

**Comment by paulux84** [comment]
Your code example is correct and the fix here seems to work. I'll searching for some dependency error in my project.

**Comment by paulux84** [comment]
Solved, thanks...the problem is related to old dependency cache.

**Comment by paulux84** [comment]
when will this fix be merged in a release branch?

**Comment by michael-simons** [comment]
https://calendar.spring.io

VMWare plans the releases.

cc @mp911de
