### ISSUE TITLE
SDN 6.1.5 not mapping related nodes from custom query result record

### ISSUE THREAD

**Issue by florian-morvai-lsyh** [spring-projects/spring-data-neo4j#2481]
Hi!

I do not know, whether this is a bug or just a misunderstanding on my side, but I am facing the following problem:

I have a custom query with pattern comprehensions for loading the data needed in a specific projection:
```java
    @Query("MATCH (customer:`Customer`) WHERE customer.name IN $names" +
            " RETURN customer, [(customer)-[customer_has_fleet:`HAS_FLEET`]->(fleet:`Fleet`) | [" +
            " customer_has_fleet," +
            " fleet," +
            " [(fleet)-[fleet_has_vehicle:`HAS_VEHICLE`]->(vehicle:`Vehicle`) | [" +
            "    fleet_has_vehicle," +
            "    vehicle" +
            "  ]]" +
            "]]")
    List<Customer> findCustomCustomer(@Param("names") Iterable<String> names);
```
, but it seems that Spring Data Neo4j fails to map the related entities from the result record:
![image](https://user-images.githubusercontent.com/100119830/154938569-e5dab20d-3271-4959-8745-32a44702c796.png)

The data is present in the database, and is retrieved by, for example, findAll
![image](https://user-images.githubusercontent.com/100119830/154938964-9106b9bf-440e-44f1-b0c7-3b3e9850d538.png)

I prepared a small example demonstrating the issue: https://github.com/florian-morvai-lsyh/sdn-custom-query-mapping/tree/main
I also checked this worked as expected in the previous version: https://github.com/florian-morvai-lsyh/sdn-custom-query-mapping/tree/sdn-ogm

I faced the problem using SDN 6.1.5, but checked that is is also present in 6.2.1

Some background:
The actual model is more complex than the example provided, and having a query series derived from the method name did not perform well in this case. The incremental queries looking for related nodes got too complex, resulting in tens of seconds of query time.

Please note, that in the original use case the custom query method returns an interface based projection of the domain type and the related nodes, but I do not think that has anything to do with the result mapping.

**Comment by meistermeier** [comment]
In the cypher query you are using you are returning nodes and relationships in a nested list (let's call it Neo4j-OGM-style).
Now you would either need to return nodes and relationships separately like described: https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-queries
If you want to mimic SDN's behaviour of query creation, we covered the basics here: https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-creation.load
I raise this here because it is closer to the nested pattern comprehension, you already have but needs some alignment. Now it is a map-style (you can see it in the linked documentation).

**Comment by florian-morvai-lsyh** [comment]
Thanks for your response! I will go through the linked documentation chapters again and hopefully see what I missed, then I'll get back to you. (Probably sometime next week)

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by florian-morvai-lsyh** [comment]
After reviewing the documentation again, I did not take away that "Neo4j-OGM-style" records are not supported anymore, just that SDN cannot process paths returned in the result.

Nevertheless, I had partial success with the suggested approaches.

Mimicking the SDN query creation did work fine (and fast) as long as the result does not contain circular references - this is sad, but to be expected, I assume.

Returning nodes and relationships separately works as expected, but is painfully slow either with server or client side reduction.

**Comment by meistermeier** [comment]
> Returning nodes and relationships separately works as expected, but is painfully slow either with server or client side reduction.

Do you have the chance to test the _6.2.3_? We brought in some improvements regarding memory consumption and as a consequence could bring down the mapping time for a lot of duplicated data (the nature of paths with repeating nodes for each permutation of the path) in the result.

**Comment by florian-morvai-lsyh** [comment]
Hi Gerrit!

We actually moved to _6.2.1_ which already performs somewhat better. Also tried _6.2.3-GH-2487-SNAPSHOT_ which performed even better - I assumed the work related to #2487 brought the performance boost and was waiting for it to find its way into a release - although our model does not rely on inheritance. Will check _6.2.3_ out 👍 

I think this ticket can be closed now. Sorry for failing to post our status in the past weeks.
Thank you for your support and your hard work! 🙂

**Comment by meistermeier** [comment]
No need to excuse, we all have this times where we cannot handle everything.
Thanks for coming back and providing feedback, much appreciated.
