### ISSUE TITLE
Inheritance determination performance improvements

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-neo4j#2487]
(better title required)

**Comment by nikobonomi** [comment]
Hello there,

First of all, thanks you for accepting this challenge :smile: your work is very much appreciated

Just for keeping track I link the neo4j community issue: https://community.neo4j.com/t/spring-data-neo4j-performance-issues/51984

Right now I cant see any 6.2.3-GH-2487-SNAPSHOT available in the two repositories you have linked.
I looked up here: https://repo.spring.io/ui/native/snapshot/org/springframework/data/spring-data-neo4j/

And also maven thorws an error at me saying: 
`Could not find artifact org.springframework.data:spring-data-neo4j:pom:6.2.3-GH-2487-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot)
`

**Comment by meistermeier** [comment]
Thanks :heart: There seems something wrong with the build and release process of artifacts right now. Investigating.

**Comment by meistermeier** [comment]
It should be available now. :tada:

**Comment by nikobonomi** [comment]
Well, first try and it seems freaking faster ⚡!

Later today I will make some more tests, but I'm pretty sure that the issue is fixed, thanks man!

**Comment by nikobonomi** [comment]
Hello there,

This weekend I have done some queries to test a bit the improvements.
I can say that the issue is fixed, the response is quite fast (event for the luke case in which there is a lot to parse).

So, a huge thanks for your work, you saved my project 🍾

**Comment by meistermeier** [comment]
Thanks for your feedback. Glad that it is working for you.
And of course thanks for reporting this in the forums. Everyone using inheritance will profit from the improvements.
