### ISSUE TITLE
relationship loop

### ISSUE THREAD

**Issue by zhageLiu** [spring-projects/spring-data-neo4j#2494]
i have two nodes, they have the same relationship and type
like this:
(node1:Node) - [out:OUT] -> (node2:Node)
(node2:Node) - [out:OUT] -> (node1:Node)

domain like this:
@Node 
```
public class Node {
    @Relationship(type = "OUT", direction = Relationship.Direction.OUTGOING)
    private List<Out> out;
    @Relationship(type = "OUT", direction = Relationship.Direction.INCOMING)
    private List<Out> in;
}
```

relationship like this:
```
@RelationshipProperties
public class Out {
    @TargetNode
    private Node node;
}
```

when i use this query:
```
@Query(match p = (node1:Node) - [out:OUT] -> (node2:Node) return p
List<Node> findNode();
```

java will throw StackOverflowError, because nodes have loop relationship
 
please tell me how to slove this error

pom like this:
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
    <version>2.6.4</version>
</dependency>

**Comment by meistermeier** [comment]
I tried to reproduce the problem in a separate branch: https://github.com/spring-projects/spring-data-neo4j/blob/4f16bdc279f29d9d2cb3d259f1593ab724842986/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L1270
But it just comes back.
Do you really refer to the loading of data, or is it the output from your application (e.g. jackson/JSON) that produces the error?

**Comment by zhageLiu** [comment]
i try to run your code
java throw error :
`2022-03-07 16:19:34.802 ERROR 14564 --- [nio-8086-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.ArrayList[0]->com.kaola.travel.area.domain.entity.neo4j.Person["knows"]->java.util.ArrayList[0]->com.kaola.travel.area.domain.entity.neo4j.Person["knows"]->java.util.ArrayList[0]->com.kaola.travel.area.domain.entity.neo4j.Person["knows"]->java.util.ArrayList[0]->com.kaola.travel.area.domain.entity.neo4j.Person["knows"]->java.util.ArrayList[0]->com.kaola.travel.area.domain.entity.neo4j`

main:
```
public List<Person> getPersons() {
      repository.save();
      return repository.find();
  }
```
domain: 
```
@Node("Person")
public class Person {
    @Id
    public Long id;

    @Relationship(type = "KNOWS", direction = Relationship.Direction.OUTGOING)
    public List<Person> knows;

    @Relationship(type = "KNOWS", direction = Relationship.Direction.INCOMING)
    public List<Person> knownBy;
}
```

repository:
```
@Repository
public interface PersonRepository extends CrudRepository<Person, Long>, CypherdslConditionExecutor<Person> {

    @Query("match p = (a:Person) - [:KNOWS] -> (b:Person) return p")
    List<Person> find();

    @Query("create (a:Person) - [:KNOWS] -> (b:Person) - [:KNOWS] -> (a)")
    void save();
}
```

**Comment by zhageLiu** [comment]
this error look like this node a have ship to b, and b have ship to a, a have ship to b......so, program is loop all the time, then the stack is overflow

**Comment by zhageLiu** [comment]
when i submit this issue, error is hashCode Infinite recursion, but they are of the same type

**Comment by meistermeier** [comment]
Although the documentation is from Neo4j-OGM and you can find references regarding JSON serialization and infinite loops with Jackson in different places, it should explain, how to break the infinite recursion: https://neo4j.com/docs/ogm-manual/current/reference/#_a_note_on_json_serialization
It is not SDN that is responsible for this loop.

**Comment by zhageLiu** [comment]
thank you for your help, i think i know how to solve this error, i override the method for hashCode, i will close this issue. thanks again
