### ISSUE TITLE
Support for SD-Commons infrastructure to make SD-Integration, e.g. SD-REST work

### ISSUE THREAD

**Issue by vince-bickers** [spring-projects/spring-data-neo4j#250]
Currently our repository infrastructure doesn't return its meta-information to SD-Commons in a way that other infrastructure building on top of it can use (specifically SD-REST).

MappingContext
PersistentEntity
PersistentProperty

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-564
