### ISSUE TITLE
Relationship statemachine uses internal ids all the time, not being able to keep track of processed values.

### ISSUE THREAD

**Issue by paolodedo** [spring-projects/spring-data-neo4j#2500]
Regarding issue

#2282 

that was about the need of adding relationship-objects to both the Sets of objects in order to save a relationship,

🔵with the dependencies:
spring-boot-starter-data-neo4j:2.6.4
spring-data-neo4j:6.2.2

🔵with the models:

```
public class Device {

    @Id
    private Long id;

    private String name;

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    @JsonIdentityReference(alwaysAsId = true)
    @Relationship(type = "BELONGS_TO", direction = Relationship.Direction.OUTGOING)
    private Set<Group> groups = new LinkedHashSet<>();
}

public class Group {

    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;

    private String name;

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    @JsonIdentityReference(alwaysAsId = true)
    @Relationship(type = "BELONGS_TO", direction = Relationship.Direction.INCOMING)
    private Set<Device> devices = new LinkedHashSet<>();
}
```

🔵with the controller for Group (empty because rest services are auto-generated):

```
    @BasePathAwareController
    public class GroupController {}
```

**the following POST request on the GroupController ReST endpoint returns a 200 OK (I expect the relationship with devices has been created):**

```
{
    "name": "test",
    "description" : "",
    "devices": ["/1"]
}
```

_but no relationship is created (not treated as a relationship for SDN as you'd have to tell your body that even the Device entity is linking to this very Group object); unfortunately, due to the double-side relationship saving mechanism, Spring Data Rest automatically generated ReST services (HATEOAS) have the relationship creation feature broken:_

Do you have a solution for that?

Thanks!

**Comment by michael-simons** [comment]
Sorry, but I can't investigate this issue with just a snippet of JSON code. The other issue had been solved.
So if you want us to work on it, please provide a *full* minimal reproducer.

**Comment by paolodedo** [comment]
Ok I edited the initial post.

**Comment by michael-simons** [comment]
Can you possibly try out the latest snapshot? 

Actually, there has been work in this area and I'm pretty sure this will affect your usecase:

https://github.com/spring-projects/spring-data-neo4j/commit/ff206fc595b6de673418cacc8abfbd91f71177a1

**Comment by paolodedo** [comment]
I've tried compiling _main_ branch and referencing it from my project.

The error is 400 Bad request if I try to add the relationship objects, with the following log:
2022-03-17 12:05:16.570  WARN 24428 --- [nio-8082-exec-5] .n.c.Neo4jPersistenceExceptionTranslator : Don't know how to translate exception of type class java.lang.ClassCastException

**Comment by michael-simons** [comment]
Please create a reproducer and share it.

**Comment by michael-simons** [comment]
Hey. So the class cast issue is due to a dependency problem with Spring Boot. They didn't upgrade the Neo4j Java driver. Sorry for that issue.

If you set 

```
<neo4j-java-driver.version>4.4.4</neo4j-java-driver.version>
```

with the snapshots, it works.

Your original problem still persist respectively I am investigating.

**Comment by paolodedo** [comment]
Ok, thank you very much.
I think this is fundamental using spring data rest, or we'll have to rewrite all the rest endpoints.

Thank and see you soon.

**Comment by paolodedo** [comment]
Thank you very much for your time and effort :)

Your PR is fixing POST and PATCH scenarios: relationship are created without the need of setting them bidirectionally.
For PATCH requests, as expected, if I do not pass my relationship IDs array then the relationships are left as they were; if I pass my array they are overridden.

But, for PUT requests scenario, relationships are not changed. 
Every relationship IDs array is ignored, I don't know why.
Do you?

**Comment by michael-simons** [comment]
No, I don't know…
the `PUT` in Spring Data Rest ignores the associations. Why it does it that why is behind my knowledge. Our persister only sees the old object without data, so it deletes the existing ones. Feel free to raise it as an issue with Spring Data Rest. 

For reference, here the `PATCH`

![image](https://user-images.githubusercontent.com/526383/159062980-aa278451-ffdb-4f41-9739-53cec4cb8e41.png)

compare it with the `PUT`

![image](https://user-images.githubusercontent.com/526383/159063070-3a4fd196-c47a-43bf-9b33-7086986b776c.png)

same data sent 

```
## Request Duplicate (2)
curl -X "PUT" "http://localhost:8082/service/groups/80ff67e2-63d6-492b-a3a4-49546507d6bf" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "name": "from put2",
  "devices": [
    "/1"
  ]
}'
```

**Comment by michael-simons** [comment]
A put on the sub resource does work as expected

```
## Request Duplicate (2)
curl -X "PUT" "http://localhost:8082/service/groups/80ff67e2-63d6-492b-a3a4-49546507d6bf/devices" \
     -H 'Content-Type: text/uri-list' \
     -d "/1"
```


don't know much more about Spring Data Rest… Maybe @odrotbohm knows more what's going on.

**Comment by paolodedo** [comment]
Thanks for being so accurate. For the moment, I'll use PATCH, and try to indagate the Spring Data Rest PUT issue.
