### ISSUE TITLE
Spring data neo4j doesn't handle correctly List in Map<String, Object>

### ISSUE THREAD

**Issue by Pandalei97** [spring-projects/spring-data-neo4j#2517]
Hi,

Given the following domain class

```java
@Node
public class SomeDynamicEntity {

    @Id
    protected Long id;

    @Property
    protected String name;

    @CompositeProperty
    protected Map<String, Object> otherProperties = new HashMap<>();

    @CompositeProperty
    protected Map<String, List> otherListProperties = new HashMap<>();

}
```

If we have a property `someProperty = ["test1", "test2"]` and we put it in both `otherProperties` and `otherListProperties`,
when we save the entity, we have only the first element of `someProperty` in `otherProperties`. Is it a bug ?

![image](https://user-images.githubusercontent.com/35604558/161998132-ca4ad3b7-2816-4d35-ad33-52e65a04cf43.png)

Thanks in advance for your response !

**Environment Information:**
- spring-data-neo4j: 6.2.3
- neo4j-java-driver: 4.4.5

**Comment by meistermeier** [comment]
Thanks for reporting this. It is not a bug but not yet requested functionality.
The Java `List`'s target type is defined as an `Object` (resp. Neo4j Java Driver's `Value`), so there is no existing built-in converter yet that sees itself responsible for doing this. It cascades down to a generic Spring converter that takes "the first" element from a collection and stores it.

**Comment by meistermeier** [comment]
Alright after some more investigation, I have to say that this is nothing we can change immediately in SDN.
The problem is another `Map` struct based functionality: Dynamic relationships. 
With a general `List` converter, SDN assumes that also those `Map<String, List<RelatedEntity>>` scenarios getting handled by the `List` converter, instead of creating related node.
What you could do for this case is to create your own converter:
```
static class MyObjectConverter implements Neo4jPersistentPropertyToMapConverter<String, Map<String, List>> {

	@Override
	public Map<String, Value> decompose(@Nullable Map<String, List> property, Neo4jConversionService neo4jConversionService) {
		Map<String, Value> decomposedMap = new HashMap<>();
		for (Map.Entry<String, List> entry : property.entrySet()) {
			decomposedMap.put(entry.getKey(), Values.value(entry.getValue()));
		}
		return decomposedMap;
	}

	@Override
	public Map<String, List> compose(Map<String, Value> source, Neo4jConversionService neo4jConversionService) {
		Map<String, List> objectMap = new HashMap<>();
		for (Map.Entry<String, Value> entry : source.entrySet()) {
			objectMap.put(entry.getKey(), entry.getValue().asList());
		}
		return objectMap;
	}
}
```
and use it like
...
@CompositeProperty(converter = MyObjectConverter.class)
public Map<String, Object> otherProperties = new HashMap<>();

```
Note that I explicitly used already the given type instead of `Object` in the declaration to keep the example simpler.

**Comment by xxLiuxx** [comment]
Hi @meistermeier, sorry to bring this old issue up. 

I'm working on `@CompositeProperty` for `Map<String, Object>` as well and noticed that the data being stored into neo4j always have a prefix which is the attribute name.

For example:
```
@CompositeProperty
public Map<String, Object> myMap = new HashMap<>();
```
Then, the data in neo4j will be something like `myMap.property1 = value1` `myMap.property2 = value2`.

Is there a way to store this kind of composite property into neo4j but only keep the last part of the name(`property1`, `property2`) and ignore the first part? (e.g. `property1 = value1`, `property2 = value2`)

Thanks
