### ISSUE TITLE
Inefficient query for entities with possible cycles

### ISSUE THREAD

**Issue by tlazarski** [spring-projects/spring-data-neo4j#2518]
Hi,

I noticed that the way how SDN handles `findAll()` for entities with possible cycles is highly inefficient. I am not sure, if it is known issue, which is caused by technical limitations. I did not find any warning about it in documentation, so I am reporting this. 

The root problem is this query, which is executed as the last query of few queries executed by SDN when finding all entities with cycles:
```
MATCH (rootNodeIds) WHERE id(rootNodeIds) IN $rootNodeIds 
WITH collect(rootNodeIds) AS n 
OPTIONAL MATCH ()-[relationshipIds]-() WHERE id(relationshipIds) IN $relationshipIds 
WITH n, collect(DISTINCT relationshipIds) AS __sr__ 
OPTIONAL MATCH (relatedNodeIds) WHERE id(relatedNodeIds) IN $relatedNodeIds 
WITH n, __sr__ AS __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ 
UNWIND n AS rootNodeIds WITH rootNodeIds AS a, __sr__, __srn__ 
RETURN a AS __sn__, __sr__, __srn__
```
I think it cause high redundancy of returned data, because in each record we have all relationships and nodes, which have been found for all returned root nodes. Example:
Assuming we have in database 10000 nodes A and 1000 nodes B, where each node A have exactly 1 relationship to 1 node B. When executing `findAll()` on repository for entity A, then the query will generate result, which consists of 10000 records where each record will contain 1000 relationships and 1000 related nodes. Finally it will force our application to receive and process 10000 * 2000 objects, what gives about 20kk objects in total. It is not optimal, because the same information can be represented as 10000 records where each record contains 1 relationship and 1 related node, so there would be only 20k objects instead of 20kk.

The redundancy of returned data is quite dangerous for applications, because it cause enormous CPU and memory usage for quite small datasets like 10k in the example. In the end simple invocation of `findAll()` on small dataset may crash an application. If optimizing this is impossible, then throwing exception (with message which indicates the problem) would be better option as soon as SDN realize that the `findAll()` for given dataset will generate such inefficient processing.

**Comment by tlazarski** [comment]
I am wondering if following query will not do the same job, but without duplicating data:
```
MATCH (rootNodeIds) WHERE id(rootNodeIds) IN $rootNodeIds 
OPTIONAL MATCH (rootNodeIds)-[relationshipIds]-(relatedNodeIds) WHERE id(relationshipIds) IN $relationshipIds AND id(relatedNodeIds) IN $relatedNodeIds 
RETURN rootNodeIds AS __sn__, collect(DISTINCT relationshipIds) AS __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ 
```

**Comment by michael-simons** [comment]
The reason why we are not matching on relationship patterns is not because we don't know Cypher, but we need all of them… So it is not only one hope, like in your idea, it may be multiple. Therefore, your suggestion is not suitable.

The thing is, with the improvements made here https://github.com/spring-projects/spring-data-neo4j/issues/2387 we just shifted the work from Neo4j to the client application…

I'm trying not to say "is find all with cyclic dependencies a good idea", but finding a solution… 

Can you try out a snapshot build? 

I'm trying to a path query working:

```
MATCH (rootNodeIds) WHERE id(rootNodeIds) IN $rootNodeIds 
OPTIONAL MATCH p = (rootNodeIds)-[*]-(relatedNodeIds) 
WHERE (
    all(r IN relationships(p) WHERE id(r) IN $relationshipIds) AND 
    all(r IN nodes(p) WHERE (id(r) IN $relatedNodeIds OR id(r) = id(rootNodeIds)))
) 
WITH rootNodeIds, collect(p) AS paths 
WITH rootNodeIds, [r IN paths | relationships(r)] AS rels, [r IN paths | nodes(r)] AS nodes 
RETURN rootNodeIds AS __sn__, rels AS __sr__, nodes AS __srn__;
```

the unbound path might be slow eventually too, but I tried to have it constrainted as much as possible.

**Comment by michael-simons** [comment]
Ok, this will die a slow death already on our integration tests… (on the database side of things…)

I need to discuss this topic with @meistermeier, I leave my generator here for the time being

```java
Statement toStatement(NodeDescription<?> nodeDescription) {

			String rootNodeIds = "rootNodeIds";
			String relationshipIds = "relationshipIds";
			String relatedNodeIds = "relatedNodeIds";

			// WHERE none(r IN relationships(p) WHERE type(r) = 'FATHER')

			Node rootNodes = Cypher.anyNode(rootNodeIds);
			Node relatedNodes = Cypher.anyNode(relatedNodeIds);
			NamedPath p = Cypher.path("p").definedBy(rootNodes.relationshipBetween(relatedNodes).unbounded());
			//Cypher.listWith(Cypher.name("r")).in(Functions.relationships(p)).where(Functions.id(Cypher.anyNode("r")).in(Cypher.parameter(relationshipIds)))
			ResultStatement build = Cypher.match(rootNodes)
					.where(Functions.id(rootNodes).in(Cypher.parameter(rootNodeIds)))
					.optionalMatch(p)
					.where(Predicates.all(Cypher.name("r")).in(Functions.relationships(p)).where(Functions.id(Cypher.anyNode("r")).in(Cypher.parameter(relationshipIds))))
					.and(Predicates.all(Cypher.name("r")).in(Functions.nodes(p)).where(
							Functions.id(Cypher.anyNode("r")).in(Cypher.parameter(relatedNodeIds)).or(Functions.id(Cypher.anyNode("r")).isEqualTo(Functions.id(rootNodes))))
					)
					.with(Cypher.name(rootNodeIds), Functions.collect(p).as("paths").asExpression())
					.with(
							Cypher.name(rootNodeIds),
							Cypher.listWith(Cypher.name("r")).in(Cypher.name("paths")).returning(Functions.relationships(Cypher.name("r"))).as("rels").asExpression(),
							Cypher.listWith(Cypher.name("r")).in(Cypher.name("paths")).returning(Functions.nodes(Cypher.name("r"))).as("nodes").asExpression()
					)
					.returning(
							rootNodes.as(Constants.NAME_OF_SYNTHESIZED_ROOT_NODE),
							Cypher.name("rels").as(Cypher.name(Constants.NAME_OF_SYNTHESIZED_RELATIONS)),
							Cypher.name("nodes").as(Cypher.name(Constants.NAME_OF_SYNTHESIZED_RELATED_NODES))
					)

					.skip(queryFragments.getSkip())
					.limit(queryFragments.getLimit()).build();
			System.out.println(build.getCypher());
			return build;
		}
```

**Comment by michael-simons** [comment]
Further update: Investigating the older version it turns out it suffers from the same issue, too.

**Comment by meistermeier** [comment]
Just an update on this issue: We changed the query creation to a form similar to the provided one above. Unfortunately other types of data constellation are far more impact now by a performance degradation.
I will keep this issue open to see if we could find some kind of "best average".

**Comment by meistermeier** [comment]
There were plenty of improvements to this query for loading data with unknown cyclic depth.
I'll close this issue now. In some future versions of SDN when we can set the base line Neo4j version to 5.LTS (to be announced), we will certainly revisit the queries, it produces, to see if we can benefit from newer query features.
But as long as the current SDN versions need (and we want them) to support Neo4j 4, we can only dial the knob towards either one part of the users with graph data format A is very happy or the other part of of users is very happy. Keeping it in the middle is the best for all.
