### ISSUE TITLE
Misleading warning message for unversioned Entities with external managed ID

### ISSUE THREAD

**Issue by Andy2003** [spring-projects/spring-data-neo4j#2525]
Given the following node:

```java
@Node
@Value
@AllArgsConstructor
@Immutable
public class Entity {
	@Id
	String id;
}
```

and Repository:

```java
public interface EntityRepository extends Neo4jRepository<Entity, String> {
}
```

and the invocation:

```java
entityRepository.save(new Entity("1"));
entityRepository.save(new Entity("1"));
entityRepository.save(new Entity("2"));

List<Entity> entities = entityRepository.findAll();
System.out.println(entities);
```

will print out:

```
WARN o.s.d.n.c.m.DefaultNeo4jIsNewStrategy    : Instances of class test.Entity with an assigned id will always be treated as new without version property!
DEBUG org.neo4j.driver.OutboundMessageHandler  : [0x1e829b67][localhost:7687][bolt-133] C: RUN "MERGE (entity:`Entity` {id: $__id__}) SET entity += $__properties__ RETURN entity" {__id__="1", __properties__={id: "1"}} {}
...
DEBUG org.neo4j.driver.OutboundMessageHandler  : [0x1e829b67][localhost:7687][bolt-133] C: RUN "MERGE (entity:`Entity` {id: $__id__}) SET entity += $__properties__ RETURN entity" {__id__="1", __properties__={id: "1"}} {}
...
DEBUG org.neo4j.driver.OutboundMessageHandler  : [0x1e829b67][localhost:7687][bolt-133] C: RUN "MERGE (entity:`Entity` {id: $__id__}) SET entity += $__properties__ RETURN entity" {__id__="2", __properties__={id: "2"}} {}
...
[Entity(id=1), Entity(id=2)]
...
```

The behavior of the library is as expected that a `merge` takes place for the entities. However, the warning message is very misleading as it suggests that either a version property is needed or duplicates of the same entity are created.

I would not expect any error message at all for this kind of usage.

BTW.: The ID property should be removed from the additionally set properties

Used library version: 2.6.0-RC1

**Comment by meistermeier** [comment]
The message itself is still needed even if it does not apply to your use-case.
It warns user why their auditing might not work as expected. Also there are some optimizations in the code if the entity is assumed as new.
For the id bit (combined with the `merge`): The merge is, strictly speaking, just used because we do not make any check if the entity is not before issuing this call. So new and existing entities end in the same code path here. This also should explain why we do not treat the custom identifier field in a special way here.

**Comment by meistermeier** [comment]
Not really. Also it is applicable for the given use case: SDN treats it as new. As I said, the merge is -like the statements for generated ids- "create or update" statements.
