### ISSUE TITLE
Better management of uncompatible types

### ISSUE THREAD

**Issue by CarbonHeartDev** [spring-projects/spring-data-neo4j#2528]
Neo4j is pretty restrictive on the types of data which it allows, or example it's impossible to nest lists or objects inside another list. The issue comes from the fact which when the developer tries to use these types on its entities it gets misleading runtime errors which can be hard to fix for teams which aren't very experienced in Neo4J.

In my opinion implementing a boot time check of the persisted entities members, looking for any type which is incompatible with Neo4j can save a lot of developers frustrations and man hours.

If you approve the idea I can volunteer to implement it, I'm experienced in the Spring Framework and in using Java Reflection.

**Comment by michael-simons** [comment]
I think we already do this and the rules from the top of my head are like this

- We check that the `@Id` fields on entities are proper and correspond with the types declared on concrete repositories as ID
- We have converters in place for a ton of additional types (see [AdditionalTypes](https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/core/convert/AdditionalTypes.java#L74l)) in addition to [CypherTypes](https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/core/convert/CypherTypes.java)
- Lists of things (or map of things) in which "things" are not understood types are usually expressed than as related objects
- There's machinery in place to "flatten" above "things" into Neo4j storable types (i.e. as strings, simple maps on nodes etc) that can be made use of

What should happen in which cases at boot time?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
