### ISSUE TITLE
@Depth  in sdk 6.X 

### ISSUE THREAD

**Issue by 410656275** [spring-projects/spring-data-neo4j#2534]
sdn 5.X have the annotation org.springframework.data.neo4j.annotation.Depth，but in the 6.X I can not find this。 
I would like to ask if there is an alternative to this annotation

**Comment by meistermeier** [comment]
You would use projections ( https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#projections.sdn.multi-level ) for this. This is an even more detailed way to define a blueprint / slice for the data to load.
