### ISSUE TITLE
Cannot query fields defined as types of base classes

### ISSUE THREAD

**Issue by sunny-chung** [spring-projects/spring-data-neo4j#2541]
------------ Basic Info ------------

Spring Data Neo4j Version: 6.3.0
Neo4j Database Version: 4.4.5
JVM Version: 11.0.12

Sample Project: https://github.com/sunny-chung/movies-java-spring-data-neo4j-6-bug-demo

------------ Description ------------

After migrating to SDN 6, entity classes defined as fields with type of base classes cannot be queried.

For example, in the sample project, part of the `Person` class is extracted to a base class named `Base`, and the type of the field `directors` in the `Movie` node entity is changed from `List<Person>` to `List<Base>`. In particular, the field `name` is extracted from the class `Person` to the class`Base`, and `directors` is a field annotated with `@Relationship` under the class `Movie`. Afterwards, following issues are observed:

1. With a custom query, `directors` cannot be queried and is always `null`, although there exists matched `Person` data.
```
	@Query("MATCH (n:`Movie`)<-[r_0:`DIRECTED`]-(m_0:`Person`) " +
			"MATCH (n)<-[r1:`ACTED_IN`]-(m1:`Person`) " +
			"WHERE m_0.name = $name RETURN n, COLLECT(r1), COLLECT(m1), COLLECT(r_0), COLLECT(m_0)")
	List<Movie> findAllByDirectorsName2(String name);
```

2. Following query always returns empty list.
```
	List<Movie> findAllByDirectorsName(String name);
```

For easy reference, entity definitions are copied to here.

```
@Node
public class Movie {

	@Id
	private final String title;

	@Property("tagline")
	private final String description;

	@Relationship(type = "ACTED_IN", direction = Direction.INCOMING)
	private List<Actor> actors = new ArrayList<>();

	@Relationship(type = "DIRECTED", direction = Direction.INCOMING)
	private List<Base> directors = new ArrayList<>();

	private Integer released;

	public Movie(String title, String description) {
		this.title = title;
		this.description = description;
	}

	// ... public getters & setter ...
}
```

```
@Node
public class Person extends Base {

	private Integer born;

	public Person(Integer born, String name) {
		super(name);
		this.born = born;
	}

	// ...
}
```

```
public abstract class Base {

    @Id
    private final String name;

    private Integer version = 0;

    public Base(String name) {
        this.name = name;
    }

    // ...
}
```

**Comment by meistermeier** [comment]
Thanks for reporting this.
At the moment there is no concept in SDN to support non-entity parent classes in the mapping declaration.
There are basically two solutions to this:
1. You have to add the `@Node` to the base class and to as a label to the node in the database.
2. You stick with the concrete definition of a `Person` in the `Movie` entity that is still a child of the `Base` class. In this case no annotations and change of the data is needed.

We will for sure have a look the next days, if this is something we might could bring into SDN without breaking any existing functionality.

**Comment by meistermeier** [comment]
Closing this, because we have a workaround and cannot fix the situation without introducing another problem.
If you have the feeling that it could be solved in another way in SDN, please re-open it.
