### ISSUE TITLE
Regression: Constraint Validations are no longer translated into DataIntegrityViolationException with neo4j-java-driver >= 4.3.2

### ISSUE THREAD

**Issue by GrahamLea** [spring-projects/spring-data-neo4j#2542]
# Scenario
Execute a modifying Neo4j transaction that results in a constraint violation.

# Expected behaviour
The repository throws a `org.springframework.dao.DataIntegrityViolationException`.
(This is what it does with `neo4j-java-driver` versions < 4.3.2)

# Actual Behaviour
The repository throws a `org.neo4j.driver.exceptions.ClientException`.

# Reproduction
1. Clone `https://github.com/GrahamLea/neo4j-bugs`
2. Load in IntelliJ IDEA
3. Run `TestNodeTest.raises DataIntegrityViolationException on constraint violation`
4. It will fail
5. In pom.xml, change `neo4j.driver.version` back to `4.3.1`
6. Run test again and it will pass

# Comments
It's possible there's a regression in [`neo4j-java-driver`](https://github.com/neo4j/neo4j-java-driver) that has caused this to happen.
But the expected result `DataIntegrityViolationException` is part of this project, so I didn't feel I could submit the issue there.

**Comment by michael-simons** [comment]
Puh, this is on a very old SDN version that we actually don't support anymore. There's actually little I can do, VMWare most likely won't do any release of the old 5.x branches anymore. 

However, I think this can be fixed in the underlying OGM.  

OGM 3.2.34 will go out this morning, please try it out and close the issue if this fixes things for you.

**Comment by michael-simons** [comment]
That's kinda odd, because our CI says the job has finished correctly and normally, central isn't that slow. 
In short: Yes, it should have been on central.

**Comment by michael-simons** [comment]
Ok, it was a problem of the operator (me, in this case) which is solved now. 

https://repo1.maven.org/maven2/org/neo4j/neo4j-ogm-core/3.2.34/

Thanks for your ping, @GrahamLea

**Comment by GrahamLea** [comment]
Yep, 3.2.34 has fixed it. Thanks. Amazing service! 😉👏

**Comment by michael-simons** [comment]
Thanks a lot for your feedback <3
