### ISSUE TITLE
save() method on Neo4JRepository does not update @RelationshipEntity object   

### ISSUE THREAD

**Issue by ChrisHilborne** [spring-projects/spring-data-neo4j#2561]
Updating any data, including nodes, is not propagated to the DB when using the default save() method. 

When I check the object that is returned from the save() method - it has the expected, and updated, properties. However, querying the Neo4J instance shows that the update has not been propagated to the DB itself. 

The method works perfectly when creating a new Relationship. So my work around at the moment is to delete the existing @RelationshipEntity and create a new one.  

I also found a [related issue](https://github.com/neo4j/neo4j-ogm/issues/607) with example code in the neo4j-ogm repository however the response does not address the issue with the Neo4JRepository method itself, since the issue was not raised in the correct place.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ChrisHilborne** [comment]
Hello again! 

After doing some further testing I realized that the problem is at my end. I was creating a new @RelationshipEntity with the updated data - changing it's id to that of the one I wanted to update - and calling save() expecting it to update...

Apologies for the trouble.

**Comment by michael-simons** [comment]
Thanks @ChrisHilborne for your kind feedback!
