### ISSUE TITLE
Custom Query With Pagination is return Same Result

### ISSUE THREAD

**Issue by wavemoroc001** [spring-projects/spring-data-neo4j#2589]
Hi there, I want to create custom query with pagination with following  Query script 

**Service**

``` java 
    public Page<Event> getEventByPage(Integer pageNo, Integer pageSize, String sortBy, String orderBy) {
        // default sortBy creatAt
        Pageable paging =  PageRequest.of(pageNo, pageSize, Sort.by(String.format("e.%s",sortBy)));
        return eventRepository.findAllEvents(paging);
    }

```

  **Repository**
  
```java 
    @Query(value = "Match (e:Event)\n" +
            "where e.endDate >= datetime.realtime().epochMillis \n" +
            "OPTIONAL Match x=(l:Location)-[:LOCATE]-(e)\n" +
            "return e,nodes(x),relationships(x) \n"+
            ":#{orderBy(#pageable)} \n" +
            "SKIP $skip LIMIT $limit \n"
            ,
            countQuery = "Match (e:Event)\n" +
                    "where e.endDate >= datetime.realtime().epochMillis \n" +
                    "RETURN count(e) \n"
    )
    Page<Event> findAllEvents(Pageable pageable);
```

I have faced with problem when i call method it always return same record event i change pageNo it still return same method (same id) following postman image

<img width="1293" alt="Screen Shot 2565-09-11 at 01 14 56" src="https://user-images.githubusercontent.com/56395197/189496469-6999d636-6593-48fa-844f-9c295f4ebff0.png">

<img width="1303" alt="Screen Shot 2565-09-11 at 01 15 07" src="https://user-images.githubusercontent.com/56395197/189496472-ffc3ed4b-b924-4e94-a055-335dba41fdee.png">

**Comment by meistermeier** [comment]
Thanks for reporting this. 
Your query looks correct and I tried to reproduce your problem but it worked on my end.
Do you have any default value for the `sortBy` attribute? I can see that you left it unchecked and was not appended to the URI.

**Comment by wavemoroc001** [comment]
@meistermeier I set default `sortBy` at controller that is `createDate`
the structor of node is same as this issues. https://github.com/spring-projects/spring-data-neo4j/issues/2573  might help you reproduced easily  


```java
    @GetMapping
    public ResponseEntity<?> getEvent(@RequestParam(defaultValue = "0") Integer pageNo,
                                      @RequestParam(defaultValue = "5") Integer pageSize,
                                      @RequestParam(defaultValue = "createDate") String sortBy,
                                      @RequestParam(defaultValue = "desc") String orderBy) {
        Page<Event> eventPage = eventService.getEventByPage(pageNo, pageSize, sortBy, orderBy);
        return ResponseEntity.ok(new GetEventPageOnFeedResponse(eventPage));
    }
```

**Comment by meistermeier** [comment]
Don't want to waste time before diving into this but two things come up in my head:
1. Did you rename the parameter from the related issue? You are using `createDate` here but the `Event` has only a `createAt` property.
2. Could it be that two create dates are the same?

Both would lead into a situation where the results are not properly sorted because either (1) there is no valid property to order by or (2) they are both the same and would get randomly returned from the database for each individual query.

**Comment by wavemoroc001** [comment]
Oh i just notice that, I' m apologize for my mistake 
then I fix it  and try again it work normally thank you so much

**Comment by wavemoroc001** [comment]
Oh i just notice that, I apologize for my mistake. I fix it and try again it work normally Thank you so much
