### ISSUE TITLE
Neo4jTemplate.saveAs throws StackOverflowError when given recursive projection

### ISSUE THREAD

**Issue by cberes** [spring-projects/spring-data-neo4j#2591]
SDN is unable to save nodes using a projection that recursively references itself. 

For example, say you have a node entity that recursively references itself

    @Getter
    @Node
    public class Person {
      private String name;

      private List<Person> children = new LinkedList<>();
    }

And a corresponding projection that references itself as well

    public interface PersonWithChildrenRecursive {
      String getName();

      List<PersonWithChildrenRecursive> getChildren();
    }

You cannot save a node using this projection

    Person alice = new Person();
    alice.setName("Alice");
    neo4jTemplate.saveAs(alice, PersonWithChildrenRecursive.class); // throws StackOverflowError

Note that other ways to save will succeed, such as `CrudRepository.save` or `Neo4jTemplate.saveAs` with a projection that is _not_ recursive.

I have an [example app](https://github.com/cberes/sdn-recursive-projection-bug) that reproduces the bug.

I don't know if this a new bug or a regression. I noticed it first while using 6.3.3-SNAPSHOT but the bug is present in 6.3.2 as well.

**Comment by meistermeier** [comment]
Thanks for reporting this and the reproducer. Yes, you are completely right. This is definitely a bug and now -thanks to your work- already solved. Just need to add some internal testing and it will get fixed in the next 6.3. patch version.
