### ISSUE TITLE
Neo4jHelper is missing in 3.3.0 version

### ISSUE THREAD

**Issue by demongloom** [spring-projects/spring-data-neo4j#261]
Hi,

The neo4jHelper class was removed in 3.3.0 RELEASE, but it presents in 3.2.3 or even in 3.3.0RC1 versions.
The class itself does not have any @deprecated warnings.

**Comment by demongloom** [comment]
The file was moved to tests in commit: https://github.com/spring-projects/spring-data-neo4j/commit/82148d36403522d55f9b93a9a921cec6928a2e07

Now it's located at
https://github.com/spring-projects/spring-data-neo4j/blob/82148d36403522d55f9b93a9a921cec6928a2e07/spring-data-neo4j/src/test/java/org/springframework/data/neo4j/support/node/Neo4jHelper.java

**Comment by monowai** [comment]
To your pom.xml you can add
```
<dependency>
   <groupId>org.springframework.data</groupId>
   <artifactId>spring-data-neo4j</artifactId>
   <classifier>tests</classifier>
   <version>${org.springdata.neo4j}</version>
   <scope>test</scope>
</dependency>

**Comment by demongloom** [comment]
I solved it using similar pom change, but the question why it was moved without any notice in changelog?

**Comment by jexp** [comment]
Good Question, it was not meant as public API. Sorry if it was perceived as such. It was just meant for *older*  tests to clean out their used databases. The new ones use ImpermanentGraphDatabase anyway.
