### ISSUE TITLE
Use projections with Relationship annotation

### ISSUE THREAD

**Issue by LeadingMoominExpert** [spring-projects/spring-data-neo4j#2616]
I would like to be able to use projections with relationships to prevent circular references and still having the ability to sort of define relationships on two connected nodes from both nodes. Written in kotlin this would look something like 
```kotlin
@Node
data class Foo(
    val name,
    @Relationship(type = "IS", direction = OUTGOING) val bar: BarProjection? = null
)

interface FooProjection {
    val name: String
}

@Node
data class Bar(
    val name,
    @Relationship(type = "IS", direction = INCOMING) val foo: FooProjection? = null
)

interface BarProjection {
    val name
}
```

I've also tried finding help on [stackoverflow](https://stackoverflow.com/questions/73617859/using-projections-as-relationship-nodes-in-spring-data-neo4j-returns-nothing) on this matter but haven't found a way to implement this using current (SDN 6.3.5) capabilities.

**Comment by meistermeier** [comment]
Sorry that I missed the question over at StackOverflow.
Maybe I read your code wrong, but you should never use a projection as a relationship type in the domain class. So I assume right now that Foo is linked to Bar and vice-versa.
Basically your idea is correct (now Java-style):

```
interface FooProjection {
  String getName();
  BarProjection getBar();
}
```
with
```
interface BarProjection {
  String getName();
}
```
would exactly do what you want. Depending on the root entity, you might have to switch `Foo` with `Bar`.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
