### ISSUE TITLE
DynamicLabels include non-dynamic label

### ISSUE THREAD

**Issue by SaschaPeukert** [spring-projects/spring-data-neo4j#2619]
Given:
```
@Node("Metric")
public abstract class Metric {
	@DynamicLabels
    public List<String> dynamicLabels;
	
	...
}

@Node("Counter")
@Value
public class CounterMetric extends Metric {
	...
}
```
And a test something like this:
```
...

var c = new CounterMetric(...);
c.dynamicLabels.add("Test");
save(c)
...
var retrievedCounter = load(counter)
...
```
It appears that `dynamicLabels` now include "Test" and "Counter" which is not ideal.

Seen with spring-boot 2.6.13 which uses spring-data-neo4j 6.2.9, I think

**Comment by SaschaPeukert** [comment]
Update: from what I see in our tests, this only happens sometimes, making it very annoying to deal with

**Comment by michael-simons** [comment]
IDK yet if relevant or not, but do these entities have `@Id @GeneratedValue Long` ids (internal neo4j) or are you using UUID or similar?

**Comment by michael-simons** [comment]
Thanks @SaschaPeukert for the report. This is fixed now.
