### ISSUE TITLE
Add support to define target node class for projections to support multilevel projections with inheritance

### ISSUE THREAD

**Issue by NilsWild** [spring-projects/spring-data-neo4j#2621]
Problem: 
Given the following Node definitions:
```
@Node
class Foo (
        val bar: Bar
        ) {
    @Id
    var id: UUID = UUID.randomUUID()
}

@Node
open class Bar(
    val value1: String
) {
    @Id
    var id: UUID = UUID.randomUUID()
}

@Node
open class BarBar(value1: String, val value2: String): Bar(value1)
```
There is no way to define a multi-level projection for Foo and Bar/BarBar that can be saved or queried, because sdn can't determine to which subtype the projection should be mapped and vice versa. e.g.: The following wont work:
```
class FooProjection(
    val bar: BarProjection
)

open class BarProjection(
    val value1: String
)

open class BarBarProjection(value1: String, val value2: String): BarProjection(value1)

val barBarProjection = BarBarProjection("v1", "v2")
val fooProjection = FooProjection(barBarProjection)
neo4jTemplate.save(Foo::class.java).one(fooProjection)
```
Querying will result in an exception as well because the mapping information is missing.

**Comment by meistermeier** [comment]
Could you elaborate on your use-case for introducing inheritance at the projection level?
The basic idea of having this support is to cover specific loading (and saving) scenarios.

Also, sorry for the (very) late reply here.

**Comment by NilsWild** [comment]
So first of all: As far as i understood, projections are used to save and load subgraphs as we would have to save the whole graph if the graph data is strongly connected. 

So let's assume i store vehicles of different kinds with relationships to owning entities like people or companies. And those entities do have relations as well. I have Node classes for the different vehicle types that have different attributes. Now i want to store a fleet of vehicles for such an entity using projections to only store and update those nodes and relationships contained in that projection instead of the whole graph as it might be strongly connected. 

So i think a CarProjection should be mapped to the CarNode subtype of VehicleNodes. And i want to map VehicleNodes that are of a certain type to their respective projection Nodes. Currently this doesn't seem to be possible.
