### ISSUE TITLE
SDN ID mapping issue

### ISSUE THREAD

**Issue by hadiyarajesh** [spring-projects/spring-data-neo4j#2628]
SDN ID mapping with neo4j seems confusing.
`Spring Boot version: "3.0.0-RC2"`
`Neo4j version: 5`

If I use following code to create `Node` 

```kotlin
@Node("Post")
data class Post(
    @Id
    @GeneratedValue
    @JsonIgnore(true)
    val id: Long? = null,
    val postId: Long,
    val url: String
)
```

And try to fetch it, it gives a warning 
`The entity com.hadiyarajesh.example.Post is using a Long value for storing internally generated Neo4j ids. The Neo4j internal Long Ids are deprecated, please consider using an external ID generator.`
AND
`One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: id)`

If I create a `Node` without `'id', as follow,
```kotlin
@Node("Post")
data class Post(
    @Id
    val postId: Long,
    val url: String
)
```

It gives a warning `Instances of class com.hadiyarajesh.example.Post with an assigned id will always be treated as new without version property`

Now, what approach should I take?
How do I use a `version` property for kotlin `data class`?
Is it fine if I don't specify `version` property?

**Comment by meistermeier** [comment]
Thanks for pointing this out.
The warning message is logged intentionally: Neo4j 5 and the Java driver (5+) deprecating the internal `long` id in favour of a more powerful one. Spring Data Neo4j 5 still supports those ids of course, but will log the warning.
There is a difference between the _external generated_ ids and your solution, a _provided_ id.
The first ones are ids that get created via `@GeneratedValue(<YouGenerator>.class)`, and will get called on persist of new entities. So in the moment SDN processes the entity, it knows that `id!=null` means this entity was already persisted to the database.
In your case, SDN cannot determine, if the entity is new or not and logs the other warning `....treated as new without version property`. So it needs another field to verify if the object needs to get created or updated, a `@Version` annotated field.

The warning regarding the property is something that comes directly from the database and thus at the moment not something we can or want take care of. There might be situation where users want to make use of this warning (or at least see this warning).
If there is anything unclear, please ask further to clarify this topic for you.

**Comment by hadiyarajesh** [comment]
Thanks @meistermeier for clear explanation.

I've tried using `@Version` in past with kotlin `data class` but had no fruitful outcome. I'll again try `@Version` in `data class` and let you know if it works.

One question is:

1. How can I `GENERATE` new ids? Is there any build in generator available? If not, how can I make one? In short, how to resolve this warning in whatever way possible?

**Comment by meistermeier** [comment]
There is a `UUIDStringGenerator` available that will create, as the same suggests, `Strings` from the `UUID` class.
If you don't have any generator in mind that would reflect more your business logic, I would suggest using this.

**Comment by hadiyarajesh** [comment]
Thanks @meistermeier for quick and insightful explanation. Closing the issue.
