### ISSUE TITLE
Count() aggregator NoRootNodeMappingException

### ISSUE THREAD

**Issue by goldman7911** [spring-projects/spring-data-neo4j#2633]
Hi all,

I have created a replicable repo for this issue: https://github.com/goldman7911/spring-data-understanding 
It will need a clear Neo4j running and run tests to validate what I'll try to explain here.

I'm starting feeling there is something wrong or my understanding is complety wrong for OGM

My data is:

```
{
  "identity": 171,
  "labels": [
    "RootMarker"
  ],
  "properties": {
"lastModifiedDate": 1666934940115,
"p5Latest": true,
"messageIds": [
      "fake-900b-49ac-92c7-fake",
      "fake-7777-4ab1-7777-fake"
    ],
"resources": 1,
"messageId": "fake-7777-4ab1-7777-fake",
"deviceId": "XXXXX",
"domainId": "fake-7777-4ab1-7777-fake",
"createdDate": 1666896513598,
"drniId": 222222222,
"id": 11,
"isFull": true,
"resyncId": "fake-7777-4ab1-7777-fake",
"status": "resync",
"latest": [
      22
    ]
  }
}
```

My objective is to map this Query to Java:

![image](https://user-images.githubusercontent.com/57152650/203626524-252e838c-ed1c-42f4-9359-0200d6b985e7.png)

As you can see, all methods getResyncIdAndMessageIdsCountPureSDNXXXX are failing with same error

![image](https://user-images.githubusercontent.com/57152650/203626572-d208154b-946b-4f41-99f5-e1dd50746f81.png)

`org.springframework.data.neo4j.core.mapping.NoRootNodeMappingException: Could not find mappable nodes or relationships inside Record<{resyncId: "fake-7777-4ab1-7777-fake", counter: 2}> for org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity@777d191f`

Is weird how the same Neo4jRepository uses neo4jClient behind the scenes but could not map it. This method bellow I could sucessfully use in MyService.java

```
public Collection<MyDTO> getResyncIdandMessageIdsCount() throws NoSuchElementException {
        Collection<MyDTO> result = neo4jClient.query("match (r:RootMarker) UNWIND r.messageIds as rx return r.resyncId as resyncId, count(rx) as counter")
                .fetchAs(MyDTO.class)
                .mappedBy((typeSystem, record) -> {
                    String resyncId = record.get("resyncId").asString();
                    Long counter = record.get("counter").asLong();
                    return new MyDTO(resyncId, counter);
                }).all();
        return result;
    }
```

Also, just the first two of MyRepository do work. The 3 left receive the same error NoRootNodeMappingException.

```
public interface MyRepository extends Neo4jRepository<RootMarker, Long> {

    @Query("MATCH (n:RootMarker) RETURN n ORDER BY n.domainId")
    List<RootMarker> getRootMarker();

    @Query("MATCH (n:RootMarker) RETURN count(n)")
    Long countRootMarker();

    //THAT'S NOT WORKING
    @Query("match (r:RootMarker) UNWIND r.messageIds as rx return r.resyncId as resyncId, count(rx) as counter")
    Collection<MyDTO> getResyncIdAndMessageIdsCountPureSDN();

    //THAT'S NOT WORKING
    @Query("match (r:RootMarker) UNWIND r.messageIds as rx return r.resyncId as resyncId, count(rx) as counter")
    <T> Collection<T> getResyncIdAndMessageIdsCountPureSDNGenerics(Class<T> type);

    //THAT'S NOT WORKING
    @Query("match (r:RootMarker) UNWIND r.messageIds as rx return r.resyncId as resyncId, count(rx) as counter")
    Collection<MyProjectionDTO> getResyncIdAndMessageIdsCountPureSDNProjections();

}
```

Please help me understand why I can't map count aggregator result as Long by using OGM

**Comment by michael-simons** [comment]
Thanks for using our stuff. 

It’s for the exact reason the message says: there’s a no node in your result set, just an arbitrary row. This project is not a row mapper, it’s a graph mapper. 

And yes, simple solution just have a look at the fields of the record and just map them to class names works in that case but the next Ticket than will ask for nested results. 

However, we will think about whether we can support this simple case with a reasonable amount of work.

**Comment by goldman7911** [comment]
Thanks @michael-simons for the quick reply. It is really clear by extends Neo4jRepository<THENODE, ID> that it needs to be using a actual node. I was in a kind of negation. 

Seems you got the point. The next natural questions that arise is how to get nested resulted. The 'weird feeling' is that seems this project has all technology capabilities to handle that by Neo4jRepository but chosed not. 

What I understand is I need create 'on-fly' a new node with a new Neo4jRepository<RESULT_NODE,ID> to fetch this result. Of course lot more work than just by neo4jClient. 

I'll try to get my 'hands dirty' as a study exercise on how I think this should be and arise a PR. I think you be a fun project. In the worst I'll learn a lot. Do you have a suggestions on how should I start?

**Comment by michael-simons** [comment]
Hey no worries.

We spoke about that today how strict do we want to keep things in the repository thing way and let's be honest: It's not the first time a question like this has been raised.

It seems that I can make this work with little effort. You see what is necessary to shape up the content (which is also documented anyway for known entities and custom queries):

```java
package org.springframework.data.neo4j.integration.lite;

import java.util.Collection;
import java.util.Optional;
import java.util.UUID;

import org.springframework.data.neo4j.repository.Neo4jRepository;
import org.springframework.data.neo4j.repository.query.Query;

/**
 * @author Michael J. Simons
 */
public interface SomeDomainRepository extends Neo4jRepository<SomeDomainObject, UUID> {

	/**
	 * @return Mapping arbitrary, ungrouped results into a dto
	 */
	// language=cypher
	@Query("UNWIND range(1,10) AS x RETURN randomUUID() AS resyncId, tointeger(x*rand()*10)+1 AS counter ORDER BY counter")
	Collection<MyDTO> getAllFlat();

	/**
	 * @return Mapping a single ungrouped result
	 */
	// language=cypher
	@Query("RETURN randomUUID() AS resyncId, 4711 AS counter")
	Optional<MyDTO> getOneFlat();

	/**
	 * @return Mapping a dto plus known domain objects
	 */
	// language=cypher
	@Query("""
			MATCH (u:User {login:'michael'}) -[r:OWNS] -> (s:SomeDomainObject)
			WITH u, collect(r) AS r, collect(s) AS ownedObjects
			RETURN
				u{.*, __internalNeo4jId__: id(u), r, ownedObjects} AS user,
				randomUUID() AS resyncId, 4711 AS counter,u
			""")
	Collection<MyDTO> getNestedStuff();

	/**
	 * @return Mapping nested dtos
	 */
	// language=cypher
	@Query("RETURN 'av' AS outer, {inner: 'bv'} AS nested")
	Optional<A> getOneNestedDTO();
}
```

**Comment by michael-simons** [comment]
Please have a look the linked PR @goldman7911, the change is basically all in the `DefaultNeo4jEntityConverter` and I wrote my idea down in the commit message.

**Comment by goldman7911** [comment]
Amazing @michael-simons !
