### ISSUE TITLE
The @Query has an exception of "Could not find mappable nodes or relationships"

### ISSUE THREAD

**Issue by Lishuaihu-222613** [spring-projects/spring-data-neo4j#2637]
The Java version i used is 1.8, and the spring-data-neo4j is 6.1.5. I get an exctption about the annotation @Query. It said that "Could not find mappable nodes or relationships inside Record<{n: node<24437>}> for org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity@343f5431".
I don't know how to deal it. Please give me some help.
![image](https://user-images.githubusercontent.com/68885929/205443813-f8912c05-2a8e-461e-bda7-2c29f0f93cc0.png)
![image](https://user-images.githubusercontent.com/68885929/205443835-834dc20c-c4cb-460e-902f-2b994c36a417.png)
![image](https://user-images.githubusercontent.com/68885929/205443928-3a0b52a8-3b58-4009-b9bc-57f94e1c50b8.png)

**Comment by meistermeier** [comment]
Thanks for reaching out. Neo4j-OGM 4.0 is not meant to be API (or byte code)-compatible with Spring Data Neo4j 5, that is already out-of-support.
On of the key changes was the removal of the auto index manager feature.

**Comment by meistermeier** [comment]
Sorry for the confusion, I don't know how the comment about Neo4j-OGM 4.0 ended up here.
For your issue: Can you post the `Material` type definition? I assume that the `MaterialInterface` does not match with the defined properties there.

**Comment by michael-simons** [comment]
This is most likely fixed with this change: https://github.com/spring-projects/spring-data-neo4j/commit/adb42ab04038250596ffd3f7d55191f34d22be5b

Any feedback would be nice, otherwise we are gonna close this issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
