### ISSUE TITLE
Issue with graph depth

### ISSUE THREAD

**Issue by Deimrus** [spring-projects/spring-data-neo4j#2659]
Hey all.
I have a simple structure:
![image](https://user-images.githubusercontent.com/38266392/213293321-bb162c13-426c-4057-af39-aea1d1c5ce1f.png)
Cypher query in Browser works as expected but the same query in @Query directive within Neo4jRepository returns just one random underlying node of label ObjectType so instead of getting one Company with two Sites with two ObjectTypes for each Site I got just one ObjectType: 
![image](https://user-images.githubusercontent.com/38266392/213294435-a58b6c76-de70-4469-a664-f80a342f30c2.png)

Neo4jClient returns all the data I need btw.

Is this a bug or I do something wrong?

**Comment by Deimrus** [comment]
Screenshots made on Spring Boot version 3.0.1 and related version of spring-boot-starter-data-neo4j. Also checked it on 2.7.* and 2.6.* with the same results.

**Comment by meistermeier** [comment]
To investigate this, I would need the domain model for the three classes in question.
It _should_ work with repositories. The `Neo4jClient` presents the correct data because it does not inspect the mappings but returns the values from the database _before_ mapping.

**Comment by Deimrus** [comment]
```
@Node
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Company {
    @Id @GeneratedValue
    private Long id;
    private String name;
    @Relationship(type = "IS_IN", direction = Relationship.Direction.INCOMING)
    private Set<Site> sites = new HashSet<>();
}
```
```
@Node
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Site {
    @Id @GeneratedValue
    private Long id;
    private Integer name;
    @Relationship(type = "IS_IN", direction = Relationship.Direction.INCOMING)
    private Set<ObjectType> types = new HashSet<>();
}
```
```
@Node
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ObjectType {
    @Id @GeneratedValue
    private Long id;
    private String name;
}
```

**Comment by Deimrus** [comment]
Also List<Company> findAll(); method without @query returns all the data as expected.

**Comment by Deimrus** [comment]
Yep, result tree as it should be. I think I got the point.

Idk how to thumbs up here but thank you for help.
