### ISSUE TITLE
Embedded Neo4j delete node and Lucene legacy indexing - node_auto_indexing out of sync issue

### ISSUE THREAD

**Issue by Artgit** [spring-projects/spring-data-neo4j#267]
Hello,

I'm struggling with Embedded Neo4j 2.1.7 and Lucene Legacy Indexing. I have described an issue  here http://stackoverflow.com/questions/29478928/embedded-neo4j-delete-node-and-lucene-legacy-indexing-node-auto-indexing-out-o

Could you please help me with this ? How to synchronize legacy index after delete operation ?

**Comment by mangrish** [comment]
Closed. Issue out of date.
