### ISSUE TITLE
Delete all method parsing does not work for related node properties

### ISSUE THREAD

**Issue by danielfedeai** [spring-projects/spring-data-neo4j#2685]
I have two different nodes: components and functions, functions relate to components, both having "entityId" and "tenantId".
I created a repository interface extending Neo4jRepository

What works is a a method: 
List<FunctionNode> findAllByComponentEntityIdAndTenantId(String componentEntityId, String tenantId);
returning a list of functions that have a related component with the given entityId.

What does not work is the same for deleting functions:
Long deleteAllByComponentEntityIdAndTenantId(String componentEntityId, String tenantId);

Looks like the translation to cypher is creating a wrong query.

Spring Data Neo4j Version 6.3.3

**Comment by meistermeier** [comment]
Thanks for reporting this. I can see that the relationship does not get into the _MATCH_ part and the (missing) parameter for the conditional makes the query invalid. Is this also what you are observing?

**Comment by danielfedeai** [comment]
Yes this is what I'm observing.
I grabbed the exception to be sure: 
org.springframework.dao.InvalidDataAccessResourceUsageException: Variable `m_0` not defined (line 1, column 40 (offset: 39))
"MATCH (functionNode:`Function`) WHERE (m_0.entityId = $componentEntityId AND functionNode.tenantId = $tenantId) DETACH DELETE functionNode RETURN count(functionNode)"
                                        ^; Error code 'Neo.ClientError.Statement.SyntaxError'; nested exception is org.neo4j.driver.exceptions.ClientException: Variable `m_0` not defined (line 1, column 40 (offset: 39))

**Comment by meistermeier** [comment]
Thanks for the confirmation. The bug will be fixed in the next release cycle, starting with 6.3.9.
