### ISSUE TITLE
Test against Java 20 in CI.

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-neo4j#2701]

**Comment by michael-simons** [comment]
Do you need input from us on that one @gregturn ?

**Comment by gregturn** [comment]
I took at shot at pushing a Jenkins update that would run on Java 20, but it failed twice. You can see the latest one at https://jenkins.spring.io/blue/organizations/jenkins/spring-data-neo4j/detail/main/1245/pipeline/ (let me know if you can't).

The details are in the latest commit on https://github.com/spring-projects/spring-data-neo4j/tree/issue/java20. (I had to test it on the main branch, but pulled back from that and moved the work to this side branch).

I'm frankly not certain WHAT is causing the grief.

FYI: I have been using this version of Java 20 locally for test purposes.
```
Temurin       | >>> | 20           | tem     | installed  | 20-tem            
```
If you wish to run the test suite locally against `Temurin 20-tem`, perhaps there would be clearer insight into what's actually broken.

**Comment by michael-simons** [comment]
My analysis of this: In `ReactiveImmutableAssignedIdsIT` we do have the following entity callback defined:

```java
@Bean
ReactiveBeforeBindCallback<ImmutablePersonWithAssignedId> valueChange() {
	return entity -> {
		entity.someValue = SOME_VALUE_VALUE;
		return Mono.just(entity);
	};
}
```

matching `ImmutablePersonWithAssignedId`.

The failure occurs when persisting a `ImmutableSecondPersonWithAssignedId`. 

`org.springframework.data.mapping.callback.DefaultReactiveEntityCallbacks.DefaultReactiveEntityCallbackInvoker` has a method `invokeCallback` that catches a `ClassCastException` when `org.springframework.data.mapping.callback.EntityCallbackDiscoverer#computeCallbackInvokerFunction` discovered a callback that does not match the actual entity type.

Sorry for the screenshots, but that's easier to reformat the reactive stack traces here. This is the stack for JDK 17 when ending up in this case:

![image](https://user-images.githubusercontent.com/526383/229089259-f05a7f6a-795d-43a6-970b-962f688cb826.png)
 
JDK 20 acts totally different

![image](https://user-images.githubusercontent.com/526383/229089466-e70e715c-3a02-4fdb-b088-60b6d273180b.png)

I am unsure if Spring Data Commons must fix this in `org.springframework.util.ReflectionUtils#invokeMethod(java.lang.reflect.Method, java.lang.Object, java.lang.Object...)` or in `org.springframework.data.mapping.callback.DefaultReactiveEntityCallbacks` but I am sure that this is not a SDN but an Spring Data Commons issue.

cc @mp911de

**Comment by michael-simons** [comment]
@gregturn I don't think its Project reactor. It's the `DefaultReactiveEntityCallbackInvoker`. It catches only `ClassCastException` commented whereas `SimpleEntityCallbackInvoker` catches `IllegalArgumentException | ClassCastException ex`, see linked ticket.

**Comment by gregturn** [comment]
Thanks @michael-simons. We've since solved this, and I've verified building Spring Data Neo4j against Java 20.
