### ISSUE TITLE
Use an official JTA API dependency rather than Geronimo's

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-data-neo4j#272]
For better alignment with the rest of Spring IO Platform, can you please update your JTA API dependency to use the official artifact in 3.3.x and master? Either `javax.transaction:transaction-api:1.1-rev1` or `javax.transaction:javax.transaction-api:1.2`. The latter is preferred.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-data-neo4j/commit/20d103f6cd77e31dcdfdf62131331c3d29236d82 moved to `javax.transaction:transaction-api:1.1-rev1` but `javax.transaction:javax.transaction-api:1.2` is still preferable from a Spring IO Platform perspective.

**Comment by olivergierke** [comment]
I've filed and fixed https://jira.spring.io/browse/DATAGRAPH-664.
