### ISSUE TITLE
Relationships not stored/deleted on update of node (Release >=7.1.0)

### ISSUE THREAD

**Issue by rainerfriesen** [spring-projects/spring-data-neo4j#2728]
After updating to Spring Boot Starter 3.1.0 (--> Spring Boot Starter Neo4j 7.1.0) the save or update of  #nodes that have relationships leads to a deletion of existing relationships on the updated node and new relationships   ##not being saved. Prior to 7.1.0 that was working as expected.

## Expected Result:
The TestEntity1 is stored with a relation to TestEntity2 (stored as well)

## Actual Result:
TestEntity1 and TestEntity2 are stored on the DB but no relation is created. (Previous existing relations would have been removed, not shown in test)

### Example  Entities:
```
@Node
public class TestEntity1 {

    @Id
    @GeneratedValue
    private Long id;

    @Property("value_one")
    private String valueOne;

    @Relationship("related_to")
    private TestEntity2 relatedEntity;

    public TestEntity1(Long id, String valueOne, TestEntity2 relatedEntity) {
        this.id = id;
        this.valueOne = valueOne;
        this.relatedEntity = relatedEntity;
    }
    public Long getId() {
        return id;
    }

    public TestEntity2 getRelatedEntity() {
        return relatedEntity;
    }
}
```

```
@Node
public class TestEntity2 {

    @Id
    @GeneratedValue
    private Long id;

    @Property("valueTwo")
    private String valueTwo;

    public TestEntity2(Long id, String valueTwo) {
        this.id = id;
        this.valueTwo = valueTwo;
    }
}
```

### Repository:
```
public interface TestEntity1Repository extends Neo4jRepository<TestEntity1, Long> {
}
```

### Test (using TestContainers):
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")
class TestEntity1IT extends IntegrationTestBase {

    @Autowired
    private TestEntity1Repository testEntity1Repository;

    @Test
    public void test() {
        TestEntity2 t2 = new TestEntity2(null, "v2");
        TestEntity1 t1 = new TestEntity1(null, "v1", t2);

        TestEntity1 result = testEntity1Repository.save(t1);

        TestEntity1 freshRetrieved = testEntity1Repository.findById(result.getId()).get();

        Assertions.assertNotNull(result.getRelatedEntity());
        Assertions.assertNotNull(freshRetrieved.getRelatedEntity()); // FAILS!
    }

}
```

**Comment by meistermeier** [comment]
Thanks for reporting this. Seems to be a problem but needs further investigation.
In the mean time, you could change the Cypher-DSL configuration to enforce the NEO4J_5 dialect like mentioned here: https://github.com/spring-projects/spring-data-neo4j/issues/2729#issuecomment-1563853038
Since I just came to this issue after looking at the other one, I did not change the configuration and it works as expected.

**Comment by michael-simons** [comment]
Thanks from my side as well, @rainerfriesen for the good reports!
