### ISSUE TITLE
String ID different on save / fetch (Release 7.1.0)

### ISSUE THREAD

**Issue by rainerfriesen** [spring-projects/spring-data-neo4j#2729]
After updating to Spring Boot Starter 3.1.0 (--> Spring Boot Starter Neo4j 7.1.0) the save operation using a node with String ID is given different IDs after save or fetch.

## Expected Result:
The TestEntity1 save operation returns a bean having an equal ID to the very same entity fetched from DB

## Actual Result:
IDs are different, e.g. "4:59a52f34-f5f5-4c8a-aff3-a9ff6183e6c3:2113" vs "2113"

### Example  Entities:
```
@Node
public class TestEntity1 {

    @Id
    @GeneratedValue
    private String id;

    @Property("value_one")
    private String valueOne;

    public TestEntity1(String id, String valueOne) {
        this.id = id;
        this.valueOne = valueOne;
    }

    public String getId() {
        return id;
    }
}
```

### Repository:
```
public interface TestEntity1Repository extends Neo4jRepository<TestEntity1, String> {
}
```

### Test (using TestContainers):
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")
class TestEntity1IT extends IntegrationTestBase {

    @Autowired
    private TestEntity1Repository testEntity1Repository;

    @Test
    public void test() {
        TestEntity1 t1 = new TestEntity1(null, "v1");

        TestEntity1 result = testEntity1Repository.save(t1);

        List<TestEntity1> allTest1s = testEntity1Repository.findAll();

        Assertions.assertEquals(1, allTest1s.size());
        Assertions.assertEquals(result.getId(), allTest1s.get(0).getId()); // FAILS!
    }

}
```

**Comment by michael-simons** [comment]
Hey @rainerfriesen 

This works as expected, please see: https://github.com/spring-projects/spring-data-commons/wiki/Spring-Data-2023.0-%28Ullman%29-Release-Notes#stop-using-neo4js-internal-id-function-unless-required-by-the-domain-model

I am a bit surprised that `@Id @GeneratedValue String something` did actual convert the internal long id to a string. 

You can have the old long ids by using an actual long value and convert later down.

I am sorry for the inconvenience and we would have that communicated better if I had realised that the converter kicks on making strings out of longs.

More information:

https://github.com/spring-projects/spring-data-neo4j/commit/d8bff18b22d82e09beca894465aa2c04a5ecfe85

**Comment by meistermeier** [comment]
FWIW: Cypher-DSL uses the default dialect (also supporting Neo4j 4.4) which does the id calls, Michael mentions.
If you really really want to see elementIds, you have to define the Cypher-DSL dialect to `NEO4J_5`
Basically it is just overriding the config function in `AbstractNeo4jConfig` but as a consequence you have to pass-through the Neo4j driver instance.
(This could be any `@Configuration` not just the application itself, I just wrote this down from the top of my head)
```
@SpringBootApplication
public class Gh2729Application extends AbstractNeo4jConfig {

	@Autowired
	Driver driver;

	public static void main(String[] args) {
		SpringApplication.run(Gh2729Application.class, args);
	}


	@Override
	public Driver driver() {
		return driver;
	}

	@Override
	public Configuration cypherDslConfiguration() {
		return Configuration.newConfig().withDialect(Dialect.NEO4J_5).build();
	}
}
```

**Comment by rainerfriesen** [comment]
Hi @michael-simons & @meistermeier for your quick feedback. That's highly appreciated. 

I just want to highlight that I'm mainly confused that the value is in both beans of type String but the content is different: "4:59a52f34-f5f5-4c8a-aff3-a9ff6183e6c3:2113" vs "2113". I'm not quite sure if the trailing 2013 in the first String is just by coincidence the "2013" of the fresh loaded bean, but that wasn't expected. 

Actually we are not using the ID field at all in our application, I just stumbled upon that difference while investigating #2728

**Comment by meistermeier** [comment]
Depends on your definition of coincidence ;)
At the moment in Neo4j it _is_ the id. Pseudo equation: `elementId(node).split(":")[2] == toString(id(node))`
But you should never assume this for the future because elementId is more a "String with blackbox content".
