### ISSUE TITLE
Cannot able to store Relationships between nodes using @RelationshipProperties and  Neo4jTemplate

### ISSUE THREAD

**Issue by Kanish2002** [spring-projects/spring-data-neo4j#2739]
Movie.kt
```
import org.springframework.data.neo4j.core.schema.Id
import org.springframework.data.neo4j.core.schema.Node
import org.springframework.data.neo4j.core.schema.Relationship

@Node
data class Movie(
    @Id
    val title: String,

    var released: Int,

    @Relationship(type = "ACTED_IN", direction = Relationship.Direction.INCOMING)
    val actors : List<Actor>,

)

```

Person.kt
```
import org.springframework.data.neo4j.core.schema.Id
import org.springframework.data.neo4j.core.schema.Node

@Node
data class Person(
    @Id val name: String,
    )
```

Actor.kt
```
import org.springframework.data.neo4j.core.schema.RelationshipId
import org.springframework.data.neo4j.core.schema.RelationshipProperties
import org.springframework.data.neo4j.core.schema.TargetNode

@RelationshipProperties
data class Actor(
    @RelationshipId
    val id: Long,
    @TargetNode
    val person: Person,
    val roles: List<String>
)

```
Main.kt

```
val person = Person("Kanish")
val actor = Actor(1, person, listOf("director"))
val movie = Movie("Movie",2002, mutableListOf(actor))
neo4jTemplate!!.saveAll(listOf(actor,movie,person))
```

While saving this I got the output in the database like this
![image](https://github.com/spring-projects/spring-data-neo4j/assets/35307799/07918606-2c12-489d-9e5f-a97920324352)

Can someone help me out how to solve this ?

**Comment by meistermeier** [comment]
Thanks for reaching out to us.
I assume that you are using the latest release version 7.1.0, right?
There was a change in the handling of ids that made the need for configuring the Cypher-DSL to use the Neo4j 5 dialect necessary. We mitigated this for the upcoming patch (planned Friday this week) in https://github.com/spring-projects/spring-data-neo4j/issues/2728
But defining the dialect is also advised now to make the Cypher-DSL use the new function for id handling (`elementId`) e.g. for creating relationships.
```
@Configuration
public class SomeConfigurationClass {
  /** other configuration things **/
  @Bean
  public Configuration cypherDslConfiguration() {
	return Configuration.newConfig().withDialect(Dialect.NEO4J_5).build();
  }
}
```

I am closing this issue now and pinned the original issue report. If there is anything wrong with my assumption, feel free to re-open your issue.

**Comment by meistermeier** [comment]
Correct (both).
But you could also add the configuration above because in the long term there might be additional changes in Neo4j 5 Cypher that we make use of in the Cypher-DSL.

**Comment by Kanish2002** [comment]
Hi @meistermeier 
while using @GeneratedValue  Annotation for  Id I'm getting the same issue like while  trying to create relationships..
Nodes are not connected with relationships.. you said about elementId() method right, do i need to use explicitly ?


now I'm sharing my code here.. If possible help me with this.. 
```
@Node
data class Starter(
    @Id @GeneratedValue
    private val id: Long,
    private val name: String,
    @Relationship(type = "INITIATES", direction = Relationship.Direction.OUTGOING)
    private val Retriever: Retriever
)
```
![image](https://github.com/spring-projects/spring-data-neo4j/assets/35307799/1669057d-3119-4ff3-ad78-9ef0e578b62b)
The seperated nodes are the ones I get when I use annotation @GeneratedValue and the one on the right(correct graph) is the one without @GeneratedValue...

Thanks..

**Comment by Kanish2002** [comment]
Hi @meistermeier, yeah I'll try with String instead of Long, Actually I'm using a Spring Data Neo4j Starter Dependency and it uses 6.3.12 version.

**Comment by Kanish2002** [comment]
Hi is there any solution to map a generated internal long id of neo4j using @Id and @GeneratedValue in 6.3.12 version

**Comment by michael-simons** [comment]
It just works. 

`@Id @GeneratedValue long fieldName`.

**Comment by Kanish2002** [comment]
Yeah actually just now I figured out that, because of default value passed while creating Object for Nodes the internal Id's collapsed mapping relationships.. after making it as a `Long?` nullable in kotlin and removing it from constructor it works fine.

**Comment by michael-simons** [comment]
Thanks a lot for your feedback @Kanish2002
