### ISSUE TITLE
Fail to use map of nodes as custom query param

### ISSUE THREAD

**Issue by rogelio-o** [spring-projects/spring-data-neo4j#2791]
We are saving a large list of nodes in Neo4j with many edges. Instead of defining the relationship as part of the node, we are saving all the nodes first and then all the edges with the Cypher query below. This reduces the number of calls to DB to 2 and improves the performance.

```
@Query("""
        UNWIND keys($relationships) as sourceId
        UNWIND $relationships[sourceId] as relationship
        MATCH
          (source:`package` {id: sourceId}),
          (target:`package` {id: relationship.__target__.__id__})
        MERGE (source)-[r:DEPENDS_ON]->(target)
        SET r += relationship.__properties__
      """)
  Mono<Void> mergeRelationships(@Param("relationships") Map<String, List<PackageRelationshipProperties>> relationships);
```

However, it does not work because entities are converted only when they are in a list, not in a map (and, of course, not in a map of lists). This happens [here](https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/repository/query/Neo4jQuerySupport.java#L190).

A perfect solution would be to reduce the number of queries to 2 in the `saveAll` method. However, if this is not possible, supporting the conversion of entities recursively will solve the problem.

**Comment by meistermeier** [comment]
There is now a _7.1.5-GH-2791-SNAPSHOT_ available in the Spring snapshot repo.
It adds the map(list(entity)) support as parameters.
Would be great to get feedback on this one.
Don't forget to add the snapshot (and milestone) repositories.
```
<repositories>
  <repository>
    <id>spring-milestones</id>
    <name>Spring Milestones</name>
    <url>https://repo.spring.io/milestone</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>spring-snapshots</id>
    <name>Spring Snapshots</name>
    <url>https://repo.spring.io/snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
  </repository>
</repositories>
```

**Comment by rogelio-o** [comment]
It works perfectly. Thanks for the quick solution!

**Comment by meistermeier** [comment]
Thank you for the swift feedback 🙇 
Will merge this next week for the coming 7.1.x version.
