### ISSUE TITLE
org.springframework.data.mapping.PropertyReferenceException: No property 'test' found for type 'Movie'

### ISSUE THREAD

**Issue by tengfei8771** [spring-projects/spring-data-neo4j#2792]
when I declare a customer repository and use jpaData alway thorw exception like this 'No property 'test'(This is the method I defined in the repository) found for type 'Movie(this is my node)''.

```
@Data
@Node(labels = "movie")
public class Movie {
    @Id
    @GeneratedValue
    private Long id;
    @Property
    private String name;
    @Property
    private String publishYear;
    @Property
    private String info;
    @Property
    private Integer duration;
    @ApiModelProperty(hidden = true)
    @Relationship(type = "ACT_IN")
    private List<Relation> actors=new ArrayList<>();
    @ApiModelProperty(hidden = true)
    @Relationship(type = "DIR")
    private List<Relation> directors=new ArrayList<>();
    //private String test;// If there is no such field, an exception will be thrown
}

public interface MovieRepository extends Neo4jRepository<Movie,Long> {
    void test(@Param("relation") RelationVo relationVo);
}

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="com.example.JavaWebApi.mapper.neo4j.MovieRepository">
    <resultMap id="BaseResultMap" type="com.example.JavaWebApi.model.neo4j.node.Movie">
        <id column="id" property="id" />
    </resultMap>
    <insert id="test" >
        MATCH (m:movie),(n:person) where id(m)=?#{#relation.startNode} and id(n)=?#{#relation.endNode} Create (m)-[r:?#{#relation.relation}]->(n) RETURN m,n,r
    </insert>
</mapper>
```

**Comment by meistermeier** [comment]
Thanks for reaching out.
I don't think that I get what you are asking for, or understand the direction you are coming from.
The entity class looks fine. As does the repository, besides the `test` method but we come to this in a bit.
The XML is some MyBatis mapping that is not supported in Spring Data Neo4j. The referring repository method would not execute the query defined there.
To get you started, you could extract this into a `neo4j-named-queries.properties` file (like here https://github.com/spring-projects/spring-data-neo4j/blob/78bb07356bd6d646bbc08ad1adcb1509c51ab655/src/test/resources/META-INF/neo4j-named-queries.properties#L17-L16) and define the method similar to yours in the repository (https://github.com/spring-projects/spring-data-neo4j/blob/64854c515570398481f9685e68c6bba061a468a5/src/test/java/org/springframework/data/neo4j/integration/imperative/repositories/PersonRepository.java#L106).
Alternatively you could add the query in a `@Query("MATCH (m....))"` annotation above the custom query method. What does not work is to use arbitrary objects as parameters. You could either directly provide two parameters for the start and the end id, or traverse from an `@Node` annotated entity (and use its id) to the relationship's target id. (described here: https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-queries.parameters).
I assume using two parameters (and e.g. unwrap the `RelationVo` before calling the repository method) might be the easiest solution in your case.

**Comment by tengfei8771** [comment]
thank you.But how I build dynamic conditions query? For example,I have a base query like this : 'MATCH (n:persn) return n' and I have two conditions : name and age. If name is not empty I want get query 'MATCH (n:persn) where n.name=#{#name} return n' and if age is not null I want 'MATCH (n:persn) where n.age=#{#age} return n' both is not null  I want MATCH (n:persn) where n.name=#{#name} and n.age=#{#age} return n'  How to implement the above statement? Thank you

**Comment by meistermeier** [comment]
I think what you are looking for is _QueryByExample_ https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-by-example
This would avoid the need for more custom methods and would also fetch the related data automatically.

**Comment by tengfei8771** [comment]
thank you very much.

**Comment by meistermeier** [comment]
Glad that it helped. I will close this now. If there is anything related, feel free to re-open this issue.
