### ISSUE TITLE
Call to id instead of elementId for assigned ids

### ISSUE THREAD

**Issue by meistermeier** [spring-projects/spring-data-neo4j#2809]
Given the right Cypher dialect for `NEO4J_5` was set, Spring Data Neo4j will still produce `id` calling queries and it might not be needed to do so.
```
UNWIND $__relationships__ AS relationship WITH relationship
MATCH (startNode:`Game`) WHERE startNode.appId = relationship.fromId
MATCH (endNode) WHERE **id(endNode)** = relationship.toId 
MERGE (startNode)-[relProps:`CATEGORIES`]->(endNode) RETURN elementId(relProps) AS __elementId__
```

For the parameters this line https://github.com/spring-projects/spring-data-neo4j/blob/52535f37f5a5d5a2cce4fbdd9d3504a1b07dacb0/src/main/java/org/springframework/data/neo4j/core/TemplateSupport.java#L430 makes elementIds for assigned ids not usable in generated queries for relationships.
The statement `targetEntity.isUsingInternalIds()` resolves to `false` and will always trigger the id fallback for https://github.com/spring-projects/spring-data-neo4j/blob/52535f37f5a5d5a2cce4fbdd9d3504a1b07dacb0/src/main/java/org/springframework/data/neo4j/core/Neo4jTemplate.java#L828

The query generator side
https://github.com/spring-projects/spring-data-neo4j/blob/52535f37f5a5d5a2cce4fbdd9d3504a1b07dacb0/src/main/java/org/springframework/data/neo4j/core/mapping/CypherGenerator.java#L530
or to be more precise the logic inside https://github.com/spring-projects/spring-data-neo4j/blob/52535f37f5a5d5a2cce4fbdd9d3504a1b07dacb0/src/main/java/org/springframework/data/neo4j/core/mapping/CypherGenerator.java#L479-L491
has the same behaviour.

I don't know the reason why I decided to go this route and this needs some deeper analysis of why this is happening.

Thanks to @pbauerochse for reporting this.

**Comment by meistermeier** [comment]
Version for testing: `7.2.0-GH-2809-SNAPSHOT`

```
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
```

**Comment by pbauerochse** [comment]
Seems to be fixed with your snapshot version. Thanks Gerrit
