### ISSUE TITLE
Traversing Graphs

### ISSUE THREAD

**Issue by Kanish2002** [spring-projects/spring-data-neo4j#2815]
Hi @meistermeier I'm creating graph using models with @Relationship annotation as it goes nested..
using Neo4jRepository I'm retrieving the graph from DB in memory using repo features like findBy......().

Is there any way to traverse these graph in memory in a efficient way..

```
@Node
class SStarter(
    @Id @GeneratedValue(UUIDStringGenerator::class)
    var id: String?,
    val sName: String,
    @Relationship(type = "RETRIEVES", direction = Relationship.Direction.OUTGOING)
    var dataRetriever: List<DataRetriever>
) {
    @PersistenceCreator
    constructor(sName: String, dataRetriever: List<DataRetriever>) : this(null, strategyName, dataRetriever)
}

@Node
class DataRetriever(
    var DataRetrieverName: String,
    var DataSource: String,
    @Relationship(type = "DATA_COLLECTED_BY", direction = Relationship.Direction.OUTGOING)
    val dataCollector: DataCollector
)
```

As of now I'm traversing it like 
val starter = findBySName()
val dataRetriever = starter.dataRetriever
.
.
. and so on..

Can you suggest me any ways of doing it.

**Comment by meistermeier** [comment]
I am pretty sure that I don't understand what you are aiming for.
Could you maybe explain this a little bit more?

What SDN (with the Neo4j driver) does is to map the incoming (driver) record to an object and, if it has relationships and related nodes, instantiate and link/map the relationships. As a result you get a Java object graph, in your case, starting with `SStarter` as the entry node for traversal. Walking through the relationship properties is the only way to access the related nodes (and their properties).

**Comment by Kanish2002** [comment]
Yeah actually I'm searching that if SDN has any feature retrieving graphs and traversing it in a generic way..
something like the CypherDSL?
but now I'm working fine with accessing relationships and getting into linked nodes (traversing).

**Comment by meistermeier** [comment]
No, there isn't such a feature in SDN.
Spring Data in general is pretty much pre-defined entity oriented. This is good and avoids creation (and with this memory allocation) of intermediate instances. If I got you right, this is exactly what you were looking for in your case.
I am closing this issue now because you said, that you solved your problem with another approach.
