### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null

### ISSUE THREAD

**Issue by jeanchristophecascade** [spring-projects/spring-data-neo4j#2818]
Dear Team,

The NPE is raised here: 

https://github.com/spring-projects/spring-data-neo4j/blob/e4f034858a58eadf2bc21beeb8f29ecb6e3bb340/src/main/java/org/springframework/data/neo4j/core/ResultSummaries.java#L120

It seems there's no guard on notification.position() being null while according to the driver java doc it should returns " the position in the query where the issue was found, or null if no position is associated with this notification": 

https://github.com/neo4j/neo4j-java-driver/blob/fbdd1ad25dbc6a58e2cbd7c505377eb6873cee74/driver/src/main/java/org/neo4j/driver/summary/Notification.java#L52

Many thanks for your great work.

Jean-Christophe

**Comment by michael-simons** [comment]
Hi Jean-Christophe,

in case this is related to that question:

https://stackoverflow.com/questions/77417303/memgraph-with-spring-data-neo4j

The driver Spring Data Neo4j uses does not give any guarantees to work with other products than Neo4j 4 and 5. this is not a bug and the driver works as intended against neo4j. 

if this happens agains Neo4j, please open up a ticket for our colleagues from the drivers team here https://github.com/neo4j/neo4j-java-driver/issues

Thanks for your understanding,
Michael.

**Comment by jeanchristophecascade** [comment]
Fair enough ;-) Thanks for your quick response Michael.

**Comment by michael-simons** [comment]
No worries and maybe you find time to try out Neo4j at some point.
