### ISSUE TITLE
Is there any possible way to set constraints like it is mentioned in Neo4j Migrations, is it possible in SDN 7.1.1 (@Unique , @Required, @Index) ?

### ISSUE THREAD

**Issue by Kanish2002** [spring-projects/spring-data-neo4j#2836]

**Comment by meistermeier** [comment]
What source are you referring to when you mention _[...]constraints like it is mentioned in Neo4j Migrations_ ?
Besides this, there is no plan to bring this feature into SDN itself. This is what Neo4j-Migrations is meant to be used for.

**Comment by meistermeier** [comment]
You are probably referring to this section in the documentation, right? https://michael-simons.github.io/neo4j-migrations/2.7.0/#appendix_annotation
Those annotations are provided by Neo4j-Migrations and also it is part of Neo4j-Migration's annotation processor to derive the catalog.

**Comment by meistermeier** [comment]
SDN does not have any knowledge about those annotations. It is all up to Neo4j-migrations to decide what to do with them.
If the question is "just" about the *6* in the word _SDN 6_, you are correct.
This is basically a pointer to say there was a time prior _SDN 6_ that means SDN(5-)/Neo4j-OGM and now there is the "new" SDN what is referred to as _SDN 6_ to make it clear that it applies to the newer versions of SDN incl. SDN 7. Raising a ticket in neo4j-migrations for documentation would in this case makes sense.
Does this answer your question?
