### ISSUE TITLE
Make Neo4jRepositoryFactory public

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects/spring-data-neo4j#2857]
Would it be possible to make the class [Neo4jRepositoryFactory](https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/repository/support/Neo4jRepositoryFactory.java) public so that it can be used with customized Spring configurations, similarly to its "counterpart" [JpaRepository](https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/JpaRepository.java) ?

**Comment by meistermeier** [comment]
I am not sure, I can follow. Why should the `Neo4jRepositoryFactory` be public, and not-as mentioned in your post regarding Jpa- the already public [Neo4jRepository](https://github.com/spring-projects/spring-data-neo4j/blob/main/src/main/java/org/springframework/data/neo4j/repository/Neo4jRepository.java) be used?

**Comment by ilgrosso** [comment]
@meistermeier the idea is to replicate something like https://github.com/apache/syncope/blob/master/core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/PersistenceContext.java#L470-L474 with neo4j.

**Comment by ilgrosso** [comment]
Incidentally, having `Neo4jRepositoryFactory` declared as `final` does not allow to override methods like `getRepositoryBaseClass()` which are usually very useful to override, at least for JPA.

**Comment by meistermeier** [comment]
You can already define your own BaseClass with this method: https://docs.spring.io/spring-data/neo4j/reference/repositories/custom-implementations.html#repositories.customize-base-repository
(The documentation is included from Spring Data commons `s/Jpa/Neo4j/g` should just work fine here ;) )
From my perspective this is the nicer approach than just overriding / extending classes and methods.

**Comment by ilgrosso** [comment]
> From my perspective this is the nicer approach than just overriding / extending classes and methods.

I agree it is nicer, but unfortunately only applicable if you can afford `@EnableNeo4jRepositories`, which is not my case.

**Comment by meistermeier** [comment]
We discussed this in the team and think that we found a suitable option without making the class public.
The idea is to make this method
https://github.com/spring-projects/spring-data-neo4j/blob/084620e92fff97efc129787c0f9c8ca99a81328b/src/main/java/org/springframework/data/neo4j/repository/support/Neo4jRepositoryFactory.java#L120-L123
not return the fixed value of `SimpleNeo4jRepository.class` anymore but there will be an additional field in this class that gets set here
https://github.com/spring-projects/spring-data-neo4j/blob/084620e92fff97efc129787c0f9c8ca99a81328b/src/main/java/org/springframework/data/neo4j/repository/support/Neo4jRepositoryFactoryBean.java#L64-L68

In this case, only the custom base repository needs to be declared in the bean config.
WDYT?

**Comment by ilgrosso** [comment]
The proposed approach would definitely solve the issue of setting a custom base repository other than `SimpleNeo4jRepository`.
So, I would be fine from the `final` side of issue.

The `public` side, however, remains unchanged: I would stil be unable to create my own `Neo4jRepositoryFactory` bean definition until such class is not made public (as this issue title says).

**Comment by ilgrosso** [comment]
I really don't see why making the class public (as its jpa counterpart) could make so much damage.

Anyway, I already have a workaround in place, I was just hoping not to use it, and to keep our neo4j module aligned with jpa. Nevermind.

**Comment by michael-simons** [comment]
Well ok. If you had explained what the workaround does in addition to the solution we suggested, we might have had been able to solve your actual problem. Thanks for taking your time though.

**Comment by ilgrosso** [comment]
I realize you do not believe this is the truth, but my **actual** issue is being able to declare each single repository as separate bean definition, as I am pointing out above, in the same way we are already doing for JPA.
[For example](https://github.com/apache/syncope/blob/master/core/persistence-jpa/src/main/java/org/apache/syncope/core/persistence/jpa/PersistenceContext.java): 

```java
    @ConditionalOnMissingBean
    @Bean
    public JpaRepositoryFactory jpaRepositoryFactory(final EntityManager entityManager) {
        return new JpaRepositoryFactory(entityManager) {

            @Override
            protected Class<?> getRepositoryBaseClass(final RepositoryMetadata metadata) {
                return SyncopeJPARepository.class;
            }
        };
    }

...

    @ConditionalOnMissingBean
    @Bean
    public AnyTypeDAO anyTypeDAO(
            final JpaRepositoryFactory jpaRepositoryFactory,
            final AnyTypeRepoExt anyTypeRepoExt) {

        return jpaRepositoryFactory.getRepository(AnyTypeRepo.class, anyTypeRepoExt);
    }
```

The rationale behind this approach is that such bean definitions can go override by product extensions or single delivery projects, hence we simply cannot rely on the "implicit" `@EnableJpaRepositories` / `@EnableNeo4jRepositories` way.

As you can see from the JPA snippet above, in order to replicate that with Neo4j I'dd need that `Neo4jRepositoryFactory` is public as `JpaRepositoryFactory` is public.

Since this does not seem to be possible, I have defined a public class in our source tree, under the same package as `Neo4jRepositoryFactory` implementing the delegate design pattern. This is my workaround.
Unfortunately I am unable to link to the source code directly since I am still evaluating wheter providing an alternative, Neo4j-based, persistence layer for Apache Syncope is feasible at all or not.

I hope this clarifies.
