### ISSUE TITLE
Request: @Label annotation to map labels to a field

### ISSUE THREAD

**Issue by renatodinhani** [spring-projects/spring-data-neo4j#288]
In my domain, node labels are created dinamically, so I can't map each type of node to a Java class. 

Currently I am using a single class to represent nodes because they have the same attributes, even if they are of different types.

I'd like to map the one or more node labels to a field in my class, but I did not find a way to do this. I was expecting an annotation ```@Label ``` to do this.

Currently I am not able to use OGM because I can't create a class for each type of existing node.

Am I missing something or the ability to map labels to fields does not exist? 
Is this that I am asking something that makes sense?

**Comment by jexp** [comment]
There is an `@Labels Collection<String> labels` annotation for that.

**Comment by renatodinhani** [comment]
Yes, the ```@Labels``` annotation is what I need. The reason I did not found it is because I am using SDN4 M1 and it was not ported, at least to M1.

I use labels to tag different concepts in the database. For example, my domain is about games, so I have labels named "Platform", "Game", "Company", etc. 

All concepts share the same attributes, so I don't need to create a class for each one, a field called "type" is enough. OR if the concepts I have were static, I could create a class for each one inheriting from a base class, but the difference is that I want to be able to create new labels/concepts in the database without the need to creating a new Java class for each new concept.

As I said, the ```Labels``` annotation solves my problem. It will be ported to SDN4?

**Comment by monowai** [comment]
Hi @renatodinhani - is this still an issue?

**Comment by renatodinhani** [comment]
@monowai I think so, but only in SDN4. I think in SDN3 it is working.

I don't know about DynamicProperties.

**Comment by vince-bickers** [comment]
Dynamic Labels and Dynamic Properties are not currently supported in SDN 4. There is some debate over whether they should be, what the technical and performance constraints might be if we were to add them, or whether there's actually a better way to handle use cases like yours, where you effectively want an infinitely flexible mapping from the graph to your POJOs.

**Comment by monowai** [comment]
DynamicProperties can probably be worked around, but @Labels is a little more troublesome for the use case renatodinhani mentions above - which I also share. The constraint of having to physically create a class for every Label seems to go against the dynamic nature of Neo4j so I hope this feature gets some traction. 

JEXP's comment "Perhaps then a static OGM like SDN might not be the best choice." would have been useful had the Labels feature never been present in v3. Working with SDN for so long and then finding that it is changing so fundamentally makes migration an unwelcome conundrum. What helps are guidelines on how to achieve functional equivalence without working against the framework.

**Comment by luanne** [comment]
Now tracked in the OGM project https://github.com/neo4j/neo4j-ogm/issues/159
