### ISSUE TITLE
@RelationshipProperties not persisted

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects/spring-data-neo4j#2885]
On spring-data-neo4j 7.2.4 (Spring Boot 3.2.4) and JDK 21, using Docker image 2.7.18.

My original need was to maintain sorted in insertion order the relationship collections as the `commands` sample below:

```java
@Relationship(type = MACRO_TASK_COMMANDS_REL, direction = Relationship.Direction.OUTGOING)
private List<Neo4jImplementation> commands = new ArrayList<>();
```

I have learned, however, that this cannot be guaranteed, and using `SortedSet` and implementing `Comparable` was the suggested way of achieving my goal.

So I turned the relationship collection as above into

```java
@Relationship(type = MACRO_TASK_COMMANDS_REL, direction = Relationship.Direction.OUTGOING)
private SortedSet<Neo4jMacroTaskCommand> commands = new TreeSet<>();
```

where

```java
@RelationshipProperties
public class Neo4jMacroTaskCommand implements Comparable<Neo4jMacroTaskCommand> {

    @RelationshipId
    private final String id;

    private int index;

    @TargetNode
    private Neo4jImplementation command;

    public Neo4jMacroTaskCommand(final int index, final Neo4jImplementation command) {
        this.id = UUID.randomUUID().toString();
        this.index = index;
        this.command = command;
    }
    
    public int getIndex() {
        return index;
    }

    @Override
    public int compareTo(final Neo4jMacroTaskCommand object) {
        return Integer.compare(index, object.getIndex());
    }
}
```

With this new layout, no relationship is persisted at all.

Essentially, I am in the same situation as https://stackoverflow.com/questions/76730323/issue-with-spring-data-neo4j-relationshipproperties-not-saving-properly-using-sp which is unanswered.

I examined the debug logs and found actually no cypher statements that resembled to persist the relationship as above.
Other relationships defined in the same node entity are regularly persisted, as it used to work with original relationship collection definition.

I have also tried with

```java
    @RelationshipId
    private final Long id;
```

but with same results.

Am I missing something?

**Comment by meistermeier** [comment]
The problem within your code is the usage of
```
this.id = UUID.randomUUID().toString();
```
There is no deterministic behaviour in SDN when a custom id is used in relationship properties.
Of course, you can still use this on an additional property but the `@RelationshipId` must not been set manually.
Otherwise SDN assumes that this is an existing relationship and only wants to update its properties.

**Comment by ilgrosso** [comment]
Thank you for your answer @meistermeier 

It seems to work as expected now, thank you!
