### ISSUE TITLE
@QueryResult POJO conversion skips inherited fields

### ISSUE THREAD

**Issue by fbiville** [spring-projects/spring-data-neo4j#289]
I just checked the codebase further to this [SO question](http://stackoverflow.com/questions/30347451/how-to-correctly-implement-class-inheritance-annotated-as-queryresult-in-java/30348554#30348554).

It seems to me the [current conversion service](https://github.com/spring-projects/spring-data-neo4j/blob/3.3.0.RELEASE/spring-data-neo4j/src/main/java/org/springframework/data/neo4j/support/conversion/EntityResultConverter.java#L101) is skipping inherited fields.

The whole hierarchy should be scanned for annotated fields.

This behavior has been around at least since `2.3.5.RELEASE`.

**Comment by jexp** [comment]
Ya, true :)
Would you mind getting your hands dirty and sending a PR ? :)

**Comment by fbiville** [comment]
Sure :)
Shall I work only on the 3.3.x branch ? 

This currently affects all 3.x versions and even older ones (I saw this on `2.3.5.RELEASE`).

**Comment by jexp** [comment]
3.3.x is good enough.

Thanks a lot

**Comment by fbiville** [comment]
Quick question: should we enforce the presence of `@MapResult`/`@QueryResult` on supertypes? 
This seems a bit artificial to me but I'm open to suggestions.

**Comment by fbiville** [comment]
Here you go: https://github.com/spring-projects/spring-data-neo4j/pull/290 :)
