### ISSUE TITLE
use " match(n:`$label`) return n  " query data  $label automatic  add quotes

### ISSUE THREAD

**Issue by kouhangting** [spring-projects/spring-data-neo4j#2896]
How to use dynamic label to query data in spring boot 2.7.10？
`
@Query("match(n:$label) return n")
List<Author> queryList(@Param("label") String label);
`
java code
![image](https://github.com/spring-projects/spring-data-neo4j/assets/66945764/8e0bf1b4-a00d-417b-97d3-b31aab33a45b)

There's no problem when i use  cypher " match(n:`作者`) return n limit 5 "  query data 

![image](https://github.com/spring-projects/spring-data-neo4j/assets/66945764/c5ef9d37-bb13-43b3-8921-87651d4b925f)

when i use dynamic label query data，there is no data or an error message，How to pass this parameter？
`@Query("match(n:$label) return n")`

**Comment by michael-simons** [comment]
Your query should look like this: `match (n) where $label in labels(n) return n;`

**Comment by kouhangting** [comment]
What if I use the following method
`
MATCH(a),(b) WHERE id(a)=1 AND id(b) = 2 create(a)-[r:$type]->(b)RETURN r
`
$type  How to handle it？

Although this approach can handle it, it's not what I want
`
$label in labels(n)
`

**Comment by kouhangting** [comment]
Although this approach can handle it, it's not what I want
`
$label in labels(n)
`

For example, when I create a relationship, the relationship can be customized as input, but it can only be used as a variable.

What if I use the following method
`
MATCH(a),(b) WHERE id(a)=1 AND id(b) = 2 create(a)-[r:$type]->(b)RETURN r
`
$type  How to handle it？

> Your query should look like this: `match (n) where $label in labels(n) return n;`

**Comment by michael-simons** [comment]
Cypher as of know does *not* let you user parameters for labels and types. Think of them as a table name in relational databases, they cannot be parameterized. For that to work you need to construct them as fixed query strings.
