### ISSUE TITLE
Question/Feature Request: Support for GeoResult, GeoResults and GeoPage

### ISSUE THREAD

**Issue by Dimibe** [spring-projects/spring-data-neo4j#2908]
Hi,

Spring Data Commons has some special query return types for geospatial queries: [Reference](https://docs.spring.io/spring-data/neo4j/reference/repositories/query-return-types-reference.html).

Spring Data Neo4j supports geospatial queries but seems not to support those three special query return types. I wonder if it's planned that those return types will be supported in the future?

As a current solution the distance can be included as a property of the returned entity. But this approach has limitations, e.g. integrating the distance property into entities might clutter the domain model.

Thanks in advance
Dimitrios

**Comment by michael-simons** [comment]
Thanks for your ticket. We are gonna add those where it makes sense!
