### ISSUE TITLE
Mapping performance issue

### ISSUE THREAD

**Issue by vexos-io** [spring-projects/spring-data-neo4j#2915]
I have testing the follow query which costs **60ms** with cypher-shell
`
MATCH p1=(o:Order)-[rt:TUPLES]->(nt:Tuple)-[ri:ITEM]->(ni:Item) WHERE o.id = $id RETURN o, collect(nodes(p1)), collect(relationships(p1));
`
where size(o) == 1 and size(rt) == 700 & size(ri) == 700.

But the mapping to objects tree cost 1600ms.

Did I miss anything?

**Comment by meistermeier** [comment]
Could it be that the content of the nodes might influence the time it takes?
Naive benchmarks on my machine come to ~290 ms max for mapping just the nodes with the 1400 relationships with the given query. Adding a few properties does also not at much to it.

**Comment by vexos-io** [comment]
With the following graph (tree)
`
(:Order)-[re1:ENTRY]->(:Tuple)-[rt700:TUPLES]->(:Tuple)-[ri1:ITEM]->(:Item)
`
the mapping takes ~1600ms
while
`
(:Order)-[re1:ENTRY]->(e:Tuple)-[rt700:TUPLES]->(t:Tuple)
`
+
`
(t)-[ri1:ITEM]->(:Item)
`
programmatically re-load t with depth 1 by WHERE t.id IN [...700 ids]
takes 300~500ms

So could you please give me some suggestion?

**Comment by meistermeier** [comment]
Maybe I am doing something wrong.
Could you give me the amount of your nodes?
At the moment I have
a) 1 Order
b) 1 "first" Tuple
c) 700 Tuples
d) 1 item for each of the 700 tuples

If I switch the amount between b and c, I can also not reproduce any issue but are left with the numbers from above.

**Comment by vexos-io** [comment]
Yes, I have exactly the same nodes as your reply above (1 -> 1 > 700 -> 1 each). So it seems weird... I think there are other causes to my case. Let me close this issue first and do more testing on it. Thank you for the help!
