### ISSUE TITLE
Retrieve @CompositeProperty data

### ISSUE THREAD

**Issue by Afler** [spring-projects/spring-data-neo4j#2916]
I have the Node class with a @CompositeProperty like this:
![image](https://github.com/spring-projects/spring-data-neo4j/assets/49097219/7f51d605-2bf8-4b4c-a3b1-16f8b1104aeb)

When I try to retrieve all object of that type by Neo4jRepository#findAll() method I got this (what is this fields?):
![image](https://github.com/spring-projects/spring-data-neo4j/assets/49097219/b67e33de-2130-42c7-92ac-fc1ae24c3651)

But I expect to get this data with nested fields like this: 
![image](https://github.com/spring-projects/spring-data-neo4j/assets/49097219/4b7bdcb8-4618-4699-befe-0ef7a3e6d9de)

So I've tried to retrieve nested data directly with Neo4jClient and it looks fine while debug...
![image](https://github.com/spring-projects/spring-data-neo4j/assets/49097219/52223cb3-d0ef-41ee-b1c4-30d06ce8f125)

..but when it got serialized (by Jakson I suppose) I've got this:
![image](https://github.com/spring-projects/spring-data-neo4j/assets/49097219/ce3d602a-5ce9-4b08-a638-4d7fc7d67680)

I think it's either about fetching depth which I've found no information about how to configure or serialization of InternalNode.class which drops nested properties for some reason
So which options do I have to get whole Node object with it @CompositeProperty field data? And how can I set fetch depth for this case?

**Comment by meistermeier** [comment]
I can only answer this question with a few knowledge about Jackson mapper.
Basically this is not a problem with Spring Data Neo4j but more "later" in the pipeline.
Defining the `Map<String, List<Object>>` makes it very vague for Jackson to guess what to do with `Object`.

Adding a (maybe a little bit naive) serializer:
```
var objectMapper = new ObjectMapper();
SimpleModule module = new SimpleModule();
module.addSerializer(Map.class, new JsonSerializer<Object>() {
	@Override
	public void serialize(Object o, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
		jsonGenerator.writeString(o.toString());
	}
});
objectMapper.registerModule(module);
```
will catch every map and render its objects with `toString()`.

**Comment by Afler** [comment]
@meistermeier Yeah, thank you. I've also found out that it was most likely a Jakson problem, while Gson convert response as I expected.

**Comment by meistermeier** [comment]
Thanks for the information. I will close this issue now.
