### ISSUE TITLE
Multiple URI for a Neo4j Cluster

### ISSUE THREAD

**Issue by Kevin-Darty** [spring-projects/spring-data-neo4j#2920]
I have a Neo4j 5 cluster with 3 servers (e.g. server-01.x.y:7687, server-02.x.y:7687, server-03.x.y:7687).
I have set my Spring API (read only) on server-01.x.y:7687 on application.yml:

```
spring:
  neo4j:
    uri: neo4j+s://server-01.x.y:7687
```

If this server is unreachable (while the two others are OK), the API responds: 

> Exception: class org.neo4j.driver.exceptions.ServiceUnavailableException: Could not perform discovery for database 'xxxxxx'. No routing server available.

How can I set the 3 URI in order to failover on another server if one is down?

**Comment by michael-simons** [comment]
Hello @Kevin-Darty That should be actually handled automatically by the driver.

@injectives Might care to chime in, please?

**Comment by injectives** [comment]
The recommended way is to provide a DNS name that resolves to all 3 servers. Something like: `neo4j+s://cluster-discovery:7687`.

The driver will resolve such DNS name and will try all IPs it contains.

Alternatively, the driver can be configures with a custom address resolver: https://neo4j.com/docs/api/java-driver/5.22/org.neo4j.driver/org/neo4j/driver/Config.ConfigBuilder.html#withResolver(org.neo4j.driver.net.ServerAddressResolver)

**Comment by Kevin-Darty** [comment]
Thanks!

I had to go with the resolver solution.
It's working well.

Ended up with this:
```
    @Bean
    public Driver neo4jDriver() {
        Config config = Config.builder()
                .withoutDriverMetrics()
                .withNotificationConfig(NotificationConfig.disableAllConfig())
                .withTelemetryDisabled(true)
                .withTrustStrategy(Config.TrustStrategy
                        .trustSystemCertificates()
                        .withHostnameVerification()
                )
                .withEncryption()
                .withResolver(address -> uris.stream().map(
                                uri -> ServerAddress.of(uri, port)
                        ).collect(Collectors.toSet())
                )
                .build();

        URI firstServer = UriComponentsBuilder.newInstance()
                .scheme(scheme)
                .host(uris.get(0))
                .port(port)
                .build()
                .toUri();
        Driver driver = GraphDatabase.driver(firstServer, AuthTokens.basic(username, password), config);
        driver.verifyConnectivity();
        return driver;
    }
```

**Comment by michael-simons** [comment]
Hey @Kevin-Darty thanks a lot for your feedback. 

Just some tips, maybe you find this helpful:
You can injection `org.springframework.boot.autoconfigure.neo4j.Neo4jProperties` into the `@Bean` method, to avoid duplicating properties.

And especially, you can use `ConfigBuilderCustomizer` to adapt the config (a custom config bean is not possible, as you might noticed).

That would look something like described here https://medium.com/neo4j/tailor-made-neo4j-connectivity-with-spring-boot-2-4-281876ef5f46 (which actually includes a resolver, too)

```java
@Bean
ConfigBuilderCustomizer driverConfigCustomizer() {

	return configBuilder -> configBuilder
		.withoutDriverMetrics()
		.withNotificationConfig(NotificationConfig.disableAllConfig())
		.withTelemetryDisabled(true)
		.withTrustStrategy(Config.TrustStrategy
			.trustSystemCertificates()
			.withHostnameVerification()
		)
		.withEncryption()
		.withResolver(address -> uris.stream().map(
				uri -> ServerAddress.of(uri, port)
			).collect(Collectors.toSet())
		);
}
```

I wil close the issue, but please feel to re-open or reach out if anything fails or is missing.
