### ISSUE TITLE
Spring data neo4j transaction default timeout at driver level not found.

### ISSUE THREAD

**Issue by amit-kumaryadav** [spring-projects/spring-data-neo4j#2921]
Is there any way to setup the transaction timeout in spring data neo4j at driver level or in application.yaml (except spring.transaction.default-timeout). We are looking a way to setup the transaction timeout for neo4j query from our application at the driver level not method level.

**Comment by michael-simons** [comment]
Hi @amit-kumaryadav no there is not. as you said there is

```
spring.transaction.default-timeout=23
```

for everything

```
@Transactional(timeout = 23)
```

declaratively on the method level

Last but not least, you can inject the `Neo4jTransactionManager` as `PlattformTransactionManager` and create an instance of 


```
TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
transactionTemplate.setTimeout(23);
```

and use 

```
transactionTemplate.execute(callback -> yourRepository().whatver());
```

or `executeWithoutResult`


If you use a repository, the Neo4j template or the Neo4j client, you must do so in Spring managed transactions
If you want to use the driver in isolation, that will happen outside the Spring managed transactions, hence you would do your call directly on the drivers sessions.

No additional repository parameters or annotations to influence this are planned. We consider the existing means to be sufficient.

**Comment by amit-kumaryadav** [comment]
@michael-simons Thank you

**Comment by michael-simons** [comment]
Very welcome, Amit!
