### ISSUE TITLE
During Fluent find operations the default renderer is used to render parts of the cypher query, thus ignoring any and all configuration

### ISSUE THREAD

**Issue by THE-ORONCO** [spring-projects/spring-data-neo4j#2927]
When using the `org.springframework.data.neo4j.core.FluentFindOperation.FindWithQuery#matching(org.neo4j.cypherdsl.core.Statement, java.util.Map)` method (for example when using the Neo4jTemplate) the given statement is rendered using the default renderer. This means any configuration provided via a `Configuration`-Bean is lost / ignored for this particular statement. 
I found this bug because the generated Cypher statements were always rendered with `id` instead of `elementId` even though I explicitly defined them via the Cypher-DSL and also set the Neo4J-Version to v5 in the `Configuration`-Bean.
A possible solution could be to not render the match-statement in place and instead delay the rendering until the configuration is in scope to get the actual renderer.

A minimal example showing the issue is provided [here](https://github.com/THE-ORONCO/spring-neo4j-uses-default-renderer).

**Comment by michael-simons** [comment]
Great catch, @THE-ORONCO A fix is on the way.
Thank you.
