### ISSUE TITLE
Deprecated ID function warnings

### ISSUE THREAD

**Issue by hornkim** [spring-projects/spring-data-neo4j#2942]
Using Neo4j DB 5.22 and Spring boot 3.3.0 & 3.3.2

Feature Deprecation warnings as Spring creates CYPHER using ID function. Running the accessing-data-neo4j example out of the box shows the issue:

```
Neo.ClientNotification.Statement.FeatureDeprecationWarning: This feature is deprecated and will be removed in future versions.
	OPTIONAL MATCH (hlp:`Person`) WHERE id(hlp) = $__id__ WITH hlp WHERE hlp IS NULL CREATE (person:`Person`) SET person = $__properties__ RETURN person UNION MATCH (person:`Person`) WHERE id(person) = $__id__ SET person += $__properties__ RETURN person
	                                    ^
The query used a deprecated function: `id`.
2024-08-21T10:26:54.462+10:00  WARN 79533 --- [accessing-data-neo4j] [           main] o.s.data.neo4j.cypher.deprecation        : Neo.ClientNotification.Statement.FeatureDeprecationWarning: This feature is deprecated and will be removed in future versions.
	OPTIONAL MATCH (hlp:`Person`) WHERE id(hlp) = $__id__ WITH hlp WHERE hlp IS NULL CREATE (person:`Person`) SET person = $__properties__ RETURN person UNION MATCH (person:`Person`) WHERE id(person) = $__id__ SET person += $__properties__ RETURN person
```

**Comment by meistermeier** [comment]
You can mute those warnings by adjusting the logger `org.springframework.data.neo4j.cypher.deprecation` to error level.
Unfortunately the deprecation of the `id` function in Cypher throws a warning instead of just an info.
But there were some categories introduced that we adapted to provide dedicated loggers for.
Reference for all categories: https://docs.spring.io/spring-data/neo4j/reference/appendix/logging.html

**Comment by hornkim** [comment]
Yes I have muted these warnings but thats not the point, the code produced is deprecated. Just pointing out it will have to be fixed at some stage. KimSent from my iPadOn 21 Aug 2024, at 6:35 PM, Gerrit Meier ***@***.***> wrote:﻿
You can mute those warnings by adjusting the logger org.springframework.data.neo4j.cypher.deprecation to error level.
Unfortunately the deprecation of the id function in Cypher throws a warning instead of just an info.
But there were some categories introduced that we adapted to provide dedicated loggers for.
Reference for all categories: https://docs.spring.io/spring-data/neo4j/reference/appendix/logging.html

**Comment by michael-simons** [comment]
Did you configure the dialect of Cypher-DSL for Neo4j?

```
import org.neo4j.cypherdsl.core.renderer.Configuration;
import org.neo4j.cypherdsl.core.renderer.Dialect;

@Bean
Configuration cypherDslConfiguration() {
     return Configuration.newConfig().withDialect(Dialect.NEO4J_5).build();
}
```

**Comment by hornkim** [comment]
Yes Michael, I did try that and no help, see below.  It would be good to put this in the Spring accessing-data-neo4j Example I mentioned above and see if it works with Latest Neo4j DB ?
I had this, and maybe its wrong:

import org.neo4j.cypherdsl.core.renderer.Dialect;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class Neo4jConfig {
    @Bean
    org.neo4j.cypherdsl.core.renderer.Configuration cypherDslConfiguration() {
        return org.neo4j.cypherdsl.core.renderer.Configuration.newConfig()
                .withDialect(Dialect.NEO4J_5).build();
    }
}
