### ISSUE TITLE
RetryExceptionPredicate has the wrong error messages

### ISSUE THREAD

**Issue by GregDThomas** [spring-projects/spring-data-neo4j#2944]
`org.springframework.data.neo4j.core.support.RetryExceptionPredicate` contains two exception messages that are retryable;

```java
private static final Set<String> RETRYABLE_ILLEGAL_STATE_MESSAGES = Set.of(
			"Transaction must be open, but has already been closed.",
			"Session must be open, but has already been closed.");
```

Neither of these messages appear anywhere in the code base. However, very similar messages (without a trailing dot) appear in exceptions raised in `org.springframework.data.neo4j.core.transaction.Neo4jTransactionHolder`. Given these exceptions should be retryable, these exception messages should match.

(Background; we've been wondering why some exceptions weren't being retried in our code base - finally narrowed it down to this!)

**Comment by GregDThomas** [comment]
I'm guessing this could/should be backported to 7.3.x, maybe 7.2.x depending on when the change was made?

**Comment by michael-simons** [comment]
I will take care of this for all supported branches. :)

**Comment by GregDThomas** [comment]
Thank you!
