### ISSUE TITLE
UpdateableState is missing

### ISSUE THREAD

**Issue by gfinger** [spring-projects/spring-data-neo4j#296]
The project https://github.com/neo4j-contrib/developer-resources/tree/gh-pages/language-guides/java/spring-data-neo4j produces an error if you update the dependency to  spring-data-neo4j from  3.2.0.RELEASE to 3.3.0.RELEASE. There is a ClassNotFoundException: java.lang.ClassNotFoundException: org.springframework.data.neo4j.core.UpdateableState
when instantiating the GraphDatabaseService.

**Comment by mangrish** [comment]
Closed. Issue out of date.
