### ISSUE TITLE
IndexProvider is deprecated

### ISSUE THREAD

**Issue by gfinger** [spring-projects/spring-data-neo4j#297]
The project https://github.com/neo4j-contrib/developer-resources/tree/gh-pages/language-guides/java/spring-data-neo4j produces a warning:
Class 'org.springframework.data.neo4j.support.index.IndexProvider' is marked deprecated	
I use Spring Boot. The managed version for spring-data-neo4j is 3.2.2.RELEASE

**Comment by jexp** [comment]
Yes, it's intentionally to mark them legacy planned to go away :)
