### ISSUE TITLE
Weird behavior with an optional match

### ISSUE THREAD

**Issue by ShiiniiDev** [spring-projects/spring-data-neo4j#2977]
Hello,

I have noticed a weird behavior while using optional match, I hope it is a mistake from me
I'm using spring-boot-starter-data-neo4j 3.3.6

```java 
var root = Cypher.node("Project").named("root");
var statement = Cypher.match(root).where(root.property("metadata.status").isEqualTo(Cypher.anonParameter("active")))
                           .returning(Cypher.collect(root).build());
assetRepository.findAll(statement);
```

It will generate

```
MATCH (root:`Project`) WHERE root.`metadata.status` = $pcdsl01 
RETURN collect(root)
```

And I get 2 projects, like expected

Now, it wanted to go deeper, if there is include the assigned people

```java 
var root = Cypher.node("Project").named("root");
var person = Cypher.node("Person").named("p0");
var relationship = root.relationshipBetween(person, "ASSIGNED").length(0, null).named("assign0");

var statement = Cypher.match(root).where(root.property("metadata.status").isEqualTo(Cypher.anonParameter("active")))
                          .optionalMatch(relationship)
                          .returning(Cypher.collect(root), Cypher.collectDistinct(relationship), Cypher.collectDistinct(person))).build());

assetRepository.findAll(statement);
```

It will generate

```
MATCH (root:`Project`) WHERE root.`metadata.status` = $pcdsl01 
OPTIONAL MATCH (root)-[assign0:`ASSIGNED`*0..]-(p0:`Person`) 
RETURN collect(root), collect(DISTINCT assign0), collect(DISTINCT p0)
```

It's where to turn out to be weird, because **I do not have project result anymore**, just an empty one.
However when I perform this above query on my neo4j db I have

![image](https://github.com/user-attachments/assets/c2c23d27-4e78-4f52-af36-e4e316eb9941)

And no error in console..

Thanks for your time

**Comment by meistermeier** [comment]
It should be solved if you won't `collect` the root node.
Spring Data Neo4j expects exactly one node as the domain entity representative for a result to map its connections. Of course with the relationships and related nodes as lists, as you have already done it.
We don't parse list representation of the "root nodes" because it all gets added into one result row and we would have to figure out which relationship and related node belongs to which root node. This is not the only reason but such a result pattern would not allow us
* to provide a truly reactive flow or
* to avoid collecting everything in memory before mapping.
The mapping of a simple list works fine because those single list result entries can be handled -although they come in as one block- one after the other.

Browser: This is some Neo4j browser magic to give visualise it proper. If you use the table or text view in the browser you can see the actual response.

**Comment by ShiiniiDev** [comment]
> It should be solved if you won't `collect` the root node. Spring Data Neo4j expects exactly one node as the domain entity representative for a result to map its connections. Of course with the relationships and related nodes as lists, as you have already done it. We don't parse list representation of the "root nodes" because it all gets added into one result row and we would have to figure out which relationship and related node belongs to which root node. This is not the only reason but such a result pattern would not allow us
> 
> * to provide a truly reactive flow or
> * to avoid collecting everything in memory before mapping.
>   The mapping of a simple list works fine because those single list result entries can be handled -although they come in as one block- one after the other.
> 
> Browser: This is some Neo4j browser magic to give visualise it proper. If you use the table or text view in the browser you can see the actual response.

Thanks, I really appreciate!
I've removed the "collect root node"

```java
var root = Cypher.node("Project").named("root");

var person = Cypher.node("Person").named("p0");
var relationship = root.relationshipBetween(person, "ASSIGNED").length(0, null).named("assign0");
var statement = Cypher.match(root).where(root.property("metadata.status").isEqualTo(Cypher.anonParameter("active")))
                           .optionalMatch(relationship)
                           .returning(Cypher.collectDistinct(relationship), Cypher.collectDistinct(person));

assetRepository.findAll(statement)
```

```
MATCH (root:`Project`) OPTIONAL MATCH (root)-[assign0:`ASSIGNED`*0..]-(p0:`Person`) RETURN collect(DISTINCT assign0), collect(DISTINCT p0)
```

Unfortunately the result is the same :/ only one empty result

![image](https://github.com/user-attachments/assets/3a774136-a532-4ea4-8fa5-8df16b614365)

In case my needing was blurry, what I'm trying to achieve is

Get all active projects, and if they have, to collect the assignees
```json
[{
   "name": "Project 1"
    "assignees": [{
         "name": "someone"
    }]
},
{
   "name": "Project 3"
    "assignees": [] // empty
}]
```

![image](https://github.com/user-attachments/assets/0e4a08ec-0c8e-4c14-85aa-87251e092689)

Maybe I'm misunderstanding Neo4j which I can accept because I didnt start for long time

To provide more details, Im using the asset repository because the project is first an asset, and by dynamic labels it is also a project

```
@Node("Asset")
public class AssetEntity {
  @Builder.Default
  @DynamicLabels
  private Set<String> types = new HashSet<>();
```

I've tried to change my query with `Cypher.node("Project").named("root")` but no changes...

**Comment by meistermeier** [comment]
This was very detailed, thanks. I meant not to completely remove the `rootNode`, but to return something like this:
```
var statement = Cypher.match(root).where(root.property("metadata.status").isEqualTo(Cypher.anonParameter("active")))
        .optionalMatch(relationship)
        .returning(root.asExpression(), Cypher.collectDistinct(relationship), Cypher.collectDistinct(person)).build();
``` 
the `asExpression()` was needed to match the signature of the `returning` method.
