### ISSUE TITLE
Node Composition

### ISSUE THREAD

**Issue by moonyoungCHAE** [spring-projects/spring-data-neo4j#2978]
Hi.
I wonder how I can implement using a class as composition. I’ve seen `@CompositeProperty`, but since it requires using a Map, it’s different from what I want to achieve.

For example:
```
public class Person {
    String name;
    Integer age;
}

@Node("Student")
public class Student {
    Person person;
    String school;
}

@Node("Manager")
public class Manager {
    Person person;
    String job;
}
```
Given the code above, I would like the Student node to have name and age properties of Person. Of course, this could be represented with an IS-A relationship, but that might make the relationships more complex. Instead, I want to store them as properties. Is there a way to implement this?

**Comment by meistermeier** [comment]
I think that you want to use just inheritance in this case.
```java
@Node
public abstract class Person {
    @Id @GeneratedValue
    String id; // or whatever you want to use as the identifier
    String name;
    Integer age;
}
```
```java
@Node("Student")
public class Student extends Person {
    String school;
}
```
```java
@Node("Manager")
public class Manager extends Person {
    String job;
}
```
This will result in nodes labeled `:Student:Person` or `:Manager:Person` and assumes that there will be no `:Person`. This gives you the benefit of fetching all `Persons` with the repository.
If you don't want the use of the `:Person` label, you would have to repeat the identifier definition in every concrete class and remove the `@Node` annotation and the identifier field from the Person.

Further information can be found in [this part of our documentation](https://docs.spring.io/spring-data/neo4j/reference/object-mapping/metadata-based-mapping.html#_a_note_on_class_hierarchies).

**Comment by moonyoungCHAE** [comment]
Thank you for your response.  I could resolve the issue by following your suggestion.
And I'm just curious as to why Composition is not supported. I think it could be necessary in some cases, especially since only single inheritance is allowed. Data JPA with MySQL has related features, but I assume the reason it's not supported in Neo4j is because it's considered better to solve such cases with relationships?
