### ISSUE TITLE
LoadByProperty depth

### ISSUE THREAD

**Issue by monowai** [spring-projects/spring-data-neo4j#299]
Is it possible to support a depth parameter when calling loadByProperty? If you wanted to hydrate the object by anything other than the PK you have to make 2 calls

```
Person p = template.loadByProperty(Person.class, "login", loginValue);
p = personRepo.findOne(p.getId(), 2);
```

Even better, 
```
// PersonRepo knows the class to project
personRepo.loadByProperty("login", loginValue, 2);
```

**Comment by luanne** [comment]
True, Neo4jOperations and derived finders don't support depth yet. https://jira.spring.io/browse/DATAGRAPH-685 will track this.

A workaround exists if you use the Session.

```
@Autowired Session session;
session.loadAll(Person.class,new Filter("login",loginValue),2);
```
