### ISSUE TITLE
@Transactional should support Unmanaged Extensions

### ISSUE THREAD

**Issue by monowai** [spring-projects/spring-data-neo4j#300]
SDN4
Given that functionality like @Labels and user defined properties have been removed from SDN3, the only option a programmer, who wants to continue to support this functionality, has is to create an unmanaged extension

At the moment, if I write a unmanaged extension I have to manage the transaction and call to the extension myself using Spring-Integration or a web client framework, circumventing the convenient template functionality

SDN should expose a mechanism for calling unmanaged extension allowing them to participate in an established @Transaction.

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-684
