### ISSUE TITLE
Batch Job issue, Error creating bean with name 'scopedTarget.getSession': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton;

### ISSUE THREAD

**Issue by lowkianping** [spring-projects/spring-data-neo4j#301]
Hi, 
I noticed in SDN4, the neo4j session is defined only in the web session scope. 

But my project requires to execute some batch job daily via Scheduled Job using the @Scheduled annotation, and it is unable to get the scopedTarget.getSession because batch job is not inside the web request context.

i checked the sdn4-university and the ogm samples codes, there isn't any example of doing this?

**Comment by luanne** [comment]
Just drop the  @Scope annotation altogether?

**Comment by lomyal** [comment]
This solves my problem. Thanks.

**Comment by KlemensEngel** [comment]
Hello @luanne,

what do you mean with 
> Just drop the @Scope annotation altogether?

I think I have the same issue like lowkianping - I am working on a Rest-Service which usually does have a request-scoped session for Neo4j. But in one part of the application I am running a schedular which does not have a underlying http session. How can I create a separated neo4j session without an underlying http request?

**Comment by mangrish** [comment]
@KlemensEngel @lowkianping @lomyal: Please note that ```@Scope``` is only relevant for Spring Boot and Spring WebMVC apps (or Spring web application context aware apps). By default at the moment (Up to SDN 4.1.x) Sessions are singletons. The session lifecycle differs to things like Hibernate/JPA in that a session does not need to explicitly be closed or destroyed. Instead we rely on GC to take care of completed sessions.  Remember though: sessions are not thread safe.

Therefore there are several options:

1. Call session.clear() at the end of every thread localised session. This will effectively reset the session to be used again on the same thread.
2. Use the 4.2.x SNAPSHOT (remember to add http://m2.neo4j.org/content/repositories/snapshots/ to your repositories to be able to get it). This API is currently changing quite a lot but you do something like this: 
```
@Configuration
@EnableWebMvc
@ComponentScan({"your.package.to.scan"})
@EnableNeo4jRepositories("your.neo4j.package.with.repositories")
@EnableTransactionManagement
public class WebAppContext {
​
	@Bean
	public PlatformTransactionManager transactionManager(SessionFactory sessionFactory) throws Exception {
		return new Neo4jTransactionManager(sessionFactory);
	}
​
	@Bean
	public SessionFactory sessionFactory() throws Exception {
		LocalSessionFactoryBean lsfb = new LocalSessionFactoryBean();
		lsfb.setPackagesToScan("org.springframework.data.neo4j.web.domain");
		lsfb.afterPropertiesSet();
		return lsfb.getObject();
	}
​
	@Bean
	public Neo4jTemplate neo4jTemplate(Session session) throws Exception {
		return new Neo4jTemplate(session);
	}
​
	@Bean
	public Session getSession(SessionFactory sessionFactory) throws Exception {
		SpringSessionProxyBean proxy = new SpringSessionProxyBean();
		proxy.setSessionFactory(sessionFactory);
		proxy.afterPropertiesSet();
		return proxy.getObject();
	}
}
```
Note that you don't need to extend Neo4jConfiguration here.

HTH

**Comment by mangrish** [comment]
Closing this issue. If it is not resolved please reopen and mention what else is required. SDN 4.2.0.RELEASE and it's associated documentation should help.
