### ISSUE TITLE
Cannot extract single value from Iterable with more than one elements.

### ISSUE THREAD

**Issue by vdatcu** [spring-projects/spring-data-neo4j#302]
Setup:

 * Spring Data Neo4j 3.3.1.RELEASE
 * Neo4j-community-2.3.0-M01

My DTO is as follows:

```
@QueryResult
public class DbTemplateQueryResult {

    @ResultColumn("id")
    private Long id;

    @ResultColumn("title")
    private String title;

    @ResultColumn("type")
    private String type;

    @ResultColumn("items")
    private Collection<DbAsset> items;
}
```
with getters and setters omitted

The query is in this repo:

```
public interface TemplateRepository extends GraphRepository<DbTemplate> {

    @Query("MATCH (a:DbAsset)-[:IN]->(t:DbTemplate) WITH a,t ORDER BY a.title,t.title DESC RETURN t.type AS type, t.title AS title, id(t) AS id, collect(a) AS items")
    List<DbTemplateQueryResult> getTemplates();

}
```

However, I get RuntimeException("Cannot extract single value from Iterable with more than one elements.") when the converter is accessing the "items" property. The exception is thrown at this line:
https://github.com/spring-projects/spring-data-neo4j/blob/0a58372cfa6980b3584f23bb2aeae7c33bc52448/spring-data-neo4j-rest/src/main/java/org/neo4j/rest/graphdb/util/DefaultConverter.java#L55

Can someone provide some help please? I saw the older thread on the google group saying this will be fixed in some future release. However, it seems the bug has not been addressed. Is this still in plan?

Note: it only happens with the server SpringCypherRestGraphDatabase, not with the embedded one. Querying the neo4j server in the browser works as expected.

**Comment by jexp** [comment]
Hi @vlad-datcu-kalon good question, It seems it was not fixed, can you recreate this issue in Spring JIRA so that we can look into this?

I presumed that we didn't manage nested entity collections at all though.

**Comment by vlad-datcu-kalon** [comment]
Yep, @jexp, will do

**Comment by vlad-datcu-kalon** [comment]
Done. https://jira.spring.io/browse/DATAGRAPH-695

**Comment by amanjs** [comment]
@jexp is there any timeline when this will be fixed?

**Comment by mangrish** [comment]
Closed. Issue out of date.
