### ISSUE TITLE
Testing projects with SDN4

### ISSUE THREAD

**Issue by ml054** [spring-projects/spring-data-neo4j#304]
Currently only remote database access is supported for SDN4. Is there any possibility for unit tests with SDN4 with in-memory database?

**Comment by monowai** [comment]
They do work with InMemory DB. Look in src/test and you will see plenty of examples.

Extend Neo4jConfiguration class and

```
    @Override
    public Neo4jServer neo4jServer() {
        return new InProcessServer();
    }
```

**Comment by luanne** [comment]
The dependencies required for the InProcessServer are documented here http://docs.spring.io/spring-data/neo4j/docs/4.0.0.RC1/reference/html/#_neo4jserver_bean

**Comment by heroicefforts** [comment]
Which group, artifact, and version defines InProcessServer.  The references above do not seem to work with 4.0.0.RELEASE.  All I can find in this code base remotely similar to InProcessServer is this godawful piece of work:  
https://github.com/spring-projects/spring-data-neo4j/blob/master/spring-data-neo4j-rest/src/test/java/org/neo4j/rest/graphdb/RestTestBase.java#L70

**Comment by luanne** [comment]
Please use the dependencies listed in the manual for 4.0.0.RELEASE-
http://docs.spring.io/spring-data/neo4j/docs/4.0.0.RELEASE/reference/html/#_neo4jserver_bean

RestTestBase.java is an SDN 3 class so it isn't a good reference.
