### ISSUE TITLE
Mapping of Domain Objects in @QueryResult does not work (4.0.0 RC1)

### ISSUE THREAD

**Issue by jansta** [spring-projects/spring-data-neo4j#306]
```java
@Query("MATCH (d:Document})-[]-(o:Other)-return doc as document, o.color as color")
public Collection<DocumentWithColor> getDocWithColor();
```
```java
@QueryResult
public class DocumentWithColor {
    @ResultColumn("document")
    public Document document;
    
    @ResultColumn("color")
    public String color;
}
```
Resulting Warning: 
09:08:37.821 [http-bio-8080-exec-24] WARN  o.n.ogm.mapper.SingleUseEntityMapper - Unable to find property: document on class: de.xxx.yyyy.tttt.DocumentWithColor for writing

The mapping works with primitive data types.

I don't have much experience working with spring data yet, so I can't figure out if I'm doing something wrong or if there is a problem with the mapping process.

**Comment by luanne** [comment]
@ResultColumn is not supported and neither is mapping a domain object to a field in the @QueryResult (https://jira.spring.io/browse/DATAGRAPH-700).
What you can do instead is have your query return ID(document) which can then be loaded. Some more info in the accepted answer here: http://stackoverflow.com/questions/31069679/sdn-4-neo4joperation-convert-deprecated

**Comment by jansta** [comment]
Thanks :) It would be amazing to have domain object mapping in a future release. Thank you and your team for your work on spring data neo4j. It's a great product.
