### ISSUE TITLE
cleanUpGraph calling invalid method

### ISSUE THREAD

**Issue by monowai** [spring-projects/spring-data-neo4j#308]
SDN 3.3.2 with Neo4j 2.2.3. Regression tests that call cleanUpGraph are failing because the isDeleted method does not exist in NodeManager.

```
Neo4jHelper.cleanDb(template);
...
    private static void removeNodes(GraphDatabaseService graphDatabaseService, boolean includeReferenceNode) {
...
...
         if (nodeManager.isDeleted(rel)) continue; // <<-- isDeleted does not exist in nodeManager
```

I believe that this is a compatible combination?

**Comment by jexp** [comment]
Yes, the tests won't work with 2.2.3 too many API changes in Neo4j.

**Comment by mangrish** [comment]
Closed. Issue out of date.
