### ISSUE TITLE
Access neo4j session in @Async methods?!

### ISSUE THREAD

**Issue by helt** [spring-projects/spring-data-neo4j#317]
I have pulled together a small project, which essentially shall kick off a background process when it receives a request for it, using `@Aync`. The layout is loosly based on [an stackoverflow question](http://stackoverflow.com/questions/29284008/spring-boot-async-method-in-controller-is-executing-synchronously). The problem is, however (besides doing my first steps with spring), that no neo4j session can be retrieved. Any suggestions how to solve this?

```java
@Service
public class BulkConverterServiceImpl implements BulkConverterService {
	@Autowired InputService inputService;
	@Autowired NeoService neo;
    
	@Async
	public List<MyNodePojo> convertInput() throws Exception {
		List<MyNodePojo> resultList = new ArrayList<>();
		for (MyPojo a : inputService.getAll()) {
			resultList.add(neo.storeMyPojoObject(a));
		}
		return resultList;
	}
}
```

The method is called as i expect it, the caller does also return a "202", as intended. But `			resultList.add(neo.storeMyPojoObject(a));` dies with this exception:
>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.getSession': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
>

What am i missing here? or is spring-data-neo4j missing somthing here?

**Comment by bachmanm** [comment]
Somewhere in your config, you declared:
```java
@Bean
@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
public Session getSession() throws Exception {
    return super.getSession();
}
```

`value="session"` means that the (OGM) `Session` bean is to be (HTTP) session scoped in Spring. But `@Async` starts a different thread no longer associated with the HTTP session that the request invoking the method came from.

Consequently, you have to use one of the non-HTTP scopes in Spring, i.e. singleton or prototype, depending what you're trying to achieve. If there are multiple different clients invoking the method, go for prototype. The OGM config will change to:

```java
@Bean
@Scope(value = "prototype", proxyMode = ScopedProxyMode.TARGET_CLASS)
public Session getSession() throws Exception {
    return super.getSession();
}
```

**Comment by helt** [comment]
yep. that did it. thanks for the answer

**Comment by alexpetroaica** [comment]
I am facing a similar issue and I am having trouble understanding why using the "prototype" scope would work.

The Neo4j Session is used inside the Neo4jTemplate, which is in turn used inside the Spring Data repositories. The repositories are "singleton" scoped beans, so this would mean that the Session instance inside a repository instance is always the same, even if the Session is "prototype" scoped.

That would mean that the same session object is used for all threads, wouldn't it?
