### ISSUE TITLE
Spring Data Neo4j 4 is not storing any data

### ISSUE THREAD

**Issue by JavaEEBoy** [spring-projects/spring-data-neo4j#323]
I encounter a very strange problem, can anyone help with that?
Here is the link, http://stackoverflow.com/questions/34340317/spring-data-neo4j-4-is-not-storing-any-data 
Thanks!

**Comment by luanne** [comment]
Github issues is primarily use for bug reports. StackOverflow is the right place for these kinds of questions- we'll respond there.
