### ISSUE TITLE
InProcessServer cleanup

### ISSUE THREAD

**Issue by heroicefforts** [spring-projects/spring-data-neo4j#325]
A developer reported our Maven tests failing with an error that Neo4j could not bind to port 7505 (already in use).  We later found that this error was masking another bug that was causing an error during the Spring context initialization after Neo4j had been instantiated.  My hypothesis is that numerous context initialization failures caused many Neo4j instances to be created (but never destroyed) until it exhausted its pool of eligible ports.  It appears that InProcessServer creates a Neo4j TestServer during construction, but never shuts it down and doesn't expose a means to shut it down?

**Comment by justinjohn83** [comment]
I worked around this for now (using Groovy) by adding a shutdown hook and accessing private variable (which you can do in Groovy) to shutdown the server:

    @Configuration
    @EnableTransactionManagement
    @EnableNeo4jRepositories("com.yourcompany.repository")
    @ComponentScan('com.yourcompany.service')
    class TestConfig extends Neo4jConfiguration {
	
	private Neo4jServer server
    @Bean
    @Override
    public Neo4jServer neo4jServer() {
        return server = new InProcessServer();
    }
	
	@PreDestroy
	public void destroy() {
		// Need to shut down the server on each unit test since by default it just registers a JVM shutdown hook which will only fire at end of all tests
		// If we shutdown here we won't pile up sockets
		((InProcessServer)server).testServer.shutdown()
	}

**Comment by luanne** [comment]
InProcessServer does not exist in SDN 4.1.1/OGM 2.x, please upgrade, thanks
