### ISSUE TITLE
[Feature 4.1.x] Support for SpEL expressions in @Query

### ISSUE THREAD

**Issue by liebowitz** [spring-projects/spring-data-neo4j#326]
This is a useful feature of Spring MongoDB, particularly for expression-based security filtering. I can take a stab at a PR if there is interest.

**Comment by yngwi** [comment]
Hi,
is there any other way to do this? I would like to use the spring security principal object in a `@Query` to access only nodes "owned" by the authenticated user.

**Comment by johndeverall** [comment]
:+1:

**Comment by luanne** [comment]
Now tracked in JIRA: https://jira.spring.io/browse/DATAGRAPH-871
