### ISSUE TITLE
missing relationships in the graph

### ISSUE THREAD

**Issue by Quazar1984** [spring-projects/spring-data-neo4j#331]
I have asked a question on [www.stackoverflow.com](url) but haven't got any answers yet. Maybe it is better to ask the question here.

Here is the link to the question: [https://stackoverflow.com/questions/35437117/sdn-4-missing-relationships-in-the-graph](url)

**Comment by gregturn** [comment]
A) This is markdown, so you have embedded the links wrong.
B) This is an issue management system so please don't open a ticket just because you haven't gotten an answer in the 21 hours since you first posed it.
