### ISSUE TITLE
Error creating bean scoped in spring application using Neo4j and Scheduled processes

### ISSUE THREAD

**Issue by zeroberto** [spring-projects/spring-data-neo4j#337]
I'm trying to access a scheduled method in a component of a Spring application that uses a Neo4j database, however, the problem occurs below. Some posts on the internet recommend removing the attribute 'session' of @Scope annotation, native of Neo4j configuration, but it does not solve, because it seems to be necessary. Does anyone have any idea what can be?

`@Bean`
`@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)`
`public Session getSession() throws Exception {`
`	return super.getSession();`
`}`

`@Scheduled(cron = "${batch.person.cron}")`
`public void cronJob() {`
`	logger.info("> cronJob");`
`	Collection<Person> persons = personService.findAll();`
`	logger.info("There are {} persons in the database.", persons.size());`
`	logger.info("< cronJob");`
`}`

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.getSession': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:355) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192) ~[spring-aop-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at com.sun.proxy.$Proxy80.getTransaction(Unknown Source) ~[na:na]
> 	at org.springframework.data.neo4j.transaction.Neo4jTransactionStatus.<init>(Neo4jTransactionStatus.java:44) ~[spring-data-neo4j-4.1.1.RELEASE.jar:na]
> 	at org.springframework.data.neo4j.transaction.Neo4jTransactionManager.getTransaction(Neo4jTransactionManager.java:42) ~[spring-data-neo4j-4.1.1.RELEASE.jar:na]
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427) ~[spring-tx-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) ~[spring-tx-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at com.itinerario.controller.PersonBatchBean$$EnhancerBySpringCGLIB$$ce0a69f9.fixedDelayJobWithInitialDelay(<generated>) ~[classes/:na]
> 	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_72]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_72]
> 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_72]
> 	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_72]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_72]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_72]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_72]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_72]
> 	at java.lang.Thread.run(Unknown Source) [na:1.8.0_72]
> Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
> 	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.web.context.request.SessionScope.get(SessionScope.java:91) ~[spring-web-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	... 24 common frames omitted

**Comment by amaral7** [comment]
When you set the value = "session" that will try return a bean instance per HTTP session. But how you are using in a scheduled event and it isn't associated with a HTTP Request, for this reason you are getting this error.

Maybe you should try change to value = "prototype", this means return a new bean session each time when requested.

**Comment by vince-bickers** [comment]
As @amaral7 says, you can't use a web bean scope outside the context of a web-mvc enabled application. Your batch process needs to have a separate application configuration from your web application. Alternatively you need to modify you application config to return either a web-scoped session bean, or a prototype or singleton one, depending on the context its running in. You could easily do this by passing a system property via the batch process launcher for example.
