### ISSUE TITLE
Tests with multiple spring test contexts fail when in certain order

### ISSUE THREAD

**Issue by frant-hartm** [spring-projects/spring-data-neo4j#338]
In a situation when there is a spring test context created using SpringJUnit4ClassRunner Spring caches the context for multiple test classes if the context is the same (e.g. base test class with configuration and multiple child classes).

If there are multiple such configurations and tests with the cached contexts interleave it causes one of the drivers to close, which results in NullPointerException:

FirstTest extends BaseTest1
...
// if this has different context configuration then 2nd Driver instance will be initialised
// this leads to closing first driver instance, the test itself runs fine
SecondTest extends BaseTest2 
...
// This tests fails because the driver was closed
ThirdTest extends BaseTest1

This all goes down to having one global instance of the driver in neo4j-ogm Components.

See this for reproducible test case for embedded driver, but other drivers fail as well (some at different places).
https://github.com/frant-hartm/spring-data-neo4j/commit/ab6416e8d28b5e64673b01fa6cb7ca9bd5f7b3d5

**Comment by mangrish** [comment]
This now passes using the new style of configuration (see https://github.com/spring-projects/spring-data-neo4j/blob/master/README.adoc#quick-start)
