### ISSUE TITLE
Can't set db URI for EmbeddedDriver under Windows

### ISSUE THREAD

**Issue by dmelching** [spring-projects/spring-data-neo4j#339]
I can't get the EmbeddedDriver working under Windows 10 x64

- Based on: movies.spring.data.neo4j.SampleMovieApplication
- spring-data-neo4j.version: 4.1.1.RELEASE
- neo4j-ogm-embedded-driver: 2.0.2
- Java: 1.8.0_91
- Windows: 10 x64

first of all with HttpDriver everything works fine.
```
driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
URI=http://neo4j:movies@localhost:7474
```

But using:
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
URI=file:///C:/Users/path/to/my/db
```
I get:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/monzta/Documents/Neo4j/default.graphdb/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:1.8.0_91]
```

Using a path without the file:/ (which the WindowsPathParser accepts)
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
URI=C:/Users/path/to/my/db
```
I get:
```
java.lang.IllegalArgumentException: URI scheme is not "file"
	at java.io.File.<init>(File.java:421) ~[na:1.8.0_91]
```

Also relative paths aren't accepted

not setting an URI to use an impermanent db works though, but this isn't what I want

(I know I shouldn't develop on Windows but...)

**Comment by dmelching** [comment]
issue got fixed in neo4j-ogm 2.0.3-SNAPSHOT

**Comment by nerrve** [comment]
I still have the same issue on 2.0.3

**Comment by dmelching** [comment]
Worked for me on 2.0.3-SNAPSHOT, 2.0.4-SNAPSHOT and now just checked the 2.0.3 release. I can't reproduce this error.

**Comment by nerrve** [comment]
Ok. Just found out that this is reproducible when the directory does not exist. The error is misleading. Sorry for the trouble.

**Comment by luanne** [comment]
@nerrve https://jira.spring.io/browse/DATAGRAPH-854 tracks the issue you're seeing with the directory not being created
