### ISSUE TITLE
REQUIRES_NEW inside another transaction is not working properly.

### ISSUE THREAD

**Issue by pointwisefixed** [spring-projects/spring-data-neo4j#340]
Using the latest build of spring-data-neo4j. I created a sample app to reproduce this. It's at https://github.com/pointwisefixed/sdn-requires-new.git

if you run it you will see that I have a flow like this.

(Transactional=REQUIRED) -> (Transactional=REQUIRED) -> (Transactional=REQUIRES_NEW)

And it throws a org.neo4j.ogm.exception.TransactionManagerException: Transaction is not current for this thread

which, if we are supporting REQUIRES_NEW, it shouldn't really. I believe it may be due to the ThreadLocal<Transaction> inside the neo4j-ogm DefaultTransactionManager because if you look at my first test case. I am wrapping the last transaction (that uses REQUIRES_NEW) inside its own thread and it seems to works fine. To me this seems like inconsistent behavior.

**Comment by bachmanm** [comment]
Neo4j does not support nested transactions in any way. Consequently, OGM does not either. I'm gonna leave this open for @luanne and @vince-bickers to judge the consistency question, but REQUIRES_NEW is simply a Spring feature that will not be supported by the OGM/SDN any time soon, sorry for that.

**Comment by vince-bickers** [comment]
@bachmanm is correct that Neo4j doesn't support nested transactions. However the OGM and SDN provide quasi-support for `REQUIRES_NEW` by creating a logical transaction extension to the primary one _for the current thread of execution_. If any such extension fails (i.e. rolls back), the primary transaction is forced to rollback, regardless of whether it succeeds itself. This is the best we can do given the transactional behaviour of Neo4j.

However I think your problem is nothing to do with transaction propagation, rather it is caused by attempting to start a new thread with an existing transactional context. SDN requires that transactional code be single-threaded at all points of interaction with Neo4j, which this is not:

```
    @Transactional
    public String anotherCall() throws ExecutionException, InterruptedException {
        LOG.debug("anotherCall in Service 3 inside a future is called:");
        Future<String> result = executorService.submit(()-> repository.query("CREATE (n:Test1 {mya:'test1'}) return n.mya as test"));
        try {
            return result.get();
        } catch (InterruptedException | ExecutionException e) {
            throw e;
        } finally {
            executorService.shutdown();
        }
    }
```

**Comment by pointwisefixed** [comment]
@vince-bickers That example is my test case that passes (because the ThreadLocal<Transaction> gets correctly created) :). Look at the other test case in which it does use the same thread in which the ThreadLocal gets overwritten by the new transaction and when spring data's tx manager tries to commit it gives a  TransactionManagerException.

````java
    @Transactional
    public String anotherCallWithError() throws ExecutionException, InterruptedException {
        LOG.debug("anotherCall in Service 3 with error is called:");
        return repository.query("CREATE (n:Test1 {mya:'test1'}) return n.mya as test");
    }
```

**Comment by mangrish** [comment]
@pointwisefixed If you try out SDN `4.2.0.BUILD-SNAPSHOT` `REQUIRES_NEW` may work with the bolt and http drivers.  This is an unsupported feature at the moment but we use the same transaction manager infrastructure as JPA now so it may be worth a try. You can see how to wire up this new version [here](http://graphaware.com/neo4j/2016/09/30/upgrading-to-sdn-42.html).

**Comment by mangrish** [comment]
@pointwisefixed If you would like us to keep looking at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
