### ISSUE TITLE
Request ability to specify DEFAULT_QUERY_DEPTH for each Repository

### ISSUE THREAD

**Issue by ssherwood** [spring-projects/spring-data-neo4j#342]
When using @RepositoryRestResource on my repos, I noticed that some had some significant performance issues under JMeter load.  After some research, I narrowed it down to the DEFAULT_QUERY_DEPTH of 1 being used on the findAll (these specific repos have entities with a large number of direct connections).

Since the RepositoryRestResource uses the default pageable findAll, this left me few options for improving my performance (ultimately, I create a custom GraphRepositoryImpl and implemented my own findAll with depth 0).  However, this solution now applies to all of my repositories.  It would be very helpful if there was a repository specific way to set the default depth.

**Comment by mangrish** [comment]
Moved to: https://jira.spring.io/browse/DATAGRAPH-953
