### ISSUE TITLE
InProcessServer in 4.1.1

### ISSUE THREAD

**Issue by mejmo** [spring-projects/spring-data-neo4j#343]
Hello, 

Where should I get InProcessServer class? I am aware that it was deleted in the latest versions but I cannot find any example with embedded server at all. Thank you for the hint.

**Comment by luanne** [comment]
Hi,

You can simply configure the embedded driver either via ogm.properties (omitting the URI will create an impermanent database for you), or via a Java configuration as documented here: http://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#_configuring_the_embedded_driver

There's also a section titled "Testing" in [this blog post](http://graphaware.com/neo4j/2016/02/24/upgrading-spring-data-neo4j-4-1.html) which talks about the changes in testing from SDN 4.0 to 4.1
