### ISSUE TITLE
Simultaneous calls to the same Match query with different filters returns the same object

### ISSUE THREAD

**Issue by treilhes** [spring-projects/spring-data-neo4j#344]
Hello,

I think this issue is the same as #341 but i think the cause is somewhat more complex.

Ok, so this is my issue:

i have a method in my repository declared as follow:
`Revision findByRevisionId(String revisionId);`

When called at the same time using multiple threads with different revisionId some calls return the same object (the cypher request sent is the same for all this calls).

Why?

I think the bug is in  `org.springframework.data.neo4j.repository.query.derived.DerivedGraphRepositoryQuery.resolveParams(Object[] parameters)`.

When setting filters, queryDefinition.getFilters() is used to get filters definition.
But queryDefinition is a cached CypherFinderQuery and is shared across requests.

So filter values set in queryDefinition.getFilters() may be overwritten by other threads before the cypher request generation.

I think that changing 
`Filters queryParams = queryDefinition.getFilters();` 
to something like 
`Filters queryParams = queryDefinition.getFilters().clone();` 
will solve the issue

Keep up the good work.

**Comment by luanne** [comment]
@treilhes thanks for the details, I've opened https://jira.spring.io/browse/DATAGRAPH-876 to track this.

**Comment by luanne** [comment]
@treilhes available in 4.2.0.BUILD-SNAPSHOT, please try it out, thanks.

**Comment by treilhes** [comment]
@luanne test successfull, thanks
