### ISSUE TITLE
@QueryResult doesn't work property with property names different from AS attribute in the query

### ISSUE THREAD

**Issue by tavolate** [spring-projects/spring-data-neo4j#347]
With SDN 4.1.1 and 4.1.2 too, if I have a query result with

````
@QueryResult
public class Result {

private UserEntity mUser;
private CarEntity mCar;

public void setUser(UserEntity pUser) {
    mUser = pUser;
}

public void setCar(CarEntity pCar) {
    mCar = pCar;
}
}
````
 and a query like that

`MATCH (u:User)  <- [:drived_by] - (c:Car) WHERE id(u) = 3 and id(c) = 5 RETURN u as user, c as car`

SDN can't map the result. Even if I use the property annotation in the query result @Property(name = "user")

Is this a bug or a normal behavior?

**Comment by luanne** [comment]
The @Property is required, but looks like it does not work when mapping domain entities. I've opened a bug in JIRA for this https://jira.spring.io/browse/DATAGRAPH-883
