### ISSUE TITLE
Child nodes created with Cypher query not getting fetched in the repository find operation on parent

### ISSUE THREAD

**Issue by NitishDeshpande** [spring-projects/spring-data-neo4j#357]
I am storing a location hierarchy tree in neo4j,
Java class looks like this,
```
@NodeEntity(label = "LOCATION")
public class LocationNode {
    @GraphId
    private Long id;
    private String shortName;
    private String displayName;
    private Integer level;
    private String description;

    @Relationship(type = "HAS_CHILD", direction = Relationship.OUTGOING)
    private Set<LocationNode> childLocations = new HashSet<>();

    //getters and setters
}

```

Repository looks like this,
```
public interface LocationRepository extends GraphRepository<LocationNode> {
	
	@Transactional(transactionManager = "neo4jTransactionManager", readOnly = true)
	@Query(value = "MATCH (n:LOCATION {level:0}) RETURN n")
	LocationNode getEntireHierarchy();

	@Transactional(transactionManager = "neo4jTransactionManager", readOnly = false)
	@Query("MATCH (n:LOCATION) WHERE ID(n)={parentId} FOREACH (r in range({rangeStart},{rangeEnd})"
			+ " | "
			+ "CREATE (n)-[:HAS_CHILD]->"
			+ "(:LOCATION {"
			+ "shortName:{prefix}+''+r+''+{suffix},"
			+ "displayName:{prefix}+''+r+''+{suffix},"
			+ "level: {level},"
			+ "description:{prefix}+''+r+''+{suffix},"
			+ "childLocations:[]"
			+ "})"
			+ ")")
	void createMultipleLocationsUnderParent(@Param("parentId") Long parentId, @Param("rangeStart") Long rangeStart,
			@Param("rangeEnd") Long rangeEnd, @Param("prefix") String prefix, @Param("suffix") String suffix, @Param("level") Integer level);
	
}
```

The second method **createMultipleLocationsUnderParent()** creates multiple nodes under a given parent node _id_ ,

Sequence of events leading to the problem:
**_1_**. Add a root location node 
```
locationRepo.save(rootNode)
```
**_2_**. Add a child node to the root node
```  
parentNode = findOne(parentId);
parentNode.getChildren().add(childNode);
locationRepo.save(parentNode);
```
**_3_**. Get the entire location hierarchy
```
rootLocation = locationrepo.getEntireHierarchy();
```
Gives back the correct and expected response
```
{
  "id":0,
  "name": "parent",
  "children": [
    {
      "id":1
      "name": "child",
      "children": [ ]
    }
  ]
}
```
**_4_**. Create multiple locations under the newly created child node
```
locationRepo.createMultipleLocationsUnderParent(1, 1, 5, "p","s", 2);
```
Created successfully. (newly created nodes can be seen in the Neo4j console)

**_5_**. Now get the entire location hierarchy
```
rootLocation = locationrepo.getEntireHierarchy();
```
Gives back the same response. Notice that the children of **child** node is empty [ ]
```
{
  "id":0,
  "name": "parent",
  "children": [
    {
      "id":1
      "name": "child",
      "children": [ ]
    }
  ]
}
```
**_6_**. Add a new child node to node with **name="child"**
```  
parentNode = findOne(1);
parentNode.getChildren().add(childNode);
locationRepo.save(parentNode);
```
**_7_**.  Now get the entire location hierarchy
```
{
  "id": 0,
  "name": "parent",
  "children": [
    {
      "id": 1",
      name": "child",
      "children": [
        {
          "id": 2,
          "name": "inner-child",
          "children": []
        },
        {
          "id": 3,
          "name": "inner-child",
          "children": []
        }, ...
        // total 6 children as expected
      ]
    }
  ]
}
```

Now we are getting the desired result.

Why Am I not getting the result like step **_7_** in step **_5_**

**Comment by luanne** [comment]
@Query(value = "MATCH (n:LOCATION {level:0}) RETURN n")
    LocationNode getEntireHierarchy()

returns only the root node and no relations and so they are not mapped. You can instead try a derived finder such as findByLevel(0) which uses the default depth 1.

Please read http://graphaware.com/neo4j/2016/04/06/mapping-query-entities-sdn.html for more info on how query results are mapped to entities.

**Comment by NitishDeshpande** [comment]
As mentioned In my question, I am getting the desired output in **_Step 7_**. _(Without changing anything in the code)_  From your comment If this statement  _"returns only the root node and no relations and so they are not mapped"_ is true then I should not be getting the results as in **_Step 7_**

**Comment by luanne** [comment]
In Step 7 you're using findOne isn't it? findOne uses a default depth of 1

**Comment by NitishDeshpande** [comment]
No. I am calling the same method in **_step 7_** `rootLocation = locationrepo.getEntireHierarchy();`

**Comment by luanne** [comment]
Could you send us a test case to demonstrate the issue? Thanks.

**Comment by NitishDeshpande** [comment]
I will do it. Meanwhile I tried using the derived finder `findByLevel(0)` It is fetching all the nodes related to the root node with a depth of 1 as you mentioned. Is there a way to specify a custom depth? I am using `spring-data-neo4j 4.1.2 RELEASE`

**Comment by luanne** [comment]
Depth on derived finders is only supported in SDN 4.2 (currently 4.2.0 M1)

**Comment by NitishDeshpande** [comment]
Achieved the same thing by changing the Cypher query. Had to create a new class to hold the Query result,

```
@Query(value = "MATCH (location:LOCATION) WHERE location.level=0 WITH location MATCH p=(location)-[r:HAS_CHILD*0..4]-() RETURN location, nodes(p), rels(p)")
LocationResult getEntireHierarchy();
```

Class to hold the query result,
```
@QueryResult
public class LocationResult {

	private LocationNode location;

	public LocationNode getLocation() {
		return location;
	}

	public void setLocation(LocationNode location) {
		this.location = location;
	}
}
```
