### ISSUE TITLE
Package org.neo4j.helpers is missing in 4.1.2.RELEASE

### ISSUE THREAD

**Issue by alchemistgo87** [spring-projects/spring-data-neo4j#358]
I am not getting the package: org.neo4j.helpers after upgrading to spring-data-neo4j:4.1.2.RELEASE. If this package is discarded in the new version how to use IteratorUtil or Iterators.

**Comment by mangrish** [comment]
Do you mean package: `org.neo4j.helpers.collection.IteratorUtil`? I don't recommend using a transient/runtime dependency for your own source. You can use http://www.findjar.com/ to track down a compatible jar you are looking for and compile directly against that.

**Comment by alchemistgo87** [comment]
@mangrish I could not find any results on  http://www.findjar.com/  for  org.neo4j.helpers.collection.IteratorUtil. 

My query is that in the previous version spring-data-neo4j:4.0.0.RELEASE  I was able to use IteratorUtil. But its not present in the latest version ie  spring-data-neo4j:4.1.2.RELEASE. So, what alternative should we use for the same?

**Comment by mangrish** [comment]
You can try making `org.neo4j:neo4j-kernal:2.3.6` a dependency which is where IteratorUtil lives.

**Comment by mangrish** [comment]
@alchemistgo87 Did that fix your issue? Please close if so 👍

**Comment by alchemistgo87** [comment]
It worked @mangrish. Thanks a lot for the help.

**Comment by mangrish** [comment]
No problems :)
