### ISSUE TITLE
Provide a way to ignore a property from a NodeEntity

### ISSUE THREAD

**Issue by frosiere** [spring-projects/spring-data-neo4j#359]
It looks their is currently no way to skip a property from a NodeEntity.

It would be nice to have a new annotation like @Ignore or @Property(ignore=true)

**Comment by geld0r** [comment]
I think there is: Annotate the property with @Transient or make the field itself transient (note: the latter didn't work for me, the first did).

As explained in the [documentation](http://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#__nodeentity_the_basic_building_block):
"Marking a field with the transient modifier has the same effect as annotating it with @Transient; it won’t be persisted to the graph database."

**Comment by frosiere** [comment]
The @Transient annotation effectively works. Thanks a lot for the quick response.
