### ISSUE TITLE
Update repositories to allow filtering data using a predicate

### ISSUE THREAD

**Issue by frosiere** [spring-projects/spring-data-neo4j#360]
It would be nice to have a way to filter the nodes to retrieve based on a predicate.

This would help to quickly retrieve results.

See Specification [1] for more details.

[1] http://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/domain/Specifications.html

**Comment by mangrish** [comment]
Hi @frosiere,

SDN has the ability to use the [Neo4jTemplate](http://docs.spring.io/spring-data/neo4j/docs/4.1.2.RELEASE/api/org/springframework/data/neo4j/template/Neo4jTemplate.html) (4.1.x and before) or the OGM [Session](https://github.com/neo4j/neo4j-ogm/blob/2.0/core/src/main/java/org/neo4j/ogm/session/Session.java) (4.2.x and above) with [Filters](https://github.com/neo4j/neo4j-ogm/blob/2.0/core/src/main/java/org/neo4j/ogm/cypher/Filter.java).

It's a little bit different to Specifications but it should do a similar job.

**Comment by frosiere** [comment]
Hello, thanks for the quick response. I was more thinking about something integrated with the repository itself. Like a findAll method having a filter as argument. This feature could either be available if a certain interface is implemented or it could simply be a standard method on the default repository.

If the method is already defined in Neo4jTemplate, it would be straight to add a similar method on the repository.

**Comment by mangrish** [comment]
Well Repository's have their own predicate based filtering.  Are you aware of the [derived finders](http://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#_queries_derived_from_finder_method_names) in `Repository`?

**Comment by frosiere** [comment]
Yes, I'm aware about that really nice feature but in some situations, it looks more flexible to have access to a generic method based on Filters (or predicate or specifications) to avoid methods duplication.

Iterable<T> findAll(Filter filter)

**Comment by mangrish** [comment]
@frosiere While this is a good idea there are several mechanisms in place to deal with the need for more flexibility. The first and easiest are the derived finders and the second and most flexible is the neo4jTemplate/session. Your proposal sits somewhere in between both of these and on top of that doesn't address any of the specialised repository interfaces defined in Spring Data Commons.

In good news through we will be increasing support of Spring Data Commons repository feature set over the coming weeks so hopefully that will add the extra flexibility you are after :)
