### ISSUE TITLE
New configuration error when execute a Neo4jRepository method

### ISSUE THREAD

**Issue by xaxoxavi** [spring-projects/spring-data-neo4j#361]
I'm using the spring-data-neo4j-4.2.0.M1 version and the neo4j-ogm 2.0.5-SNAPSHOT version.

I want to substitute the deprecated abstract class _Neo4jConfiguration_ and the deprecated annotation _@EnableNeo4jRepositories_...

`@Configuration
@EnableNeo4jRepositories(basePackages = "com.xxxxx.xxxxx")
@EnableTransactionManagement
public class Neo4jConfig extends Neo4jConfiguration {
    @Bean
    public org.neo4j.ogm.config.Configuration getConfiguration() {
        org.neo4j.ogm.config.Configuration config = new org.neo4j.ogm.config.Configuration();

          config.driverConfiguration()
                .setDriverClassName("org.neo4j.ogm.drivers.http.driver.HttpDriver")
                .setURI("http://ccccccccc.com:00000/")
                .setCredentials("ccccc","cCccCccCcCccccc");
        return config;
    }

    @Bean
    public Neo4jTransactionManager transactionManager() throws Exception {
        return new Neo4jTransactionManager(getSessionFactory());
    }

    @Bean
    public SessionFactory getSessionFactory() {
        return new SessionFactory(getConfiguration(), "com.xxxxx.xxxxx) {
            @Override
            public Session openSession() {
                Session session = super.openSession();

                session.register(new EventListenerAdapter() {

                    @Override
                    public void onPreSave(Event event) {
                        Object eventObject = event.getObject();
                        if (eventObject instanceof IdentifiableEntity) {
                            IdentifiableEntity entity = (IdentifiableEntity) eventObject;
                            if (entity.getId() == null) entity.setId((String) identifierFactory().generateId());
                        }

                        if (eventObject instanceof CreationDateAware){
                            CreationDateAware creationDateAware = (CreationDateAware) eventObject;
                            creationDateAware.setCreationDate(Calendar.getInstance().getTime());
                        }
                    }
                });
                return session;
            }
        };

         @Bean
         @Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
         public Session getSession() throws Exception {
            return getSessionFactory().openSession();
         }
    }`

... by the new way (with @EnableExperimentalNeo4jRepositories annotation) .....

`@Configuration
@EnableExperimentalNeo4jRepositories(basePackages = "com.xxxxx.xxxxx")
@EnableTransactionManagement
public class Neo4jConfig  {

    @Bean
    public org.neo4j.ogm.config.Configuration getConfiguration() {
        org.neo4j.ogm.config.Configuration config = new org.neo4j.ogm.config.Configuration();
 
       config.driverConfiguration()
                .setDriverClassName("org.neo4j.ogm.drivers.http.driver.HttpDriver")
                .setURI("http://cccccccc.com:00000/")
                .setCredentials("ccccc","ccccccccccccc");
        return config;
    }

    @Bean
    public SessionFactory getSessionFactory() {
        return new SessionFactory(getConfiguration(), "com.xxxxx.xxxxx") {
            @Override
            public Session openSession() {
                Session session = super.openSession();

                session.register(new EventListenerAdapter() {
                    @Override
                    public void onPreSave(Event event) {
                        Object eventObject = event.getObject();
                        if (eventObject instanceof IdentifiableEntity) {
                            IdentifiableEntity entity = (IdentifiableEntity) eventObject;
                            if (entity.getId() == null) entity.setId((String) identifierFactory().generateId());
                        }

                        if (eventObject instanceof CreationDateAware){
                            CreationDateAware creationDateAware = (CreationDateAware) eventObject;
                            creationDateAware.setCreationDate(Calendar.getInstance().getTime());
                        }
                    }
                });
                return session;
            }
        };
    }

    @Bean
    public Neo4jTransactionManager transactionManager() throws Exception {
        return new Neo4jTransactionManager(getSessionFactory());
    }
`

But when I execute a method of the _Neo4jRepository_  I have this exception:

`java.lang.IllegalStateException: No Neo4j Session bound to thread, and configuration does not allow creation of non-transactional one here at org.springframework.data.neo4j.transaction.SessionFactoryUtils.getSession(SessionFactoryUtils.java:66) at org.springframework.data.neo4j.transaction.SharedSessionCreator$SharedSessionInvocationHandler.invoke(SharedSessionCreator.java:90)
	at com.sun.proxy.$Proxy41.resolveGraphIdFor(Unknown Source)
	at org.springframework.data.neo4j.repository.query.GraphRepositoryQuery.resolveParams(GraphRepositoryQuery.java:133) 	at org.springframework.data.neo4j.repository.query.GraphRepositoryQuery.execute(GraphRepositoryQuery.java:64) 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:482)	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)`

I've tried to add a Session bean with prototype session scope (like the older way), but It not works because there are two Session beans for autowire.

**Comment by mangrish** [comment]
Spring is pedantic about naming.

You have called your session factory bean `getSessionFactory` rather than `sessionFactory` which is what SDN expects. This means it won't find the session factory by name.

Try changing this to `sessionFactory()` and see if it fixes the issue.

[Documentation](http://docs.spring.io/spring-data/neo4j/docs/4.2.0.M1/reference/html/#reference.getting_started.spring-configuration.java)

**Comment by xaxoxavi** [comment]
It seems doesn't work. The same error.

**Comment by mangrish** [comment]
Can you please try with: 4.2.0.BUILD-SNAPSHOT

**Comment by mangrish** [comment]
I can't recreate this. Could you supply a test please?

**Comment by xaxoxavi** [comment]
Hello @mangrish ,
I did a test with the  4.2.0.BUILD-SNAPSHOT  with the configurations above and it works for the `Neo4jRepository`. Thanks.

The problem now is that I can't use the Session object directly (in a prototype scope) because when Spring creates the `Neo4jRepository` bean,  two candidates exists:

```
17:46:37.237 [main] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'test': Unsatisfied dependency expressed through field 'repository': Error creating bean with name 'exampleRepository': Unsatisfied dependency expressed through method 'setSession' parameter 0: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exampleRepository': Unsatisfied dependency expressed through method 'setSession' parameter 0: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'test': Unsatisfied dependency expressed through field 'repository': Error creating bean with name 'exampleRepository': Unsatisfied dependency expressed through method 'setSession' parameter 0: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exampleRepository': Unsatisfied dependency expressed through method 'setSession' parameter 0: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.neo4j.ogm.session.Session] is defined: expected single matching bean but found 2: getSession,org.springframework.data.neo4j.transaction.SharedSessionCreator#0
```

You can see this test at: https://github.com/xaxoxavi/spring-data-neo4j-test/blob/master/src/main/java/my/example/Test.java

**Comment by mangrish** [comment]
@xaxoxavi You need to remove this:

```
    @Bean
    @Scope(value = "prototype", proxyMode = ScopedProxyMode.TARGET_CLASS)
    public Session getSession() throws Exception {
        return sessionFactory().openSession();
    }
```

from: https://github.com/xaxoxavi/spring-data-neo4j-test/blob/master/src/main/java/my/example/config/Neo4jConfig.java as well as remove any references to `getSession` (using `@Qualifier`). You can just `@Autowired` `Session` into any spring managed component. Be sure to wrap any calls through session in an `@Transactional` to make sure a thread is available to handle the work.

and it should all work.

Developers are no longer responsible for proxying and defining the lifecycle of sessions.

Also note that our next candidate release of SDN will have some slight name changes to the names of things from M1. We'll publish a blog post when that happens.

**Comment by mangrish** [comment]
@xaxoxavi I'm going to close this issue. If you still have problems regarding this issue please reopen. If you have any general questions please raise either a new issue or drop us a line on Slack :)
