### ISSUE TITLE
Paging and sorting not working for custom queries when returning QueryResult

### ISSUE THREAD

**Issue by jefalbino** [spring-projects/spring-data-neo4j#362]
I have tested the 4.2.0.M1 that according to the issue DATAGRAPH-653 (http://stackoverflow.com/questions/30624435/paging-and-sorting-in-spring-data-neo4j-4/30625554)  should provide sorting and paging for custom queries but it is not working when the return is using QueryResult.

Example:

```
@Query("MATCH (a:Account)--(u:User) WHERE a.code={accountCode} RETURN a.name AS name, COUNT(u.code) AS users")
List<GroupResult> findAllByType(@Param("accountCode") String accountCode, Pageable pageable);
```

**Comment by mangrish** [comment]
Hi @jefalbino,

Sorry for the delay. Can you try 4.2.0.BUILD-SNAPSHOT and see if you get the same error?

You see how to get set up with that version [here](http://graphaware.com/neo4j/2016/09/30/upgrading-to-sdn-42.html).

**Comment by jefalbino** [comment]
Hi @mangrish, let me try!

**Comment by mangrish** [comment]
Closing. Please reopen in https://jira.spring.io/browse/DATAGRAPH if this is still an issue.
