### ISSUE TITLE
Problem removing relationships when multiple custom relationships of the same type exist between the same two entities

### ISSUE THREAD

**Issue by shinyhut** [spring-projects/spring-data-neo4j#370]
Suppose I have two Node Entity types A and B and create nodes A1, B1, and B2.

I define a Relationship Entity type R with a property 'sequence', start node A, end node B, and create the following relationships:

A1------ R (sequence: 0)------->B1
A1------ R (sequence: 1)------->B1
A1------ R (sequence: 2)------->B2
A1------ R (sequence: 3)------->B2
A1------ R (sequence: 4)------->B1
A1------ R (sequence: 5)------->B1

I am able to create and persist this graph just fine using Spring Data, but problems arise when I try to update it:

Issue 1: Remove all entries
If I try to remove all the relationships from A1's set and call save(), when I check A1, it still has 4 relationships left. It appears the framework is only deleting one relationship for each of B1 and B2.

Issue 2: Update entries
I try to remove all the existing relationships and re-create as follows:

A1------ R (sequence: 0)------->B1
A1------ R (sequence: 1)------->B1
A1------ R (sequence: 2)------->B2
A1------ R (sequence: 3)------->B2

I would expect A1 to now have just the 4 relationships set out above, but it now has 10 (i.e. the 6 original entries plus the 4 I just added, despite the Set of Rs being emptied before the replacement relationships were created).

Here are the relevant code snippets:

```
@NodeEntity
public class EntityA {

    @GraphId
    public Long id;

    @Relationship(type = "CUSTOM_RELATIONSHIP")
    public Set<CustomRelationship> entityBs = new HashSet<>();

    public String name;

}

@NodeEntity
public class EntityB {

    @GraphId
    public Long id;

    public String name;

}

@RelationshipEntity(type = "CUSTOM_RELATIONSHIP")
public class CustomRelationship {
    @GraphId
    public Long id;

    @Property
    public Integer sequence;

    @StartNode
    public EntityA entityA;

    @EndNode
    public EntityB entityB;
}
```

Here is the 'create' method, which works fine:

```
public EntityA createEntityA(String name, List<Long> entityBIds) {
    EntityA entityA = new EntityA();
    entityA.name = name;

    for (int i = 0; i < entityBIds.size(); i++) {
        EntityB entityB = entityBRepository.findOne(entityBIds.get(i));

        CustomRelationship relationship = new CustomRelationship();
        relationship.entityA = entityA;
        relationship.entityB = entityB;
        relationship.sequence = i;

        entityA.entityBs.add(relationship);
    }

    return entityARepository.save(entityA);
}
```

And here is the 'update' method, which seems to be problematic when the original list contained references to the same entity at more than one position:

```
public void updateEntityA(Long id, String name, List<Long> entityBIds) {
    EntityA entityA = entityARepository.findOne(id);
    entityA.name = name;

    entityA.entityBs.clear();

    for (int i = 0; i < entityBIds.size(); i++) {
        EntityB entityB = entityBRepository.findOne(entityBIds.get(i));

        CustomRelationship relationship = new CustomRelationship();
        relationship.entityA = entityA;
        relationship.entityB = entityB;
        relationship.sequence = i;

        entityA.entityBs.add(relationship);
    }

    entityARepository.save(entityA);
}
```

The full example project demonstrating this issue is here: https://github.com/shinyhut/Neo4JTest - see the test cases in "EntityAServiceTest'

**Comment by mangrish** [comment]
@shinyhut We are currently investigating an issue in 2.1.0-SNAPSHOT which might have affected 2.0.x users regarding your problem. I'll update this thread when we have a fix andsoyou can try out see if it resolves this problem before we investigate this issue further.

**Comment by shinyhut** [comment]
Thanks @mangrish. Is there a ticket for the 2.1.0-SNAPSHOT issue?

**Comment by mangrish** [comment]
https://github.com/neo4j/neo4j-ogm/issues/261

**Comment by mangrish** [comment]
@shinyhut: Does this work now? The fix went through the OGM.

**Comment by mangrish** [comment]
Closing. Please reopen if you still have issues.
