### ISSUE TITLE
Neo4j graph db nodes relationships not getting committed with SpringBoot

### ISSUE THREAD

**Issue by lalitbansal1** [spring-projects/spring-data-neo4j#374]
I'm using Spring Boot to populate my Neo4j grapb db entities (So, i've my pom referring to parent as `spring-boot-starter-parent` and have imported dependency of `spring-boot-starter-data-neo4j` along with other dependencies).
I'm using 1.4.2.RELEASE of SpringBoot.
Neo4j version is 3.0.7 and is the community edition.

I'm observing a weird issue after I populate my graph db with entities and their relationships.

I see that, many times, few of the relationships do not get committed and on querying via Cypher sql, I get "no rows".
I've observed this issue when running my code (to populate neo4j graph db) 
More strangely what I've observed is that if I run my code in debug mode (with few breakpoints) to try to debug the issue, I can see nothing wrong in my code logic and on completion of debug mode if I query, I find relationships committed and I get correct results after firing Cypher sql.
However, running the same code logic in normal mode, I end up getting "no rows".

This is a very weird behavior and I don't know if there is a definite pattern to it (apart from fact that debug mode gives me the desired results whilst normal mode does not).
Also not sure what other info I can share on this forum to suggest me any pointers to this issue.

Thanks in advance for any help !

**Comment by mangrish** [comment]
@lalitbansal1 What version of the Neo4j OGM & Spring Data Neo4j (SDN) are you running? Do you have any sample code/project we can try to replicate your issue?

**Comment by mangrish** [comment]
@lalitbansal1: If you would like us to keep looking at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
