### ISSUE TITLE
Can not save relationshipentity correctly!

### ISSUE THREAD

**Issue by billho** [spring-projects/spring-data-neo4j#375]
**I use SND 4.1.4 to persist my data , and lots of old RelationShipEntitys were delete when saving new one.** 
some core code as below:

1. Define NodeEntity and RelationshipEntity:
```
@Data
@NodeEntity
@NoArgsConstructor
public class Node{
	@GraphId
	Long graphId;
	@NonNull
	String text;
}
```

```
@Data
@NodeEntity
@NoArgsConstructor
public class Phrase {
	@GraphId
        Long graphId;
	@NonNull
	String text;
}
```

```
@Data
@RelationshipEntity(type="phrasenode")
public class PhraseNodeRelation {
	@GraphId
	private Long graphId;
	@StartNode
	private Phrase phrase;
	@EndNode
	private Node outline;
	//@RelationshipType
	@Property
	private String relationName = "phrasenode";
}
```

2、Define Repositories

```
public interface PhraseNodeRelationRepo extends GraphRepository<PhraseNodeRelation>{ }

public interface PhraseRepo extends GraphRepository<Phrase>{ }

public interface NodeRepo extends GraphRepository<Node>{ }

```

3、Save Entity and RelaitonshipEntity

```
@autowired
PhraseNodeRelationRepo  relrepo;
@autowired
PhraseRepo  prepo;
@autowired
NodeRepo  nrepo;

public void save(){
    Phrase p = new Phrase();//set props
    Phrase p1 = new Phrase();//set props
    Phrase p2= new Phrase();//set props
    Node o = new Node();//set props
    prepo.save(p);
    prepo.save(p1);
    prepo.save(p2);
    
    nrepo.save(o);

    PhreaseNodeRelation rel = new PhraseNodeRelation(p,o);
    PhreaseNodeRelation rel1 = new PhraseNodeRelation(p1,o);
    PhreaseNodeRelation rel2 = new PhraseNodeRelation(p2,o);

    relrepo.save(rel);
    relrepo.save(rel1);
    relrepo.save(rel2);
}
```

**4、And finally, I only got `rel2` store in my neo4j database. `rel` and `rel1` was deleted automatically.** 

Can someone help me ? Thank you a lot.

**Comment by mangrish** [comment]
Can you please try with SDN version 4.2.0.BUILD-SNAPSHOT and OGM 2.1.0-SNAPSHOT please?

**Comment by billho** [comment]
@mangrish I use spring-boot-starter-data-neo4j , can you tell me the  spring-boot-starter-data-neo4j version?

**Comment by billho** [comment]
@mangrish I use spring-boot-starter-data-neo4j   2.0.0.BUILD-SNAPSHOT , It seems ok.

**Comment by mangrish** [comment]
@billho OK. So everything is working with that version? You can see a migration guide from 4.1 to 4.2 here: http://graphaware.com/neo4j/2016/09/30/upgrading-to-sdn-42.html. If everything is good let me know or please close 👍

**Comment by billho** [comment]
@mangrish I will test for one or two days , then will let you know the result. Thank you for you help.
