### ISSUE TITLE
Why can not read the relaionship of an entity?

### ISSUE THREAD

**Issue by billho** [spring-projects/spring-data-neo4j#376]
1.entity
```
public class OutlineHNode{
        ....//pros
	@Relationship(type="suboutline",direction=Relationship.OUTGOING)
	private Set<OutlineHNode> childNodes=new HashSet<OutlineHNode>();

	@Relationship(type="phraseoutline",direction=Relationship.INCOMING)
	private Set<OutlinePhrase> phrases= new HashSet<OutlinePhrase>();
}
```

2.Repository

```
public interface INeo4jRepo extends GraphRepository<OutlineHNode>{
	
	@Query("START n=node({id}) RETURN n")
	@Depth(value=3)
	public OutlineHNode findById(@Param("id") long id);
}
```

3. run

```
 @Bean
    public boolean testNeoj() {
		val node = neo4jRepo.findById(10L);
		node.getPhrases().forEach(System.out::println);
                node.getChildNodes().forEach(System.out::println);
		System.out.println(node);
		return true;
	}
```

## Then, `node.getPhrases()` and `node.getChildNodes()` always empty. Why ?

The new version SDN makes me very confused.

**Comment by billho** [comment]
using SDN 4.2.0-SNAPSHOT and OGM 2.1.0M01

**Comment by mangrish** [comment]
@billho There are several things going on that will result in why `getPhrases()` and `getChildNodes()` doesn't work.

`GraphRepository` already has a `findById()` method built in. In your `testNeoj()` method replace the call to `val node = neo4jRepo.findById(10L);` with `val node = neo4jRepo.load(OutlineHNode.class, 10L, 3);`. You can delete the method you have in `INeo4jRepo`.

Furthermore the use the `@Depth` annotation with a custom query is not currently supported or documented (well). We are looking in to how we can support finer grained loading policies: https://github.com/neo4j/neo4j-ogm/issues/70.

I hope that clears up your confusion. Which version of SDN are you migrating to 4.2 from?

**Comment by billho** [comment]
@mangrish there is not a `load()` method bulit in  `GraphRepository` or other interface it extends, so I use `val node =  neo4jRepo.findOne(10L,1);` instead. This time `getPhrases()` works but 'getChildNodes()' dosen't ,even I change the `depth` param  to 3 or more. And I migrating from V 3.2.4 .

**Comment by mangrish** [comment]
@billho Sorry I gave you the underlying OGM method name. `findOne()` is the correct method as you have found.

Is `OutlineHNode` annotated with `@EntityNode`?

If it is can you confirm in your database that your graph has the right pattern. You should see: `(: OutlineHNode)-[:suboutline]->(:OutlineHNode)`.

**Comment by billho** [comment]
@mangrish Yes .I can confirm about the database and the entity definition.
here is the database :
![image](https://cloud.githubusercontent.com/assets/7029336/20693438/68a16808-b619-11e6-8051-3ed56c2e7a7c.png)

and the @EntityNode

```
@Data
@NodeEntity
@RequiredArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(of={"graphId"})
@ToString(of={"text","graphId"})
public class OutlineHNode{
	@GraphId
    private Long graphId;
	@NonNull
	String text;
	
	@NonNull
	Integer year;
	
	@NonNull
	String articleId;
	@NonNull
	String outlineId;
	
	@Relationship(type="suboutline")
	private Set<OutlineHNode> childNodes=new HashSet<OutlineHNode>();

	@Relationship(type="phraseoutline",direction=Relationship.INCOMING)
	private Set<OutlinePhrase> phrases= new HashSet<OutlinePhrase>();
}
```

What more , these data into neo4j is persisted by the same data model.

**Comment by mangrish** [comment]
Can you kill the `equalsAndHashCode`? You don't need that on your model anymore.

I might need to debug this one. If you have a small project I can use send it over or link on GH otherwise I'll try taking a look soon.

In the mean time if you need to just get it working type out the full query in the Repository method. Something like this should work:

```
public interface INeo4jRepo extends GraphRepository<OutlineHNode>{
	
	@Query("MATCH (n:OutlineHNode{id:{id}}) OPTIONAL MATCH -[r: suboutline| phraseoutline]-(m) RETURN n, r, m")
	public OutlineHNode findById(@Param("id") long id);
}
```

**Comment by billho** [comment]
@mangrish Here is the small project . https://github.com/billho/neodebug .
 
please let me know if I have something wrong .

**Comment by billho** [comment]
@mangrish  One more thing ,you can visit my database directly (can find it in the `application.properties` file.). Please let me know when you don't need it anymore.

**Comment by mangrish** [comment]
@luanne Will look into this for you @billho. We'll hopefully work out what going on in the next couple of hours.

**Comment by luanne** [comment]
@billho why do you have a relationship entity called `OutlineRelation`? It does not seem to be used but the type defined on it is `suboutline` which conflicts with the simple relationship type `suboutline` used in `OutlineHNode.childNodes`

**Comment by billho** [comment]
@luanne I use it to store a rich relationship in another part of application, which not presented at this small project. I also has a relationship entity call `PhraseOutlineRelation ` which has the same (conflicted) type definition with ` OutlineHNode.getPhrases()` , but  `OutlineHNode.getPhrases()` works fine.

**Comment by billho** [comment]
I don't think using the same relationship type in different Entities/RelationshipEntities  should lead to a conflicted situation, because the relationship type inside an Entity is unique.  In my case, `OutlineHNode` has only one `suboutline`, while querying and ogm-ing , there is the only one type of object (`OutlineHNode`) should map to.

**Comment by luanne** [comment]
@billho if you have a relationship entity  `OutlineRelation`, then you'd need to use that in `OutlineHNode` e.g.

```
@Relationship(type="suboutline")
	private Set<OutlineRelation> childNodes=new HashSet<OutlineRelation>();
```

When the OGM tries to map the relationship of type `suboutline`, the metadata tells it that this is represented by a RelationshipEntity `OutlineRelation`- and it maps to this relationship entity. But there isn't anything in class `OutlineHNode` that uses this relationship entity, so it is ignored.

**Comment by billho** [comment]
I have change my data model so that can read all of relationships now, But another problem comes : I wish to travel  from one determinate node to all of its leaves, but the depth is inconstant (some leaves' depth are 3, some 4 or more).  if I set the depth to 4 or 5, neo4j will take a very long time, but if set to 1 or 2, I can not get deeper data. Is there any way to solve this problem? Like  the old way `@Fetch` . @mangrish @luanne

**Comment by luanne** [comment]
What does your query look like? Or are you using a finder with depth?

**Comment by mangrish** [comment]
@billho If you would like us to keep looking at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by billho** [comment]
@luanne  The query is :
```
@autowired 
INeo4jRepo  repo;
....
val node = repo.findOne(10L,1);
```
And then I wish I can traverse the whole subtree  from `node` like this:
```
      private void traverse(OutlineHNode node) {
		while (node.getChildNodes().size()>0) {
			node.getChildNodes().forEach(n->{
				log.info(n);
				traverse(n);
			});
		}
	}
```

The problem is : the traverse processing will stop because some of `node.getChildNodes()` is Null or Empty. 
But if i set the Max Depth  to `repo.findOne`, it will take a very long time.
Is there better way ?

**Comment by mangrish** [comment]
This issue has been moved to: https://jira.spring.io/browse/DATAGRAPH-954
