### ISSUE TITLE
Spring data neo4j repositories not working since DATAGRAPH-939

### ISSUE THREAD

**Issue by tigrou83** [spring-projects/spring-data-neo4j#384]
I'm using:

Spring-data-neo4j 4.2.0-SNAPSHOT (tried with 4.2.0.RC1 too)

and since the DATAGRAPH-939 commit, I'm not able to work with repositories anymore.

    @Repository
    public interface MyEventRepository extends GraphRepository<Event> {}

The error:

    Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myEventRepository': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.Class<org.springframework.data.repository.Repository<?, ?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
    	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:735)
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
    	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
    	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
    	... 25 common frames omitted
    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.Class<org.springframework.data.repository.Repository<?, ?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1466)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1097)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
    	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
    	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
    	... 41 common frames omitted

Here is an example of my failing test:

    @RunWith(SpringJUnit4ClassRunner.class)
    @ContextConfiguration(loader = AnnotationConfigContextLoader.class, classes = { SimpleTest.TestConfiguration.class })
    public class SimpleTest {
        
        @Configuration
        @EnableNeo4jRepositories("com.nagra.ml.sp.cpm.core.repositories.test")
        public static class TestConfiguration {

            @Bean
            public org.neo4j.ogm.config.Configuration configuration() {
                org.neo4j.ogm.config.Configuration config = new org.neo4j.ogm.config.Configuration();
            config  .driverConfiguration()
                    .setDriverClassName("org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver");
                return config;
            }
            
            @Bean
            public SessionFactory sessionFactory() {
                return new SessionFactory(configuration(), "com.nagra.ml.sp.cpm.model");
            }
        
            @Bean
            public Neo4jTransactionManager transactionManager() {
                return new Neo4jTransactionManager(sessionFactory());
            }
        }
        
        @Test
        public void test() {
            assertTrue(true);
        }
    }

According to documentation, the way of declaring repositories seems to be correct, am I doing something wrong ?

Thanks

**Comment by mangrish** [comment]
@tigrou83 I've run your test and it passes. Can you run `mvn dependency:tree` and paste the results please?

**Comment by tigrou83** [comment]
Here is the maven dependency tree:

com.nagra.ml.sp.cms.cpm:ml-sp-cpm-core:jar:5.6.2
[INFO] +- com.nagra.ml.sp.cms.cpm:ml-sp-cpm-fwk:jar:5.6.2:compile
[INFO] |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  +- org.zeroturnaround:zt-zip:jar:1.10:compile
[INFO] |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- com.nagra.ml.sp.cms.cpm:ml-sp-cpm-model:jar:5.6.2:compile
[INFO] +- com.nagra.ml.sp.cms.cpm:ml-sp-cpm-api:jar:5.6.2:compile
[INFO] +- com.nagra.ml.sp.bcm:ml-sp-bcm-api:jar:1.1.2:compile
[INFO] |  \- javax.ws.rs:javax.ws.rs-api:jar:2.0:compile
[INFO] +- com.nagra.ml.sp.cwm:ml-sp-cwm-api:jar:1.2.2:compile
[INFO] |  +- org.apache.camel:camel-jaxb:jar:2.17.3:compile
[INFO] |  +- org.apache.camel:camel-jackson:jar:2.17.3:compile
[INFO] |  +- org.apache.camel:camel-xmljson:jar:2.17.3:compile
[INFO] |  |  \- net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[INFO] |  |     +- commons-beanutils:commons-beanutils:jar:1.9.3:compile
[INFO] |  |     \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] |  +- org.apache.camel:camel-cxf:jar:2.17.3:compile
[INFO] |  |  +- org.apache.camel:camel-cxf-transport:jar:2.17.3:compile
[INFO] |  |  |  \- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.1.7:compile
[INFO] |  |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  |  +- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.1.7:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.1.7:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-addr:jar:3.1.7:compile
[INFO] |  |  |     \- org.apache.cxf:cxf-rt-ws-policy:jar:3.1.7:compile
[INFO] |  |  |        \- org.apache.neethi:neethi:jar:3.0.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-rs-security-oauth:jar:3.1.7:compile
[INFO] |  |  |  \- net.oauth.core:oauth-provider:jar:20100527:compile
[INFO] |  |  |     \- net.oauth.core:oauth:jar:20100527:compile
[INFO] |  |  \- org.apache.cxf:cxf-rt-bindings-soap:jar:3.1.7:compile
[INFO] |  |     +- org.apache.cxf:cxf-rt-wsdl:jar:3.1.7:compile
[INFO] |  |     |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |     \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.1.7:compile
[INFO] |  +- xom:xom:jar:1.2.5:compile
[INFO] |  |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  |  +- xerces:xercesImpl:jar:2.8.0:compile
[INFO] |  |  \- xalan:xalan:jar:2.7.0:compile
[INFO] |  \- org.apache.camel:camel-script:jar:2.17.3:compile
[INFO] +- org.neo4j:neo4j:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-kernel:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-graphdb-api:jar:3.0.7:compile
[INFO] |  |  |  \- org.neo4j:neo4j-resource:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-common:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-collections:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-primitive-collections:jar:3.0.7:compile
[INFO] |  |  |  \- org.neo4j:neo4j-unsafe:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-io:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-csv:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-logging:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-security:jar:3.0.7:compile
[INFO] |  |  \- org.neo4j:neo4j-lucene-upgrade:jar:3.0.7:compile
[INFO] |  |     \- org.apache.lucene:lucene-backward-codecs:jar:5.5.0:compile
[INFO] |  +- org.neo4j:neo4j-lucene-index:jar:3.0.7:compile
[INFO] |  |  +- org.apache.lucene:lucene-analyzers-common:jar:5.5.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-core:jar:5.5.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queryparser:jar:5.5.0:compile
[INFO] |  |  \- org.apache.lucene:lucene-codecs:jar:5.5.0:compile
[INFO] |  +- org.neo4j:neo4j-graph-algo:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-udc:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-graph-matching:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-cypher:jar:3.0.7:compile
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.11.8:compile
[INFO] |  |  +- org.scala-lang:scala-reflect:jar:2.11.8:compile
[INFO] |  |  +- org.neo4j:neo4j-codegen:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-cypher-compiler-2.3:jar:2.3.7:compile
[INFO] |  |  |  \- org.neo4j:neo4j-cypher-frontend-2.3:jar:2.3.7:compile
[INFO] |  |  +- org.neo4j:neo4j-cypher-compiler-3.0:jar:3.0.7:compile
[INFO] |  |  |  \- org.neo4j:neo4j-cypher-frontend-3.0:jar:3.0.7:compile
[INFO] |  |  +- org.parboiled:parboiled-scala_2.11:jar:1.1.7:compile
[INFO] |  |  |  \- org.parboiled:parboiled-core:jar:1.1.7:compile
[INFO] |  |  +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |  |  \- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.2:compile
[INFO] |  +- org.neo4j:neo4j-jmx:jar:3.0.7:compile
[INFO] |  \- org.neo4j:neo4j-consistency-check:jar:3.0.7:compile
[INFO] +- org.neo4j:neo4j-enterprise:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-query-logging:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-com:jar:3.0.7:compile
[INFO] |  |  +- org.neo4j:neo4j-enterprise-kernel:jar:3.0.7:compile
[INFO] |  |  \- io.netty:netty:jar:3.9.9.Final:compile
[INFO] |  +- org.neo4j:neo4j-backup:jar:3.0.7:compile
[INFO] |  +- org.neo4j:neo4j-ha:jar:3.0.7:compile
[INFO] |  \- org.neo4j:neo4j-management:jar:3.0.7:compile
[INFO] +- org.springframework.data:spring-data-neo4j:jar:4.2.0.RC1:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.4.RELEASE:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.12.5.RELEASE:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] +- org.neo4j:neo4j-ogm-core:jar:2.1.0:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] |  \- com.e-movimento.tinytools:privilegedaccessor:jar:1.2.2:compile
[INFO] +- org.neo4j:neo4j-ogm-api:jar:2.1.0:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- org.neo4j:neo4j-ogm-compiler:jar:2.1.0:compile
[INFO] +- org.neo4j:neo4j-ogm-http-driver:jar:2.1.0:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] +- org.neo4j:neo4j-ogm-embedded-driver:jar:2.1.0:compile
[INFO] |  \- org.neo4j:neo4j-cluster:jar:3.0.7:compile
[INFO] +- org.neo4j:neo4j-ogm-bolt-driver:jar:2.1.0:test
[INFO] |  \- org.neo4j.driver:neo4j-java-driver:jar:1.1.0:test
[INFO] +- org.apache.camel:camel-core:jar:2.17.3:compile
[INFO] |  +- com.sun.xml.bind:jaxb-core:jar:2.2.11:compile
[INFO] |  \- com.sun.xml.bind:jaxb-impl:jar:2.2.11:compile
[INFO] +- org.apache.camel:camel-spring:jar:2.17.3:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.3.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.3.4.RELEASE:compile
[INFO] +- org.apache.camel:camel-spring-javaconfig:jar:2.17.3:compile
[INFO] |  \- org.apache.servicemix.bundles:org.apache.servicemix.bundles.cglib:jar:3.2.0_1:compile
[INFO] +- org.apache.camel:camel-saxon:jar:2.17.3:compile
[INFO] |  \- net.sf.saxon:Saxon-HE:jar:9.5.1-5:compile
[INFO] +- org.apache.camel:camel-quartz2:jar:2.17.3:compile
[INFO] |  +- org.quartz-scheduler:quartz:jar:2.2.2:compile
[INFO] |  \- com.mchange:c3p0:jar:0.9.5.2:compile
[INFO] |     \- com.mchange:mchange-commons-java:jar:0.2.11:compile
[INFO] +- org.apache.camel:camel-ftp:jar:2.17.3:compile
[INFO] |  +- com.jcraft:jsch:jar:0.1.53:compile
[INFO] |  \- commons-net:commons-net:jar:3.3:compile
[INFO] +- org.apache.camel:camel-test-spring:jar:2.17.3:test
[INFO] |  +- org.apache.camel:camel-test:jar:2.17.3:test
[INFO] |  \- org.springframework:spring-test:jar:4.3.4.RELEASE:test
[INFO] +- org.drools:drools-decisiontables:jar:6.5.0.Final:compile
[INFO] |  +- org.drools:drools-core:jar:6.5.0.Final:compile
[INFO] |  |  \- org.mvel:mvel2:jar:2.2.8.Final:compile
[INFO] |  +- org.drools:drools-compiler:jar:6.5.0.Final:compile
[INFO] |  |  +- org.antlr:antlr-runtime:jar:3.5:compile
[INFO] |  |  +- org.eclipse.jdt.core.compiler:ecj:jar:4.4.2:compile
[INFO] |  |  +- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
[INFO] |  |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:2.6.0:compile
[INFO] |  +- org.drools:drools-templates:jar:6.5.0.Final:compile
[INFO] |  +- org.kie:kie-api:jar:6.5.0.Final:compile
[INFO] |  +- org.kie:kie-internal:jar:6.5.0.Final:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:3.13:compile
[INFO] |  |  \- org.apache.poi:poi-ooxml-schemas:jar:3.13:compile
[INFO] |  |     \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |  |        \- stax:stax-api:jar:1.0.1:compile
[INFO] |  \- org.apache.poi:poi:jar:3.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.4.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.4.2.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.2.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] |  +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.3:compile
[INFO] |  +- org.springframework:spring-web:jar:4.3.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.3.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-jetty:jar:1.4.2.RELEASE:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util:jar:9.3.14.v20161028:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.3.14.v20161028:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.3.14.v20161028:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.3.14.v20161028:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-security:jar:9.3.14.v20161028:compile
[INFO] |  +- org.eclipse.jetty.websocket:websocket-server:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.3.14.v20161028:compile
[INFO] |  |  |  \- org.eclipse.jetty.websocket:websocket-api:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.3.14.v20161028:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-servlet:jar:9.3.14.v20161028:compile
[INFO] |  +- org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:9.3.14.v20161028:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-annotations:jar:9.3.14.v20161028:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-plus:jar:9.3.14.v20161028:compile
[INFO] |  |  |  \- org.ow2.asm:asm-commons:jar:5.0.1:compile
[INFO] |  |  |     \- org.ow2.asm:asm-tree:jar:5.0.1:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:javax-websocket-client-impl:jar:9.3.14.v20161028:compile
[INFO] |  |  \- javax.websocket:javax.websocket-api:jar:1.0:compile
[INFO] |  \- org.mortbay.jasper:apache-el:jar:8.0.33:compile
[INFO] +- org.springframework.boot:spring-boot-actuator:jar:1.4.2.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:1.4.2.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.2.RELEASE:compile
[INFO] +- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.1.8:compile
[INFO] |  +- org.apache.cxf:cxf-core:jar:3.1.8:compile
[INFO] |  |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.1:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  \- org.apache.cxf:cxf-rt-transports-http:jar:3.1.8:compile
[INFO] +- org.apache.cxf:cxf-rt-rs-service-description:jar:3.1.8:compile
[INFO] +- org.apache.cxf:cxf-rt-rs-client:jar:3.1.8:compile
[INFO] +- org.apache.cxf:cxf-rt-transports-http-hc:jar:3.1.8:compile
[INFO] |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.4:compile
[INFO] +- org.apache.cxf:cxf-rt-transports-local:jar:3.1.8:test
[INFO] +- io.hawt:hawtio-core:jar:2.0.0:compile
[INFO] |  \- io.hawt:hawtio-util:jar:2.0.0:compile
[INFO] +- io.hawt:hawtio-system:jar:2.0.0:compile
[INFO] |  +- io.hawt:hawtio-git:jar:2.0.0:compile
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.3.1:compile
[INFO] |  +- org.osgi:org.osgi.core:jar:4.3.0:compile
[INFO] |  \- org.osgi:org.osgi.enterprise:jar:4.2.0:compile
[INFO] +- io.hawt:hawtio-plugin-mbean:jar:2.0.0:compile
[INFO] +- io.hawt:hawtio-springboot:jar:2.0.0:compile
[INFO] +- io.hawt:hawtio-web:war:2.0.0:compile
[INFO] +- org.jolokia:jolokia-core:jar:1.3.5:compile
[INFO] |  \- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  +- com.google.guava:guava:jar:15.0:compile
[INFO] |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] +- org.codehaus.janino:janino:jar:2.7.8:compile
[INFO] |  \- org.codehaus.janino:commons-compiler:jar:2.7.8:compile
[INFO] +- com.nagra.ml.sp.cms.cpm:ml-sp-cpm-test-fwk:jar:5.6.2:test
[INFO] +- bad.robot:simple-excel:jar:1.0:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  \- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- org.unitils:unitils-core:jar:3.4.2:test
[INFO] |  +- commons-logging:commons-logging:jar:1.1:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- ognl:ognl:jar:2.6.9:test
[INFO] +- com.nagra.ml.sp.bcm:ml-sp-bcm-fwk:jar:1.1.2:test
[INFO] |  \- io.dropwizard:dropwizard-core:jar:0.9.2:test
[INFO] |     +- io.dropwizard:dropwizard-util:jar:0.9.2:test
[INFO] |     |  +- com.google.code.findbugs:jsr305:jar:3.0.1:test
[INFO] |     |  \- joda-time:joda-time:jar:2.9.5:test
[INFO] |     +- io.dropwizard:dropwizard-jackson:jar:0.9.2:test
[INFO] |     |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk7:jar:2.6.3:test
[INFO] |     |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.8.4:test
[INFO] |     |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.6.3:test
[INFO] |     |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.8.4:test
[INFO] |     +- io.dropwizard:dropwizard-validation:jar:0.9.2:test
[INFO] |     |  \- org.glassfish:javax.el:jar:3.0.0:test
[INFO] |     +- io.dropwizard:dropwizard-configuration:jar:0.9.2:test
[INFO] |     |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.4:test
[INFO] |     +- io.dropwizard:dropwizard-logging:jar:0.9.2:test
[INFO] |     |  +- io.dropwizard.metrics:metrics-logback:jar:3.1.2:test
[INFO] |     |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |     +- io.dropwizard:dropwizard-metrics:jar:0.9.2:test
[INFO] |     +- io.dropwizard:dropwizard-jersey:jar:0.9.2:test
[INFO] |     |  +- org.glassfish.jersey.core:jersey-server:jar:2.23.2:test
[INFO] |     |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.23.2:test
[INFO] |     |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.23.2:test
[INFO] |     |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:test
[INFO] |     |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.23.2:test
[INFO] |     |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.23.2:test
[INFO] |     |  |  +- org.glassfish.hk2:hk2-api:jar:2.5.0-b05:test
[INFO] |     |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.5.0-b05:test
[INFO] |     |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b05:test
[INFO] |     |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b05:test
[INFO] |     |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0-b05:test
[INFO] |     |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.22.1:test
[INFO] |     |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.23.2:test
[INFO] |     |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.2:test
[INFO] |     |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.23.2:test
[INFO] |     |  |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.23.2:test
[INFO] |     |  \- org.eclipse.jetty:jetty-server:jar:9.3.14.v20161028:compile
[INFO] |     +- io.dropwizard:dropwizard-servlets:jar:0.9.2:test
[INFO] |     |  \- io.dropwizard.metrics:metrics-annotation:jar:3.1.2:test
[INFO] |     +- io.dropwizard:dropwizard-jetty:jar:0.9.2:test
[INFO] |     |  \- io.dropwizard.metrics:metrics-jetty9:jar:3.1.2:test
[INFO] |     +- io.dropwizard:dropwizard-lifecycle:jar:0.9.2:test
[INFO] |     +- io.dropwizard.metrics:metrics-core:jar:3.1.2:test
[INFO] |     +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:test
[INFO] |     +- io.dropwizard.metrics:metrics-servlets:jar:3.1.2:test
[INFO] |     |  \- io.dropwizard.metrics:metrics-json:jar:3.1.2:test
[INFO] |     +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:test
[INFO] |     +- net.sourceforge.argparse4j:argparse4j:jar:0.6.0:test
[INFO] |     \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:test
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.8.5:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.5:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.5:compile
[INFO] +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.8.5:compile
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.4:compile
[INFO] +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.8.5:compile
[INFO] +- com.nagra.ml.sp.filetransfer:ml-sp-filetransfer:jar:1.0.3:compile
[INFO] +- org.jmockit:jmockit:jar:1.29:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] +- info.cukes:cucumber-junit:jar:1.2.5:test
[INFO] |  \- info.cukes:cucumber-core:jar:1.2.5:test
[INFO] |     +- info.cukes:cucumber-html:jar:0.2.3:test
[INFO] |     +- info.cukes:cucumber-jvm-deps:jar:1.0.5:test
[INFO] |     \- info.cukes:gherkin:jar:2.12.2:test
[INFO] \- com.github.tomakehurst:wiremock:jar:standalone:1.58:test

**Comment by mangrish** [comment]
Moved to here: https://jira.spring.io/browse/DATAGRAPH-950
