### ISSUE TITLE
T result from repository finder should throw exception when there is not a single unique result

### ISSUE THREAD

**Issue by frant-hartm** [spring-projects/spring-data-neo4j#387]
SDN should follow Spring Data conventions where it can.

> "T | An unique entity. Expects the query method to return one result at most. In case no result is found null is returned. More than one result will trigger an IncorrectResultSizeDataAccessException."
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-return-types

Test case:
```@Test(expected = IncorrectResultSizeDataAccessException.class)
    @Ignore
    public void findByNameSingleResult() throws Exception {
        World world1 = new World("world 1", 1);
        worldRepository.save(world1, 0);

        World world2 = new World("world 1", 2);
        worldRepository.save(world2, 0);

        World world = worldRepository.findByName("world 1"); // there are 2 results, 1 is returned instead of IncorrectResultSizeDataAccessException thrown
    }
```

**Comment by mangrish** [comment]
This issue has been moved to: https://jira.spring.io/browse/DATAGRAPH-948
